XIncludeFile "RW_Firebird_Res.pb"
Import "fbclient_ms.lib"
  isc_array_gen_sdl(a.l, b.l, c.l, d.l, e.l) As "_isc_array_gen_sdl@20"
  isc_array_get_slice(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_array_get_slice@28"
  isc_array_lookup_bounds(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_array_lookup_bounds@24"
  isc_array_lookup_desc(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_array_lookup_desc@24"
  isc_array_put_slice(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_array_put_slice@28"
  isc_array_set_desc(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_array_set_desc@28"
  isc_get_slice(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l) As "_isc_get_slice@44"
  isc_put_slice(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l) As "_isc_put_slice@40"
  isc_blob_default_desc(a.l, b.l, c.l) As "_isc_blob_default_desc@12"
  isc_blob_gen_bpb(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_blob_gen_bpb@24"
  isc_blob_info(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_blob_info@24"
  isc_blob_lookup_desc(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_blob_lookup_desc@28"
  isc_blob_set_desc(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_blob_set_desc@28"
  isc_cancel_blob(a.l, b.l) As "_isc_cancel_blob@8"
  isc_close_blob(a.l, b.l) As "_isc_close_blob@8"
  isc_create_blob(a.l, b.l, c.l, d.l, e.l) As "_isc_create_blob@20"
  isc_create_blob2(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_create_blob2@28"
  isc_get_segment(a.l, b.l, c.l, d.l, e.l) As "_isc_get_segment@20"
  isc_open_blob(a.l, b.l, c.l, d.l, e.l) As "_isc_open_blob@20"
  isc_open_blob2(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_open_blob2@28"
  isc_put_segment(a.l, b.l, c.l, d.l) As "_isc_put_segment@16"
  isc_attach_database(a.l, b.l, c.s, d.l, e.l, f.l) As "_isc_attach_database@24"
  isc_create_database(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_create_database@28"
  isc_database_info(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_database_info@24"
  isc_detach_database(a.l, b.l) As "_isc_detach_database@8"
  isc_drop_database(a.l, b.l) As "_isc_drop_database@8"
  isc_expand_dpb() As "_isc_expand_dpb"
  isc_modify_dpb(a.l, b.l, c.l, d.l, e.l) As "_isc_modify_dpb@20"
  isc_version(a.l, b.l, c.l) As "_isc_version@12"
  isc_get_client_major_version() As "_isc_get_client_major_version@0"
  isc_get_client_minor_version() As "_isc_get_client_minor_version@0"
  isc_get_client_version(a.l) As "_isc_get_client_version@4"
  isc_decode_date(a.l, b.l) As "_isc_decode_date@8"
  isc_decode_sql_date(a.l, b.l) As "_isc_decode_sql_date@8"
  isc_decode_sql_time(a.l, b.l) As "_isc_decode_sql_time@8"
  isc_decode_timestamp(a.l, b.l) As "_isc_decode_timestamp@8"
  isc_encode_date(a.l, b.l) As "_isc_encode_date@8"
  isc_encode_sql_date(a.l, b.l) As "_isc_encode_sql_date@8"
  isc_encode_sql_time(a.l, b.l) As "_isc_encode_sql_time@8"
  isc_encode_timestamp(a.l, b.l) As "_isc_encode_timestamp@8"
  isc_portable_integer(a.l, b.l) As "_isc_portable_integer@8"
  isc_vax_integer(a.l, b.l) As "_isc_vax_integer@8"
  isc_dsql_allocate_statement(a.l, b.l, c.l) As "_isc_dsql_allocate_statement@12"
  isc_dsql_alloc_statement2(a.l, b.l, c.l) As "_isc_dsql_alloc_statement2@12"
  isc_dsql_describe(a.l, b.l, c.l, d.l) As "_isc_dsql_describe@16"
  isc_dsql_describe_bind(a.l, b.l, c.l, d.l) As "_isc_dsql_describe_bind@16"
  isc_dsql_execute(a.l, b.l, c.l, d.l, e.l) As "_isc_dsql_execute@20"
  isc_dsql_execute2(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_dsql_execute2@24"
  isc_dsql_execute_m(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l) As "_isc_dsql_execute_m@32"
  isc_dsql_execute2_m(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l, l.l, m.l) As "_isc_dsql_execute2_m@52"
  isc_dsql_execute_immediate(a.l, b.l, c.l, d.l, e.s, f.l, g.l) As "_isc_dsql_execute_immediate@28"
  isc_dsql_exec_immed2(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l) As "_isc_dsql_exec_immed2@32"
  isc_dsql_execute_immediate_m(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l) As "_isc_dsql_execute_immediate_m@44"
  isc_dsql_exec_immed2_m(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l, l.l, m.l, n.l, o.l, p.l) As "_isc_dsql_exec_immed2_m@64"
  isc_dsql_exec_immed3_m(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l, l.l, m.l, n.l, o.l, p.l) As "_isc_dsql_exec_immed3_m@64"
  isc_dsql_fetch(a.l, b.l, c.l, d.l) As "_isc_dsql_fetch@16"
  isc_dsql_fetch_a(a.l, b.l, c.l, d.l, e.l) As "_isc_dsql_fetch_a@20"
  isc_dsql_fetch_m(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_dsql_fetch_m@28"
  isc_dsql_finish(a.l) As "_isc_dsql_finish@4"
  isc_dsql_free_statement(a.l, b.l, c.l) As "_isc_dsql_free_statement@12"
  isc_dsql_insert(a.l, b.l, c.l, d.l) As "_isc_dsql_insert@16"
  isc_dsql_insert_m(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_dsql_insert_m@28"
  isc_dsql_prepare(a.l, b.l, c.l, d.l, e.s, f.l, g.l) As "_isc_dsql_prepare@28"
  isc_dsql_prepare_m(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l) As "_isc_dsql_prepare_m@40"
  isc_dsql_release(a.l, b.l) As "_isc_dsql_release@8"
  isc_dsql_set_cursor_name(a.l, b.l, c.l, d.l) As "_isc_dsql_set_cursor_name@16"
  isc_dsql_sql_info(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_dsql_sql_info@24"
  isc_embed_dsql_close(a.l, b.l) As "_isc_embed_dsql_close@8"
  isc_embed_dsql_declare(a.l, b.l, c.l) As "_isc_embed_dsql_declare@12"
  isc_embed_dsql_describe(a.l, b.l, c.l, d.l) As "_isc_embed_dsql_describe@16"
  isc_embed_dsql_describe_bind(a.l, b.l, c.l, d.l) As "_isc_embed_dsql_describe_bind@16"
  isc_embed_dsql_execute(a.l, b.l, c.l, d.l, e.l) As "_isc_embed_dsql_execute@20"
  isc_embed_dsql_execute2(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_embed_dsql_execute2@24"
  isc_embed_dsql_execute_immed(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_embed_dsql_execute_immed@28"
  isc_embed_dsql_exec_immed2(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l) As "_isc_embed_dsql_exec_immed2@32"
  isc_embed_dsql_fetch(a.l, b.l, c.l, d.l) As "_isc_embed_dsql_fetch@16"
  isc_embed_dsql_fetch_a(a.l, b.l, c.l, d.l, e.l) As "_isc_embed_dsql_fetch_a@20"
  isc_embed_dsql_insert(a.l, b.l, c.l, d.l) As "_isc_embed_dsql_insert@16"
  isc_embed_dsql_open(a.l, b.l, c.l, d.l, e.l) As "_isc_embed_dsql_open@20"
  isc_embed_dsql_open2(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_embed_dsql_open2@24"
  isc_embed_dsql_prepare(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l) As "_isc_embed_dsql_prepare@32"
  isc_embed_dsql_release(a.l, b.l) As "_isc_embed_dsql_release@8"
  isc_embed_dsql_length(a.l, b.l) As "_isc_embed_dsql_length@8"
  isc_interprete(a.l, b.l) As "_isc_interprete@8"
  isc_print_sqlerror(a.l, b.l) As "_isc_print_sqlerror@8"
  isc_print_status(a.l) As "_isc_print_status@4"
  isc_sqlcode(a.l) As "_isc_sqlcode@4"
  isc_sql_interprete(a.l, b.l, c.l) As "_isc_sql_interprete@12"
  isc_sqlcode_s(a.l, b.l) As "_isc_sqlcode_s@8"
  isc_cancel_events(a.l, b.l, c.l) As "_isc_cancel_events@12"
  isc_event_block() As "_isc_event_block"
  isc_event_counts(a.l, b.l, c.l, d.l) As "_isc_event_counts@16"
  isc_que_events(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_que_events@28"
  isc_wait_for_event(a.l, b.l, c.l, d.l, e.l) As "_isc_wait_for_event@20"
  isc_event_block_a(a.l, b.l, c.l, d.l) As "_isc_event_block_a@16"
  isc_event_block_s(a.l, b.l, c.l, d.l, e.l) As "_isc_event_block_s@20"
  isc_add_user(a.l, b.l) As "_isc_add_user@8"
  isc_delete_user(a.l, b.l) As "_isc_delete_user@8"
  isc_modify_user(a.l, b.l) As "_isc_modify_user@8"
  isc_service_attach(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_service_attach@24"
  isc_service_detach(a.l, b.l) As "_isc_service_detach@8"
  isc_service_query(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l) As "_isc_service_query@36"
  isc_service_start(a.l, b.l, c.l, d.l, e.l) As "_isc_service_start@20"
  isc_commit_retaining(a.l, b.l) As "_isc_commit_retaining@8"
  isc_commit_transaction(a.l, b.l) As "_isc_commit_transaction@8"
  isc_prepare_transaction(a.l, b.l) As "_isc_prepare_transaction@8"
  isc_prepare_transaction2(a.l, b.l, c.l, d.l) As "_isc_prepare_transaction2@16"
  isc_rollback_retaining(a.l, b.l) As "_isc_rollback_retaining@8"
  isc_rollback_transaction(a.l, b.l) As "_isc_rollback_transaction@8"
  isc_start_multiple(a.l, b.l, c.l, d.l) As "_isc_start_multiple@16"
  isc_start_transaction(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_start_transaction"
  isc_transaction_info(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_transaction_info@24"
  isc_compile_request(a.l, b.l, c.l, d.l, e.l) As "_isc_compile_request@20"
  isc_compile_request2(a.l, b.l, c.l, d.l, e.l) As "_isc_compile_request2@20"
  isc_ddl(a.l, b.l, c.l, d.l, e.l) As "_isc_ddl@20"
  isc_prepare(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_prepare@28"
  isc_receive(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_receive@24"
  isc_reconnect_transaction(a.l, b.l, c.l, d.l, e.l) As "_isc_reconnect_transaction@20"
  isc_release_request(a.l, b.l) As "_isc_release_request@8"
  isc_request_info(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_request_info@28"
  isc_seek_blob(a.l, b.l, c.l, d.l, e.l) As "_isc_seek_blob@20"
  isc_send(a.l, b.l, c.l, d.l, e.l, f.l) As "_isc_send@24"
  isc_start_and_send(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_isc_start_and_send@28"
  isc_start_request(a.l, b.l, c.l, d.l) As "_isc_start_request@16"
  isc_transact_request(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l) As "_isc_transact_request@36"
  isc_unwind_request(a.l, b.l, c.l) As "_isc_unwind_request@12"
  isc_close(a.l, b.l) As "_isc_close@8"
  isc_declare(a.l, b.l, c.l) As "_isc_declare@12"
  isc_describe(a.l, b.l, c.l) As "_isc_describe@12"
  isc_describe_bind(a.l, b.l, c.l) As "_isc_describe_bind@12"
  isc_execute(a.l, b.l, c.l, d.l) As "_isc_execute@16"
  isc_execute_immediate(a.l, b.l, c.l, d.l, e.l) As "_isc_execute_immediate@20"
  isc_fetch(a.l, b.l, c.l) As "_isc_fetch@12"
  isc_fetch_a(a.l, b.l, c.l, d.l) As "_isc_fetch_a@16"
  isc_open(a.l, b.l, c.l, d.l) As "_isc_open@16"
  isc_ftof(a.l, b.l, c.l, d.l) As "_isc_ftof@16"
  isc_free(a.l) As "_isc_free@4"
  isc_print_blr(a.l, b.l, c.l, d.l) As "_isc_print_blr@16"
  isc_qtoq(a.l, b.l) As "_isc_qtoq@8"
  isc_reset_fpe(a.l) As "_isc_reset_fpe@4"
  isc_set_debug(a.l) As "_isc_set_debug@4"
  isc_to_sqlda(a.l, b.l, c.l, d.l, e.l) As "_isc_to_sqlda@20"
  isc_vtof(a.l, b.l, c.l) As "_isc_vtof@12"
  isc_vtov(a.l, b.l, c.l) As "_isc_vtov@12"
  isc_baddress(a.l) As "_isc_baddress@4"
  isc_baddress_s(a.l, b.l) As "_isc_baddress_s@8"
EndImport
Import "fbclient_ms.lib"

  fb_interpret(a.l, b.l, c.l) As "_fb_interpret@12"

  gds__alloc(a.l) As "_gds__alloc@4"
  gds__attach_database(a.l, b.l, c.l, d.l, e.l, f.l) As "_gds__attach_database@24"
  gds__blob_info(a.l, b.l, c.l, d.l, e.l, f.l) As "_gds__blob_info@24"
  gds__blob_size(a.l, b.l, c.l, d.l) As "_gds__blob_size@16"
  gds__cancel_blob(a.l, b.l) As "_gds__cancel_blob@8"
  gds__cancel_events(a.l, b.l, c.l) As "_gds__cancel_events@12"
  gds__close(a.l, b.l) As "_gds__close@8"
  gds__close_blob(a.l, b.l) As "_gds__close_blob@8"
  gds__commit_retaining(a.l, b.l) As "_gds__commit_retaining@8"
  gds__commit_transaction(a.l, b.l) As "_gds__commit_transaction@8"
  gds__compile_request(a.l, b.l, c.l, d.l, e.l) As "_gds__compile_request@20"
  gds__compile_request2(a.l, b.l, c.l, d.l, e.l) As "_gds__compile_request2@20"
  gds__create_blob(a.l, b.l, c.l, d.l, e.l) As "_gds__create_blob@20"
  gds__create_blob2(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_gds__create_blob2@28"
  gds__create_database(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_gds__create_database@28"
  gds__database_cleanup(a.l, b.l, c.l, d.l) As "_gds__database_cleanup@16"
  gds__database_info(a.l, b.l, c.l, d.l, e.l, f.l) As "_gds__database_info@24"
  gds__ddl(a.l, b.l, c.l, d.l, e.l) As "_gds__ddl@20"
  gds__declare(a.l, b.l, c.l) As "_gds__declare@12"
  gds__decode(a.l, b.l, c.l) As "_gds__decode@12"
  gds__decode_date(a.l, b.l) As "_gds__decode_date@8"
  gds__describe(a.l, b.l, c.l) As "_gds__describe@12"
  gds__describe_bind(a.l, b.l, c.l) As "_gds__describe_bind@12"
  gds__detach_database(a.l, b.l) As "_gds__detach_database@8"
  gds__disable_subsystem(a.l) As "_gds__disable_subsystem@4"
  gds__dsql_finish(a.l) As "_gds__dsql_finish@4"
  gds__edit(a.l, b.l) As "_gds__edit@8"
  gds__enable_subsystem(a.l) As "_gds__enable_subsystem@4"
  gds__encode(a.l, b.l) As "_gds__encode@8"
  gds__encode_date(a.l, b.l) As "_gds__encode_date@8"
  gds__event_block() As "_gds__event_block"
  gds__event_counts(a.l, b.l, c.l, d.l) As "_gds__event_counts@16"
  gds__event_wait(a.l, b.l, c.l, d.l, e.l) As "_gds__event_wait@20"
  gds__execute(a.l, b.l, c.l, d.l) As "_gds__execute@16"
  gds__execute_immediate(a.l, b.l, c.l, d.l, e.l) As "_gds__execute_immediate@20"
  gds__fetch(a.l, b.l, c.l) As "_gds__fetch@12"
  gds__free(a.l) As "_gds__free@4"
  gds__ftof(a.l, b.l, c.l, d.l) As "_gds__ftof@16"
  gds__get_prefix(a.l, b.l) As "_gds__get_prefix@8"
  gds__get_segment(a.l, b.l, c.l, d.l, e.l) As "_gds__get_segment@20"
  gds__get_slice(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l, k.l) As "_gds__get_slice@44"
  gds__interprete(a.l, b.l) As "_gds__interprete@8"
  gds__log() As "_gds__log"
  gds__log_status(a.l, b.l) As "_gds__log_status@8"
  gds__map_blobs(a.l, b.l) As "_gds__map_blobs@8"
  gds__msg_close(a.l) As "_gds__msg_close@4"
  gds__msg_format(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l) As "_gds__msg_format@40"
  gds__msg_lookup(a.l, b.l, c.l, d.l, e.l, f.l) As "_gds__msg_lookup@24"
  gds__msg_open(a.l, b.l) As "_gds__msg_open@8"
  gds__msg_put(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l) As "_gds__msg_put@32"
  gds__open(a.l, b.l, c.l, d.l) As "_gds__open@16"
  gds__open_blob(a.l, b.l, c.l, d.l, e.l) As "_gds__open_blob@20"
  gds__open_blob2(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_gds__open_blob2@28"
  gds__parse_bpb(a.l, b.l, c.l, d.l) As "_gds__parse_bpb@16"
  gds__prefix(a.l, b.l) As "_gds__prefix@8"
  gds__prefix_lock(a.l, b.l) As "_gds__prefix_lock@8"
  gds__prefix_msg(a.l, b.l) As "_gds__prefix_msg@8"
  gds__prepare(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_gds__prepare@28"
  gds__prepare_transaction(a.l, b.l) As "_gds__prepare_transaction@8"
  gds__prepare_transaction2(a.l, b.l, c.l, d.l) As "_gds__prepare_transaction2@16"
  gds__print_blr(a.l, b.l, c.l, d.l) As "_gds__print_blr@16"
  gds__print_status(a.l) As "_gds__print_status@4"
  gds__put_error(a.l) As "_gds__put_error@4"
  gds__put_segment(a.l, b.l, c.l, d.l) As "_gds__put_segment@16"
  gds__put_slice(a.l, b.l, c.l, d.l, e.l, f.l, g.l, h.l, i.l, j.l) As "_gds__put_slice@40"
  gds__qtoq(a.l, b.l) As "_gds__qtoq@8"
  gds__que_events(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_gds__que_events@28"
  gds__receive(a.l, b.l, c.l, d.l, e.l, f.l) As "_gds__receive@24"
  gds__reconnect_transaction(a.l, b.l, c.l, d.l, e.l) As "_gds__reconnect_transaction@20"
  gds__register_cleanup(a.l, b.l) As "_gds__register_cleanup@8"
  gds__release_request(a.l, b.l) As "_gds__release_request@8"
  gds__request_info(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_gds__request_info@28"
  gds__rollback_transaction(a.l, b.l) As "_gds__rollback_transaction@8"
  gds__seek_blob(a.l, b.l, c.l, d.l, e.l) As "_gds__seek_blob@20"
  gds__send(a.l, b.l, c.l, d.l, e.l, f.l) As "_gds__send@24"
  gds__set_debug(a.l) As "_gds__set_debug@4"
  gds__sqlcode(a.l) As "_gds__sqlcode@4"
  gds__start_and_send(a.l, b.l, c.l, d.l, e.l, f.l, g.l) As "_gds__start_and_send@28"
  gds__start_multiple(a.l, b.l, c.l, d.l) As "_gds__start_multiple@16"
  gds__start_request(a.l, b.l, c.l, d.l) As "_gds__start_request@16"
  gds__start_transaction() As "_gds__start_transaction"
  gds__temp_file(a.l, b.l, c.l, d.l, e.l) As "_gds__temp_file@20"
  gds__thread_enable(a.l) As "_gds__thread_enable@4"
  gds__thread_enter() As "_gds__thread_enter@0"
  gds__thread_exit() As "_gds__thread_exit@0"
  gds__thread_start(a.l, b.l, c.l, d.l, e.l) As "_gds__thread_start@20"
  gds__to_sqlda(a.l, b.l, c.l, d.l, e.l) As "_gds__to_sqlda@20"
  gds__transaction_cleanup(a.l, b.l, c.l, d.l) As "_gds__transaction_cleanup@16"
  gds__transaction_info(a.l, b.l, c.l, d.l, e.l, f.l) As "_gds__transaction_info@24"
  gds__unregister_cleanup(a.l, b.l) As "_gds__unregister_cleanup@8"
  gds__unwind_request(a.l, b.l, c.l) As "_gds__unwind_request@12"
  gds__validate_lib_path(a.l, b.l, c.l, d.l) As "_gds__validate_lib_path@16"
  gds__vax_integer(a.l, b.l) As "_gds__vax_integer@8"
  gds__version(a.l, b.l, c.l) As "_gds__version@12"
  gds__vtof(a.l, b.l, c.l) As "_gds__vtof@12"
  gds__vtov(a.l, b.l, c.l) As "_gds__vtov@12"
  gds__default_printer() As "_gds__default_printer"
  gds__alloc_debug(a.l, b.l, c.l) As "_gds__alloc_debug@12"
  gds_alloc_flag_unfreed(a.l) As "_gds_alloc_flag_unfreed@4"
  gds_alloc_report(a.l, b.l, c.l) As "_gds_alloc_report@12"
  perf_format(a.l, b.l, c.l, d.l, e.l) As "_perf_format@20"
  perf_get_info(a.l, b.l) As "_perf_get_info@8"
  perf_report(a.l, b.l, c.l, d.l) As "_perf_report@16"
  BLOB_close(a.l) As "_BLOB_close@4"
  BLOB_display(a.l, b.l, c.l, d.l) As "_BLOB_display@16"
  BLOB_dump(a.l, b.l, c.l, d.l) As "_BLOB_dump@16"
  BLOB_edit(a.l, b.l, c.l, d.l) As "_BLOB_edit@16"
  BLOB_get(a.l) As "_BLOB_get@4"
  BLOB_load(a.l, b.l, c.l, d.l) As "_BLOB_load@16"
  BLOB_open(a.l, b.l, c.l) As "_BLOB_open@12"
  BLOB_put(a.l, b.l) As "_BLOB_put@8"
  BLOB_text_dump(a.l, b.l, c.l, d.l) As "_BLOB_text_dump@16"
  BLOB_text_load(a.l, b.l, c.l, d.l) As "_BLOB_text_load@16"
  Bopen(a.l, b.l, c.l, d.l) As "_Bopen@16"
;   isc_start_transaction() As "__isc_start_transaction"
;   isc_expand_dpb() As "__isc_expand_dpb"
;   isc_event_block() As "__isc_event_block"
  CVT_move() As "_CVT_move"
  KEYWORD_stringIsAToken() As "_KEYWORD_stringIsAToken"
  KEYWORD_getTokens() As "_KEYWORD_getTokens"
EndImport

; IDE Options = PureBasic 4.20 (Windows - x86)
; CursorPosition = 274
; Folding = 9
; EnableUnicode