XIncludeFile "RW_AntTweakBar_Res.pb"
ImportC "AntTweakBar.lib"
  TwEventCharGLFW(glfwChar.l, glfwAction.l) As "_TwEventCharGLFW@8"
  TwEventKeyGLFW(glfwKey.l, glfwAction.l) As "_TwEventKeyGLFW@8"
  TwEventMouseButtonGLFW(glfwButton.l, glfwAction.l) As "_TwEventMouseButtonGLFW@8"
  TwEventSpecialGLUT(glutKey.l, mouseX.l, mouseY.l) As "_TwEventSpecialGLUT"
  TwEventKeyboardGLUT(glutKey.s, mouseX.l, mouseY.l) As "_TwEventKeyboardGLUT"
  TwGLUTModifiersFunc(*glutGetModifiersFunc_fn) As "_TwGLUTModifiersFunc@4"
  TwEventMouseMotionGLUT(mouseX.l, mouseY.l) As "_TwEventMouseMotionGLUT"
  TwEventMouseButtonGLUT(glutButtonl, glutState.l, mouseX.l, mouseY.l) As "_TwEventMouseButtonGLUT"
  TwEventSDL(*sdlEvent) As "_TwEventSDL@4"
  TwEventWin32(wnd.l, msg.q, wParam.q, lParam.q) As "_TwEventWin32@16"
  TwEventWin(wnd.l, msg.q, wParam.q, lParam.q) As "_TwEventWin@16"
  ;-TwCopyStdStringToLibrary(bar.TwBar, b.l) As "_TwCopyStdStringToLibrary@8"
  ;-TwCopyStdStringToClientFunc(bar.TwBar) As "_TwCopyStdStringToClientFunc@4"
  TwCopyCDStringToLibrary(*destinationLibraryStringPtr.s, sourceClientString.s) As "_TwCopyCDStringToLibrary@8"
  TwCopyCDStringToClientFunc(*copyCDStringFunc_fn) As "_TwCopyCDStringToClientFunc@4"
  TwKeyPressed(key.l, modifiers.l) As "_TwKeyPressed@8"
  TwMouseWheel(pos.l) As "_TwMouseWheel@4"
  TwMouseMotion(mouseX.l, mouseY.l) As "_TwMouseMotion@8"
  TwMouseButton(action.TwMouseAction, button.TwMouseButtonID) As "_TwMouseButton@8"
  TwDefineStruct(name.s, *structMembers.TwStructMember, nbMembers.l, structSize.l, *summaryCallback_fn, *summaryClientData) As "_TwDefineStruct@24"
  TwDefineEnum(name.s, *enumValues.TwEnumVal, nbValues.l) As "_TwDefineEnum@12"
  TwDefine(def.s) As "_TwDefine@4"
  TwRemoveAllVars(bar.TwBar) As "_TwRemoveAllVars@4"
  TwRemoveVar(bar.TwBar, name.s) As "_TwRemoveVar@8"
  TwAddSeparator(bar.TwBar, name.s, def.s) As "_TwAddSeparator@12"
  TwAddButton(bar.TwBar, name.s, *callback_fn, *clientData, def.s) As "_TwAddButton@20"
  TwAddVarCB(bar.TwBar, name.s, type.TwType, *setCallback_fn, *getCallback_fn, *clientData, def.s) As "_TwAddVarCB@28"
  TwAddVarRO(bar.TwBar, name.s, type.TwType, *var, def.s) As "_TwAddVarRO@20"
  TwAddVarRW(bar.TwBar, name.s, type.TwType, *var, def.s) As "_TwAddVarRW@20"
  TwSetParam(bar.TwBar, varName.s, paramName.s, paramValueType.TwParamValueType, inValueMaxCount.l, *inValues.l) As "_TwSetParam@24"
  TwGetParam(bar.TwBar, varName.s, paramName.s, paramValueType.TwParamValueType, outValueMaxCount.l, *outValues.l) As "_TwGetParam@24"
  TwRefreshBar(bar.TwBar) As "_TwRefreshBar@4"
  TwGetBarByName(barName.s) As "_TwGetBarByName@4"
  TwGetBarByIndex(barIndex.l) As "_TwGetBarByIndex@4"
  TwGetBarCount() As "_TwGetBarCount@0"
  TwGetBarName(bar.TwBar) As "_TwGetBarName@4" ; return String
  TwGetBottomBar() As "_TwGetBottomBar@0"
  TwSetBottomBar(bar.TwBar) As "_TwSetBottomBar@4"
  TwGetTopBar() As "_TwGetTopBar@0"
  TwSetTopBar(bar.TwBar) As "_TwSetTopBar@4"
  TwDeleteAllBars() As "_TwDeleteAllBars@0"
  TwDeleteBar(bar.TwBar) As "_TwDeleteBar@4"
  TwNewBar(barName.s) As "_TwNewBar@4"
  TwGetLastError() As "_TwGetLastError@0" ; Return String
  TwHandleErrors(*errorHandler_fn) As "_TwHandleErrors@4"
  TwWindowSize(width.l, height.l) As "_TwWindowSize@8"
  TwDraw() As "_TwDraw@0"
  TwTerminate() As "_TwTerminate@0"
  TwInit(graphAPI.TwGraphAPI, *device) As "_TwInit@8"
EndImport

