XIncludeFile "RW_MediaInfo_Res.pb"

Import "MediaInfo.lib"
;   MediaInfoA_Close(a.l) As "_MediaInfoA_Close@4"
;   MediaInfoA_Count_Get(a.l,b.l,c.l) As "_MediaInfoA_Count_Get@12"
;   MediaInfoA_Delete(a.l) As "_MediaInfoA_Delete@4"
;   MediaInfoA_Get(a.l,b.l,c.l,d.l,e.l,f.l) As "_MediaInfoA_Get@24"
;   MediaInfoA_GetI(a.l,b.l,c.l,d.l,e.l) As "_MediaInfoA_GetI@20"
;   MediaInfo_inform(a.l,b.l) As "_MediaInfo_inform@8"
;   MediaInfoA_New() As "_MediaInfoA_New@0"
;   MediaInfoA_New_Quick(a.l,b.l) As "_MediaInfoA_New_Quick@8"
;   MediaInfoA_Open(a.l,b.l) As "_MediaInfoA_Open@8"
;   MediaInfoA_Open_Buffer(a.l,b.l,c.l,d.l,e.l) As "_MediaInfoA_Open_Buffer@20"
;   MediaInfoA_Option(a.l,b.l,c.l) As "_MediaInfoA_Option@12"
;   MediaInfoA_Save(a.l) As "_MediaInfoA_Save@4"
;   MediaInfoA_Set(a.l,b.l,c.l,d.l,e.l,f.l) As "_MediaInfoA_Set@24"
;   MediaInfoA_SetI(a.l,b.l,c.l,d.l,e.l,f.l) As "_MediaInfoA_SetI@24"
;   MediaInfoA_State_Get(a.l) As "_MediaInfoA_State_Get@4"
;   MediaInfoListA_Close(a.l,b.l) As "_MediaInfoListA_Close@8"
;   MediaInfoListA_Count_Get(a.l,b.l,c.l,d.l) As "_MediaInfoListA_Count_Get@16"
;   MediaInfoListA_Count_Get_Files(a.l) As "_MediaInfoListA_Count_Get_Files@4"
;   MediaInfoListA_Delete(a.l) As "_MediaInfoListA_Delete@4"
;   MediaInfoListA_Get(a.l,b.l,c.l,d.l,e.l,f.l,g.l) As "_MediaInfoListA_Get@28"
;   MediaInfoListA_GetI(a.l,b.l,c.l,d.l,e.l,f.l) As "_MediaInfoListA_GetI@24"
;   MediaInfoListA_Inform(a.l,b.l,c.l) As "_MediaInfoListA_Inform@12"
;   MediaInfoListA_New() As "_MediaInfoListA_New@0"
;   MediaInfoListA_New_Quick(a.l,b.l) As "_MediaInfoListA_New_Quick@8"
;   MediaInfoListA_Open(a.l,b.l,c.l) As "_MediaInfoListA_Open@12"
;   MediaInfoListA_Open_Buffer(a.l,b.l,c.l,d.l,e.l) As "_MediaInfoListA_Open_Buffer@20"
;   MediaInfoListA_Option(a.l,b.l,c.l) As "_MediaInfoListA_Option@12"
;   MediaInfoListA_Save(a.l,b.l) As "_MediaInfoListA_Save@8"
;   MediaInfoListA_Set(a.l,b.l,c.l,d.l,e.l,f.l,g.l) As "_MediaInfoListA_Set@28"
;   MediaInfoListA_SetI(a.l,b.l,c.l,d.l,e.l,f.l,g.l) As "_MediaInfoListA_SetI@28"
;   MediaInfoListA_State_Get(a.l) As "_MediaInfoListA_State_Get@4"
  CompilerIf #PB_Compiler_Unicode = #False
    MediaInfoList_Close(handle.l,arg2.l) As "_MediaInfoListA_Close@8"
    MediaInfoList_Count_Get(handle.l, arg2.l, StreamKind.MediaInfo_stream, StreamNumber.l) As "_MediaInfoListA_Count_Get@16"
    MediaInfoList_Count_Get_Files(handle.l) As "_MediaInfoListA_Count_Get_Files@4"
    MediaInfoList_Delete(handle.l) As "_MediaInfoListA_Delete@4"
    MediaInfoList_Get.l(handle.l, arg2.l, StreamKind.MediaInfo_stream, StreamNumber.l, Parameter.s, KindOfInfo.MediaInfo_info, KindOfSearch.MediaInfo_info) As "_MediaInfoListA_Get@28"
    MediaInfoList_GetI.l(handle.l, arg2.l, StreamKind.MediaInfo_stream, StreamNumber.l, Parameter.l, KindOfInfo.MediaInfo_info) As "_MediaInfoListA_GetI@24"
    MediaInfoList_Inform.l(handle.l, arg2.l, arg3.l) As "_MediaInfoListA_Inform@12"
    MediaInfoList_New() As "_MediaInfoListA_New@0"
    MediaInfoList_Open(handle.l, arg2.s, arg3.MediaInfo_fileoptions) As "_MediaInfoListA_Open@12"
    MediaInfoList_State_Get(handle.l) As "_MediaInfoListA_State_Get@4"
    MediaInfo_Close(handle.l) As "_MediaInfoA_Close@4"
    MediaInfo_Count_Get(handle.l, StreamKind.MediaInfo_stream, StreamNumber.l) As "_MediaInfoA_Count_Get@12"
    MediaInfo_Delete(handle.l) As "_MediaInfoA_Delete@4"
    MediaInfo_Get.l(handle.l, StreamKind.MediaInfo_stream, StreamNumber.l, Parameter.s, KindOfInfo.MediaInfo_info, KindOfSearch.MediaInfo_info) As "_MediaInfoA_Get@24"
    MediaInfo_GetI.l(handle.l, StreamKind.MediaInfo_stream, StreamNumber.l, Parameter.L, KindOfInfo.MediaInfo_info) As "_MediaInfoA_GetI@20"
    MediaInfo_inform.l(handle.l, arg2.l) As "_MediaInfoA_Inform@8"
    MediaInfo_New() As "_MediaInfoA_New@0"
    MediaInfo_Open(handle.l, arg2.s) As "_MediaInfoA_Open@8"
    MediaInfo_Option.l(handle.l, Parameter.s, Value.s) As "_MediaInfoA_Option@12"
    MediaInfo_State_Get(handle.l) As "_MediaInfoA_State_Get@4"
  CompilerElse
    MediaInfoList_Close(handle.l,arg2.l) As "_MediaInfoList_Close@8"
    MediaInfoList_Count_Get(handle.l, arg2.l, StreamKind.MediaInfo_stream, StreamNumber.l) As "_MediaInfoList_Count_Get@16"
    MediaInfoList_Count_Get_Files(handle.l) As "_MediaInfoList_Count_Get_Files@4"
    MediaInfoList_Delete(handle.l) As "_MediaInfoList_Delete@4"
    MediaInfoList_Get.l(handle.l, arg2.l, StreamKind.MediaInfo_stream, StreamNumber.l, Parameter.s, KindOfInfo.MediaInfo_info, KindOfSearch.MediaInfo_info) As "_MediaInfoList_Get@28"
    MediaInfoList_GetI.l(handle.l, arg2.l, StreamKind.MediaInfo_stream, StreamNumber.l, Parameter.l, KindOfInfo.MediaInfo_info) As "_MediaInfoList_GetI@24"
    MediaInfoList_Inform.l(handle.l, arg2.l, arg3.l) As "_MediaInfoList_Inform@12"
    MediaInfoList_New() As "_MediaInfoList_New@0"
    MediaInfoList_Open(handle.l, arg2.s, arg3.MediaInfo_fileoptions) As "_MediaInfoList_Open@12"
    MediaInfoList_State_Get(handle.l) As "_MediaInfoList_State_Get@4"
    MediaInfo_Close(handle.l) As "_MediaInfo_Close@4"
    MediaInfo_Count_Get(handle.l, StreamKind.MediaInfo_stream, StreamNumber.l) As "_MediaInfo_Count_Get@12"
    MediaInfo_Delete(handle.l) As "_MediaInfo_Delete@4"
    MediaInfo_Get.l(handle.l, StreamKind.MediaInfo_stream, StreamNumber.l, Parameter.s, KindOfInfo.MediaInfo_info, KindOfSearch.MediaInfo_info) As "_MediaInfo_Get@24"
    MediaInfo_GetI.l(handle.l, StreamKind.MediaInfo_stream, StreamNumber.l, Parameter.L, KindOfInfo.MediaInfo_info) As "_MediaInfo_GetI@20"
    MediaInfo_Inform.l(handle.l, arg2.l) As "_MediaInfo_Inform@8"
    MediaInfo_New() As "_MediaInfo_New@0"
    MediaInfo_Open(handle.l, arg2.s) As "_MediaInfo_Open@8"
    MediaInfo_Option.l(handle.l, Parameter.s, Value.s) As "_MediaInfo_Option@12"
    MediaInfo_State_Get(handle.l) As "_MediaInfo_State_Get@4"
  CompilerEndIf
EndImport


; IDE Options = PureBasic 4.20 (Windows - x86)
; CursorPosition = 50
; FirstLine = 27
; Folding = -
; EnableUnicode