XIncludeFile "RW_LibMing_Res.pb"
Import "libming.lib"
  ;-ASClassMember_append() As "_ASClassMember_append"
  ;-ASClass_getConstructor() As "_ASClass_getConstructor"
  ;-FLVStream_fromInput() As "_FLVStream_fromInput"
  ;-FLVStream_getDuration() As "_FLVStream_getDuration"
  ;-FLVStream_getNumFrames() As "_FLVStream_getNumFrames"
  ;-FLVStream_nextTag() As "_FLVStream_nextTag"
  ;-FLVStream_nextTagType() As "_FLVStream_nextTagType"
  ;-FLVStream_rewind() As "_FLVStream_rewind"
  ;-FLVStream_setStreamOffset() As "_FLVStream_setStreamOffset"
  ;-FLVStream_skipTagData() As "_FLVStream_skipTagData"
  ;-FLVTag_getPayloadInput() As "_FLVTag_getPayloadInput"
  Ming_cleanup() As "_Ming_cleanup"
  ;-Ming_cleanupFonts() As "_Ming_cleanupFonts"
  Ming_collectGarbage() As "_Ming_collectGarbage"
  ;-Ming_getFont() As "_Ming_getFont"
  Ming_getScale.f() As "_Ming_getScale"
  Ming_init() As "_Ming_init"
  ;-Ming_loadFont() As "_Ming_loadFont"
  Ming_setCubicThreshold(num.L) As "_Ming_setCubicThreshold"
  Ming_setErrorFunction(*SWFMsgFunc_fn) As "_Ming_setErrorFunction"
  Ming_setSWFCompression(level.l) As "_Ming_setSWFCompression"
  Ming_setScale(scale.f) As "_Ming_setScale"
  Ming_setWarnFunction(*SWFMsgFunc_fn) As "_Ming_setWarnFunction"
  Ming_useConstants(flag.l) As "_Ming_useConstants"
  Ming_useSWFVersion(version.l) As "_Ming_useSWFVersion"
  SWFAction_compile(action.SWFAction, swfVersion.l, *length.l) As "_SWFAction_compile"
  SWFAction_getByteCode(action.SWFAction, *length.l) As "_SWFAction_getByteCode"
  SWFAction_setDebug(action.SWFAction, debug_.l) As "_SWFAction_setDebug"
  SWFBitmap_getHeight(b.SWFBitmap) As "_SWFBitmap_getHeight"
  SWFBitmap_getWidth(b.SWFBitmap) As "_SWFBitmap_getWidth"
  ;-SWFBlockInit() As "_SWFBlockInit"
  ;-SWFBlockList_addBlock() As "_SWFBlockList_addBlock"
  ;-SWFBlockList_addToSprite() As "_SWFBlockList_addToSprite"
  ;-SWFBlockList_completeBlocks() As "_SWFBlockList_completeBlocks"
  ;-SWFBlockList_getLastBlock() As "_SWFBlockList_getLastBlock"
  ;-SWFBlockList_writeBlocksToMethod() As "_SWFBlockList_writeBlocksToMethod"
  ;-SWFBlock_getLength() As "_SWFBlock_getLength"
  ;-SWFBlock_getType() As "_SWFBlock_getType"
  ;-SWFBlock_isCharacter() As "_SWFBlock_isCharacter"
  ;-SWFBlock_isDefined() As "_SWFBlock_isDefined"
  ;-SWFBlock_setDefined() As "_SWFBlock_setDefined"
  ;-SWFBrowserFont_getOutput() As "_SWFBrowserFont_getOutput"
  SWFButtonRecord_addFilter(b.SWFButtonRecord, f.SWFFilter) As "_SWFButtonRecord_addFilter"
  SWFButtonRecord_move(record.SWFButtonRecord, x.d, y.d) As "_SWFButtonRecord_move"
  SWFButtonRecord_moveTo(record.SWFButtonRecord, x.d, y.d) As "_SWFButtonRecord_moveTo"
  SWFButtonRecord_rotate(record.SWFButtonRecord, deg.d) As "_SWFButtonRecord_rotate"
  SWFButtonRecord_rotateTo(record.SWFButtonRecord, deg.d) As "_SWFButtonRecord_rotateTo"
  SWFButtonRecord_scale(record.SWFButtonRecord, scaleX.d, scaleY.d) As "_SWFButtonRecord_scale"
  SWFButtonRecord_scaleTo(record.SWFButtonRecord, scaleX.d, scaleY.d) As "_SWFButtonRecord_scaleTo"
  SWFButtonRecord_setBlendMode(b.SWFButtonRecord, mode.l) As "_SWFButtonRecord_setBlendMode"
  SWFButtonRecord_setDepth(b.SWFButtonRecord, depth.l) As "_SWFButtonRecord_setDepth"
  SWFButtonRecord_setMatrix(record.SWFButtonRecord, a.d, b.d, c.d, d.d, x.d, y.d) As "_SWFButtonRecord_setMatrix"
  SWFButtonRecord_skewX(record.SWFButtonRecord, skewX.d) As "_SWFButtonRecord_skewX"
  SWFButtonRecord_skewXTo(record.SWFButtonRecord, skewX.d) As "_SWFButtonRecord_skewXTo"
  SWFButtonRecord_skewY(record.SWFButtonRecord, skewY.d) As "_SWFButtonRecord_skewY"
  SWFButtonRecord_skewYTo(record.SWFButtonRecord, skewY.d) As "_SWFButtonRecord_skewYTo"
  ;-SWFButtonSound_setSound() As "_SWFButtonSound_setSound"
  SWFButton_addAction(button.SWFButton, action.SWFAction, flags.l) As "_SWFButton_addAction"
  SWFButton_addCharacter(button.SWFButton, character.SWFCharacter, flags.b) As "_SWFButton_addCharacter"
  SWFButton_addShape(button.SWFButton, character.SWFCharacter, flags.b) As "_SWFButton_addShape"
  SWFButton_addSound(button.SWFButton, action.SWFSound, flags.b) As "_SWFButton_addSound"
  SWFButton_removeScalingGrid(b.SWFButton) As "_SWFButton_removeScalingGrid"
  SWFButton_setMenu(button.SWFButton, flag.l) As "_SWFButton_setMenu"
  SWFButton_setScalingGrid(b.SWFButton, x.l, y.l, w.l, h.l) As "_SWFButton_setScalingGrid"
  SWFCXform_setColorAdd(cXform.SWFCXform, rAdd.l, gAdd.l, bAdd.l, aAdd.l) As "_SWFCXform_setColorAdd"
  SWFCXform_setColorMult(cXform.SWFCXform, rMult.f, gMult.f, bMult.f, aMult.f) As "_SWFCXform_setColorMult"
  ;-SWFCharacterInit() As "_SWFCharacterInit"
  ;-SWFCharacter_addDependency() As "_SWFCharacter_addDependency"
  ;-SWFCharacter_getBounds() As "_SWFCharacter_getBounds"
  ;-SWFCharacter_getDependencies() As "_SWFCharacter_getDependencies"
  SWFCharacter_getHeight.f(character.SWFCharacter) As "_SWFCharacter_getHeight"
  ;-SWFCharacter_getID() As "_SWFCharacter_getID"
  ;-SWFCharacter_getScaledHeight() As "_SWFCharacter_getScaledHeight"
  ;-SWFCharacter_getScaledWidth() As "_SWFCharacter_getScaledWidth"
  SWFCharacter_getWidth.f(character.SWFCharacter) As "_SWFCharacter_getWidth"
  ;-SWFCharacter_isFinished() As "_SWFCharacter_isFinished"
  ;-SWFCharacter_setFinished() As "_SWFCharacter_setFinished"
  ;-SWFCharacter_setID() As "_SWFCharacter_setID"
  SWFDisplayItem_addAction(item.SWFDisplayItem, action.SWFAction, flags.l) As "_SWFDisplayItem_addAction"
  SWFDisplayItem_addFilter(item.SWFDisplayItem, filter.SWFFilter) As "_SWFDisplayItem_addFilter"
  SWFDisplayItem_cacheAsBitmap(item.SWFDisplayItem, flag.l) As "_SWFDisplayItem_cacheAsBitmap"
  SWFDisplayItem_endMask(item.SWFDisplayItem) As "_SWFDisplayItem_endMask"
  SWFDisplayItem_flush(item.SWFDisplayItem) As "_SWFDisplayItem_flush"
  SWFDisplayItem_getCharacter(item.SWFDisplayItem) As "_SWFDisplayItem_getCharacter"
  SWFDisplayItem_getDepth(item.SWFDisplayItem) As "_SWFDisplayItem_getDepth"
  SWFDisplayItem_getMatrix(item.SWFDisplayItem) As "_SWFDisplayItem_getMatrix"
  SWFDisplayItem_getPosition(item.SWFDisplayItem, *x.d, *y.d) As "_SWFDisplayItem_getPosition"
  SWFDisplayItem_getRotation(item.SWFDisplayItem, *degrees.d) As "_SWFDisplayItem_getRotation"
  SWFDisplayItem_getScale(item.SWFDisplayItem, *xScale.d, *yScale.d) As "_SWFDisplayItem_getScale"
  SWFDisplayItem_getSkew(item.SWFDisplayItem, *xSkew.d, *ySkew.d) As "_SWFDisplayItem_getSkew"
  SWFDisplayItem_move(item.SWFDisplayItem, x.d, y.d) As "_SWFDisplayItem_move"
  SWFDisplayItem_moveTo(item.SWFDisplayItem, x.d, y.d) As "_SWFDisplayItem_moveTo"
  SWFDisplayItem_remove(item.SWFDisplayItem) As "_SWFDisplayItem_remove"
  ;-SWFDisplayItem_removeFromList() As "_SWFDisplayItem_removeFromList"
  ;-SWFDisplayItem_replace() As "_SWFDisplayItem_replace"
  SWFDisplayItem_rotate(item.SWFDisplayItem, degrees.d) As "_SWFDisplayItem_rotate"
  SWFDisplayItem_rotateTo(item.SWFDisplayItem, degrees.d) As "_SWFDisplayItem_rotateTo"
  SWFDisplayItem_scale(item.SWFDisplayItem, xScale.d, yScale.d) As "_SWFDisplayItem_scale"
  SWFDisplayItem_scaleTo(item.SWFDisplayItem, xScale.d, yScale.d) As "_SWFDisplayItem_scaleTo"
  SWFDisplayItem_setBlendMode(item.SWFDisplayItem, mode.l) As "_SWFDisplayItem_setBlendMode"
  SWFDisplayItem_setCXform(item.SWFDisplayItem, cXform.SWFCXform) As "_SWFDisplayItem_setCXform"
  SWFDisplayItem_setColorAdd(item.SWFDisplayItem, r.l, g.l, b.l, a.l) As "_SWFDisplayItem_setColorAdd"
  SWFDisplayItem_setColorMult(item.SWFDisplayItem, r.f, g.f, b.f, a.f) As "_SWFDisplayItem_setColorMult"
  SWFDisplayItem_setDepth(item.SWFDisplayItem, depth.l) As "_SWFDisplayItem_setDepth"
  SWFDisplayItem_setMaskLevel(item.SWFDisplayItem, masklevel.l) As "_SWFDisplayItem_setMaskLevel"
  SWFDisplayItem_setMatrix(i.SWFDisplayItem, a.d, b.d, c.d, d.d, x.d, y.d) As "_SWFDisplayItem_setMatrix"
  SWFDisplayItem_setName(item.SWFDisplayItem, name.s) As "_SWFDisplayItem_setName"
  SWFDisplayItem_setRatio(item.SWFDisplayItem, ratio.f) As "_SWFDisplayItem_setRatio"
  SWFDisplayItem_skewX(item.SWFDisplayItem, x.d) As "_SWFDisplayItem_skewX"
  SWFDisplayItem_skewXTo(item.SWFDisplayItem, x.d) As "_SWFDisplayItem_skewXTo"
  SWFDisplayItem_skewY(item.SWFDisplayItem, y.d) As "_SWFDisplayItem_skewY"
  SWFDisplayItem_skewYTo(item.SWFDisplayItem, y.d) As "_SWFDisplayItem_skewYTo"
  ;-SWFDisplayList_add() As "_SWFDisplayList_add"
  ;-SWFDisplayList_rewindSoundStream() As "_SWFDisplayList_rewindSoundStream"
  ;-SWFDisplayList_setSoundStream() As "_SWFDisplayList_setSoundStream"
  ;-SWFDisplayList_writeBlocks() As "_SWFDisplayList_writeBlocks"
  ;-SWFFileAttributes_hasMetadata() As "_SWFFileAttributes_hasMetadata"
  ;-SWFFileAttributes_useNetwork() As "_SWFFileAttributes_useNetwork"
  ;-SWFFillStyle_addDependency() As "_SWFFillStyle_addDependency"
  ;-SWFFillStyle_equals() As "_SWFFillStyle_equals"
  SWFFillStyle_getMatrix(fill.SWFFillStyle) As "_SWFFillStyle_getMatrix"
  SWFFill_getFillStyle(fill.SWFFill) As "_SWFFill_getFillStyle"
  SWFFill_move(fill.SWFFill, x.f, y.f) As "_SWFFill_move"
  SWFFill_moveTo(fill.SWFFill, x.f, y.f) As "_SWFFill_moveTo"
  SWFFill_rotate(fill.SWFFill, degrees.f) As "_SWFFill_rotate"
  SWFFill_rotateTo(fill.SWFFill, degrees.f) As "_SWFFill_rotateTo"
  SWFFill_scaleX(fill.SWFFill, x.f) As "_SWFFill_scaleX"
  SWFFill_scaleXTo(fill.SWFFill, x.f) As "_SWFFill_scaleXTo"
  SWFFill_scaleXY(fill.SWFFill, x.f, y.f) As "_SWFFill_scaleXY"
  SWFFill_scaleXYTo(fill.SWFFill, x.f, y.f) As "_SWFFill_scaleXYTo"
  SWFFill_scaleY(fill.SWFFill, y.f) As "_SWFFill_scaleY"
  SWFFill_scaleYTo(fill.SWFFill, y.f) As "_SWFFill_scaleYTo"
  SWFFill_setMatrix(fill.SWFFill, a.f, b.f, c.f, d.f, x.f, y.f) As "_SWFFill_setMatrix"
  SWFFill_skewX(fill.SWFFill, x.f) As "_SWFFill_skewX"
  SWFFill_skewXTo(fill.SWFFill, x.f) As "_SWFFill_skewXTo"
  SWFFill_skewY(fill.SWFFill, y.f) As "_SWFFill_skewY"
  SWFFill_skewYTo(fill.SWFFill, y.f) As "_SWFFill_skewYTo"
  ;-SWFFilterList_add() As "_SWFFilterList_add"
  SWFFontCharacter_addAllChars(font.SWFFontCharacter) As "_SWFFontCharacter_addAllChars"
  ;-SWFFontCharacter_addCharToTable() As "_SWFFontCharacter_addCharToTable"
  SWFFontCharacter_addChars(font.SWFFontCharacter, string.s) As "_SWFFontCharacter_addChars"
  ;-SWFFontCharacter_addTextToList() As "_SWFFontCharacter_addTextToList"
  SWFFontCharacter_addUTF8Chars(font.SWFFontCharacter, string.s) As "_SWFFontCharacter_addUTF8Chars"
  ;-SWFFontCharacter_addWideChars() As "_SWFFontCharacter_addWideChars"
  ;-SWFFontCharacter_exportCharacterRange() As "_SWFFontCharacter_exportCharacterRange"
  ;-SWFFontCharacter_getFont() As "_SWFFontCharacter_getFont"
  ;-SWFFontCharacter_getGlyphCode() As "_SWFFontCharacter_getGlyphCode"
  ;-SWFFontCharacter_getNGlyphs() As "_SWFFontCharacter_getNGlyphs"
  ;-SWFFontCollection_addFont() As "_SWFFontCollection_addFont"
  SWFFontCollection_getFont(collection.SWFFontCollection, index.l) As "_SWFFontCollection_getFont"
  SWFFontCollection_getFontCount(collection.SWFFontCollection) As "_SWFFontCollection_getFontCount"
  SWFFontCollection_getFonts(collection.SWFFontCollection, *count.l) As "_SWFFontCollection_getFonts"
  ;-SWFFont_buildReverseMapping() As "_SWFFont_buildReverseMapping"
  SWFFont_getAscent.f(font.SWFFont) As "_SWFFont_getAscent"
  ;-SWFFont_getCharacterAdvance() As "_SWFFont_getCharacterAdvance"
  ;-SWFFont_getCharacterKern() As "_SWFFont_getCharacterKern"
  SWFFont_getDescent.f(font.SWFFont) As "_SWFFont_getDescent"
  ;-SWFFont_getFlags() As "_SWFFont_getFlags"
  ;-SWFFont_getGlyph() As "_SWFFont_getGlyph"
  ;-SWFFont_getGlyphBounds() As "_SWFFont_getGlyphBounds"
  SWFFont_getGlyphCount(font.SWFFont) As "_SWFFont_getGlyphCount"
  SWFFont_getLeading.f(font.SWFFont) As "_SWFFont_getLeading"
  SWFFont_getName.l(font.SWFFont) As "_SWFFont_getName" ; return String
  ;-SWFFont_getScaledAscent() As "_SWFFont_getScaledAscent"
  ;-SWFFont_getScaledDescent() As "_SWFFont_getScaledDescent"
  ;-SWFFont_getScaledLeading() As "_SWFFont_getScaledLeading"
  ;-SWFFont_getScaledStringWidth() As "_SWFFont_getScaledStringWidth"
  ;-SWFFont_getScaledUTF8StringWidth() As "_SWFFont_getScaledUTF8StringWidth"
  ;-SWFFont_getScaledWideStringWidth() As "_SWFFont_getScaledWideStringWidth"
  SWFFont_getShape(font.SWFFont, c.l) As "_SWFFont_getShape"
  SWFFont_getStringWidth.f(font.SWFFont, string.a) As "_SWFFont_getStringWidth"
  SWFFont_getUTF8StringWidth.f(font.SWFFont, string.u) As "_SWFFont_getUTF8StringWidth"
  SWFFont_getWideStringWidth.f(font.SWFFont, string.l, len_.l) As "_SWFFont_getWideStringWidth"
  ;-SWFGradientMatrix_update() As "_SWFGradientMatrix_update"
  SWFGradient_addEntry(gradient.SWFGradient, ratio.f, r.b, g.b, b.b, a.b) As "_SWFGradient_addEntry"
  ;-SWFGradient_isFocalGradient() As "_SWFGradient_isFocalGradient"
  SWFGradient_setFocalPoint(gradient.SWFGradient, flocalPoint.f) As "_SWFGradient_setFocalPoint"
  SWFGradient_setInterpolationMode(gradient.SWFGradient, mode.GradientInterpolationMode) As "_SWFGradient_setInterpolationMode"
  SWFGradient_setSpreadMode(gradient.SWFGradient, mode.GradientSpreadMode) As "_SWFGradient_setSpreadMode"
  ;-SWFInitAction_getMovieClip() As "_SWFInitAction_getMovieClip"
  ;-SWFInput_byteAlign() As "_SWFInput_byteAlign"
  SWFInput_eof(input.SWFInput) As "_SWFInput_eof"
  ;-SWFInput_getChar() As "_SWFInput_getChar"
  ;-SWFInput_getSInt16() As "_SWFInput_getSInt16"
  ;-SWFInput_getUInt16() As "_SWFInput_getUInt16"
  ;-SWFInput_getUInt16_BE() As "_SWFInput_getUInt16_BE"
  ;-SWFInput_getUInt24_BE() As "_SWFInput_getUInt24_BE"
  ;-SWFInput_getUInt32() As "_SWFInput_getUInt32"
  ;-SWFInput_getUInt32_BE() As "_SWFInput_getUInt32_BE"
  SWFInput_length(input.SWFInput) As "_SWFInput_length"
  ;-SWFInput_read() As "_SWFInput_read"
  ;-SWFInput_readBits() As "_SWFInput_readBits"
  ;-SWFInput_readSBits() As "_SWFInput_readSBits"
  SWFInput_rewind(input.SWFInput) As "_SWFInput_rewind"
  SWFInput_seek(input.SWFInput, offset.l, whence.l) As "_SWFInput_seek"
  SWFInput_tell(input.SWFInput) As "_SWFInput_tell"
  ;-SWFLineStyle_equals() As "_SWFLineStyle_equals"
  ;-SWFLineStyle_equals2filled() As "_SWFLineStyle_equals2filled"
  ;-SWFLineStyle_getWidth() As "_SWFLineStyle_getWidth"
  ;-SWFMatrix_apply() As "_SWFMatrix_apply"
  ;-SWFMatrix_clearTransform() As "_SWFMatrix_clearTransform"
  ;-SWFMatrix_clearTranslate() As "_SWFMatrix_clearTranslate"
  ;-SWFMatrix_dup() As "_SWFMatrix_dup"
  SWFMatrix_getRotate0.d(m.SWFMatrix) As "_SWFMatrix_getRotate0"
  SWFMatrix_getRotate1.d(m.SWFMatrix) As "_SWFMatrix_getRotate1"
  SWFMatrix_getScaleX.d(m.SWFMatrix) As "_SWFMatrix_getScaleX"
  SWFMatrix_getScaleY.d(m.SWFMatrix) As "_SWFMatrix_getScaleY"
  SWFMatrix_getTranslateX(m.SWFMatrix) As "_SWFMatrix_getTranslateX"
  SWFMatrix_getTranslateY(m.SWFMatrix) As "_SWFMatrix_getTranslateY"
  ;-SWFMatrix_leftMultiply() As "_SWFMatrix_leftMultiply"
  ;-SWFMatrix_moveTo() As "_SWFMatrix_moveTo"
  ;-SWFMatrix_multiply() As "_SWFMatrix_multiply"
  ;-SWFMatrix_numBits() As "_SWFMatrix_numBits"
  ;-SWFMatrix_rotate() As "_SWFMatrix_rotate"
  ;-SWFMatrix_scale() As "_SWFMatrix_scale"
  ;-SWFMatrix_scaleXY() As "_SWFMatrix_scaleXY"
  ;-SWFMatrix_set() As "_SWFMatrix_set"
  ;-SWFMatrix_translate() As "_SWFMatrix_translate"
  SWFMorph_getShape1(morph.SWFMorph) As "_SWFMorph_getShape1"
  SWFMorph_getShape2(morph.SWFMorph) As "_SWFMorph_getShape2"
  SWFMovieClip_add(clip.SWFMovieClip, block.SWFBlock) As "_SWFMovieClip_add"
  SWFMovieClip_addInitAction(clip.SWFMovieClip, action.SWFAction) As "_SWFMovieClip_addInitAction"
  SWFMovieClip_labelFrame(clip.SWFMovieClip, label.s) As "_SWFMovieClip_labelFrame"
  SWFMovieClip_nextFrame(clip.SWFMovieClip) As "_SWFMovieClip_nextFrame"
  SWFMovieClip_remove(clip.SWFMovieClip, item.SWFDisplayItem) As "_SWFMovieClip_remove"
  SWFMovieClip_removeScalingGrid(clip.SWFMovieClip) As "_SWFMovieClip_removeScalingGrid"
  SWFMovieClip_setNumberOfFrames(clip.SWFMovieClip, frames.l) As "_SWFMovieClip_setNumberOfFrames"
  SWFMovieClip_setScalingGrid(clip.SWFMovieClip, x.l, y.l, w.l, h.l) As "_SWFMovieClip_setScalingGrid"
  SWFMovieClip_setSoundStream(clip.SWFMovieClip, sound.SWFSoundStream, rate.f) As "_SWFMovieClip_setSoundStream"
  SWFMovieClip_setSoundStreamAt(clip.SWFMovieClip, sound.SWFSoundStream, rate.f, skip.f) As "_SWFMovieClip_setSoundStreamAt"
  SWFMovieClip_startSound(clip.SWFMovieClip, sound.SWFSound) As "_SWFMovieClip_startSound"
  SWFMovieClip_stopSound(clip.SWFMovieClip, sound.SWFSound) As "_SWFMovieClip_stopSound"
  SWFMovie_add(movie.SWFMovie, block.SWFBlock) As "_SWFMovie_add"
  ;-SWFMovie_addBlock(movie.SWFMovie, block.SWFBlock) As "_SWFMovie_addBlock"
  SWFMovie_addExport(movie.SWFMovie, block.SWFBlock, name.s) As "_SWFMovie_addExport"
  SWFMovie_addFont(movie.SWFMovie, font.SWFFont) As "_SWFMovie_addFont"
  ;-SWFMovie_addImport() As "_SWFMovie_addImport"
  SWFMovie_addMetadata(movie.SWFMovie, xml.s) As "_SWFMovie_addMetadata"
  SWFMovie_add_internal(movie.SWFMovie, *ublock.SWFMovieBlockType) As "_SWFMovie_add_internal"
  SWFMovie_assignSymbol(m.SWFMovie, character.SWFCharacter, name.s) As "_SWFMovie_assignSymbol"
  SWFMovie_defineScene(m.SWFMovie, offset.q, name.s) As "_SWFMovie_defineScene"
  SWFMovie_getRate.f(movie.SWFMovie) As "_SWFMovie_getRate"
  SWFMovie_importCharacter(movie.SWFMovie, filename.s, name.s) As "_SWFMovie_importCharacter"
  SWFMovie_importFont(movie.SWFMovie, filename.s, name.s) As "_SWFMovie_importFont"
  SWFMovie_labelFrame(movie.SWFMovie, label.s) As "_SWFMovie_labelFrame"
  SWFMovie_namedAnchor(movie.SWFMovie, label.s) As "_SWFMovie_namedAnchor"
  SWFMovie_nextFrame(movie.SWFMovie) As "_SWFMovie_nextFrame"
  SWFMovie_output(movie.SWFMovie, method.SWFByteOutputMethod, *data_) As "_SWFMovie_output"
  SWFMovie_output_to_stream(movie.SWFMovie, *fp) As "_SWFMovie_output_to_stream"
  SWFMovie_protect(movie.SWFMovie, password.s) As "_SWFMovie_protect"
  SWFMovie_remove(movie.SWFMovie, item.SWFDisplayItem) As "_SWFMovie_remove"
  SWFMovie_replace_internal(movie.SWFMovie, item.SWFDisplayItem, *block.SWFMovieBlockType) As "_SWFMovie_replace_internal"
  SWFMovie_save(movie.SWFMovie, filename.s) As "_SWFMovie_save"
  SWFMovie_setBackground(movie.SWFMovie, r.b, g.b, b.b) As "_SWFMovie_setBackground"
  SWFMovie_setDimension(movie.SWFMovie, x.f, y.f) As "_SWFMovie_setDimension"
  SWFMovie_setNetworkAccess(movie.SWFMovie, flag.l) As "_SWFMovie_setNetworkAccess"
  SWFMovie_setNumberOfFrames(movie.SWFMovie, frames.l) As "_SWFMovie_setNumberOfFrames"
  SWFMovie_setRate(movie.SWFMovie, rate.f) As "_SWFMovie_setRate"
  SWFMovie_setScriptLimits(movie.SWFMovie, maxRecursion.l, timeout.l) As "_SWFMovie_setScriptLimits"
  SWFMovie_setSoundStream(movie.SWFMovie, sound.SWFSoundStream) As "_SWFMovie_setSoundStream"
  SWFMovie_setSoundStreamAt(movie.SWFMovie, stream.SWFSoundStream, skip.f) As "_SWFMovie_setSoundStreamAt"
  SWFMovie_setTabIndex(movie.SWFMovie, depth.l, index.l) As "_SWFMovie_setTabIndex"
  SWFMovie_startSound(movie.SWFMovie, sound.SWFSound) As "_SWFMovie_startSound"
  SWFMovie_stopSound(movie.SWFMovie, sound.SWFSound) As "_SWFMovie_stopSound"
  ;-SWFMovie_toOutput() As "_SWFMovie_toOutput"
  SWFMovie_writeExports(movie.SWFMovie) As "_SWFMovie_writeExports"
  ;-SWFOutputBlock_getLength() As "_SWFOutputBlock_getLength"
  ;-SWFOutputBlock_getOutput() As "_SWFOutputBlock_getOutput"
  ;-SWFOutputMethod() As "_SWFOutputMethod"
  ;-SWFOutput_byteAlign() As "_SWFOutput_byteAlign"
  ;-SWFOutput_checkSize() As "_SWFOutput_checkSize"
  ;-SWFOutput_getBuffer() As "_SWFOutput_getBuffer"
  ;-SWFOutput_getCurPos() As "_SWFOutput_getCurPos"
  ;-SWFOutput_getLength() As "_SWFOutput_getLength"
  ;-SWFOutput_getNext() As "_SWFOutput_getNext"
  ;-SWFOutput_grow() As "_SWFOutput_grow"
  ;-SWFOutput_numBits() As "_SWFOutput_numBits"
  ;-SWFOutput_numSBits() As "_SWFOutput_numSBits"
  ;-SWFOutput_setNext() As "_SWFOutput_setNext"
  ;-SWFOutput_truncate() As "_SWFOutput_truncate"
  ;-SWFOutput_writeAction() As "_SWFOutput_writeAction"
  ;-SWFOutput_writeBits() As "_SWFOutput_writeBits"
  ;-SWFOutput_writeBuffer() As "_SWFOutput_writeBuffer"
  ;-SWFOutput_writeCXform() As "_SWFOutput_writeCXform"
  ;-SWFOutput_writeDouble() As "_SWFOutput_writeDouble"
  ;-SWFOutput_writeEncUInt32() As "_SWFOutput_writeEncUInt32"
  ;-SWFOutput_writeFillStyle() As "_SWFOutput_writeFillStyle"
  ;-SWFOutput_writeFillStyles() As "_SWFOutput_writeFillStyles"
  ;-SWFOutput_writeFilterList() As "_SWFOutput_writeFilterList"
  ;-SWFOutput_writeFixed() As "_SWFOutput_writeFixed"
  ;-SWFOutput_writeFixed8() As "_SWFOutput_writeFixed8"
  ;-SWFOutput_writeFloat() As "_SWFOutput_writeFloat"
  ;-SWFOutput_writeFloat16() As "_SWFOutput_writeFloat16"
  ;-SWFOutput_writeGlyphShape() As "_SWFOutput_writeGlyphShape"
  ;-SWFOutput_writeGradient() As "_SWFOutput_writeGradient"
  ;-SWFOutput_writeGradientAsFilter() As "_SWFOutput_writeGradientAsFilter"
  ;-SWFOutput_writeLineStyles() As "_SWFOutput_writeLineStyles"
  ;-SWFOutput_writeMatrix() As "_SWFOutput_writeMatrix"
  ;-SWFOutput_writeMorphFillStyle() As "_SWFOutput_writeMorphFillStyle"
  ;-SWFOutput_writeMorphFillStyles() As "_SWFOutput_writeMorphFillStyles"
  ;-SWFOutput_writeMorphGradient() As "_SWFOutput_writeMorphGradient"
  ;-SWFOutput_writeMorphLineStyles() As "_SWFOutput_writeMorphLineStyles"
  ;-SWFOutput_writeMorphLineStyles2() As "_SWFOutput_writeMorphLineStyles2"
  ;-SWFOutput_writeRect() As "_SWFOutput_writeRect"
  ;-SWFOutput_writeSBits() As "_SWFOutput_writeSBits"
  ;-SWFOutput_writeSInt16() As "_SWFOutput_writeSInt16"
  ;-SWFOutput_writeSInt32() As "_SWFOutput_writeSInt32"
  ;-SWFOutput_writeSInt8() As "_SWFOutput_writeSInt8"
  ;-SWFOutput_writeSWFFilter() As "_SWFOutput_writeSWFFilter"
  ;-SWFOutput_writeString() As "_SWFOutput_writeString"
  ;-SWFOutput_writeToMethod() As "_SWFOutput_writeToMethod"
  ;-SWFOutput_writeUInt16() As "_SWFOutput_writeUInt16"
  ;-SWFOutput_writeUInt32() As "_SWFOutput_writeUInt32"
  ;-SWFOutput_writeUInt8() As "_SWFOutput_writeUInt8"
  ;-SWFPlaceObject2Block_addAction() As "_SWFPlaceObject2Block_addAction"
  ;-SWFPlaceObject2Block_addFilter() As "_SWFPlaceObject2Block_addFilter"
  ;-SWFPlaceObject2Block_setBlendMode() As "_SWFPlaceObject2Block_setBlendMode"
  ;-SWFPlaceObject2Block_setCXform() As "_SWFPlaceObject2Block_setCXform"
  ;-SWFPlaceObject2Block_setCacheFlag() As "_SWFPlaceObject2Block_setCacheFlag"
  ;-SWFPlaceObject2Block_setCharacter() As "_SWFPlaceObject2Block_setCharacter"
  ;-SWFPlaceObject2Block_setColorAdd() As "_SWFPlaceObject2Block_setColorAdd"
  ;-SWFPlaceObject2Block_setColorMult() As "_SWFPlaceObject2Block_setColorMult"
  ;-SWFPlaceObject2Block_setDepth() As "_SWFPlaceObject2Block_setDepth"
  ;-SWFPlaceObject2Block_setMaskLevel() As "_SWFPlaceObject2Block_setMaskLevel"
  ;-SWFPlaceObject2Block_setMatrix() As "_SWFPlaceObject2Block_setMatrix"
  ;-SWFPlaceObject2Block_setMove() As "_SWFPlaceObject2Block_setMove"
  ;-SWFPlaceObject2Block_setName() As "_SWFPlaceObject2Block_setName"
  ;-SWFPlaceObject2Block_setRatio() As "_SWFPlaceObject2Block_setRatio"
  SWFPosition_getMatrix(p.SWFPosition) As "_SWFPosition_getMatrix"
  SWFPosition_getRotation.d(position.SWFPosition) As "_SWFPosition_getRotation"
  SWFPosition_getX.d(position.SWFPosition) As "_SWFPosition_getX"
  SWFPosition_getXScale.d(position.SWFPosition) As "_SWFPosition_getXScale"
  SWFPosition_getXSkew.d(position.SWFPosition) As "_SWFPosition_getXSkew"
  SWFPosition_getXY(position.SWFPosition, *outX.d, *outY.d) As "_SWFPosition_getXY"
  SWFPosition_getXYScale(position.SWFPosition, *outXScale.d, *outYScale.d) As "_SWFPosition_getXYScale"
  SWFPosition_getXYSkew(position.SWFPosition, *outXSkew.d, *outYSkew.d) As "_SWFPosition_getXYSkew"
  SWFPosition_getY.d(position.SWFPosition) As "_SWFPosition_getY"
  SWFPosition_getYScale.d(position.SWFPosition) As "_SWFPosition_getYScale"
  SWFPosition_getYSkew.d(position.SWFPosition) As "_SWFPosition_getYSkew"
  SWFPosition_move(position.SWFPosition, x.d, y.d) As "_SWFPosition_move"
  SWFPosition_moveTo(position.SWFPosition, x.d, y.d) As "_SWFPosition_moveTo"
  SWFPosition_rotate(position.SWFPosition, degrees.d) As "_SWFPosition_rotate"
  SWFPosition_rotateTo(position.SWFPosition, degrees.d) As "_SWFPosition_rotateTo"
  SWFPosition_scaleX(position.SWFPosition, x.d) As "_SWFPosition_scaleX"
  SWFPosition_scaleXTo(position.SWFPosition, x.d) As "_SWFPosition_scaleXTo"
  SWFPosition_scaleXY(position.SWFPosition, x.d, y.d) As "_SWFPosition_scaleXY"
  SWFPosition_scaleXYTo(position.SWFPosition, x.d, y.d) As "_SWFPosition_scaleXYTo"
  SWFPosition_scaleY(position.SWFPosition, y.d) As "_SWFPosition_scaleY"
  SWFPosition_scaleYTo(position.SWFPosition, y.d) As "_SWFPosition_scaleYTo"
  SWFPosition_setMatrix(p.SWFPosition, a.d, b.d, c.d, d.d, x.d, y.d) As "_SWFPosition_setMatrix"
  SWFPosition_skewX(position.SWFPosition, x.d) As "_SWFPosition_skewX"
  SWFPosition_skewXTo(position.SWFPosition, x.d) As "_SWFPosition_skewXTo"
  SWFPosition_skewY(position.SWFPosition, y.d) As "_SWFPosition_skewY"
  SWFPosition_skewYTo(position.SWFPosition, y.d) As "_SWFPosition_skewYTo"
  ;-SWFPrebuiltClipLength() As "_SWFPrebuiltClipLength"
  ;-SWFRect_copy() As "_SWFRect_copy"
  ;-SWFRect_getBounds() As "_SWFRect_getBounds"
  ;-SWFRect_getHeight() As "_SWFRect_getHeight"
  ;-SWFRect_getWidth() As "_SWFRect_getWidth"
  ;-SWFRect_includePoint() As "_SWFRect_includePoint"
  ;-SWFRect_includeRect() As "_SWFRect_includeRect"
  ;-SWFRect_numBits() As "_SWFRect_numBits"
  ;-SWFRect_setBounds() As "_SWFRect_setBounds"
  ;-SWFSceneData_addFrameLabel() As "_SWFSceneData_addFrameLabel"
  ;-SWFSceneData_addScene() As "_SWFSceneData_addScene"
  ;-SWFScriptLimits_maxRecursion() As "_SWFScriptLimits_maxRecursion"
  ;-SWFScriptLimits_setTimeout() As "_SWFScriptLimits_setTimeout"
  SWFShape_addBitmapFill(shape.SWFShape, bitmap.SWFBitmap, flags.b) As "_SWFShape_addBitmapFill"
  SWFShape_addBitmapFillStyle(shape.SWFShape, bitmap.SWFBitmap, flags.b) As "_SWFShape_addBitmapFillStyle"
  SWFShape_addGradientFill(shape.SWFShape, gradient.SWFGradient, flags.b) As "_SWFShape_addGradientFill"
  SWFShape_addGradientFillStyle(shape.SWFShape, gradient.SWFGradient, flags.b) As "_SWFShape_addGradientFillStyle"
  SWFShape_addSolidFill(shape.SWFShape, r.b, g.b, b.b, a.b) As "_SWFShape_addSolidFill"
  SWFShape_addSolidFillStyle(shape.SWFShape, r.b, g.b, b.b, a.b) As "_SWFShape_addSolidFillStyle"
  ;-SWFShape_addStyleHeader() As "_SWFShape_addStyleHeader"
  SWFShape_drawArc(shape.SWFShape, r.d, startAngle.d, endAngle.d) As "_SWFShape_drawArc"
  SWFShape_drawCharacterBounds(shape.SWFShape, character.SWFCharacter) As "_SWFShape_drawCharacterBounds"
  SWFShape_drawCircle(shape.SWFShape, r.d) As "_SWFShape_drawCircle"
  SWFShape_drawCubic(shape.SWFShape, bx.d, by.d, cx.d, cy.d, dx.d, dy.d) As "_SWFShape_drawCubic"
  SWFShape_drawCubicTo(shape.SWFShape, bx.d, by.d, cx.d, cy.d, dx.d, dy.d) As "_SWFShape_drawCubicTo"
  SWFShape_drawCurve(shape.SWFShape, controlx.d, controly.d, anchorx.d, anchory.d) As "_SWFShape_drawCurve"
  SWFShape_drawCurveTo(shape.SWFShape, controlx.d, controly.d, anchorx.d, anchory.d) As "_SWFShape_drawCurveTo"
  SWFShape_drawGlyph(shape.SWFShape, font.SWFFont, c.l) As "_SWFShape_drawGlyph"
  SWFShape_drawLine(shape.SWFShape, dx.d, dy.d) As "_SWFShape_drawLine"
  SWFShape_drawLineTo(shape.SWFShape, x.d, y.d) As "_SWFShape_drawLineTo"
  ;-SWFShape_drawScaledCubicTo() As "_SWFShape_drawScaledCubicTo"
  ;-SWFShape_drawScaledCurve() As "_SWFShape_drawScaledCurve"
  ;-SWFShape_drawScaledCurveTo() As "_SWFShape_drawScaledCurveTo"
  ;-SWFShape_drawScaledGlyph() As "_SWFShape_drawScaledGlyph"
  ;-SWFShape_drawScaledLine() As "_SWFShape_drawScaledLine"
  ;-SWFShape_drawScaledLineTo() As "_SWFShape_drawScaledLineTo"
  SWFShape_drawSizedGlyph(shape.SWFShape, font.SWFFont, c.l, size.l) As "_SWFShape_drawSizedGlyph"
  SWFShape_dumpOutline(s.SWFShape) As "_SWFShape_dumpOutline"
  SWFShape_end(shape.SWFShape) As "_SWFShape_end"
  ;-SWFShape_getEdgeBounds() As "_SWFShape_getEdgeBounds"
  ;-SWFShape_getFills() As "_SWFShape_getFills"
  ;-SWFShape_getFlags() As "_SWFShape_getFlags"
  ;-SWFShape_getLines() As "_SWFShape_getLines"
  ;-SWFShape_getOutput() As "_SWFShape_getOutput"
  SWFShape_getPen(shape.SWFShape, *penX.d, *penY.d) As "_SWFShape_getPen"
  SWFShape_getPenX.d(shape.SWFShape) As "_SWFShape_getPenX"
  SWFShape_getPenY.d(shape.SWFShape) As "_SWFShape_getPenY"
  ;-SWFShape_getScaledPenX() As "_SWFShape_getScaledPenX"
  ;-SWFShape_getScaledPenY() As "_SWFShape_getScaledPenY"
  SWFShape_getVersion(shape.SWFShape) As "_SWFShape_getVersion"
  SWFShape_hideLine(shape.SWFShape) As "_SWFShape_hideLine"
  SWFShape_movePen(shape.SWFShape, x.d, y.d) As "_SWFShape_movePen"
  SWFShape_movePenTo(shape.SWFShape, x.d, y.d) As "_SWFShape_movePenTo"
  ;-SWFShape_moveScaledPen() As "_SWFShape_moveScaledPen"
  ;-SWFShape_moveScaledPenTo() As "_SWFShape_moveScaledPenTo"
  SWFShape_setLeftFill(shape.SWFShape, fill.SWFFill) As "_SWFShape_setLeftFill"
  SWFShape_setLeftFillStyle(shape.SWFShape, fill.SWFFillStyle) As "_SWFShape_setLeftFillStyle"
  SWFShape_setLine(shape.SWFShape, width.l, r.b, g.b, b.b, a.b) As "_SWFShape_setLine"
  SWFShape_setLine2(shape.SWFShape, width.l, r.b, g.b, b.b, a.b, flags.l, miterLimit.f) As "_SWFShape_setLine2"
  SWFShape_setLine2Filled(shape.SWFShape, width.l, fill.SWFFillStyle, flags.l, miterLimit.f) As "_SWFShape_setLine2Filled"
  SWFShape_setLineStyle(shape.SWFShape, width.l, r.b, g.b, b.b, a.b) As "_SWFShape_setLineStyle"
  SWFShape_setLineStyle2(shape.SWFShape, width.l, r.b, g.b, b.b, a.b, flags.l, miterLimit.f) As "_SWFShape_setLineStyle2"
  ;-SWFShape_setLineStyle2_internal() As "_SWFShape_setLineStyle2_internal"
  SWFShape_setLineStyle2filled(shape.SWFShape, width.l, fill.SWFFillStyle, flags.l, miterLimit.f) As "_SWFShape_setLineStyle2filled"
  ;-SWFShape_setLineStyle2filled_internal() As "_SWFShape_setLineStyle2filled_internal"
  ;-SWFShape_setLineStyle_internal() As "_SWFShape_setLineStyle_internal"
  ;-SWFShape_setMorphFlag() As "_SWFShape_setMorphFlag"
  SWFShape_setRenderHintingFlags(shape.SWFShape, flags.l) As "_SWFShape_setRenderHintingFlags"
  SWFShape_setRightFill(shape.SWFShape, fill.SWFFill) As "_SWFShape_setRightFill"
  SWFShape_setRightFillStyle(shape.SWFShape, fill.SWFFillStyle) As "_SWFShape_setRightFillStyle"
  SWFShape_useVersion(shape.SWFShape, version.l) As "_SWFShape_useVersion"
  SWFSoundInstance_addEnvelope(inst.SWFSoundInstance, mark44.q, left.w, right.w) As "_SWFSoundInstance_addEnvelope"
  SWFSoundInstance_setLoopCount(instance.SWFSoundInstance, count.l) As "_SWFSoundInstance_setLoopCount"
  SWFSoundInstance_setLoopInPoint(instance.SWFSoundInstance, point.q) As "_SWFSoundInstance_setLoopInPoint"
  SWFSoundInstance_setLoopOutPoint(instance.SWFSoundInstance, point.q) As "_SWFSoundInstance_setLoopOutPoint"
  SWFSoundInstance_setNoMultiple(instance.SWFSoundInstance) As "_SWFSoundInstance_setNoMultiple"
  SWFSoundStream_getDuration(sound.SWFSoundStream) As "_SWFSoundStream_getDuration"
  ;-SWFSoundStream_getFlags() As "_SWFSoundStream_getFlags"
  SWFSoundStream_getFrames(sound.SWFSoundStream) As "_SWFSoundStream_getFrames"
  ;-SWFSoundStream_getLength() As "_SWFSoundStream_getLength"
  ;-SWFSoundStream_getStreamBlock() As "_SWFSoundStream_getStreamBlock"
  ;-SWFSoundStream_getStreamHead() As "_SWFSoundStream_getStreamHead"
  ;-SWFSoundStream_rewind() As "_SWFSoundStream_rewind"
  ;-SWFSoundStream_setInitialMp3Delay() As "_SWFSoundStream_setInitialMp3Delay"
  SWFSprite_addBlock(sprite.SWFSprite, block.SWFBlock) As "_SWFSprite_addBlock"
  ;-SWFSprite_getDependencies() As "_SWFSprite_getDependencies"
  ;-SWFSprite_setNumberOfFrames() As "_SWFSprite_setNumberOfFrames"
  ;-SWFSymbolClass_addSymbol() As "_SWFSymbolClass_addSymbol"
  SWFTextField_addChars(field.SWFTextField, string.s) As "_SWFTextField_addChars"
  SWFTextField_addString(field.SWFTextField, string.a) As "_SWFTextField_addString"
  ;-SWFTextField_addUTF8Chars() As "_SWFTextField_addUTF8Chars"
  SWFTextField_addUTF8String(field.SWFTextField, string.u) As "_SWFTextField_addUTF8String"
  ;-SWFTextField_getUnresolvedFont() As "_SWFTextField_getUnresolvedFont"
  SWFTextField_setAlignment(ield.SWFTextField, alignment.SWFTextFieldAlignment) As "_SWFTextField_setAlignment"
  SWFTextField_setBounds(field.SWFTextField, width.f, height.f) As "_SWFTextField_setBounds"
  SWFTextField_setColor(field.SWFTextField, r.b, g.b, b.b, a.b) As "_SWFTextField_setColor"
  SWFTextField_setFieldHeight(field.SWFTextField, height.f) As "_SWFTextField_setFieldHeight"
  SWFTextField_setFlags(field.SWFTextField, flags.l) As "_SWFTextField_setFlags"
  SWFTextField_setFont(field.SWFTextField, font.SWFBlock) As "_SWFTextField_setFont"
  ;-SWFTextField_setFontCharacter() As "_SWFTextField_setFontCharacter"
  SWFTextField_setHeight(field.SWFTextField, height.f) As "_SWFTextField_setHeight"
  SWFTextField_setIndentation(field.SWFTextField, indentation.f) As "_SWFTextField_setIndentation"
  SWFTextField_setLeftMargin(field.SWFTextField, leftMargin.f) As "_SWFTextField_setLeftMargin"
  SWFTextField_setLength(field.SWFTextField, length.l) As "_SWFTextField_setLength"
  SWFTextField_setLineSpacing(field.SWFTextField, lineSpacing.f) As "_SWFTextField_setLineSpacing"
  SWFTextField_setPadding(field.SWFTextField, padding.f) As "_SWFTextField_setPadding"
  ;-SWFTextField_setRightMargin() As "_SWFTextField_setRightMargin"
  ;-SWFTextField_setScaledBounds() As "_SWFTextField_setScaledBounds"
  ;-SWFTextField_setScaledFieldHeight() As "_SWFTextField_setScaledFieldHeight"
  ;-SWFTextField_setScaledFontHeight() As "_SWFTextField_setScaledFontHeight"
  ;-SWFTextField_setScaledIndentation() As "_SWFTextField_setScaledIndentation"
  ;-SWFTextField_setScaledLeftMargin() As "_SWFTextField_setScaledLeftMargin"
  ;-SWFTextField_setScaledLineSpacing() As "_SWFTextField_setScaledLineSpacing"
  ;-SWFTextField_setScaledPadding() As "_SWFTextField_setScaledPadding"
  SWFTextField_setScaledRightMargin(field.SWFTextField, rightMargin.f) As "_SWFTextField_setScaledRightMargin"
  ;-SWFTextField_setScaledWidth() As "_SWFTextField_setScaledWidth"
  SWFTextField_setVariableName(field.SWFTextField, name.s) As "_SWFTextField_setVariableName"
  ;-SWFTextRecord_getNextRecord() As "_SWFTextRecord_getNextRecord"
  ;-SWFTextRecord_getString() As "_SWFTextRecord_getString"
  ;-SWFTextRecord_getUnresolvedFont() As "_SWFTextRecord_getUnresolvedFont"
  ;-SWFTextRecord_setFontCharacter() As "_SWFTextRecord_setFontCharacter"
  SWFText_addString(text.SWFText, string.a, advance.l) As "_SWFText_addString"
  ;-SWFText_addTextRecord() As "_SWFText_addTextRecord"
  SWFText_addUTF8String(text.SWFText, string.u, advance.l) As "_SWFText_addUTF8String"
  SWFText_addWideString(text.SWFText, string.l, strlen.l, advance.l) As "_SWFText_addWideString"
  SWFText_getAscent.f(text.SWFText) As "_SWFText_getAscent"
  SWFText_getDescent.f(text.SWFText) As "_SWFText_getDescent"
  ;-SWFText_getInitialRecord() As "_SWFText_getInitialRecord"
  SWFText_getLeading.f(text.SWFText) As "_SWFText_getLeading"
  ;-SWFText_getScaledAscent() As "_SWFText_getScaledAscent"
  ;-SWFText_getScaledDescent() As "_SWFText_getScaledDescent"
  ;-SWFText_getScaledLeading() As "_SWFText_getScaledLeading"
  ;-SWFText_getScaledStringWidth() As "_SWFText_getScaledStringWidth"
  ;-SWFText_getScaledUTF8StringWidth() As "_SWFText_getScaledUTF8StringWidth"
  ;-SWFText_getScaledWideStringWidth() As "_SWFText_getScaledWideStringWidth"
  SWFText_getStringWidth(text.SWFText, string.a) As "_SWFText_getStringWidth"
  SWFText_getUTF8StringWidth(text.SWFText, string.u) As "_SWFText_getUTF8StringWidth"
  SWFText_getWideStringWidth(text.SWFText, string.l) As "_SWFText_getWideStringWidth"
  SWFText_moveTo(text.SWFText, x.f, y.f) As "_SWFText_moveTo"
  ;-SWFText_resolveCodes() As "_SWFText_resolveCodes"
  ;-SWFText_scaledMoveTo() As "_SWFText_scaledMoveTo"
  SWFText_setColor(text.SWFText, r.b, g.b, b.b, a.b) As "_SWFText_setColor"
  SWFText_setFont(text.SWFText, font.SWFFont) As "_SWFText_setFont"
  SWFText_setHeight(text.SWFText, height.f) As "_SWFText_setHeight"
  ;-SWFText_setScaledHeight() As "_SWFText_setScaledHeight"
  ;-SWFText_setScaledSpacing() As "_SWFText_setScaledSpacing"
  SWFText_setSpacing(text.SWFText, spacing.f) As "_SWFText_setSpacing"
  ;-SWFVideoStream_getFrameNumber() As "_SWFVideoStream_getFrameNumber"
  SWFVideoStream_getNumFrames(stream.SWFVideoStream) As "_SWFVideoStream_getNumFrames"
  ;-SWFVideoStream_getVideoFrame() As "_SWFVideoStream_getVideoFrame"
  SWFVideoStream_hasAudio(stream.SWFVideoStream) As "_SWFVideoStream_hasAudio"
  SWFVideoStream_nextFrame(stream.SWFVideoStream) As "_SWFVideoStream_nextFrame"
  SWFVideoStream_seek(stream.SWFVideoStream, frame.l, whence.l) As "_SWFVideoStream_seek"
  SWFVideoStream_setDimension(stream.SWFVideoStream, width.l, height.l) As "_SWFVideoStream_setDimension"
  SWFVideoStream_setFrameMode(stream.SWFVideoStream, mode.l) As "_SWFVideoStream_setFrameMode"
  ;-UTF8ExpandString() As "_UTF8ExpandString"
  ;-UTF8GetChar() As "_UTF8GetChar"
  ;-UTF8Length() As "_UTF8Length"
  ;-addConstant() As "_addConstant"
  ;-addctx() As "_addctx"
  ;-bufferBranchTarget() As "_bufferBranchTarget"
  ;-bufferCheckSize() As "_bufferCheckSize"
  ;-bufferConcat() As "_bufferConcat"
  ;-bufferConcatSimple() As "_bufferConcatSimple"
  ;-bufferLength() As "_bufferLength"
  ;-bufferPatchLength() As "_bufferPatchLength"
  ;-bufferPatchPushLength() As "_bufferPatchPushLength"
  ;-bufferPatchTargets() As "_bufferPatchTargets"
  ;-bufferResolveJumpsFull() As "_bufferResolveJumpsFull"
  ;-bufferResolveSwitch() As "_bufferResolveSwitch"
  ;-bufferWriteBoolean() As "_bufferWriteBoolean"
  ;-bufferWriteBuffer() As "_bufferWriteBuffer"
  ;-bufferWriteClass() As "_bufferWriteClass"
  ;-bufferWriteConstantString() As "_bufferWriteConstantString"
  ;-bufferWriteConstants() As "_bufferWriteConstants"
  ;-bufferWriteData() As "_bufferWriteData"
  ;-bufferWriteDataAndPush() As "_bufferWriteDataAndPush"
  ;-bufferWriteDouble() As "_bufferWriteDouble"
  ;-bufferWriteFloat() As "_bufferWriteFloat"
  ;-bufferWriteFunction() As "_bufferWriteFunction"
  ;-bufferWriteHardString() As "_bufferWriteHardString"
  ;-bufferWriteInt() As "_bufferWriteInt"
  ;-bufferWriteNull() As "_bufferWriteNull"
  ;-bufferWriteOp() As "_bufferWriteOp"
  ;-bufferWriteProperty() As "_bufferWriteProperty"
  ;-bufferWritePushOp() As "_bufferWritePushOp"
  ;-bufferWritePushString() As "_bufferWritePushString"
  ;-bufferWriteRegister() As "_bufferWriteRegister"
  ;-bufferWriteS16() As "_bufferWriteS16"
  ;-bufferWriteSetRegister() As "_bufferWriteSetRegister"
  ;-bufferWriteString() As "_bufferWriteString"
  ;-bufferWriteU8() As "_bufferWriteU8"
  ;-bufferWriteUndef() As "_bufferWriteUndef"
  ;-bufferWriteWTHITProperty() As "_bufferWriteWTHITProperty"
  ;-chkctx() As "_chkctx"
  compileSWFActionCode(script.s) As "_compileSWFActionCode"
  ;-completeDefineSWFSoundBlock() As "_completeDefineSWFSoundBlock"
  ;-completeDefineSWFSoundWithSoundStreamBlock() As "_completeDefineSWFSoundWithSoundStreamBlock"
  ;-completeSWFBlock() As "_completeSWFBlock"
  ;-completeSWFButton() As "_completeSWFButton"
  ;-completeSWFButtonSound() As "_completeSWFButtonSound"
  ;-completeSWFImportBlock() As "_completeSWFImportBlock"
  ;-completeSWFImportCharacter() As "_completeSWFImportCharacter"
  ;-completeSWFPlaceObject2Block() As "_completeSWFPlaceObject2Block"
  ;-completeSWFSoundInstance() As "_completeSWFSoundInstance"
  ;-completeSWFSoundStream() As "_completeSWFSoundStream"
  ;-completeSWFTextField() As "_completeSWFTextField"
  ;-completeSWFVideoFrame() As "_completeSWFVideoFrame"
  ;-completeSWFVideoStream() As "_completeSWFVideoStream"
  ;-delctx() As "_delctx"
  ;-destroyASClass() As "_destroyASClass"
  ;-destroyASFunction() As "_destroyASFunction"
  ;-destroyBuffer() As "_destroyBuffer"
  ;-destroyFLVStream() As "_destroyFLVStream"
  destroySWFAction(action.SWFAction) As "_destroySWFAction"
  destroySWFBinaryData(*data_.SWFBinaryData) As "_destroySWFBinaryData"
  destroySWFBitmap(bitmap.SWFBitmap) As "_destroySWFBitmap"
  ;-destroySWFBlock() As "_destroySWFBlock"
  ;-destroySWFBlockList() As "_destroySWFBlockList"
  destroySWFBlur(b.SWFBlur) As "_destroySWFBlur"
  destroySWFBrowserFont(browserFont.SWFBrowserFont) As "_destroySWFBrowserFont"
  destroySWFButton(button.SWFButton) As "_destroySWFButton"
  ;-destroySWFButtonSound() As "_destroySWFButtonSound"
  destroySWFCXform(cXform.SWFCXform) As "_destroySWFCXform"
  ;-destroySWFCharacter() As "_destroySWFCharacter"
  ;-destroySWFDisplayItem() As "_destroySWFDisplayItem"
  ;-destroySWFDisplayList() As "_destroySWFDisplayList"
  ;-destroySWFFileAttributes() As "_destroySWFFileAttributes"
  destroySWFFill(fill.SWFFill) As "_destroySWFFill"
  destroySWFFillStyle(fill.SWFFillStyle) As "_destroySWFFillStyle"
  destroySWFFilter(filter.SWFFilter) As "_destroySWFFilter"
  ;-destroySWFFilterList() As "_destroySWFFilterList"
  destroySWFFilterMatrix(m.SWFFilterMatrix) As "_destroySWFFilterMatrix"
  destroySWFFont(font.SWFFont) As "_destroySWFFont"
  ;-destroySWFFontCharacter() As "_destroySWFFontCharacter"
  destroySWFFontCollection(collection.SWFFontCollection) As "_destroySWFFontCollection"
  destroySWFGradient(gradient.SWFGradient) As "_destroySWFGradient"
  ;-destroySWFImportBlock() As "_destroySWFImportBlock"
  destroySWFInitAction(init.SWFInitAction) As "_destroySWFInitAction"
  destroySWFInput(input.SWFInput) As "_destroySWFInput"
  ;-destroySWFJpegAlpha_andInputs() As "_destroySWFJpegAlpha_andInputs"
  ;-destroySWFJpegBitmap() As "_destroySWFJpegBitmap"
  ;-destroySWFMatrix() As "_destroySWFMatrix"
  ;-destroySWFMetadata() As "_destroySWFMetadata"
  destroySWFMorph(morph.SWFMorph) As "_destroySWFMorph"
  destroySWFMovie(movie.SWFMovie) As "_destroySWFMovie"
  destroySWFMovieClip(movieClip.SWFMovieClip) As "_destroySWFMovieClip"
  ;-destroySWFOutput() As "_destroySWFOutput"
  ;-destroySWFOutputBlock() As "_destroySWFOutputBlock"
  ;-destroySWFPlaceObject2Block() As "_destroySWFPlaceObject2Block"
  destroySWFPosition(position.SWFPosition) As "_destroySWFPosition"
  ;-destroySWFPrebuilt() As "_destroySWFPrebuilt"
  destroySWFPrebuiltClip(clip.SWFPrebuiltClip) As "_destroySWFPrebuiltClip"
  ;-destroySWFProtect() As "_destroySWFProtect"
  ;-destroySWFRect() As "_destroySWFRect"
  ;-destroySWFScalingGrid() As "_destroySWFScalingGrid"
  ;-destroySWFSceneData() As "_destroySWFSceneData"
  ;-destroySWFScriptLimits() As "_destroySWFScriptLimits"
  destroySWFShadow(s.SWFShadow) As "_destroySWFShadow"
  destroySWFShape(shape.SWFShape) As "_destroySWFShape"
  destroySWFSound(sound.SWFSound) As "_destroySWFSound"
  destroySWFSoundInstance(inst.SWFSoundInstance) As "_destroySWFSoundInstance"
  destroySWFSoundStream(soundStream.SWFSoundStream) As "_destroySWFSoundStream"
  destroySWFSprite(sprite.SWFSprite) As "_destroySWFSprite"
  ;-destroySWFSymbolClass() As "_destroySWFSymbolClass"
  ;-destroySWFTabIndex() As "_destroySWFTabIndex"
  destroySWFText(text.SWFText) As "_destroySWFText"
  destroySWFTextField(textField.SWFTextField) As "_destroySWFTextField"
  ;-destroySWFTextRecord() As "_destroySWFTextRecord"
  destroySWFVideoStream(stream.SWFVideoStream) As "_destroySWFVideoStream"
  ;-do_unput4() As "_do_unput4"
  ;-do_unput5() As "_do_unput5"
  ;-dumpBytes() As "_dumpBytes"
  ;-dumpJpegBlock() As "_dumpJpegBlock"
  ;-error_default() As "_error_default"
  fileOutputMethod(b.b, *data_) As "_fileOutputMethod"
  ;-getMP3Duration() As "_getMP3Duration"
  ;-getMP3Flags() As "_getMP3Flags"
  ;-getMP3Samples() As "_getMP3Samples"
  ;-getSWFOutputBlockLength() As "_getSWFOutputBlockLength"
  ;-getTransparentColor() As "_getTransparentColor"
  loadSWFFontFromFile(*file) As "_loadSWFFontFromFile"
  ;-loadSWFFontFromInput() As "_loadSWFFontFromInput"
  ;-loadSWFFontTTF() As "_loadSWFFontTTF"
  ;-loadSWFFont_fromFdbFile() As "_loadSWFFont_fromFdbFile"
  ;-loadTTFCollection() As "_loadTTFCollection"
  ;-lookupProperty() As "_lookupProperty"
  ;-lower() As "_lower"
  ;-methodWriteJpegFile() As "_methodWriteJpegFile"
  ;-methodWriteUInt16() As "_methodWriteUInt16"
  ;-methodWriteUInt32() As "_methodWriteUInt32"
  ;-ming_gc_add_node() As "_ming_gc_add_node"
  ;-ming_gc_remove_node() As "_ming_gc_remove_node"
  ;-newASClass() As "_newASClass"
  ;-newASClassMember_buffer() As "_newASClassMember_buffer"
  ;-newASClassMember_function() As "_newASClassMember_function"
  ;-newASClassMember_variable() As "_newASClassMember_variable"
  ;-newASFunction() As "_newASFunction"
  ;-newASVariable() As "_newASVariable"
  newBevelFilter(*shadowColor.SWFColor, *highlightColor.SWFColor, blur.SWFBlur, shadow.SWFShadow, flags.l) As "_newBevelFilter"
  newBlurFilter(blur.SWFBlur) As "_newBlurFilter"
  ;-newBuffer() As "_newBuffer"
  newColorMatrixFilter(matrix.SWFFilterMatrix) As "_newColorMatrixFilter"
  newConvolutionFilter(matrix.SWFFilterMatrix, divisor.f, bias.f, *color.SWFColor, flags.l) As "_newConvolutionFilter"
  newDropShadowFilter(*color.SWFColor, blur.SWFBlur, shadow.SWFShadow, flags.l) As "_newDropShadowFilter"
  ;-newEmptySWFBlock() As "_newEmptySWFBlock"
  newGlowFilter(*color.SWFColor, blur.SWFBlur, strength.f, flags.l) As "_newGlowFilter"
  newGradientBevelFilter(gradient.SWFGradient, blur.SWFBlur, shadow.SWFShadow, flags.l) As "_newGradientBevelFilter"
  newGradientGlowFilter(gradient.SWFGradient, blur.SWFBlur, shadow.SWFShadow, flags.l) As "_newGradientGlowFilter"
  newSWFAction(script.s) As "_newSWFAction"
  newSWFAction_fromFile(filename.s) As "_newSWFAction_fromFile"
  newSWFAddCXform(rAdd.l, gAdd.l, bAdd.l, aAdd.l) As "_newSWFAddCXform"
  newSWFBinaryData(*blob.b, length.l) As "_newSWFBinaryData"
  newSWFBitmapFillStyle(bitmap.SWFCharacter, flags.b) As "_newSWFBitmapFillStyle"
  newSWFBitmap_fromInput(input.SWFInput) As "_newSWFBitmap_fromInput"
  newSWFBitmap_fromRawImg(*raw, srcFmt.SWFRawImgFmt, dstFmt.SWFRawImgFmt, width.l, height.l) As "_newSWFBitmap_fromRawImg"
  ;-newSWFBlockList() As "_newSWFBlockList"
  newSWFBlur(blurX.f, blurY.f, passes.l) As "_newSWFBlur"
  newSWFBrowserFont(name.s) As "_newSWFBrowserFont"
  newSWFButton() As "_newSWFButton"
  ;-newSWFButtonSound() As "_newSWFButtonSound"
  newSWFCXform(rAdd.l, gAdd.l, bAdd.l, aAdd.l, rMult.f, gMult.f, bMult.f, aMult.f) As "_newSWFCXform"
  newSWFDBLBitmap(*f) As "_newSWFDBLBitmap"
  ;-newSWFDBLBitmapData_fromData() As "_newSWFDBLBitmapData_fromData"
  newSWFDBLBitmapData_fromGifFile(name.s) As "_newSWFDBLBitmapData_fromGifFile"
  newSWFDBLBitmapData_fromGifInput(input.SWFInput) As "_newSWFDBLBitmapData_fromGifInput"
  newSWFDBLBitmapData_fromPngFile(name.s) As "_newSWFDBLBitmapData_fromPngFile"
  newSWFDBLBitmapData_fromPngInput(input.SWFInput) As "_newSWFDBLBitmapData_fromPngInput"
  newSWFDBLBitmap_fromInput(input.SWFInput) As "_newSWFDBLBitmap_fromInput"
  ;-newSWFDisplayList() As "_newSWFDisplayList"
  ;-newSWFDummyFontCharacter() As "_newSWFDummyFontCharacter"
  ;-newSWFEndBlock() As "_newSWFEndBlock"
  ;-newSWFExportBlock() As "_newSWFExportBlock"
  ;-newSWFFileAttributes() As "_newSWFFileAttributes"
  newSWFFill(fillstyle.SWFFillStyle) As "_newSWFFill"
  ;-newSWFFilterList() As "_newSWFFilterList"
  newSWFFilterMatrix(cols.l, rows.l, *vals.f) As "_newSWFFilterMatrix"
  ;-newSWFFont() As "_newSWFFont"
  ;-newSWFFontCharacter() As "_newSWFFontCharacter"
  ;-newSWFFontCollection() As "_newSWFFontCollection"
  newSWFFontCollection_fromFile(filename.s) As "_newSWFFontCollection_fromFile"
  newSWFFont_fromFile(filename.s) As "_newSWFFont_fromFile"
  ;-newSWFFrameLabelBlock() As "_newSWFFrameLabelBlock"
  ;-newSWFGlyphShape() As "_newSWFGlyphShape"
  newSWFGradient() As "_newSWFGradient"
  newSWFGradientFillStyle(gradient.SWFGradient, radial.b) As "_newSWFGradientFillStyle"
  ;-newSWFImportBlock() As "_newSWFImportBlock"
  newSWFInitAction(action.SWFAction) As "_newSWFInitAction"
  ;-newSWFInitAction_MovieClip() As "_newSWFInitAction_MovieClip"
  newSWFInitAction_withId(action.SWFAction, id.l) As "_newSWFInitAction_withId"
  newSWFInput_allocedBuffer(*buffer, length.l) As "_newSWFInput_allocedBuffer"
  newSWFInput_buffer(*buffer, length.l) As "_newSWFInput_buffer"
  newSWFInput_bufferCopy(*buffer, length.l) As "_newSWFInput_bufferCopy"
  newSWFInput_file(*f) As "_newSWFInput_file"
  newSWFInput_filename(filename.s) As "_newSWFInput_filename"
  newSWFInput_input(in.SWFInput, length.l) As "_newSWFInput_input"
  newSWFInput_stream(*f) As "_newSWFInput_stream"
  newSWFJpegBitmap(*f) As "_newSWFJpegBitmap"
  newSWFJpegBitmap_fromInput(input.SWFInput) As "_newSWFJpegBitmap_fromInput"
  newSWFJpegWithAlpha(*f, *alpha) As "_newSWFJpegWithAlpha"
  newSWFJpegWithAlpha_fromInput(input.SWFInput, alpha.SWFInput) As "_newSWFJpegWithAlpha_fromInput"
  newSWFLineStyle(width.l, r.b, g.b, b.b, a.b) As "_newSWFLineStyle"
  newSWFLineStyle2(width.l, r.b, g.b, b.b, a.b, flags.l, miterLimit.f) As "_newSWFLineStyle2"
  newSWFLineStyle2_filled(width.l, fill.SWFFillStyle, flags.l, miterLimit.f) As "_newSWFLineStyle2_filled"
  ;-newSWFMatrix() As "_newSWFMatrix"
  ;-newSWFMetadata() As "_newSWFMetadata"
  newSWFMorphShape() As "_newSWFMorphShape"
  newSWFMovie() As "_newSWFMovie"
  newSWFMovieClip() As "_newSWFMovieClip"
  newSWFMovieWithVersion(version.l) As "_newSWFMovieWithVersion"
  newSWFMultCXform(rMult.f, gMult.f, bMult.f, aMult.f) As "_newSWFMultCXform"
  ;-newSWFNamedAnchorBlock() As "_newSWFNamedAnchorBlock"
  ;-newSWFOutput() As "_newSWFOutput"
  ;-newSWFOutputBlock() As "_newSWFOutputBlock"
  ;-newSWFPlaceObject2Block() As "_newSWFPlaceObject2Block"
  ;-newSWFPlaceObjectBlock() As "_newSWFPlaceObjectBlock"
  newSWFPosition(matrix.SWFMatrix) As "_newSWFPosition"
  ;-newSWFPrebuilt() As "_newSWFPrebuilt"
  ;-newSWFPrebuiltClip() As "_newSWFPrebuiltClip"
  newSWFPrebuiltClip_fromFile(filename.s) As "_newSWFPrebuiltClip_fromFile"
  newSWFPrebuiltClip_fromInput(input.SWFInput) As "_newSWFPrebuiltClip_fromInput"
  ;-newSWFProtect() As "_newSWFProtect"
  ;-newSWFRect() As "_newSWFRect"
  ;-newSWFRemoveObject2Block() As "_newSWFRemoveObject2Block"
  ;-newSWFRemoveObjectBlock() As "_newSWFRemoveObjectBlock"
  ;-newSWFRotateMatrix() As "_newSWFRotateMatrix"
  ;-newSWFScalingGrid() As "_newSWFScalingGrid"
  ;-newSWFSceneData() As "_newSWFSceneData"
  ;-newSWFScriptLimits() As "_newSWFScriptLimits"
  ;-newSWFSetBackgroundBlock() As "_newSWFSetBackgroundBlock"
  newSWFShadow(angle.f, distance.f, strength.f) As "_newSWFShadow"
  newSWFShape() As "_newSWFShape"
  newSWFShapeFromBitmap(bitmap.SWFBitmap, flag.l) As "_newSWFShapeFromBitmap"
  ;-newSWFShowFrameBlock() As "_newSWFShowFrameBlock"
  newSWFSolidFillStyle(r.b, g.b, b.b, a.b) As "_newSWFSolidFillStyle"
  newSWFSound(*file, flags.b) As "_newSWFSound"
  newSWFSoundFromFileno(fd.l, flags.b) As "_newSWFSoundFromFileno"
  ;-newSWFSoundInstance() As "_newSWFSoundInstance"
  ;-newSWFSoundInstance_startNoMultiple() As "_newSWFSoundInstance_startNoMultiple"
  ;-newSWFSoundInstance_stop() As "_newSWFSoundInstance_stop"
  newSWFSoundStream(*file) As "_newSWFSoundStream"
  newSWFSoundStreamFromFileno(fd.l) As "_newSWFSoundStreamFromFileno"
  ;-newSWFSoundStream_fromInput() As "_newSWFSoundStream_fromInput"
  newSWFSound_fromInput(input.SWFInput, flags.b) As "_newSWFSound_fromInput"
  newSWFSound_fromSoundStream(stream.SWFSoundStream) As "_newSWFSound_fromSoundStream"
  newSWFSprite() As "_newSWFSprite"
  ;-newSWFSpriteDisplayList() As "_newSWFSpriteDisplayList"
  ;-newSWFSymbolClass() As "_newSWFSymbolClass"
  ;-newSWFTabIndex() As "_newSWFTabIndex"
  newSWFText() As "_newSWFText"
  newSWFText2() As "_newSWFText2"
  newSWFTextField() As "_newSWFTextField"
  newSWFVideoStream() As "_newSWFVideoStream"
  newSWFVideoStream_fromFile(*f) As "_newSWFVideoStream_fromFile"
  newSWFVideoStream_fromInput(input.SWFInput) As "_newSWFVideoStream_fromInput"
  ;-newSizedSWFOutput() As "_newSizedSWFOutput"
  ;-nextMP3Frame() As "_nextMP3Frame"
  ;-openPngFromInput() As "_openPngFromInput"
  ;-printActionRecord() As "_printActionRecord"
  ;-printDoAction() As "_printDoAction"
  ;-println() As "_println"
  ;-ReadDouble() As "_readDouble"
  ;-readGif() As "_readGif"
  ;-readMP3Header() As "_readMP3Header"
  ;-readSInt16() As "_readSInt16"
  ;-readSInt32() As "_readSInt32"
  ;-readSInt8() As "_readSInt8"
  ;-ReadString() As "_readString"
  ;-readUInt16() As "_readUInt16"
  ;-readUInt32() As "_readUInt32"
  ;-readUInt8() As "_readUInt8"
  ;-read_int() As "_read_int"
  ;-setSWFErrorFunction() As "_setSWFErrorFunction"
  ;-setSWFWarnFunction() As "_setSWFWarnFunction"
  ;-skipJpegBlock() As "_skipJpegBlock"
  ;-skipMP3() As "_skipMP3"
  ;-stringConcat() As "_stringConcat"
  ;-swf4ParseInit() As "_swf4ParseInit"
  ;-swf4_create_buffer() As "_swf4_create_buffer"
  ;-swf4_delete_buffer() As "_swf4_delete_buffer"
  ;-swf4_flush_buffer() As "_swf4_flush_buffer"
  ;-swf4_scan_buffer() As "_swf4_scan_buffer"
  ;-swf4_scan_bytes() As "_swf4_scan_bytes"
  ;-swf4_scan_string() As "_swf4_scan_string"
  ;-swf4_switch_to_buffer() As "_swf4_switch_to_buffer"
  ;-swf4alloc() As "_swf4alloc"
  ;-swf4error() As "_swf4error"
  ;-swf4free() As "_swf4free"
  ;-swf4get_debug() As "_swf4get_debug"
  ;-swf4get_in() As "_swf4get_in"
  ;-swf4get_leng() As "_swf4get_leng"
  ;-swf4get_lineno() As "_swf4get_lineno"
  ;-swf4get_out() As "_swf4get_out"
  ;-swf4get_text() As "_swf4get_text"
  ;-swf4lex() As "_swf4lex"
  ;-swf4lex_destroy() As "_swf4lex_destroy"
  ;-swf4parse() As "_swf4parse"
  ;-swf4pop_buffer_state() As "_swf4pop_buffer_state"
  ;-swf4push_buffer_state() As "_swf4push_buffer_state"
  ;-swf4realloc() As "_swf4realloc"
  ;-swf4restart() As "_swf4restart"
  ;-swf4set_debug() As "_swf4set_debug"
  ;-swf4set_in() As "_swf4set_in"
  ;-swf4set_lineno() As "_swf4set_lineno"
  ;-swf4set_out() As "_swf4set_out"
  ;-swf4wrap() As "_swf4wrap"
  ;-swf5ParseInit() As "_swf5ParseInit"
  ;-swf5_create_buffer() As "_swf5_create_buffer"
  ;-swf5_delete_buffer() As "_swf5_delete_buffer"
  ;-swf5_flush_buffer() As "_swf5_flush_buffer"
  ;-swf5_scan_buffer() As "_swf5_scan_buffer"
  ;-swf5_scan_bytes() As "_swf5_scan_bytes"
  ;-swf5_scan_string() As "_swf5_scan_string"
  ;-swf5_switch_to_buffer() As "_swf5_switch_to_buffer"
  ;-swf5alloc() As "_swf5alloc"
  ;-swf5error() As "_swf5error"
  ;-swf5free() As "_swf5free"
  ;-swf5get_debug() As "_swf5get_debug"
  ;-swf5get_in() As "_swf5get_in"
  ;-swf5get_leng() As "_swf5get_leng"
  ;-swf5get_lineno() As "_swf5get_lineno"
  ;-swf5get_out() As "_swf5get_out"
  ;-swf5get_text() As "_swf5get_text"
  ;-swf5lex() As "_swf5lex"
  ;-swf5lex_destroy() As "_swf5lex_destroy"
  ;-swf5parse() As "_swf5parse"
  ;-swf5pop_buffer_state() As "_swf5pop_buffer_state"
  ;-swf5push_buffer_state() As "_swf5push_buffer_state"
  ;-swf5realloc() As "_swf5realloc"
  ;-swf5restart() As "_swf5restart"
  ;-swf5set_debug() As "_swf5set_debug"
  ;-swf5set_in() As "_swf5set_in"
  ;-swf5set_lineno() As "_swf5set_lineno"
  ;-swf5set_out() As "_swf5set_out"
  ;-swf5wrap() As "_swf5wrap"
  ;-warn_default() As "_warn_default"
  ;-writeSWFBlockToMethod() As "_writeSWFBlockToMethod"
  ;-writeSWFButtonSoundToMethod() As "_writeSWFButtonSoundToMethod"
  ;-writeSWFButtonToMethod() As "_writeSWFButtonToMethod"
  ;-writeSWFFontCharacterToMethod() As "_writeSWFFontCharacterToMethod"
  ;-writeSWFImportBlockToMethod() As "_writeSWFImportBlockToMethod"
  ;-writeSWFJpegBitmapToMethod() As "_writeSWFJpegBitmapToMethod"
  ;-writeSWFJpegWithAlphaToMethod() As "_writeSWFJpegWithAlphaToMethod"
  ;-writeSWFMorphBlockToStream() As "_writeSWFMorphBlockToStream"
  ;-writeSWFOutputBlockToStream() As "_writeSWFOutputBlockToStream"
  ;-writeSWFPlaceObject2BlockToStream() As "_writeSWFPlaceObject2BlockToStream"
  ;-writeSWFSoundInstanceToMethod() As "_writeSWFSoundInstanceToMethod"
  ;-writeSWFSoundStreamToMethod() As "_writeSWFSoundStreamToMethod"
  ;-writeSWFSoundToStream() As "_writeSWFSoundToStream"
  ;-writeSWFSoundWithSoundStreamToMethod() As "_writeSWFSoundWithSoundStreamToMethod"
  ;-writeSWFSoundWithSoundStreamToStream() As "_writeSWFSoundWithSoundStreamToStream"
  ;-writeSWFTextFieldToMethod() As "_writeSWFTextFieldToMethod"
  ;-writeSWFVideoFrameToMethod() As "_writeSWFVideoFrameToMethod"
  ;-writeSWFVideoStreamToMethod() As "_writeSWFVideoStreamToMethod"
EndImport