XIncludeFile "RW_DevIL_Res.pb"

CompilerIf #PB_Compiler_Unicode = #True
  #DevIL_Lib_Path = "unicode/"
CompilerElse
  #DevIL_Lib_Path = ""
CompilerEndIf

Import #DevIL_Lib_Path+"DevIL.lib"
  ilActiveFace.ILboolean(Number.ILuint) As "_ilActiveFace@4"
  ilActiveImage.ILboolean(Number.ILuint) As "_ilActiveImage@4"
  ilActiveLayer.ILboolean(Number.ILuint) As "_ilActiveLayer@4"
  ilActiveMipmap.ILboolean(Number.ILuint) As "_ilActiveMipmap@4"
  ilApplyProfile.ILboolean(InProfile.ILstring, OutProfile.ILstring) As "_ilApplyProfile@8"
  ilApplyPal.ILboolean(FileName.ILconst_string) As "_ilApplyPal@4"
  ilBindImage(Image.ILuint) As "_ilBindImage@4"
  ilBlit.ILboolean(Source.ILuint, DestX.ILint, DestY.ILint, DestZ.ILint, SrcX.ILuint, SrcY.ILuint, SrcZ.ILuint, Width.ILuint, Height.ILuint, Depth.ILuint) As "_ilBlit@40"
  ilClampNTSC.ILboolean() As "_ilClampNTSC@0"
  ilClearColour(Red.ILclampf, Green.ILclampf, Blue.ILclampf, Alpha.ILclampf) As "_ilClearColour@16"
  ilClearImage.ILboolean() As "_ilClearImage@0"
  ilCloneCurImage.ILuint() As "_ilCloneCurImage@0"
  ilCompressDXT(*Data_.ILubyte, Width.ILuint, Height.ILuint, Depth.ILuint, DXTCFormat.ILenum, *DXTCSize.ILuint) As "_ilCompressDXT@24"
  ilCompressFunc.ILboolean(Mode.ILenum) As "_ilCompressFunc@4"
  ilConvertImage.ILboolean(DestFormat.ILenum, DestType.ILenum) As "_ilConvertImage@8"
  ilConvertPal.ILboolean(DestFormat.ILenum) As "_ilConvertPal@4"
  ilCopyImage.ILboolean(Src.ILuint) As "_ilCopyImage@4"
  ilCopyPixels.ILuint(XOff.ILuint, YOff.ILuint, ZOff.ILuint, Width.ILuint, Height.ILuint, Depth.ILuint, Format.ILenum, Type.ILenum, *Data_) As "_ilCopyPixels@36"
  ilCreateSubImage.ILuint(Type.ILenum, num.ILuint) As "_ilCreateSubImage@8"
  ilDefaultImage.ILboolean() As "_ilDefaultImage@0"
  ilDeleteImage(num.ILuint) As "_ilDeleteImage@4"
  ilDeleteImages(Num.ILsizei, *Images.ILuint) As "_ilDeleteImages@8"
  ilDetermineType.ILenum(FileName.ILconst_string) As "_ilDetermineType@4"
  ilDetermineTypeF.ILenum(File.ILHANDLE) As "_ilDetermineTypeF@4"
  ilDetermineTypeL.ILenum(*Lump, Size.ILuint) As "_ilDetermineTypeL@8"
  ilDisable.ILboolean(Mode.ILenum) As "_ilDisable@4"
  ilDxtcDataToImage.ILboolean() As "_ilDxtcDataToImage@0"
  ilDxtcDataToSurface.ILboolean() As "_ilDxtcDataToSurface@0"
  ilEnable.ILboolean(Mode.ILenum) As "_ilEnable@4"
  ilFormatFunc.ILboolean(Mode.ILenum) As "_ilFormatFunc@4"
  ilGenImage.ILuint() As "_ilGenImage@0"
  ilGenImages(Num.ILsizei, *Images.ILuint) As "_ilGenImages@8"
  ilGetAlpha(Type.ILenum) As "_ilGetAlpha@4"
  ilGetBoolean.ILboolean(Mode.ILenum) As "_ilGetBoolean@4"
  ilGetBooleanv(Mode.ILenum, *Param.ILboolean) As "_ilGetBooleanv@8"
  ilGetBppFormat.ILubyte(Format.ILenum) As "_ilGetBppFormat@4"
  ilGetBppPal.ILubyte(PalType.ILenum) As "_ilGetBppPal@4"
  ilGetBpcType.ILubyte(Type.ILenum) As "_ilGetBpcType@4"
  ilGetClear(*Colours, Format.ILenum, Type.ILenum) As "_ilGetClear@12"
  ilGetCurImage() As "_ilGetCurImage@0"
  ilGetCurName.ILuint() As "_ilGetCurName@0"
  ilGetData() As "_ilGetData@0"
  ilGetDXTCData.ILuint(*Buffer, BufferSize.ILuint, DXTCFormat.ILenum) As "_ilGetDXTCData@12"
  ilGetError.ILenum() As "_ilGetError@0"
  ilGetFormatBpp.ILenum(Bpp.ILubyte) As "_ilGetFormatBpp@4"
  ilGetInteger.ILint(Mode.ILenum) As "_ilGetInteger@4"
  ilGetIntegerv(Mode.ILenum, *Param.ILint) As "_ilGetIntegerv@8"
  ilGetLumpPos.ILuint() As "_ilGetLumpPos@0"
  ilGetPalBaseType.ILenum(PalType.ILenum) As "_ilGetPalBaseType@4"
  ilGetPalette() As "_ilGetPalette@0"
  ilGetString(StringName.ILenum) As "_ilGetString@4"  ; returns ILconst_string
  ilGetTypeBpc.ILenum(Bpc.ILubyte) As "_ilGetTypeBpc@4"
  ilHint(Target.ILenum, Mode.ILenum) As "_ilHint@8"
  ilInit() As "_ilInit@0"
  ilInitImage.ILboolean(*Image.ILimage, Width.ILuint, Height.ILuint, Depth.ILuint, Bpp.ILubyte, Format.ILenum, Type.ILenum, *Data_) As "_ilInitImage@32"
  ilImageToDxtcData.ILboolean(Format.ILenum) As "_ilImageToDxtcData@4"
  ilIsDisabled.ILboolean(Mode.ILenum) As "_ilIsDisabled@4"
  ilIsEnabled.ILboolean(Mode.ILenum) As "_ilIsEnabled@4"
  ilIsImage.ILboolean(Image.ILuint) As "_ilIsImage@4"
  ilIsValid.ILboolean(Type.ILenum, FileName.ILconst_string) As "_ilIsValid@8"
  ilIsValidF.ILboolean(Type.ILenum, File.ILHANDLE) As "_ilIsValidF@8"
  ilIsValidL.ILboolean(Type.ILenum,  *Lump, Size.ILuint) As "_ilIsValidL@12"
  ilKeyColour(Red.ILclampf, Green.ILclampf, Blue.ILclampf, Alpha.ILclampf) As "_ilKeyColour@16"
  ilLoad.ILboolean(Type.ILenum, FileName.ILconst_string) As "_ilLoad@8"
  ilLoadF.ILboolean(Type.ILenum, File.ILHANDLE) As "_ilLoadF@8"
  ilLoadImage.ILboolean(FileName.ILconst_string) As "_ilLoadImage@4"
  ilLoadL.ILboolean(Type.ILenum, *Lump, Size.ILuint) As "_ilLoadL@12"
  ilLoadPal.ILboolean(FileName.ILconst_string) As "_ilLoadPal@4"
  ilModAlpha(AlphaValue.ILdouble) As "_ilModAlpha@8"
  ilNewImageFull(Width.ILuint, Height.ILuint, Depth.ILuint, Bpp.ILubyte, Format.ILenum, Type.ILenum, *Data_) As "_ilNewImageFull@28"
  ilNextPower2.ILuint(num.ILuint) As "_ilNextPower2@4"
  ilOriginFunc.ILboolean(Mode.ILenum) As "_ilOriginFunc@4"
  ilOverlayImage.ILboolean(Source.ILuint, XCoord.ILint, YCoord.ILint, ZCoord.ILint) As "_ilOverlayImage@16"
  ilPopAttrib() As "_ilPopAttrib@0"
  ilPushAttrib(Bits.ILuint) As "_ilPushAttrib@4"
  ilRegisterFormat(Format.ILenum) As "_ilRegisterFormat@4"
  ilRegisterLoad.ILboolean(Ext.ILconst_string, *Load_func) As "_ilRegisterLoad@8"
  ilRegisterMipNum.ILboolean(num.ILuint) As "_ilRegisterMipNum@4"
  ilRegisterNumFaces.ILboolean(num.ILuint) As "_ilRegisterNumFaces@4"
  ilRegisterNumImages.ILboolean(num.ILuint) As "_ilRegisterNumImages@4"
  ilRegisterOrigin(Origin.ILenum) As "_ilRegisterOrigin@4"
  ilRegisterPal(*Pal, Size.ILuint, Type.ILenum) As "_ilRegisterPal@12"
  ilRegisterSave.ILboolean(Ext.ILconst_string, *Save_func) As "_ilRegisterSave@8"
  ilRegisterType(Type.ILenum) As "_ilRegisterType@4"
  ilRemoveLoad.ILboolean(Ext.ILconst_string) As "_ilRemoveLoad@4"
  ilRemoveSave.ILboolean(Ext.ILconst_string) As "_ilRemoveSave@4"
  ilReplaceCurImage(*Image.ILimage) As "_ilReplaceCurImage@4"
  ilResetMemory() As "_ilResetMemory@0" ; Deprecated
  ilResetRead() As "_ilResetRead@0"
  ilResetWrite() As "_ilResetWrite@0"
  ilSave.ILboolean(Type.ILenum, FileName.ILconst_string) As "_ilSave@8"
  ilSaveF.ILuint(Type.ILenum, File.ILHANDLE) As "_ilSaveF@8"
  ilSaveImage.ILboolean(FileName.ILconst_string) As "_ilSaveImage@4"
  ilSaveL.ILuint(Type.ILenum,  *Lump, Size.ILuint) As "_ilSaveL@12"
  ilSavePal.ILboolean(FileName.ILconst_string) As "_ilSavePal@4"
  ilSaveData.ILboolean(FileName.ILconst_string) As "_ilSaveData@4"
  ilSetAlpha.ILboolean(AlphaValue.ILdouble) As "_ilSetAlpha@8"
  ilSetData.ILboolean(*Data_) As "_ilSetData@4"
  ilSetDuration.ILboolean(Duration.ILuint) As "_ilSetDuration@4"
  ilSetError(Error.ILenum) As "_ilSetError@4"
  ilSetInteger(Mode.ILenum, Param.ILint) As "_ilSetInteger@8"
  ilSetMemory(mAlloc, mFree) As "_ilSetMemory@8"
  ilSetPal(*Pal.ILpal) As "_ilSetPal@4"
  ilSetRead(fOpenRProc, fCloseRProc, fEofProc, fGetcProc, fReadProc, fSeekRProc, fTellRProc) As "_ilSetRead@28"
  ilSetPixels(XOff.ILint, YOff.ILint, ZOff.ILint, Width.ILuint, Height.ILuint, Depth.ILuint, Format.ILenum, Type.ILenum, *Data_) As "_ilSetPixels@36"
  ilSetString(Mode.ILenum, String.s) As "_ilSetString@8"
  ilSetWrite(fOpenWProc, fCloseWProc, fPutcProc, fSeekWProc, fTellWProc, fWriteProc) As "_ilSetWrite@24"
  ilShutDown() As "_ilShutDown@0"
  ilSurfaceToDxtcData.ILboolean(Format.ILenum) As "_ilSurfaceToDxtcData@4"
  ilTexImage.ILboolean(Width.ILuint, Height.ILuint, Depth.ILuint, NumChannels.ILubyte, Format.ILenum, Type.ILenum,  *Data_) As "_ilTexImage@28"
  ilTexImageDxtc.ILboolean(w.ILint, h.ILint, d.ILint, DxtFormat.ILenum, *Data_.ILubyte) As "_ilTexImageDxtc@20"
  ilTypeFromExt.ILenum(FileName.ILconst_string) As "_ilTypeFromExt@4"
  ilTypeFunc.ILboolean(Mode.ILenum) As "_ilTypeFunc@4"
  ilLoadData.ILboolean(FileName.ILconst_string, Width.ILuint, Height.ILuint, Depth.ILuint, Bpp.ILubyte) As "_ilLoadData@20"
  ilLoadDataF.ILboolean(File.ILHANDLE, Width.ILuint, Height.ILuint, Depth.ILuint, Bpp.ILubyte) As "_ilLoadDataF@20"
  ilLoadDataL.ILboolean(*Lump, Size.ILuint, Width.ILuint, Height.ILuint, Depth.ILuint, Bpp.ILubyte) As "_ilLoadDataL@24"
  iBindImageTemp() As "_iBindImageTemp@0"
  ilClearImage_.ILboolean(*Image.ILimage) As "_ilClearImage_@4"
  ilConvertBuffer(SizeOfData.ILuint, SrcFormat.ILenum, DestFormat.ILenum, SrcType.ILenum, DestType.ILenum, *SrcPal.ILpal, *Buffer) As "_ilConvertBuffer@28"
  ilCloseImage(*Image.ILimage) As "_ilCloseImage@4"
  ilClosePal(*Palette.ILpal) As "_ilClosePal@4"
  iConvertImage(*Image.ILimage, DestFormat.ILenum, DestType.ILenum) As "_iConvertImage@12"
  iConvertPal(*Pal.ILpal, DestFormat.ILenum) As "_iConvertPal@8"
  iCopyPal() As "_iCopyPal@0"
  ilCopyImageAttr.ILboolean(*Dest.ILimage, *Src.ILimage) As "_ilCopyImageAttr@8"
  ilCopyImage_(*Src.ILimage) As "_ilCopyImage_@4"
  iGetFlipped(*Image.ILimage) As "_iGetFlipped@4"
  ilIsValidPal.ILboolean(*Palette.ILpal) As "_ilIsValidPal@4"
  ilNewImage(Width.ILuint, Height.ILuint, Depth.ILuint, Bpp.ILubyte, Bpc.ILubyte) As "_ilNewImage@20"
  ilResizeImage.ILboolean(*Image.ILimage, Width.ILuint, Height.ILuint, Depth.ILuint, Bpp.ILubyte, Bpc.ILubyte) As "_ilResizeImage@24"
  ilSetCurImage(*Image.ILimage) As "_ilSetCurImage@4"
  ilTexImage_.ILboolean(*Image.ILimage, Width.ILuint, Height.ILuint, Depth.ILuint, Bpp.ILubyte, Format.ILenum, Type.ILenum, *Data_) As "_ilTexImage_@32"
  ilTexSubImage_.ILboolean(*Image.ILimage, *Data_) As "_ilTexSubImage_@8"
  ialloc(Size.ILsizei) As "_ialloc@4"
  ifree(*Ptr) As "_ifree@4"
  icalloc(Size.ILsizei, Num.ILsizei) As "_icalloc@8"
  iFlipBuffer(*buff.ILubyte, Depth.ILuint, line_size.ILuint, line_num.ILuint) As "_iFlipBuffer@16"
  iMirror.ILboolean() As "_iMirror@0"
  ;-ilNVidiaCompressDXT(a.l,b.l,c.l,d.l,e.l,f.l) As "_ilNVidiaCompressDXT@24"
  ;-ilSquishCompressDXT(a.l,b.l,c.l,d.l,e.l,f.l) As "_ilSquishCompressDXT@24"
  iGetIntegervImage(*Image.ILimage, Mode.ILenum, *Param.ILint) As "_iGetIntegervImage@12"
  iMemSwap(*val1.ILubyte, *val2.ILubyte, val3.ILubyte) As "_iMemSwap@12"
  ilFlipSurfaceDxtcData() As "_ilFlipSurfaceDxtcData@0"
  ilInvertSurfaceDxtcDataAlpha.ILboolean() As "_ilInvertSurfaceDxtcDataAlpha@0"
EndImport
Import #DevIL_Lib_Path+"ILU.lib"
  iluAlienify.ILboolean() As "_iluAlienify@0"
  iluBlurAvg.ILboolean(Iter.ILuint) As "_iluBlurAvg@4"
  iluBlurGaussian.ILboolean(Iter.ILuint) As "_iluBlurGaussian@4"
  iluBuildMipmaps.ILboolean() As "_iluBuildMipmaps@0"
  iluColoursUsed.ILuint() As "_iluColoursUsed@0"
  iluConvolution.ILboolean(*matrix.ILint, scale.ILint, bias.ILint) As "_iluConvolution@12"
  iluCompareImage.ILboolean(Comp.ILuint) As "_iluCompareImage@4"
  iluContrast.ILboolean(Contrast.ILfloat) As "_iluContrast@4"
  iluCrop.ILboolean(XOff.ILuint, YOff.ILuint, ZOff.ILuint, Width.ILuint, Height.ILuint, Depth.ILuint) As "_iluCrop@24"
  iluDeleteImage(Id.ILuint) As "_iluDeleteImage@4"
  iluEdgeDetectE.ILboolean() As "_iluEdgeDetectE@0"
  iluEdgeDetectP.ILboolean() As "_iluEdgeDetectP@0"
  iluEdgeDetectS.ILboolean() As "_iluEdgeDetectS@0"
  iluEmboss.ILboolean() As "_iluEmboss@0"
  iluEnlargeCanvas.ILboolean(Width.ILuint, Height.ILuint, Depth.ILuint) As "_iluEnlargeCanvas@12"
  iluEnlargeImage.ILboolean(xDim.ILfloat, yDim.ILfloat, zDim.ILfloat) As "_iluEnlargeImage@12"
  iluEqualize.ILboolean() As "_iluEqualize@0"
  iluErrorString.l(Error.ILenum) As "_iluErrorString@4" ; returns ILconst_string
  iluFlipImage.ILboolean() As "_iluFlipImage@0"
  iluGenImage.ILuint() As "_iluGenImage@0"
  iluGetImageInfo(*Info.ILinfo) As "_iluGetImageInfo@4"
  iluGetString.l(StringName.ILenum) As "_iluGetString@4" ; returns ILstring
  iluGammaCorrect.ILboolean(gamma.ILfloat) As "_iluGammaCorrect@4"
  iluGetInteger.ILint(Mode.ILenum) As "_iluGetInteger@4"
  iluGetIntegerv(Mode.ILenum, *Param.ILint) As "_iluGetIntegerv@8"
  iluImageParameter(PName.ILenum, Param.ILenum) As "_iluImageParameter@8"
  iluInit() As "_iluInit@0"
  iluInvertAlpha.ILboolean() As "_iluInvertAlpha@0"
  iluLoadImage.ILuint(FileName.ILconst_string) As "_iluLoadImage@4"
  iluMirror.ILboolean() As "_iluMirror@0"
  iluNegative.ILboolean() As "_iluNegative@0"
  iluNoisify.ILboolean(Tolerance.ILclampf) As "_iluNoisify@4"
  iluPixelize.ILboolean(PixSize.ILuint) As "_iluPixelize@4"
  iluRegionfv(*Points.ILpointf, n.ILuint) As "_iluRegionfv@8"
  iluRegioniv(*Points.ILpointf, n.ILuint) As "_iluRegioniv@8"
  iluReplaceColour.ILboolean(Red.ILubyte, Green.ILubyte, Blue.ILubyte, Tolerance.ILfloat) As "_iluReplaceColour@16"
  iluRotate.ILboolean(Angle.ILfloat) As "_iluRotate@4"
  iluRotate3D.ILboolean(x.ILfloat, y.ILfloat, z.ILfloat, Angle.ILfloat) As "_iluRotate3D@16"
  iluSaturate1f.ILboolean(Saturation.ILfloat) As "_iluSaturate1f@4"
  iluSaturate4f.ILboolean(r.ILfloat, g.ILfloat, b.ILfloat, Saturation.ILfloat) As "_iluSaturate4f@16"
  iluScaleColours.ILboolean(r.ILfloat, g.ILfloat, b.ILfloat) As "_iluScaleColours@12"
  iluScale.ILboolean(Width.ILuint, Height.ILuint, Depth.ILuint) As "_iluScale@12"
  iluScaleAlpha.ILboolean(scale.ILfloat) As "_iluScaleAlpha@4"
  iluSetLanguage.ILboolean(Language.ILenum) As "_iluSetLanguage@4"
  iluSharpen.ILboolean(Factor.ILfloat, Iter.ILuint) As "_iluSharpen@8"
  iluSwapColours.ILboolean() As "_iluSwapColours@0"
  iluWave.ILboolean(Angle.ILfloat) As "_iluWave@4"
  iluRotate_(*Image.ILimage, Angle.ILfloat) As "_iluRotate_@8"
  iluRotate3D_(*Image.ILimage, x.ILfloat, y.ILfloat, z.ILfloat, Angle.ILfloat) As "_iluRotate3D_@20"
  iluScale_(*Image.ILimage, Width.ILuint, Height.ILuint, Depth.ILuint) As "_iluScale_@16"
EndImport
Import #DevIL_Lib_Path+"ILUT.lib"
  CompilerIf #PB_Compiler_OS = #PB_OS_Windows
    ilutConvertToHBitmap(hDC.HDC) As "_ilutConvertToHBitmap@4"
    ilutConvertSliceToHBitmap(hDC.HDC, slice.ILuint) As "_ilutConvertSliceToHBitmap@8"
  CompilerEndIf
  ilutDisable.ILboolean(Mode.ILenum) As "_ilutDisable@4"
  ilutEnable.ILboolean(Mode.ILenum) As "_ilutEnable@4"
  CompilerIf #PB_Compiler_OS = #PB_OS_Windows
    ilutFreePaddedData(*Data_.ILubyte) As "_ilutFreePaddedData@4"
    ilutGetBmpInfo(*Info.BITMAPINFO) As "_ilutGetBmpInfo@4"
  CompilerEndIf
  ilutGetBoolean.ILboolean(Mode.ILenum) As "_ilutGetBoolean@4"
  ilutGetBooleanv(Mode.ILenum, *Param.ILboolean) As "_ilutGetBooleanv@8"
  CompilerIf #PB_Compiler_OS = #PB_OS_Windows
    ilutGetHPal() As "_ilutGetHPal@0"
  CompilerEndIf
  ilutGetInteger.ILint(Mode.ILenum) As "_ilutGetInteger@4"
  ilutGetIntegerv(Mode.ILenum, *Param.ILint) As "_ilutGetIntegerv@8"
  CompilerIf #PB_Compiler_OS = #PB_OS_Windows
    ilutGetPaddedData() As "_ilutGetPaddedData@0"
  CompilerEndIf
  ilutGetString.l(StringName.ILenum) As "_ilutGetString@4" ; returns ILstring
  CompilerIf #PB_Compiler_OS = #PB_OS_Windows
    ilutGetWinClipboard() As "_ilutGetWinClipboard@0"
  CompilerEndIf
  ilutInit() As "_ilutInit@0"
  ilutIsDisabled.ILboolean(Mode.ILenum) As "_ilutIsDisabled@4"
  ilutIsEnabled.ILboolean(Mode.ILenum) As "_ilutIsEnabled@4"
  CompilerIf #PB_Compiler_OS = #PB_OS_Windows
    ilutLoadResource(hInst.HINSTANCE, ID.ILint, ResourceType.ILstring,Type.ILenum) As "_ilutLoadResource@16"
  CompilerEndIf
  CompilerIf Defined(ILUT_USE_OPENGL, #PB_Constant) = #True
    CompilerIf #ILUT_USE_OPENGL = #True
      ilutGLBindTexImage.GLuint() As "_ilutGLBindTexImage@0"
      ilutGLBindMipmaps.GLuint() As "_ilutGLBindMipmaps@0"
      ilutGLBuildMipmaps.ILboolean() As "_ilutGLBuildMipmaps@0"
      ilutGLLoadImage.GLuint(FileName.ILstring) As "_ilutGLLoadImage@4"
      ilutGLScreen.ILboolean() As "_ilutGLScreen@0"
      ilutGLScreenie.ILboolean() As "_ilutGLScreenie@0"
      ilutGLSaveImage.ILboolean(FileName.ILstring, TexID.GLuint) As "_ilutGLSaveImage@8"
      ilutGLSubTex2D.ILboolean(TexID.GLuint, XOff.ILuint, YOff.ILuint) As "_ilutGLSubTex2D@12"
      ilutGLSubTex3D.ILboolean(TexID.GLuint, XOff.ILuint, YOff.ILuint, ZOff.ILuint) As "_ilutGLSubTex3D@16"
      ilutGLSetTex2D.ILboolean(TexID.GLuint) As "_ilutGLSetTex2D@4"
      ilutGLSetTex3D.ILboolean(TexID.GLuint) As "_ilutGLSetTex3D@4"
      ilutGLTexImage.ILboolean(Level.GLuint) As "_ilutGLTexImage@4"
      ilutGLSubTex.ILboolean(TexID.GLuint, XOff.ILuint, YOff.ILuint) As "_ilutGLSubTex@12"
      ilutGLSetTex.ILboolean(TexID.GLuint) As "_ilutGLSetTex@4"  ; Deprecated - use ilutGLSetTex2D.
    CompilerEndIf
  CompilerEndIf
  ilutPopAttrib() As "_ilutPopAttrib@0"
  ilutPushAttrib(Bits.ILuint) As "_ilutPushAttrib@4"
  ilutRenderer.ILboolean(Renderer.ILenum) As "_ilutRenderer@4"
  CompilerIf #PB_Compiler_OS = #PB_OS_Windows
    ilutSetHBitmap(Bitmap.HBITMAP) As "_ilutSetHBitmap@4"
    ilutSetHPal(Pal.HPALETTE) As "_ilutSetHPal@4"
  CompilerEndIf
  ilutSetInteger(Mode.ILenum, Param.ILint) As "_ilutSetInteger@8"
  CompilerIf #PB_Compiler_OS = #PB_OS_Windows
    ilutSetWinClipboard() As "_ilutSetWinClipboard@0"
    ilutWinLoadImage(FileName.ILstring, hDC.HDC) As "_ilutWinLoadImage@8"
    ilutWinLoadUrl(Url.ILstring) As "_ilutWinLoadUrl@4"
    ilutWinPrint(XPos.ILuint, YPos.ILuint, Width.ILuint, Height.ILuint,hDC.HDC) As "_ilutWinPrint@20"
    ilutWinSaveImage(FileName.ILstring, Bitmap.HBITMAP) As "_ilutWinSaveImage@8"
  CompilerEndIf
EndImport
; not supported
;   ivec_align_buffer(*buffer, Size.ILuint)
;   iFlipNewBuffer(*buff.ILubyte, Depth.ILuint, line_size.ILuint, line_num.ILuint)


