XIncludeFile "RW_TidyLib_Res.pb"

;{ Imports }
  ImportC "tidy.lib"
    tidyCreate() As "_tidyCreate@0"
    tidyRelease(*tdoc.TidyDoc) As "_tidyRelease@4"
    tidySetAppData(*tdoc.TidyDoc, *appData) As "_tidySetAppData@8"
    tidyGetAppData(*tdoc.TidyDoc) As "_tidyGetAppData@4"
    tidyReleaseDate() As "_tidyReleaseDate@0"
    tidyStatus(*tdoc.TidyDoc) As "_tidyStatus@4"
    tidyDetectedHtmlVersion(*tdoc.TidyDoc) As "_tidyDetectedHtmlVersion@4"
    tidyDetectedXhtml(*tdoc.TidyDoc) As "_tidyDetectedXhtml@4"
    tidyDetectedGenericXml(*tdoc.TidyDoc) As "_tidyDetectedGenericXml@4"
    tidyErrorCount(*tdoc.TidyDoc) As "_tidyErrorCount@4"
    tidyWarningCount(*tdoc.TidyDoc) As "_tidyWarningCount@4"
    tidyAccessWarningCount(*tdoc.TidyDoc) As "_tidyAccessWarningCount@4"
    tidyConfigErrorCount(*tdoc.TidyDoc) As "_tidyConfigErrorCount@4"
    tidyLoadConfig(*tdoc.TidyDoc, confFile.p-ascii) As "_tidyLoadConfig@8"
    tidyLoadConfigEnc(*tdoc.TidyDoc, configFile.p-ascii, charenc.p-ascii) As "_tidyLoadConfigEnc@12"
    tidyFileExists(filename.p-ascii) As "_tidyFileExists@4"
    tidySetCharEncoding(*tdoc.TidyDoc, encnam.p-ascii) As "_tidySetCharEncoding@8"
    tidySetInCharEncoding(*tdoc.TidyDoc, encnam.p-ascii) As "_tidySetInCharEncoding@8"
    tidySetOutCharEncoding(*tdoc.TidyDoc, encnam.p-ascii) As "_tidySetOutCharEncoding@8"
    tidySetOptionCallback(*tdoc.TidyDoc, pOptCallback.l) As "_tidySetOptionCallback@8"
    tidyOptGetIdForName(optnam.p-ascii) As "_tidyOptGetIdForName@4"
    tidyGetOptionList(*tdoc.TidyDoc) As "_tidyGetOptionList@4"
    tidyGetNextOption(*tdoc.TidyDoc, *pos.TidyIterator) As "_tidyGetNextOption@8"
    tidyGetOption(*tdoc.TidyDoc, optId.l) As "_tidyGetOption@8"
    tidyGetOptionByName(*tdoc.TidyDoc, optnam.p-ascii) As "_tidyGetOptionByName@8"
    tidyOptGetId(opt.l) As "_tidyOptGetId@4"
    tidyOptGetName(opt.l) As "_tidyOptGetName@4"
    tidyOptGetType(opt.l) As "_tidyOptGetType@4"
    tidyOptIsReadOnly(opt.l) As "_tidyOptIsReadOnly@4"
    tidyOptGetCategory(opt.l) As "_tidyOptGetCategory@4"
    tidyOptGetDefault(opt.l) As "_tidyOptGetDefault@4"
    tidyOptGetDefaultInt(opt.l) As "_tidyOptGetDefaultInt@4"
    tidyOptGetDefaultBool(opt.l) As "_tidyOptGetDefaultBool@4"
    tidyOptGetPickList(opt.l) As "_tidyOptGetPickList@4"
    tidyOptGetNextPick(opt.l, *pos.TidyIterator) As "_tidyOptGetNextPick@8"
    tidyOptGetValue(*tdoc.TidyDoc, optId.l) As "_tidyOptGetValue@8"
    tidyOptSetValue(*tdoc.TidyDoc, optId.l, val.p-ascii) As "_tidyOptSetValue@12"
    tidyOptParseValue(*tdoc.TidyDoc, optnam.p-ascii, val.p-ascii) As "_tidyOptParseValue@12"
    tidyOptGetInt(*tdoc.TidyDoc, optId.l) As "_tidyOptGetInt@8"
    tidyOptSetInt(*tdoc.TidyDoc, optId.l, val.l) As "_tidyOptSetInt@12"
    tidyOptGetBool(*tdoc.TidyDoc,optId.l) As "_tidyOptGetBool@8"
    tidyOptSetBool(*tdoc.TidyDoc, optId.l, val.l) As "_tidyOptSetBool@12"
    tidyOptResetToDefault(*tdoc.TidyDoc, opt.l) As "_tidyOptResetToDefault@8"
    tidyOptResetAllToDefault(*tdoc.TidyDoc) As "_tidyOptResetAllToDefault@4"
    tidyOptSnapshot(*tdoc.TidyDoc) As "_tidyOptSnapshot@4"
    tidyOptResetToSnapshot(*tdoc.TidyDoc) As "_tidyOptResetToSnapshot@4"
    tidyOptDiffThanDefault(*tdoc.TidyDoc) As "_tidyOptDiffThanDefault@4"
    tidyOptDiffThanSnapshot(*tdoc.TidyDoc) As "_tidyOptDiffThanSnapshot@4"
    tidyOptCopyConfig(*tdocTo.TidyDoc, *tdocFrom.TidyDoc) As "_tidyOptCopyConfig@8"
    tidyOptGetEncName(*tdoc.TidyDoc, optId.l) As "_tidyOptGetEncName@8"
    tidyOptGetCurrPick(*tdoc.TidyDoc, optId.l) As "_tidyOptGetCurrPick@8"
    tidyOptGetDeclTagList(*tdoc.TidyDoc) As "_tidyOptGetDeclTagList@4"
    tidyOptGetNextDeclTag(*tdoc.TidyDoc, optId.l, *iter.TidyIterator) As "_tidyOptGetNextDeclTag@12"
    tidyOptGetDoc(*tdoc.TidyDoc, opt.l) As "_tidyOptGetDoc@8"
    tidyOptGetDocLinksList(*tdoc.TidyDoc, opt.l) As "_tidyOptGetDocLinksList@8"
    tidyOptGetNextDocLinks(*tdoc.TidyDoc, *pos.TidyIterator) As "_tidyOptGetNextDocLinks@8"
    tidyInitSource(*source.TidyInputSource, *srcData, *gbFunc, *ugbFunc, *endFunc) As "_tidyInitSource@20"
    tidyGetByte(*source.TidyInputSource) As "_tidyGetByte@4"
    tidyUngetByte(*source.TidyInputSource, byteValue.l) As "_tidyUngetByte@8"
    tidyIsEOF(*source.TidyInputSource) As "_tidyIsEOF@4"
    tidyInitSink(*sink.TidyOutputSink, *snkData, *pbFunc) As "_tidyInitSink@12"
    tidyPutByte(*sink.TidyOutputSink, byteValue.l) As "_tidyPutByte@8"
    tidySetReportFilter(*tdoc.TidyDoc, *filtCallback) As "_tidySetReportFilter@8"
    tidySetErrorFile(*tdoc.TidyDoc, errfilnam.p-ascii) As "_tidySetErrorFile@8"
    tidySetErrorBuffer(*tdoc.TidyDoc, *errbuf.TidyBuffer) As "_tidySetErrorBuffer@8"
    tidySetErrorSink(*tdoc.TidyDoc, *sink.TidyOutputSink) As "_tidySetErrorSink@8"
    tidySetMallocCall(*fmalloc) As "_tidySetMallocCall@4"
    tidySetReallocCall(*frealloc) As "_tidySetReallocCall@4"
    tidySetFreeCall(*ffree) As "_tidySetFreeCall@4"
    tidySetPanicCall(*fpanic) As "_tidySetPanicCall@4"
    tidyParseFile(*tdoc.TidyDoc, filename.p-ascii) As "_tidyParseFile@8"
    tidyParseStdin(*tdoc.TidyDoc) As "_tidyParseStdin@4"
    tidyParseString(*tdoc.TidyDoc, content.p-ascii) As "_tidyParseString@8"
    tidyParseBuffer(*tdoc.TidyDoc, *buf.tidyBuffer) As "_tidyParseBuffer@8"
    tidyParseSource(*tdoc.TidyDoc, *source.TidyInputSource) As "_tidyParseSource@8"
    tidyCleanAndRepair(*tdoc.TidyDoc) As "_tidyCleanAndRepair@4"
    tidyRunDiagnostics(*tdoc.TidyDoc) As "_tidyRunDiagnostics@4"
    tidySaveFile(*tdoc.TidyDoc, filename.p-ascii) As "_tidySaveFile@8"
    tidySaveStdout(*tdoc.TidyDoc) As "_tidySaveStdout@4"
    tidySaveBuffer(*tdoc.TidyDoc, *buf.TidyBuffer) As "_tidySaveBuffer@8"
    tidySaveString(*tdoc.TidyDoc, buffer.p-ascii, buflen.l) As "_tidySaveString@12"
    tidySaveSink(*tdoc.TidyDoc, *sink.TidyOutputSink) As "_tidySaveSink@8"
    tidyOptSaveFile(*tdoc.TidyDoc, cfgfil.p-ascii) As "_tidyOptSaveFile@8"
    tidyOptSaveSink(*tdoc.TidyDoc, *sink.TidyOutputSink) As "_tidyOptSaveSink@8"
    tidyErrorSummary(*tdoc.TidyDoc) As "_tidyErrorSummary@4"
    tidyGeneralInfo(*tdoc.TidyDoc) As "_tidyGeneralInfo@4"
    tidyGetRoot(*tdoc.TidyDoc) As "_tidyGetRoot@4"
    tidyGetHtml(*tdoc.TidyDoc) As "_tidyGetHtml@4"
    tidyGetHead(*tdoc.TidyDoc) As "_tidyGetHead@4"
    tidyGetBody(*tdoc.TidyDoc) As "_tidyGetBody@4"
    tidyGetParent(*tnod.TidyNode) As "_tidyGetParent@4"
    tidyGetChild(*tnod.TidyNode) As "_tidyGetChild@4"
    tidyGetNext(*tnod.TidyNode) As "_tidyGetNext@4"
    tidyGetPrev(*tnod.TidyNode) As "_tidyGetPrev@4"
    tidyAttrFirst(*tnod.TidyNode) As "_tidyAttrFirst@4"
    tidyAttrNext(*tattr.TidyAttr) As "_tidyAttrNext@4"
    tidyAttrName(*tattr.TidyAttr) As "_tidyAttrName@4"
    tidyAttrValue(*tattr.TidyAttr) As "_tidyAttrValue@4"
    tidyNodeGetType(*tnod.TidyNode) As "_tidyNodeGetType@4"
    tidyNodeGetName(*tnod.TidyNode) As "_tidyNodeGetName@4"
    tidyNodeIsText(*tnod.TidyNode) As "_tidyNodeIsText@4"
    tidyNodeIsProp(*tdoc.TidyDoc, *tnod.TidyNode) As "_tidyNodeIsProp@8"
    tidyNodeIsHeader(*tnod.TidyNode) As "_tidyNodeIsHeader@4"
    tidyNodeHasText(*tdoc.TidyDoc, *tnod.TidyNode) As "_tidyNodeHasText@8"
    tidyNodeGetText(*tdoc.TidyDoc, *tnod.TidyNode, *buf.TidyBuffer) As "_tidyNodeGetText@12"
    tidyNodeGetId(*tnod.TidyNode) As "_tidyNodeGetId@4"
    tidyNodeLine(*tnod.TidyNode) As "_tidyNodeLine@4"
    tidyNodeColumn(*tnod.TidyNode) As "_tidyNodeColumn@4"
    tidyNodeIsHTML(*tnod.TidyNode) As "_tidyNodeIsHTML@4"
    tidyNodeIsHEAD(*tnod.TidyNode) As "_tidyNodeIsHEAD@4"
    tidyNodeIsTITLE(*tnod.TidyNode) As "_tidyNodeIsTITLE@4"
    tidyNodeIsBASE(*tnod.TidyNode) As "_tidyNodeIsBASE@4"
    tidyNodeIsMETA(*tnod.TidyNode) As "_tidyNodeIsMETA@4"
    tidyNodeIsBODY(*tnod.TidyNode) As "_tidyNodeIsBODY@4"
    tidyNodeIsFRAMESET(*tnod.TidyNode) As "_tidyNodeIsFRAMESET@4"
    tidyNodeIsFRAME(*tnod.TidyNode) As "_tidyNodeIsFRAME@4"
    tidyNodeIsIFRAME(*tnod.TidyNode) As "_tidyNodeIsIFRAME@4"
    tidyNodeIsNOFRAMES(*tnod.TidyNode) As "_tidyNodeIsNOFRAMES@4"
    tidyNodeIsHR(*tnod.TidyNode) As "_tidyNodeIsHR@4"
    tidyNodeIsH1(*tnod.TidyNode) As "_tidyNodeIsH1@4"
    tidyNodeIsH2(*tnod.TidyNode) As "_tidyNodeIsH2@4"
    tidyNodeIsPRE(*tnod.TidyNode) As "_tidyNodeIsPRE@4"
    tidyNodeIsLISTING(*tnod.TidyNode) As "_tidyNodeIsLISTING@4"
    tidyNodeIsP(*tnod.TidyNode) As "_tidyNodeIsP@4"
    tidyNodeIsUL(*tnod.TidyNode) As "_tidyNodeIsUL@4"
    tidyNodeIsOL(*tnod.TidyNode) As "_tidyNodeIsOL@4"
    tidyNodeIsDL(*tnod.TidyNode) As "_tidyNodeIsDL@4"
    tidyNodeIsDIR(*tnod.TidyNode) As "_tidyNodeIsDIR@4"
    tidyNodeIsLI(*tnod.TidyNode) As "_tidyNodeIsLI@4"
    tidyNodeIsDT(*tnod.TidyNode) As "_tidyNodeIsDT@4"
    tidyNodeIsDD(*tnod.TidyNode) As "_tidyNodeIsDD@4"
    tidyNodeIsTABLE(*tnod.TidyNode) As "_tidyNodeIsTABLE@4"
    tidyNodeIsCAPTION(*tnod.TidyNode) As "_tidyNodeIsCAPTION@4"
    tidyNodeIsTD(*tnod.TidyNode) As "_tidyNodeIsTD@4"
    tidyNodeIsTH(*tnod.TidyNode) As "_tidyNodeIsTH@4"
    tidyNodeIsTR(*tnod.TidyNode) As "_tidyNodeIsTR@4"
    tidyNodeIsCOL(*tnod.TidyNode) As "_tidyNodeIsCOL@4"
    tidyNodeIsCOLGROUP(*tnod.TidyNode) As "_tidyNodeIsCOLGROUP@4"
    tidyNodeIsBR(*tnod.TidyNode) As "_tidyNodeIsBR@4"
    tidyNodeIsA(*tnod.TidyNode) As "_tidyNodeIsA@4"
    tidyNodeIsLINK(*tnod.TidyNode) As "_tidyNodeIsLINK@4"
    tidyNodeIsB(*tnod.TidyNode) As "_tidyNodeIsB@4"
    tidyNodeIsI(*tnod.TidyNode) As "_tidyNodeIsI@4"
    tidyNodeIsSTRONG(*tnod.TidyNode) As "_tidyNodeIsSTRONG@4"
    tidyNodeIsEM(*tnod.TidyNode) As "_tidyNodeIsEM@4"
    tidyNodeIsBIG(*tnod.TidyNode) As "_tidyNodeIsBIG@4"
    tidyNodeIsSMALL(*tnod.TidyNode) As "_tidyNodeIsSMALL@4"
    tidyNodeIsPARAM(*tnod.TidyNode) As "_tidyNodeIsPARAM@4"
    tidyNodeIsOPTION(*tnod.TidyNode) As "_tidyNodeIsOPTION@4"
    tidyNodeIsOPTGROUP(*tnod.TidyNode) As "_tidyNodeIsOPTGROUP@4"
    tidyNodeIsIMG(*tnod.TidyNode) As "_tidyNodeIsIMG@4"
    tidyNodeIsMAP(*tnod.TidyNode) As "_tidyNodeIsMAP@4"
    tidyNodeIsAREA(*tnod.TidyNode) As "_tidyNodeIsAREA@4"
    tidyNodeIsNOBR(*tnod.TidyNode) As "_tidyNodeIsNOBR@4"
    tidyNodeIsWBR(*tnod.TidyNode) As "_tidyNodeIsWBR@4"
    tidyNodeIsFONT(*tnod.TidyNode) As "_tidyNodeIsFONT@4"
    tidyNodeIsLAYER(*tnod.TidyNode) As "_tidyNodeIsLAYER@4"
    tidyNodeIsSPACER(*tnod.TidyNode) As "_tidyNodeIsSPACER@4"
    tidyNodeIsCENTER(*tnod.TidyNode) As "_tidyNodeIsCENTER@4"
    tidyNodeIsSTYLE(*tnod.TidyNode) As "_tidyNodeIsSTYLE@4"
    tidyNodeIsSCRIPT(*tnod.TidyNode) As "_tidyNodeIsSCRIPT@4"
    tidyNodeIsNOSCRIPT(*tnod.TidyNode) As "_tidyNodeIsNOSCRIPT@4"
    tidyNodeIsFORM(*tnod.TidyNode) As "_tidyNodeIsFORM@4"
    tidyNodeIsTEXTAREA(*tnod.TidyNode) As "_tidyNodeIsTEXTAREA@4"
    tidyNodeIsBLOCKQUOTE(*tnod.TidyNode) As "_tidyNodeIsBLOCKQUOTE@4"
    tidyNodeIsAPPLET(*tnod.TidyNode) As "_tidyNodeIsAPPLET@4"
    tidyNodeIsOBJECT(*tnod.TidyNode) As "_tidyNodeIsOBJECT@4"
    tidyNodeIsDIV(*tnod.TidyNode) As "_tidyNodeIsDIV@4"
    tidyNodeIsSPAN(*tnod.TidyNode) As "_tidyNodeIsSPAN@4"
    tidyNodeIsINPUT(*tnod.TidyNode) As "_tidyNodeIsINPUT@4"
    tidyNodeIsQ(*tnod.TidyNode) As "_tidyNodeIsQ@4"
    tidyNodeIsLABEL(*tnod.TidyNode) As "_tidyNodeIsLABEL@4"
    tidyNodeIsH3(*tnod.TidyNode) As "_tidyNodeIsH3@4"
    tidyNodeIsH4(*tnod.TidyNode) As "_tidyNodeIsH4@4"
    tidyNodeIsH5(*tnod.TidyNode) As "_tidyNodeIsH5@4"
    tidyNodeIsH6(*tnod.TidyNode) As "_tidyNodeIsH6@4"
    tidyNodeIsADDRESS(*tnod.TidyNode) As "_tidyNodeIsADDRESS@4"
    tidyNodeIsXMP(*tnod.TidyNode) As "_tidyNodeIsXMP@4"
    tidyNodeIsSELECT(*tnod.TidyNode) As "_tidyNodeIsSELECT@4"
    tidyNodeIsBLINK(*tnod.TidyNode) As "_tidyNodeIsBLINK@4"
    tidyNodeIsMARQUEE(*tnod.TidyNode) As "_tidyNodeIsMARQUEE@4"
    tidyNodeIsEMBED(*tnod.TidyNode) As "_tidyNodeIsEMBED@4"
    tidyNodeIsBASEFONT(*tnod.TidyNode) As "_tidyNodeIsBASEFONT@4"
    tidyNodeIsISINDEX(*tnod.TidyNode) As "_tidyNodeIsISINDEX@4"
    tidyNodeIsS(*tnod.TidyNode) As "_tidyNodeIsS@4"
    tidyNodeIsSTRIKE(*tnod.TidyNode) As "_tidyNodeIsSTRIKE@4"
    tidyNodeIsU(*tnod.TidyNode) As "_tidyNodeIsU@4"
    tidyNodeIsMENU(*tnod.TidyNode) As "_tidyNodeIsMENU@4"
    tidyAttrGetId(*tattr.TidyAttr) As "_tidyAttrGetId@4"
    tidyAttrIsEvent(*tattr.TidyAttr) As "_tidyAttrIsEvent@4"
    tidyAttrIsProp(*tattr.TidyAttr) As "_tidyAttrIsProp@4"
    tidyAttrIsHREF(*tattr.TidyAttr) As "_tidyAttrIsHREF@4"
    tidyAttrIsSRC(*tattr.TidyAttr) As "_tidyAttrIsSRC@4"
    tidyAttrIsID(*tattr.TidyAttr) As "_tidyAttrIsID@4"
    tidyAttrIsNAME(*tattr.TidyAttr) As "_tidyAttrIsNAME@4"
    tidyAttrIsSUMMARY(*tattr.TidyAttr) As "_tidyAttrIsSUMMARY@4"
    tidyAttrIsALT(*tattr.TidyAttr) As "_tidyAttrIsALT@4"
    tidyAttrIsLONGDESC(*tattr.TidyAttr) As "_tidyAttrIsLONGDESC@4"
    tidyAttrIsUSEMAP(*tattr.TidyAttr) As "_tidyAttrIsUSEMAP@4"
    tidyAttrIsISMAP(*tattr.TidyAttr) As "_tidyAttrIsISMAP@4"
    tidyAttrIsLANGUAGE(*tattr.TidyAttr) As "_tidyAttrIsLANGUAGE@4"
    tidyAttrIsTYPE(*tattr.TidyAttr) As "_tidyAttrIsTYPE@4"
    tidyAttrIsVALUE(*tattr.TidyAttr) As "_tidyAttrIsVALUE@4"
    tidyAttrIsCONTENT(*tattr.TidyAttr) As "_tidyAttrIsCONTENT@4"
    tidyAttrIsTITLE(*tattr.TidyAttr) As "_tidyAttrIsTITLE@4"
    tidyAttrIsXMLNS(*tattr.TidyAttr) As "_tidyAttrIsXMLNS@4"
    tidyAttrIsDATAFLD(*tattr.TidyAttr) As "_tidyAttrIsDATAFLD@4"
    tidyAttrIsWIDTH(*tattr.TidyAttr) As "_tidyAttrIsWIDTH@4"
    tidyAttrIsHEIGHT(*tattr.TidyAttr) As "_tidyAttrIsHEIGHT@4"
    tidyAttrIsFOR(*tattr.TidyAttr) As "_tidyAttrIsFOR@4"
    tidyAttrIsSELECTED(*tattr.TidyAttr) As "_tidyAttrIsSELECTED@4"
    tidyAttrIsCHECKED(*tattr.TidyAttr) As "_tidyAttrIsCHECKED@4"
    tidyAttrIsLANG(*tattr.TidyAttr) As "_tidyAttrIsLANG@4"
    tidyAttrIsTARGET(*tattr.TidyAttr) As "_tidyAttrIsTARGET@4"
    tidyAttrIsHTTP_EQUIV(*tattr.TidyAttr) As "_tidyAttrIsHTTP_EQUIV@4"
    tidyAttrIsREL(*tattr.TidyAttr) As "_tidyAttrIsREL@4"
    tidyAttrIsOnMOUSEMOVE(*tattr.TidyAttr) As "_tidyAttrIsOnMOUSEMOVE@4"
    tidyAttrIsOnMOUSEDOWN(*tattr.TidyAttr) As "_tidyAttrIsOnMOUSEDOWN@4"
    tidyAttrIsOnMOUSEUP(*tattr.TidyAttr) As "_tidyAttrIsOnMOUSEUP@4"
    tidyAttrIsOnCLICK(*tattr.TidyAttr) As "_tidyAttrIsOnCLICK@4"
    tidyAttrIsOnMOUSEOVER(*tattr.TidyAttr) As "_tidyAttrIsOnMOUSEOVER@4"
    tidyAttrIsOnMOUSEOUT(*tattr.TidyAttr) As "_tidyAttrIsOnMOUSEOUT@4"
    tidyAttrIsOnKEYDOWN(*tattr.TidyAttr) As "_tidyAttrIsOnKEYDOWN@4"
    tidyAttrIsOnKEYUP(*tattr.TidyAttr) As "_tidyAttrIsOnKEYUP@4"
    tidyAttrIsOnKEYPRESS(*tattr.TidyAttr) As "_tidyAttrIsOnKEYPRESS@4"
    tidyAttrIsOnFOCUS(*tattr.TidyAttr) As "_tidyAttrIsOnFOCUS@4"
    tidyAttrIsOnBLUR(*tattr.TidyAttr) As "_tidyAttrIsOnBLUR@4"
    tidyAttrIsBGCOLOR(*tattr.TidyAttr) As "_tidyAttrIsBGCOLOR@4"
    tidyAttrIsLINK(*tattr.TidyAttr) As "_tidyAttrIsLINK@4"
    tidyAttrIsALINK(*tattr.TidyAttr) As "_tidyAttrIsALINK@4"
    tidyAttrIsVLINK(*tattr.TidyAttr) As "_tidyAttrIsVLINK@4"
    tidyAttrIsTEXT(*tattr.TidyAttr) As "_tidyAttrIsTEXT@4"
    tidyAttrIsSTYLE(*tattr.TidyAttr) As "_tidyAttrIsSTYLE@4"
    tidyAttrIsABBR(*tattr.TidyAttr) As "_tidyAttrIsABBR@4"
    tidyAttrIsCOLSPAN(*tattr.TidyAttr) As "_tidyAttrIsCOLSPAN@4"
    tidyAttrIsROWSPAN(*tattr.TidyAttr) As "_tidyAttrIsROWSPAN@4"
    tidyAttrGetById(*tnod.TidyNode, attId.l) As "_tidyAttrGetById@8"
    tidyAttrGetHREF(*tnod.TidyNode) As "_tidyAttrGetHREF@4"
    tidyAttrGetSRC(*tnod.TidyNode) As "_tidyAttrGetSRC@4"
    ;tidyAttrGetID(*tnod.TidyNode) As "_tidyAttrGetID@4"
    tidyAttrGetNAME(*tnod.TidyNode) As "_tidyAttrGetNAME@4"
    tidyAttrGetSUMMARY(*tnod.TidyNode) As "_tidyAttrGetSUMMARY@4"
    tidyAttrGetALT(*tnod.TidyNode) As "_tidyAttrGetALT@4"
    tidyAttrGetLONGDESC(*tnod.TidyNode) As "_tidyAttrGetLONGDESC@4"
    tidyAttrGetUSEMAP(*tnod.TidyNode) As "_tidyAttrGetUSEMAP@4"
    tidyAttrGetISMAP(*tnod.TidyNode) As "_tidyAttrGetISMAP@4"
    tidyAttrGetLANGUAGE(*tnod.TidyNode) As "_tidyAttrGetLANGUAGE@4"
    tidyAttrGetTYPE(*tnod.TidyNode) As "_tidyAttrGetTYPE@4"
    tidyAttrGetVALUE(*tnod.TidyNode) As "_tidyAttrGetVALUE@4"
    tidyAttrGetCONTENT(*tnod.TidyNode) As "_tidyAttrGetCONTENT@4"
    tidyAttrGetTITLE(*tnod.TidyNode) As "_tidyAttrGetTITLE@4"
    tidyAttrGetXMLNS(*tnod.TidyNode) As "_tidyAttrGetXMLNS@4"
    tidyAttrGetDATAFLD(*tnod.TidyNode) As "_tidyAttrGetDATAFLD@4"
    tidyAttrGetWIDTH(*tnod.TidyNode) As "_tidyAttrGetWIDTH@4"
    tidyAttrGetHEIGHT(*tnod.TidyNode) As "_tidyAttrGetHEIGHT@4"
    tidyAttrGetFOR(*tnod.TidyNode) As "_tidyAttrGetFOR@4"
    tidyAttrGetSELECTED(*tnod.TidyNode) As "_tidyAttrGetSELECTED@4"
    tidyAttrGetCHECKED(*tnod.TidyNode) As "_tidyAttrGetCHECKED@4"
    tidyAttrGetLANG(*tnod.TidyNode) As "_tidyAttrGetLANG@4"
    tidyAttrGetTARGET(*tnod.TidyNode) As "_tidyAttrGetTARGET@4"
    tidyAttrGetHTTP_EQUIV(*tnod.TidyNode) As "_tidyAttrGetHTTP_EQUIV@4"
    tidyAttrGetREL(*tnod.TidyNode) As "_tidyAttrGetREL@4"
    tidyAttrGetOnMOUSEMOVE(*tnod.TidyNode) As "_tidyAttrGetOnMOUSEMOVE@4"
    tidyAttrGetOnMOUSEDOWN(*tnod.TidyNode) As "_tidyAttrGetOnMOUSEDOWN@4"
    tidyAttrGetOnMOUSEUP(*tnod.TidyNode) As "_tidyAttrGetOnMOUSEUP@4"
    tidyAttrGetOnCLICK(*tnod.TidyNode) As "_tidyAttrGetOnCLICK@4"
    tidyAttrGetOnMOUSEOVER(*tnod.TidyNode) As "_tidyAttrGetOnMOUSEOVER@4"
    tidyAttrGetOnMOUSEOUT(*tnod.TidyNode) As "_tidyAttrGetOnMOUSEOUT@4"
    tidyAttrGetOnKEYDOWN(*tnod.TidyNode) As "_tidyAttrGetOnKEYDOWN@4"
    tidyAttrGetOnKEYUP(*tnod.TidyNode) As "_tidyAttrGetOnKEYUP@4"
    tidyAttrGetOnKEYPRESS(*tnod.TidyNode) As "_tidyAttrGetOnKEYPRESS@4"
    tidyAttrGetOnFOCUS(*tnod.TidyNode) As "_tidyAttrGetOnFOCUS@4"
    tidyAttrGetOnBLUR(*tnod.TidyNode) As "_tidyAttrGetOnBLUR@4"
    tidyAttrGetBGCOLOR(*tnod.TidyNode) As "_tidyAttrGetBGCOLOR@4"
    tidyAttrGetLINK(*tnod.TidyNode) As "_tidyAttrGetLINK@4"
    tidyAttrGetALINK(*tnod.TidyNode) As "_tidyAttrGetALINK@4"
    tidyAttrGetVLINK(*tnod.TidyNode) As "_tidyAttrGetVLINK@4"
    tidyAttrGetTEXT(*tnod.TidyNode) As "_tidyAttrGetTEXT@4"
    tidyAttrGetSTYLE(*tnod.TidyNode) As "_tidyAttrGetSTYLE@4"
    tidyAttrGetABBR(*tnod.TidyNode) As "_tidyAttrGetABBR@4"
    tidyAttrGetCOLSPAN(*tnod.TidyNode) As "_tidyAttrGetCOLSPAN@4"
    tidyAttrGetROWSPAN(*tnod.TidyNode) As "_tidyAttrGetROWSPAN@4"
    tidyBufInit(*buf.TidyBuffer) As "_tidyBufInit@4"
    tidyBufAlloc(*buf.TidyBuffer, allocSize.l) As "_tidyBufAlloc@8"
    tidyBufCheckAlloc(*buf.TidyBuffer, allocSize.l, chunkSize.l) As "_tidyBufCheckAlloc@12"
    tidyBufFree(*buf.TidyBuffer) As "_tidyBufFree@4"
    tidyBufClear(*buf.TidyBuffer) As "_tidyBufClear@4"
    tidyBufAttach(*buf.TidyBuffer, *bp.b, size.l) As "_tidyBufAttach@12"
    tidyBufDetach(*buf.TidyBuffer) As "_tidyBufDetach@4"
    tidyBufAppend(*buf.TidyBuffer, *vp, size.l) As "_tidyBufAppend@12"
    tidyBufPutByte(*buf.TidyBuffer, bv.l) As "_tidyBufPutByte@8"
    tidyBufPopByte(*buf.TidyBuffer) As "_tidyBufPopByte@4"
    tidyBufGetByte(*buf.TidyBuffer) As "_tidyBufGetByte@4"
    tidyBufEndOfInput(*buf.TidyBuffer) As "_tidyBufEndOfInput@4"
    tidyBufUngetByte(*buf.TidyBuffer, bv.l) As "_tidyBufUngetByte@8"
    initInputBuffer(*inp.TidyInputSource, *buf.TidyBuffer) As "_initInputBuffer@8"
    initOutputBuffer(*outp.TidyOutputSink, *buf.TidyBuffer) As "_initOutputBuffer@8"
  EndImport
;}

; IDE Options = PureBasic 4.10 (Windows - x86)
; Folding = +