XIncludeFile "RW_Aspell_Res.pb"
ImportC "aspell.lib"
  ;-mutable container
  aspell_mutable_container_add(*ths.AspellMutableContainer, to_add.p-ascii) As "_aspell_mutable_container_add"
  aspell_mutable_container_remove(*ths.AspellMutableContainer, to_rem.p-ascii) As "_aspell_mutable_container_remove"
  aspell_mutable_container_clear(*ths.AspellMutableContainer) As "_aspell_mutable_container_clear"
  aspell_mutable_container_to_mutable_container(*ths.AspellMutableContainer) As "_aspell_mutable_container_to_mutable_container"
  ;-config 
  aspell_key_info_enumeration_at_end(*ths.AspellKeyInfoEnumeration) As "_aspell_key_info_enumeration_at_end"
  aspell_key_info_enumeration_next(*ths.AspellKeyInfoEnumeration) As "_aspell_key_info_enumeration_next"
  delete_aspell_key_info_enumeration(*ths.AspellKeyInfoEnumeration) As "_delete_aspell_key_info_enumeration"
  aspell_key_info_enumeration_clone(*ths.AspellKeyInfoEnumeration) As "_aspell_key_info_enumeration_clone"
  aspell_key_info_enumeration_assign(*ths.AspellKeyInfoEnumeration, *other.AspellKeyInfoEnumeration) As "_aspell_key_info_enumeration_assign"
  ;-config 
  new_aspell_config() As "_new_aspell_config"
  delete_aspell_config(*ths.AspellConfig) As "_delete_aspell_config"
  aspell_config_clone(*ths.AspellConfig) As "_aspell_config_clone"
  aspell_config_assign(*ths.AspellConfig, *other.AspellConfig) As "_aspell_config_assign"
  aspell_config_error_number(*ths.AspellConfig) As "_aspell_config_error_number"
  aspell_config_error_message(*ths.AspellConfig) As "_aspell_config_error_message"
  aspell_config_error(*ths.AspellConfig) As "_aspell_config_error"
  aspell_config_set_extra(*ths.AspellConfig, *begin.AspellKeyInfo, *end_.AspellKeyInfo) As "_aspell_config_set_extra"
  aspell_config_keyinfo(*ths.AspellConfig, key.p-ascii) As "_aspell_config_keyinfo"
  aspell_config_possible_elements(*ths.AspellConfig, include_extra.l) As "_aspell_config_possible_elements"
  aspell_config_get_default(*ths.AspellConfig, key.p-ascii) As "_aspell_config_get_default"
  aspell_config_elements(*ths.AspellConfig) As "_aspell_config_elements"
  aspell_config_replace(*ths.AspellConfig, key.p-ascii, value.p-ascii) As "_aspell_config_replace"
  aspell_config_remove(*ths.AspellConfig, key.p-ascii) As "_aspell_config_remove"
  aspell_config_have(*ths.AspellConfig, key.p-ascii) As "_aspell_config_have"
  aspell_config_retrieve(*ths.AspellConfig, key.l) As "_aspell_config_retrieve"
  aspell_config_retrieve_list(*ths.AspellConfig, key.p-ascii, *lst.AspellMutableContainer) As "_aspell_config_retrieve_list"
  aspell_config_retrieve_bool(*ths.AspellConfig, key.p-ascii) As "_aspell_config_retrieve_bool"
  aspell_config_retrieve_int(*ths.AspellConfig, key.p-ascii) As "_aspell_config_retrieve_int"
  ;-error 
  ;aspell_error_is_a(*ths.AspellError, *e.AspellErrorInfo)
  ;-can have error
  aspell_error_number(*ths.AspellCanHaveError) As "_aspell_error_number"
  aspell_error_message(*ths.AspellCanHaveError) As "_aspell_error_message"
  aspell_error(*ths.AspellCanHaveError) As "_aspell_error"
  delete_aspell_can_have_error(*ths.AspellCanHaveError) As "_delete_aspell_can_have_error"
  ;-speller 
  new_aspell_speller(*config.AspellConfig) As "_new_aspell_speller"
  to_aspell_speller(*obj.AspellCanHaveError) As "_to_aspell_speller"
  delete_aspell_speller(*ths.AspellSpeller) As "_delete_aspell_speller"
  aspell_speller_error_number(*ths.AspellSpeller) As "_aspell_speller_error_number"
  aspell_speller_error_message(*ths.AspellSpeller) As "_aspell_speller_error_message"
  aspell_speller_error(*ths.AspellSpeller) As "_aspell_speller_error"
  aspell_speller_config(*ths.AspellSpeller) As "_aspell_speller_config"
  aspell_speller_check(*ths.AspellSpeller, word.p-ascii, word_size.l) As "_aspell_speller_check"
  aspell_speller_add_to_personal(*ths.AspellSpeller, word.p-ascii, word_size.l) As "_aspell_speller_add_to_personal"
  aspell_speller_add_to_session(*ths.AspellSpeller, word.p-ascii, word_size.l) As "_aspell_speller_add_to_session"
  aspell_speller_personal_word_list(*ths.AspellSpeller) As "_aspell_speller_personal_word_list"
  aspell_speller_session_word_list(*ths.AspellSpeller) As "_aspell_speller_session_word_list"
  aspell_speller_main_word_list(*ths.AspellSpeller) As "_aspell_speller_main_word_list"
  aspell_speller_save_all_word_lists(*ths.AspellSpeller) As "_aspell_speller_save_all_word_lists"
  aspell_speller_clear_session(*ths.AspellSpeller) As "_aspell_speller_clear_session"
  aspell_speller_suggest(*ths.AspellSpeller, word.p-ascii, word_size.l) As "_aspell_speller_suggest"
  aspell_speller_store_replacement(*ths.AspellSpeller, mis.p-ascii, mis_size.l, cor.p-ascii, cor_size.l) As "_aspell_speller_store_replacement"
  ;-filter
  delete_aspell_filter(*ths.AspellFilter) As "_delete_aspell_filter"
  aspell_filter_error_number(*ths.AspellFilter) As "_aspell_filter_error_number"
  aspell_filter_error_message(*ths.AspellFilter) As "_aspell_filter_error_message"
  aspell_filter_error(*ths.AspellFilter) As "_aspell_filter_error"
  to_aspell_filter(*obj.AspellCanHaveError) As "_to_aspell_filter"
  ;-document checker 
  delete_aspell_document_checker(*ths.AspellDocumentChecker) As "_delete_aspell_document_checker"
  aspell_document_checker_error_number(*ths.AspellDocumentChecker) As "_aspell_document_checker_error_number"
  aspell_document_checker_error_message(*ths.AspellDocumentChecker) As "_aspell_document_checker_error_message"
  aspell_document_checker_error(*ths.AspellDocumentChecker) As "_aspell_document_checker_error"
  new_aspell_document_checker(*speller.AspellSpeller) As "_new_aspell_document_checker"
  to_aspell_document_checker(*obj.AspellCanHaveError) As "_to_aspell_document_checker"
  aspell_document_checker_reset(*ths.AspellDocumentChecker) As "_aspell_document_checker_reset"
  aspell_document_checker_process(*ths.AspellDocumentChecker, str.p-ascii, size.l) As "_aspell_document_checker_process"
  aspell_document_checker_next_misspelling(*ths.AspellDocumentChecker) As "_aspell_document_checker_next_misspelling"
  aspell_document_checker_filter(*ths.AspellDocumentChecker) As "_aspell_document_checker_filter"
  ;-word list
  aspell_word_list_empty(*ths.AspellWordList) As "_aspell_word_list_empty"
  aspell_word_list_size(*ths.AspellWordList) As "_aspell_word_list_size"
  aspell_word_list_elements(*ths.AspellWordList) As "_aspell_word_list_elements"
  ;-string enumeration
  delete_aspell_string_enumeration(*ths.AspellStringEnumeration) As "_delete_aspell_string_enumeration"
  aspell_string_enumeration_clone(*ths.AspellStringEnumeration) As "_aspell_string_enumeration_clone"
  aspell_string_enumeration_assign(*ths.AspellStringEnumeration, *other.AspellStringEnumeration) As "_aspell_string_enumeration_assign"
  aspell_string_enumeration_at_end(*ths.AspellStringEnumeration) As "_aspell_string_enumeration_at_end"
  aspell_string_enumeration_next(*ths.AspellStringEnumeration) As "_aspell_string_enumeration_next"
  ;-info
  get_aspell_module_info_list(*config.AspellConfig) As "_get_aspell_module_info_list"
  aspell_module_info_list_empty(*ths.AspellModuleInfoList) As "_aspell_module_info_list_empty"
  aspell_module_info_list_size(*ths.AspellModuleInfoList) As "_aspell_module_info_list_size"
  aspell_module_info_list_elements(*ths.AspellModuleInfoList) As "_aspell_module_info_list_elements"
  get_aspell_dict_info_list(*config.AspellConfig) As "_get_aspell_dict_info_list"
  aspell_dict_info_list_empty(*ths.AspellDictInfoList) As "_aspell_dict_info_list_empty"
  aspell_dict_info_list_size(*ths.AspellDictInfoList) As "_aspell_dict_info_list_size"
  aspell_dict_info_list_elements(*ths.AspellDictInfoList) As "_aspell_dict_info_list_elements"
  aspell_module_info_enumeration_at_end(*ths.AspellModuleInfoEnumeration) As "_aspell_module_info_enumeration_at_end"
  aspell_module_info_enumeration_next(*ths.AspellModuleInfoEnumeration) As "_aspell_module_info_enumeration_next"
  delete_aspell_module_info_enumeration(*ths.AspellModuleInfoEnumeration) As "_delete_aspell_module_info_enumeration"
  aspell_module_info_enumeration_clone(*ths.AspellModuleInfoEnumeration) As "_aspell_module_info_enumeration_clone"
  aspell_module_info_enumeration_assign(*ths.AspellModuleInfoEnumeration, *other.AspellModuleInfoEnumeration) As "_aspell_module_info_enumeration_assign"
  aspell_dict_info_enumeration_at_end(*ths.AspellDictInfoEnumeration) As "_aspell_dict_info_enumeration_at_end"
  aspell_dict_info_enumeration_next(*ths.AspellDictInfoEnumeration) As "_aspell_dict_info_enumeration_next"
  delete_aspell_dict_info_enumeration(*ths.AspellDictInfoEnumeration) As "_delete_aspell_dict_info_enumeration"
  aspell_dict_info_enumeration_clone(*ths.AspellDictInfoEnumeration) As "_aspell_dict_info_enumeration_clone"
  aspell_dict_info_enumeration_assign(*ths.AspellDictInfoEnumeration, *other.AspellDictInfoEnumeration) As "_aspell_dict_info_enumeration_assign"
  ;-string list
  new_aspell_string_list() As "_new_aspell_string_list"
  aspell_string_list_empty(*ths.AspellStringList) As "_aspell_string_list_empty"
  aspell_string_list_size(*ths.AspellStringList) As "_aspell_string_list_size"
  aspell_string_list_elements(*ths.AspellStringList) As "_aspell_string_list_elements"
  aspell_string_list_add(*ths.AspellStringList, to_add.p-ascii) As "_aspell_string_list_add"
  aspell_string_list_remove(*ths.AspellStringList, to_rem.p-ascii) As "_aspell_string_list_remove"
  aspell_string_list_clear(*ths.AspellStringList) As "_aspell_string_list_clear"
  aspell_string_list_to_mutable_container(*ths.AspellStringList) As "_aspell_string_list_to_mutable_container"
  delete_aspell_string_list(*ths.AspellStringList) As "_delete_aspell_string_list"
  aspell_string_list_clone(*ths.AspellStringList) As "_aspell_string_list_clone"
  aspell_string_list_assign(*ths.AspellStringList, *other.AspellStringList) As "_aspell_string_list_assign"
  ;-string map
  new_aspell_string_map() As "_new_aspell_string_map"
  aspell_string_map_add(*ths.AspellStringMap, to_add.p-ascii) As "_aspell_string_map_add"
  aspell_string_map_remove(*ths.AspellStringMap, to_rem.p-ascii) As "_aspell_string_map_remove"
  aspell_string_map_clear(*ths.AspellStringMap) As "_aspell_string_map_clear"
  aspell_string_map_to_mutable_container(*ths.AspellStringMap) As "_aspell_string_map_to_mutable_container"
  delete_aspell_string_map(*ths.AspellStringMap) As "_delete_aspell_string_map"
  aspell_string_map_clone(*ths.AspellStringMap) As "_aspell_string_map_clone"
  aspell_string_map_assign(*ths.AspellStringMap, *other.AspellStringMap) As "_aspell_string_map_assign"
  aspell_string_map_empty(*ths.AspellStringMap) As "_aspell_string_map_empty"
  aspell_string_map_size(*ths.AspellStringMap) As "_aspell_string_map_size"
  aspell_string_map_elements(*ths.AspellStringMap) As "_aspell_string_map_elements"
  aspell_string_map_insert(*ths.AspellStringMap, key.p-ascii, value.p-ascii) As "_aspell_string_map_insert"
  aspell_string_map_replace(*ths.AspellStringMap, key.p-ascii, value.p-ascii) As "_aspell_string_map_replace"
  aspell_string_map_lookup(*ths.AspellStringMap, key.p-ascii) As "_aspell_string_map_lookup"
  ;-string pair enumeration
  aspell_string_pair_enumeration_at_end(*ths.AspellStringPairEnumeration) As "_aspell_string_pair_enumeration_at_end"
  aspell_string_pair_enumeration_next(*ths.AspellStringPairEnumeration) As "_aspell_string_pair_enumeration_next"
  delete_aspell_string_pair_enumeration(*ths.AspellStringPairEnumeration) As "_delete_aspell_string_pair_enumeration"
  aspell_string_pair_enumeration_clone(*ths.AspellStringPairEnumeration) As "_aspell_string_pair_enumeration_clone"
  aspell_string_pair_enumeration_assign(*ths.AspellStringPairEnumeration, *other.AspellStringPairEnumeration) As "_aspell_string_pair_enumeration_assign"
  ;-cache
  ;aspell_reset_cache(which.p-ascii)
EndImport


; IDE Options = PureBasic 4.10 (Windows - x86)
; CursorPosition = 29
; FirstLine = 26
; Folding = -