  Enumeration 0
    #ISL_Value1
    #ISL_Value2
    #ISL_Value3
    #ISL_Value4
    #ISL_Value5
    #ISL_Value6
    #ISL_Value7
    #ISL_Value8
    #ISL_Value9
    #ISL_Value10
    #ISL_Value11
    #ISL_Value12
    #ISL_Value13
    #ISL_Value14
    #ISL_Value15
    #ISL_Value16
    #ISL_Value17
    #ISL_Value18
    #ISL_Value19
    #ISL_Value20
  EndEnumeration
  Enumeration 0
    #ISL_Effect1
    #ISL_Effect2
    #ISL_Effect3
    #ISL_Effect4
    #ISL_Effect5
    #ISL_Effect6
    #ISL_Effect7
    #ISL_Effect8
    #ISL_Effect9
    #ISL_Effect10
    #ISL_Effect11
    #ISL_Effect12
    #ISL_Effect13
    #ISL_Effect14
    #ISL_Effect15
    #ISL_Effect16
    #ISL_Effect17
    #ISL_Effect18
    #ISL_Effect19
    #ISL_Effect20
  EndEnumeration
  Enumeration 1
    #ISL_LINES
    #ISL_CIRCLES
    #ISL_RECTANGLES
    #ISL_SPLINES
    #ISL_PLASMA 
    #ISL_TWIRL 
    #ISL_BLUR 
    #ISL_CLEAR_IMAGE 
    #ISL_GAMMA_CORRECTION 
    #ISL_BRIGHTNESS 
    #ISL_PERLIN_NOISE 
    #ISL_MOVE_TO_BUFFER 
    #ISL_SINE_DISTORTION 
    #ISL_DISTORTION_BY_BUFFER 
    #ISL_CONNECT_BUFFER 
    #ISL_WAVES 
    #ISL_DIVIDER 
    #ISL_CARPET 
    #ISL_EDGE 
    #ISL_BLOBS 
    #ISL_NOISE 
    #ISL_VOXEL 
    #ISL_EMBOSS 
    #ISL_SINE_PLASMA 
    #ISL_MAXIMUM 
    #ISL_MINIMUM 
    #ISL_BUMP 
    #ISL_COLORIZE 
    #ISL_INVERSION 
    #ISL_THRESHOLD 
    #ISL_CONTRAST 
    #ISL_HSV 
    #ISL_ADD_TO_BUFFER 
    #ISL_EXCHANGE_BUFFER 
    #ISL_UNSHARP_MASK 
    #ISL_MEDIAN 
    #ISL_WORMS 
    #ISL_OFFSET 
    #ISL_GLASS 
    #ISL_IMAGE_FILE 
    #ISL_FLIP 
    #ISL_PATTERN 
    #ISL_POINTS 
    #ISL_SHIFTER 
    #ISL_PINCH 
    #ISL_MOTION_BLUR 
    #ISL_FREEHAND_LAYER 
    #ISL_GRADIENT_MAP 
    #ISL_KALEIDOSCOPE 
    #ISL_ZOOM 
    #ISL_ROTATE 
    #ISL_SEAMLESS 
    #ISL_BORDER 
    #ISL_TILT 
    #ISL_FRACTAL_PLASMA 
    #ISL_SCRATCH 
    #ISL_GAUSSIAN_BLUR 
    #ISL_TREES 
    #ISL_FIBERS 
  EndEnumeration
  #ISL_NOERROR  = 1

  Structure ISL_ScriptHeader
    soh.l
    marker.l
    version.l
    effects.l
    width.l
    height.l
    seamless.l
    remark.b[64]
    buffers.l
    rnd.l
  EndStructure

; IDE Options = PureBasic 4.20 (Windows - x86)
; CursorPosition = 119
; Folding = w