XIncludeFile "RW_qDecoder_Res.pb"

Import "qDecoder.lib"
  qCheckEmail(email.s) As "_qCheckEmail"
  qCheckURL(url.s) As "_qCheckURL"
  qGetGMTime(gmt.s, plus_sec.l) As "_qGetGMTime"
  qGetTime() As "_qGetTime"
  qPrintf(mode.l, format.s) As "_qPrintf"
  qPuts(mode.l, buf.s) As "_qPuts"
  qRemoveSpace(str.s) As "_qRemoveSpace"
  qStr09AZaz(str.s) As "_qStr09AZaz"
  qStrReplace(mode.s, srcstr.s, tokstr.s, word.s) As "_qStrReplace"
  qStricmp(s1.s, s2.s) As "_qStricmp"
  qStrincmp(s1.s, s2.s, len.l) As "_qStrincmp"
  qStristr(big.s, small.s) As "_qStristr"
  qStrlwr(str.s) As "_qStrlwr"
  qStrupr(str.s) As "_qStrupr"
  qitocomma(value.l) As "_qitocomma"
  qSession(repository.s) As "_qSession"
  qSessionAdd(name.s, format.s) As "_qSessionAdd"
  qSessionAddInteger(name.s, valueint.l) As "_qSessionAddInteger"
  qSessionDestroy() As "_qSessionDestroy"
  qSessionFree() As "_qSessionFree"
  qSessionGetCreated() As "_qSessionGetCreated"
  qSessionGetID() As "_qSessionGetID"
  qSessionPrint() As "_qSessionPrint"
  qSessionRemove(format.s) As "_qSessionRemove"
  qSessionSave() As "_qSessionSave"
  qSessionSetTimeout(seconds.l) As "_qSessionSetTimeout"
  qSessionUpdateInteger(name.s, plusint.l) As "_qSessionUpdateInteger"
  qSessionValue(format.s) As "_qSessionValue"
  qSessionValueInteger(format.s) As "_qSessionValueInteger"
  qSedArgAdd(*first.Q_Entry, name.s, format.s) As "_qSedArgAdd"
  qSedArgFree(*first.Q_Entry) As "_qSedArgFree"
  qSedArgPrint(*first.Q_Entry) As "_qSedArgPrint"
  qSedFile(*first.Q_Entry, filename.s, *fpout) As "_qSedFile"
  qSedStr(*first.Q_Entry, srcstr.s, *fpout) As "_qSedStr"
  qsDecoder(str.s) As "_qsDecoder"
  qsFree(*first.Q_Entry) As "_qsFree"
  qsPrint(*first.Q_Entry) As "_qsPrint"
  qsValue(*first.Q_Entry, format.s) As "_qsValue"
  qsValueFirst(*first.Q_Entry, format.s) As "_qsValueFirst"
  qsValueNext() As "_qsValueNext"
  qsiValue(*first.Q_Entry, format.s) As "_qsiValue"
  qFreeAll() As "_qFreeAll"
  qReset() As "_qReset"
  qUniqueID() As "_qUniqueID"
  EntryAdd(*first.Q_Entry, name.s, value.s) As "__EntryAdd"
  EntryFree(*first.Q_Entry) As "__EntryFree"
  EntryLoad(filename.s) As "__EntryLoad"
  EntryNo(*first.Q_Entry, name.s) As "__EntryNo"
  EntryPrint(*first.Q_Entry) As "__EntryPrint"
  EntryRemove(*first.Q_Entry, name.s) As "__EntryRemove"
  EntrySave(*first.Q_Entry, filename.s) As "__EntrySave"
  EntryValue(*first.Q_Entry, name.s) As "__EntryValue"
  EntryiValue(*first.Q_Entry, name.s) As "__EntryiValue"
  fgets(str.s, size.l, *stream) As "__fgets"
  flockclose(*fp) As "__flockclose"
  flockopen(*fp) As "__flockopen"
  Makeword(str.s, *stop) As "__makeword"
  strtok2(str.s, token.s, retstop.s) As "__strtok2"
  x2c(*hex_up, *hex_low) As "__x2c"
  qContentType(mimetype.s) As "_qContentType"
  qGetContentFlag() As "_qGetContentFlag"
  qRedirect(url.s) As "_qRedirect"
  qResetContentFlag() As "_qResetContentFlag"
  qCatFile(format.s) As "_qCatFile"
  qCheckFile(format.s) As "_qCheckFile"
  qFileSize(filename.s) As "_qFileSize"
  qReadFile(filename.s, size.l) As "_qReadFile"
  qSaveStr(sp.s, spsize.l, filename.s, mode.s) As "_qSaveStr"
  qfGetLine(*fp) As "_qfGetLine"
  qfclose(*stream) As "_qfclose"
  qfopen(path.s, mode.s) As "_qfopen"
  qfDecoder(filename.s) As "_qfDecoder"
  qError(format.s) As "_qError"
  qErrorContact(msg.s) As "_qErrorContact"
  qErrorLog(filename.s) As "_qErrorLog"
  qCGIenv(*env.Q_CGIenv) As "_qCGIenv"
  qCGIname() As "_qCGIname"
  qGetenvDefault(nullstr.s, envname.s) As "_qGetenvDefault"
  qMD5File(filename.s) As "_qMD5File"
  qMD5Str(string.s) As "_qMD5Str"
  qURLdecode(str.s) As "_qURLdecode"
  qURLencode(str.s) As "_qURLencode"
  qDownload(filename.s) As "_qDownload"
  qDownloadMime(filename.s, mime.s) As "_qDownloadMime"
  qCookieRemove(name.s, path.s, domain.s, secure.s) As "_qCookieRemove"
  qCookieSet(name.s, value.s, expl_day.s, path.s, domain.s, secure.s) As "_qCookieSet"
  qCookieValue(format.s) As "_qCookieValue"
  qDecoder() As "_qDecoder"
  qFree() As "_qFree"
  qGetFirstEntry() As "_qGetFirstEntry"
  qPrint() As "_qPrint"
  qValue(format.s) As "_qValue"
  qValueAdd(name.s, format.s) As "_qValueAdd"
  qValueDefault(defstr.s, format.s) As "_qValueDefault"
  qValueFirst(format.s) As "_qValueFirst"
  qValueNext() As "_qValueNext"
  qValueNotEmpty(errmsg.s, format.s) As "_qValueNotEmpty"
  qValueRemove(format.s) As "_qValueRemove"
  qValueReplace(mode.s, name.s, tokstr.s, word.s) As "_qValueReplace"
  qValueType(format.s) As "_qValueType"
  qiValue(format.s) As "_qiValue"
  qCountRead(filename.s) As "_qCountRead"
  qCountSave(filename.s, number.l) As "_qCountSave"
  qCountUpdate(filename.s, number.l) As "_qCountUpdate"
  qAwkClose() As "_qAwkClose"
  qAwkNext(array_.s) As "_qAwkNext"
  qAwkOpen(filename.s, *separator) As "_qAwkOpen"
  qArgEmprint(mode.l, str.s, *qlist) As "_qArgEmprint"
  qArgFree(*qlist) As "_qArgFree"
  qArgMake(str.s, *qlist) As "_qArgMake"
  qArgMatch(str.s, *qlist) As "_qArgMatch"
  qArgPrint(*qlist) As "_qArgPrint"
  MD5Final(arg1.s, *str.MD5_CTX) As "_MD5Final"
  MD5Init(*str.MD5_CTX) As "_MD5Init"
  MD5Update(*str.MD5_CTX, arg1.s, arg2.l) As "_MD5Update"
EndImport
