XIncludeFile "RW_MySQL_Res.pb"

Import "libmysql.lib"
;   dig_vec_lower() As "__dig_vec_lower"
;   dig_vec_upper() As "__dig_vec_upper"
;   bmove_upp() As "_bmove_upp"
;   delete_dynamic() As "_delete_dynamic"
;   free_defaults() As "_free_defaults"
;   getopt_compare_strings() As "_getopt_compare_strings"
;   getopt_ull_limit_value() As "_getopt_ull_limit_value"
;   handle_options() As "_handle_options"
;   init_dynamic_array() As "_init_dynamic_array"
;   insert_dynamic() As "_insert_dynamic"
;   int2str() As "_int2str"
;   is_prefix() As "_is_prefix"
  list_add(*root.LIST, *element.LIST) As "_list_add"
  list_delete(*root.LIST, *element.LIST) As "_list_delete"
  load_defaults(conf_file.p-ascii, *groups.p-ascii, argc.l, argv.l) As "_load_defaults"
;   my_end() As "_my_end"
;   my_getopt_print_errors() As "_my_getopt_print_errors"
;   my_init() As "_my_init"
;   my_malloc() As "_my_malloc"
;   my_memdup() As "_my_memdup"
;   my_no_flags_free() As "_my_no_flags_free"
;   my_path() As "_my_path"
  mysql_get_parameters() As "_mysql_get_parameters@0"
;   my_print_help() As "_my_print_help"
;   my_print_variables() As "_my_print_variables"
;   my_realloc() As "_my_realloc"
;   my_strdup() As "_my_strdup"
  mysql_thread_end() As "_mysql_thread_end@0"
  mysql_thread_init() As "_mysql_thread_init@0"
  myodbc_remove_escape(*mysql.MYSQL, name.p-ascii) As "_myodbc_remove_escape@8"
  mysql_affected_rows(*mysql.MYSQL) As "_mysql_affected_rows@4"
  mysql_autocommit(*mysql.MYSQL, auto_mode.l) As "_mysql_autocommit@8"
  mysql_stmt_bind_param(*stmt.MYSQL_STMT, *bnd.MYSQL_BIND) As "_mysql_stmt_bind_param@8"
  mysql_stmt_bind_result(*stmt.MYSQL_STMT, *bnd.MYSQL_BIND) As "_mysql_stmt_bind_result@8"
  mysql_change_user(*mysql.MYSQL, user.p-ascii, passwd.p-ascii, db.p-ascii) As "_mysql_change_user@16"
  mysql_character_set_name(*mysql.MYSQL) As "_mysql_character_set_name@4"
  mysql_close(*mysql.MYSQL) As "_mysql_close@4"
  mysql_commit(*mysql.MYSQL) As "_mysql_commit@4"
  mysql_data_seek(*result.MYSQL_RES, offset.l) As "_mysql_data_seek@12"
  mysql_debug(debug_.p-ascii) As "_mysql_debug@4"
  mysql_dump_debug_info(*mysql.MYSQL) As "_mysql_dump_debug_info@4"
  mysql_eof(*res.MYSQL_RES) As "_mysql_eof@4"
  mysql_errno(*mysql.MYSQL) As "_mysql_errno@4"
  mysql_error(*mysql.MYSQL) As "_mysql_error@4"
  mysql_escape_string(to_.p-ascii, from_.p-ascii, from_length.l) As "_mysql_escape_string@12"
  mysql_hex_string(to_.p-ascii, from_.p-ascii, from_length.l) As "_mysql_hex_string@12"
  mysql_stmt_execute(*stmt.MYSQL_STMT) As "_mysql_stmt_execute@4"
  mysql_stmt_fetch(*stmt.MYSQL_STMT) As "_mysql_stmt_fetch@4"
  mysql_stmt_fetch_column(*stmt.MYSQL_STMT, *bind_arg.MYSQL_BIND, colum.l, offset.l) As "_mysql_stmt_fetch_column@16"
  mysql_fetch_field(*res.MYSQL_RES) As "_mysql_fetch_field@4"
  mysql_fetch_field_direct(*res.MYSQL_RES, fieldnr.l) As "_mysql_fetch_field_direct@8"
  mysql_fetch_fields(*result.MYSQL_RES) As "_mysql_fetch_fields@4"
  mysql_fetch_lengths(*result.MYSQL_RES) As "_mysql_fetch_lengths@4"
  mysql_fetch_row(*result.MYSQL_RES) As "_mysql_fetch_row@4"
  mysql_field_count(*mysql.MYSQL) As "_mysql_field_count@4"
  mysql_field_seek(*result.MYSQL_RES, offset.l) As "_mysql_field_seek@8"
  mysql_field_tell(*res.MYSQL_RES) As "_mysql_field_tell@4"
  mysql_free_result(*result.MYSQL_RES) As "_mysql_free_result@4"
  mysql_get_client_info() As "_mysql_get_client_info@0"
  mysql_get_host_info(*mysql.MYSQL) As "_mysql_get_host_info@4"
  mysql_get_proto_info(*mysql.MYSQL) As "_mysql_get_proto_info@4"
  mysql_get_server_info(*mysql.MYSQL) As "_mysql_get_server_info@4"
  mysql_get_client_version() As "_mysql_get_client_version@0"
  mysql_get_ssl_cipher(*mysql.MYSQL) As "_mysql_get_ssl_cipher@4"
  mysql_info(*mysql.MYSQL) As "_mysql_info@4"
  mysql_init(*mysql.MYSQL) As "_mysql_init@4"
  mysql_insert_id(*mysql.MYSQL) As "_mysql_insert_id@4"
  mysql_kill(*mysql.MYSQL, pid.l) As "_mysql_kill@8"
  mysql_set_server_option(*mysql.MYSQL, option.l) As "_mysql_set_server_option@8"
  mysql_list_dbs(*mysql.MYSQL, wild.p-ascii) As "_mysql_list_dbs@8"
  mysql_list_fields(*mysql.MYSQL, table.p-ascii, wild.p-ascii) As "_mysql_list_fields@12"
  mysql_list_processes(*mysql.MYSQL) As "_mysql_list_processes@4"
  mysql_list_tables(*mysql.MYSQL, wild.p-ascii) As "_mysql_list_tables@8"
  mysql_more_results(*mysql.MYSQL) As "_mysql_more_results@4"
  mysql_next_result(*mysql.MYSQL) As "_mysql_next_result@4"
  mysql_num_fields(*res.MYSQL_RES) As "_mysql_num_fields@4"
  mysql_num_rows(*res.MYSQL_RES) As "_mysql_num_rows@4"
  mysql_options(*mysql.MYSQL, option.l, arg.p-ascii) As "_mysql_options@12"
  mysql_stmt_param_count(*stmt.MYSQL_STMT) As "_mysql_stmt_param_count@4"
  mysql_stmt_param_metadata(*stmt.MYSQL_STMT) As "_mysql_stmt_param_metadata@4"
  mysql_ping(*mysql.MYSQL) As "_mysql_ping@4"
  mysql_stmt_result_metadata(*stmt.MYSQL_STMT) As "_mysql_stmt_result_metadata@4"
  mysql_query(*mysql.MYSQL, q.p-ascii) As "_mysql_query@8"
  mysql_read_query_result(*mysql.MYSQL) As "_mysql_read_query_result@4"
  mysql_real_connect(*mysql.MYSQL, host.p-ascii, user.p-ascii, passwd.p-ascii, db.p-ascii, port.l, unix_socket.p-ascii, clientflag.l) As "_mysql_real_connect@32"
  mysql_real_escape_string(*mysql.MYSQL, to_.p-ascii, from_.p-ascii, length.l) As "_mysql_real_escape_string@16"
  mysql_real_query(*mysql.MYSQL, q.p-ascii, length.l) As "_mysql_real_query@12"
  mysql_refresh(*mysql.MYSQL, refresh_options.l) As "_mysql_refresh@8"
  mysql_rollback(*mysql.MYSQL) As "_mysql_rollback@4"
  mysql_row_seek(*result.MYSQL_RES, offset.l) As "_mysql_row_seek@8"
  mysql_row_tell(a.l) As "_mysql_row_tell@4"
  mysql_select_db(*mysql.MYSQL, db.p-ascii) As "_mysql_select_db@8"
  mysql_stmt_send_long_data(*stmt.MYSQL_STMT, param_number.l, data_.p-ascii, length.l) As "_mysql_stmt_send_long_data@16"
  mysql_send_query(*mysql.MYSQL, q.p-ascii, length.l) As "_mysql_send_query@12"
  mysql_shutdown(*mysql.MYSQL, shutdown_level.l) As "_mysql_shutdown@8"
  mysql_ssl_set(*mysql.MYSQL, key.p-ascii, cert.p-ascii, ca.p-ascii, capath.p-ascii, cipher.p-ascii) As "_mysql_ssl_set@24"
  mysql_stat(*mysql.MYSQL) As "_mysql_stat@4"
  mysql_stmt_affected_rows(*stmt.MYSQL_STMT) As "_mysql_stmt_affected_rows@4"
  mysql_stmt_close(*stmt.MYSQL_STMT) As "_mysql_stmt_close@4"
  mysql_stmt_reset(*stmt.MYSQL_STMT) As "_mysql_stmt_reset@4"
  mysql_stmt_data_seek(*stmt.MYSQL_STMT, offset.l) As "_mysql_stmt_data_seek@12"
  mysql_stmt_errno(*stmt.MYSQL_STMT) As "_mysql_stmt_errno@4"
  mysql_stmt_error(*stmt.MYSQL_STMT) As "_mysql_stmt_error@4"
  mysql_stmt_free_result(*stmt.MYSQL_STMT) As "_mysql_stmt_free_result@4"
  mysql_stmt_num_rows(*stmt.MYSQL_STMT) As "_mysql_stmt_num_rows@4"
  mysql_stmt_row_seek(*stmt.MYSQL_STMT, offset.l) As "_mysql_stmt_row_seek@8"
  mysql_stmt_row_tell(*stmt.MYSQL_STMT) As "_mysql_stmt_row_tell@4"
  mysql_stmt_store_result(*stmt.MYSQL_STMT) As "_mysql_stmt_store_result@4"
  mysql_store_result(*mysql.MYSQL) As "_mysql_store_result@4"
  mysql_thread_id(*mysql.MYSQL) As "_mysql_thread_id@4"
  mysql_thread_safe() As "_mysql_thread_safe@0"
  mysql_use_result(*mysql.MYSQL) As "_mysql_use_result@4"
  mysql_warning_count(*mysql.MYSQL) As "_mysql_warning_count@4"
  mysql_stmt_sqlstate(*stmt.MYSQL_STMT) As "_mysql_stmt_sqlstate@4"
  mysql_sqlstate(*mysql.MYSQL) As "_mysql_sqlstate@4"
  mysql_get_server_version(*mysql.MYSQL) As "_mysql_get_server_version@4"
;   set_dynamic() As "_set_dynamic"
;   strcend() As "_strcend"
;   strcont() As "_strcont"
;   strdup_root() As "_strdup_root"
;   strfill() As "_strfill"
;   strinstr() As "_strinstr"
;   strmake() As "_strmake"
;   strmov() As "_strmov"
;   strxmov() As "_strxmov"
  mysql_stmt_prepare(*mysql.MYSQL, query.p-ascii, length.l) As "_mysql_stmt_prepare@12"
  mysql_stmt_init(*mysql.MYSQL) As "_mysql_stmt_init@4"
  mysql_stmt_insert_id(*stmt.MYSQL_STMT) As "_mysql_stmt_insert_id@4"
  mysql_stmt_attr_get(*stmt.MYSQL_STMT, attr_type.l, *attr) As "_mysql_stmt_attr_get@12"
  mysql_stmt_attr_set(*stmt.MYSQL_STMT, attr_type.l, *attr) As "_mysql_stmt_attr_set@12"
  mysql_stmt_field_count(a.l) As "_mysql_stmt_field_count@4"
;   client_errors() As "_client_errors"
  mysql_set_local_infile_default(*mysql.MYSQL) As "_mysql_set_local_infile_default"
  mysql_set_local_infile_handler(*mysql.MYSQL, *local_infile_init, *local_infile_read, *local_infile_end, *local_infile_error, arg.l) As "_mysql_set_local_infile_handler"
  mysql_disable_reads_from_master(*mysql.MYSQL) As "_mysql_disable_reads_from_master@4"
  mysql_disable_rpl_parse(*mysql.MYSQL) As "_mysql_disable_rpl_parse@4"
  mysql_enable_reads_from_master(*mysql.MYSQL) As "_mysql_enable_reads_from_master@4"
  mysql_enable_rpl_parse(*mysql.MYSQL) As "_mysql_enable_rpl_parse@4"
  mysql_master_query(*mysql.MYSQL, q.p-ascii, length.l) As "_mysql_master_query@12"
  mysql_rpl_parse_enabled(*mysql.MYSQL) As "_mysql_rpl_parse_enabled@4"
  mysql_rpl_probe(*mysql.MYSQL) As "_mysql_rpl_probe@4"
  mysql_rpl_query_type(q.p-ascii, length.l) As "_mysql_rpl_query_type@8"
  mysql_slave_query(*mysql.MYSQL, q.p-ascii, length.l) As "_mysql_slave_query@12"
  mysql_embedded() As "_mysql_embedded@0"
  mysql_server_init(argc.l, argv.l, groups.l) As "_mysql_server_init@12"
  mysql_server_end() As "_mysql_server_end@0"
  mysql_set_character_set(*mysql.MYSQL, csname.p-ascii) As "_mysql_set_character_set@8"
  mysql_get_character_set_info(*mysql.MYSQL, charset.l) As "_mysql_get_character_set_info@8"
;   get_defaults_options() As "_get_defaults_options"
  modify_defaults_file(file_location.p-ascii, option.p-ascii, option_value.p-ascii, section_name.p-ascii, remove_option.l) As "_modify_defaults_file"
EndImport
Import "mysqlclient.lib"
;   LOCK_gethostbyname_r() As "_LOCK_gethostbyname_r"
;   LOCK_localtime_r() As "_LOCK_localtime_r"
;   TERMINATE() As "_TERMINATE"
;   THR_COND_threads() As "_THR_COND_threads"
;   THR_KEY_mysys() As "_THR_KEY_mysys"
;   THR_LOCK_charset() As "_THR_LOCK_charset"
;   THR_LOCK_heap() As "_THR_LOCK_heap"
;   THR_LOCK_isam() As "_THR_LOCK_isam"
;   THR_LOCK_lock() As "_THR_LOCK_lock"
;   THR_LOCK_malloc() As "_THR_LOCK_malloc"
;   THR_LOCK_myisam() As "_THR_LOCK_myisam"
;   THR_LOCK_net() As "_THR_LOCK_net"
;   THR_LOCK_open() As "_THR_LOCK_open"
;   THR_LOCK_threads() As "_THR_LOCK_threads"
;   THR_thread_count() As "_THR_thread_count"
;   TIME_to_ulonglong() As "_TIME_to_ulonglong"
;   TIME_to_ulonglong_date() As "_TIME_to_ulonglong_date"
;   TIME_to_ulonglong_datetime() As "_TIME_to_ulonglong_datetime"
;   TIME_to_ulonglong_time() As "_TIME_to_ulonglong_time"
;   dig_vec_lower() As "__dig_vec_lower"
;   dig_vec_upper() As "__dig_vec_upper"
;   dist_code() As "__dist_code"
;   hash_init() As "__hash_init"
;   length_code() As "__length_code"
;   my_b_get() As "__my_b_get"
;   my_b_read() As "__my_b_read"
;   my_b_read_r() As "__my_b_read_r"
;   my_b_seq_read() As "__my_b_seq_read"
;   my_b_write() As "__my_b_write"
;   my_memdup() As "__my_memdup"
;   my_sig_remember() As "__my_sig_remember"
;   my_signals() As "__my_signals"
;   my_strdup() As "__my_strdup"
;   my_strdup_with_length() As "__my_strdup_with_length"
;   my_thread_var() As "__my_thread_var"
;   myfree() As "__myfree"
;   mymalloc() As "__mymalloc"
;   myrealloc() As "__myrealloc"
;   real00000000000000() As "__real@0000000000000000"
;   real000730d67819e8() As "__real@000730d67819e8d2"
;   real3e100000004000() As "__real@3e10000000400000"
;   real3fd55555555555() As "__real@3fd5555555555555"
;   real3fe55555555555() As "__real@3fe5555555555555"
;   real3ff00000000000() As "__real@3ff0000000000000"
;   real3ffcc359e067a3() As "__real@3ffcc359e067a348"
;   real40033333333333() As "__real@4003333333333333"
;   real40140000000000() As "__real@4014000000000000"
;   real40240000000000() As "__real@4024000000000000"
;   real403f0000000000() As "__real@403f000000000000"
;   real40408000000000() As "__real@4040800000000000"
;   real40500000000000() As "__real@4050000000000000"
;   real40578000000000() As "__real@4057800000000000"
;   real41cfffffff8000(a.l,b.l,c.l,d.l,e.l,f.l,g.l,h.l,i.l,j.l) As "__real@41cfffffff800000"
;   real41f00000000000(a.l,b.l,c.l,d.l,e.l,f.l,g.l,h.l,i.l,j.l) As "__real@41f0000000000000"
;   real43f00000000000(a.l,b.l,c.l,d.l,e.l,f.l,g.l,h.l,i.l,j.l) As "__real@43f0000000000000"
;   real7fe1ccf385ebc8(a.l) As "__real@7fe1ccf385ebc8a0"
;   real7fefffffffffff(a.l) As "__real@7fefffffffffffff"
;   sanity() As "__sanity"
;   tr_align() As "__tr_align"
;   tr_flush_block() As "__tr_flush_block"
;   tr_init() As "__tr_init"
;   tr_stored_block() As "__tr_stored_block"
;   tr_tally() As "__tr_tally"
;   add_compiled_collation() As "_add_compiled_collation"
;   adler32() As "_adler32"
;   adler32_combine() As "_adler32_combine"
;   all_charsets() As "_all_charsets"
;   alloc_dynamic() As "_alloc_dynamic"
;   alloc_root() As "_alloc_root"
;   array_append_string_unique() As "_array_append_string_unique"
;   bchange() As "_bchange"
;   bmove_upp() As "_bmove_upp"
;   calc_daynr() As "_calc_daynr"
;   calc_days_in_year() As "_calc_days_in_year"
;   cant_connect_sqlstate() As "_cant_connect_sqlstate"
;   charsets_dir() As "_charsets_dir"
;   check_date() As "_check_date"
;   check_if_legal_filename() As "_check_if_legal_filename"
  check_scramble(reply.p-ascii, message.p-ascii, hast_stage2.l) As "_check_scramble"
  check_scramble_323(arg1.p-ascii, message.p-ascii, salt.l) As "_check_scramble_323"
;   check_time_range() As "_check_time_range"
;   cleanup_dirname() As "_cleanup_dirname"
;   cli_advanced_command() As "_cli_advanced_command"
;   cli_list_fields() As "_cli_list_fields"
;   cli_read_binary_rows() As "_cli_read_binary_rows"
;   cli_read_change_user_result() As "_cli_read_change_user_result"
;   cli_read_prepare_result() As "_cli_read_prepare_result"
;   cli_read_rows() As "_cli_read_rows"
;   cli_read_statistics() As "_cli_read_statistics"
;   cli_safe_read() As "_cli_safe_read"
;   cli_stmt_execute() As "_cli_stmt_execute"
;   cli_unbuffered_fetch() As "_cli_unbuffered_fetch"
;   client_errors() As "_client_errors"
;   close_cached_file() As "_close_cached_file"
;   combo1map() As "_combo1map"
;   combo2map() As "_combo2map"
;   compiled_charsets() As "_compiled_charsets"
;   compress() As "_compress"
;   compress2() As "_compress2"
;   compressBound() As "_compressBound"
;   convert_dirname() As "_convert_dirname"
  copy_typelib(*root.MEM_ROOT, *from.TYPELIB) As "_copy_typelib"
;   crc32() As "_crc32"
;   crc32_combine() As "_crc32_combine"
;   create_named_pipe() As "_create_named_pipe"
  create_random_string(to_.p-ascii, length.l, *rand_st.rand_struct) As "_create_random_string"
;   create_shared_memory() As "_create_shared_memory"
;   create_temp_file() As "_create_temp_file"
;   cs_to_uni() As "_cs_to_uni"
;   ctype_cp1250_bin() As "_ctype_cp1250_bin"
;   ctype_cp1250_croatian_ci() As "_ctype_cp1250_croatian_ci"
;   ctype_cp1250_general_ci() As "_ctype_cp1250_general_ci"
;   ctype_latin1_danish_ci() As "_ctype_latin1_danish_ci"
;   ctype_latin1_general_ci() As "_ctype_latin1_general_ci"
;   ctype_latin1_general_cs() As "_ctype_latin1_general_cs"
;   ctype_latin1_german1_ci() As "_ctype_latin1_german1_ci"
;   ctype_latin1_spanish_ci() As "_ctype_latin1_spanish_ci"
;   ctype_latin2_bin() As "_ctype_latin2_bin"
;   ctype_latin2_croatian_ci() As "_ctype_latin2_croatian_ci"
;   ctype_latin2_general_ci() As "_ctype_latin2_general_ci"
;   ctype_latin2_hungarian_ci() As "_ctype_latin2_hungarian_ci"
;   curr_dir() As "_curr_dir"
;   days_in_month() As "_days_in_month"
;   def_shared_memory_base_name() As "_def_shared_memory_base_name"
;   default_charset_info() As "_default_charset_info"
;   default_client_charset_info() As "_default_client_charset_info"
;   deflate() As "_deflate"
;   deflateBound() As "_deflateBound"
;   deflateCopy() As "_deflateCopy"
;   deflateEnd() As "_deflateEnd"
;   deflateInit2_() As "_deflateInit2_"
;   deflateInit_() As "_deflateInit_"
;   deflateParams() As "_deflateParams"
;   deflatePrime() As "_deflatePrime"
;   deflateReset() As "_deflateReset"
;   deflateSetDictionary() As "_deflateSetDictionary"
;   deflateSetHeader() As "_deflateSetHeader"
;   deflateTune() As "_deflateTune"
;   deflate_copyright() As "_deflate_copyright"
;   delete_dynamic() As "_delete_dynamic"
;   delete_dynamic_element() As "_delete_dynamic_element"
;   dirname_length() As "_dirname_length"
;   dirname_part() As "_dirname_part"
;   disabled_my_option() As "_disabled_my_option"
;   dynstr_append() As "_dynstr_append"
;   dynstr_append_mem() As "_dynstr_append_mem"
;   dynstr_append_os_quoted() As "_dynstr_append_os_quoted"
;   dynstr_free() As "_dynstr_free"
;   dynstr_realloc() As "_dynstr_realloc"
;   dynstr_set() As "_dynstr_set"
;   end_io_cache() As "_end_io_cache"
;   end_server() As "_end_server"
;   err_helper() As "_err_helper"
;   errbuff() As "_errbuff"
;   error_handler_hook() As "_error_handler_hook"
;   escape_quotes_for_mysql() As "_escape_quotes_for_mysql"
;   escape_string_for_mysql() As "_escape_string_for_mysql"
;   factorial() As "_factorial"
;   fatal_error_handler_hook() As "_fatal_error_handler_hook"
  find_type(x.p-ascii, *typelib.TYPELIB, full_name.l) As "_find_type"
  finish_client_errs() As "_finish_client_errs"
;   fn_ext() As "_fn_ext"
;   fn_format() As "_fn_format"
;   free_charsets() As "_free_charsets"
;   free_defaults() As "_free_defaults"
;   free_old_query() As "_free_old_query"
;   free_root() As "_free_root"
;   free_rows() As "_free_rows"
;   freeze_size() As "_freeze_size"
;   fs_character_set() As "_fs_character_set"
;   get_charset() As "_get_charset"
;   get_charset_by_csname() As "_get_charset_by_csname"
;   get_charset_by_name() As "_get_charset_by_name"
;   get_charset_name() As "_get_charset_name"
;   get_charset_number() As "_get_charset_number"
;   get_charsets_dir() As "_get_charsets_dir"
;   get_collation_number() As "_get_collation_number"
;   get_compatible_charset_with_ctype() As "_get_compatible_charset_with_ctype"
;   get_crc_table() As "_get_crc_table"
;   get_defaults_options() As "_get_defaults_options"
;   get_dynamic() As "_get_dynamic"
  get_salt_from_password(res.p-ascii, password.p-ascii) As "_get_salt_from_password"
  get_salt_from_password_323(res.l, password.p-ascii) As "_get_salt_from_password_323"
  get_tty_password(opt_message.l) As "_get_tty_password"
  get_type(*typelib.TYPELIB, nr.l) As "_get_type"
;   getopt_compare_strings() As "_getopt_compare_strings"
;   getopt_ull_limit_value() As "_getopt_ull_limit_value"
;   globerrs() As "_globerrs"
;   gmtime_r() As "_gmtime_r"
;   gzclearerr() As "_gzclearerr"
;   gzclose() As "_gzclose"
;   gzdirect() As "_gzdirect"
;   gzdopen() As "_gzdopen"
;   gzeof() As "_gzeof"
;   gzerror() As "_gzerror"
;   gzflush() As "_gzflush"
;   gzgetc() As "_gzgetc"
;   gzgets() As "_gzgets"
;   gzopen() As "_gzopen"
;   gzprintf() As "_gzprintf"
;   gzputc() As "_gzputc"
;   gzputs() As "_gzputs"
;   gzread() As "_gzread"
;   gzrewind() As "_gzrewind"
;   gzseek() As "_gzseek"
;   gzsetparams() As "_gzsetparams"
;   gztell() As "_gztell"
;   gzungetc() As "_gzungetc"
;   gzwrite() As "_gzwrite"
;   handle_local_infile() As "_handle_local_infile"
;   handle_options() As "_handle_options"
;   has_path() As "_has_path"
;   hash_delete() As "_hash_delete"
;   hash_element() As "_hash_element"
;   hash_first() As "_hash_first"
;   hash_free() As "_hash_free"
;   hash_next() As "_hash_next"
  hash_password(to_.p-ascii, password.p-ascii, password_len.l) As "_hash_password"
;   hash_replace() As "_hash_replace"
;   hash_search() As "_hash_search"
;   hash_update() As "_hash_update"
;   have_tcpip() As "_have_tcpip"
;   home_dir() As "_home_dir"
;   home_dir_buff() As "_home_dir_buff"
;   i_am_a_dummy_function() As "_i_am_a_dummy_function"
;   inflate() As "_inflate"
;   inflateBack() As "_inflateBack"
;   inflateBackEnd() As "_inflateBackEnd"
;   inflateBackInit_() As "_inflateBackInit_"
;   inflateCopy() As "_inflateCopy"
;   inflateEnd() As "_inflateEnd"
;   inflateGetHeader() As "_inflateGetHeader"
;   inflateInit2_() As "_inflateInit2_"
;   inflateInit_() As "_inflateInit_"
;   inflatePrime() As "_inflatePrime"
;   inflateReset() As "_inflateReset"
;   inflateSetDictionary() As "_inflateSetDictionary"
;   inflateSync() As "_inflateSync"
;   inflateSyncPoint() As "_inflateSyncPoint"
;   inflate_copyright() As "_inflate_copyright"
;   inflate_fast() As "_inflate_fast"
;   inflate_table() As "_inflate_table"
;   init_alloc_root() As "_init_alloc_root"
  init_client_errs() As "_init_client_errs"
;   init_compiled_charsets() As "_init_compiled_charsets"
;   init_dynamic_array() As "_init_dynamic_array"
;   init_dynamic_string() As "_init_dynamic_string"
;   init_glob_errs() As "_init_glob_errs"
;   init_io_cache() As "_init_io_cache"
;   init_io_cache_share() As "_init_io_cache_share"
;   insert_dynamic() As "_insert_dynamic"
;   int10_to_str() As "_int10_to_str"
;   int2str() As "_int2str"
;   intern_filename() As "_intern_filename"
;   is_prefix() As "_is_prefix"
;   key_cache_inited() As "_key_cache_inited"
;   list_add() As "_list_add"
  list_cons(data_.p-ascii, *root.LIST) As "_list_cons"
;   list_delete() As "_list_delete"
  list_free(*root.LIST, free_data.l) As "_list_free"
  list_length(*item.LIST) As "_list_length"
  list_reverse(*root.LIST) As "_list_reverse"
  list_walk(*item.LIST, action.l, argument.l) As "_list_walk"
;   llstr() As "_llstr"
;   load_defaults() As "_load_defaults"
;   localtime_r() As "_localtime_r"
;   log_10() As "_log_10"
;   log_10_int() As "_log_10_int"
;   longlong10_to_str() As "_longlong10_to_str"
;   longlong2str() As "_longlong2str"
  make_password_from_salt(to_.p-ascii, hash_stage2.l) As "_make_password_from_salt"
  make_password_from_salt_323(to_.p-ascii, salt.l) As "_make_password_from_salt_323"
  make_scrambled_password(to_.p-ascii, password.p-ascii) As "_make_scrambled_password"
  make_scrambled_password_323(to_.p-ascii, password.p-ascii) As "_make_scrambled_password_323"
  make_type(to_.p-ascii, nr.l, *typelib.TYPELIB) As "_make_type"
;   max_allowed_packet() As "_max_allowed_packet"
;   memdup_root() As "_memdup_root"
;   modify_defaults_file() As "_modify_defaults_file"
;   multi_alloc_root() As "_multi_alloc_root"
;   my_TIME_to_str() As "_my_TIME_to_str"
;   my_abort_hook() As "_my_abort_hook"
;   my_access() As "_my_access"
;   my_atof() As "_my_atof"
;   my_b_append() As "_my_b_append"
;   my_b_append_tell() As "_my_b_append_tell"
;   my_b_filelength() As "_my_b_filelength"
;   my_b_fill() As "_my_b_fill"
;   my_b_flush_io_cache() As "_my_b_flush_io_cache"
;   my_b_gets() As "_my_b_gets"
;   my_b_printf() As "_my_b_printf"
;   my_b_safe_tell() As "_my_b_safe_tell"
;   my_b_safe_write() As "_my_b_safe_write"
;   my_b_seek() As "_my_b_seek"
;   my_b_vprintf() As "_my_b_vprintf"
;   my_block_write() As "_my_block_write"
;   my_casedn_8bit() As "_my_casedn_8bit"
;   my_casedn_mb() As "_my_casedn_mb"
;   my_casedn_str_8bit() As "_my_casedn_str_8bit"
;   my_casedn_str_mb() As "_my_casedn_str_mb"
;   my_caseup_8bit() As "_my_caseup_8bit"
;   my_caseup_mb() As "_my_caseup_mb"
;   my_caseup_str_8bit() As "_my_caseup_str_8bit"
;   my_caseup_str_mb() As "_my_caseup_str_mb"
;   my_charpos_8bit() As "_my_charpos_8bit"
;   my_charpos_mb() As "_my_charpos_mb"
;   my_charset_8bit_handler() As "_my_charset_8bit_handler"
;   my_charset_big5_bin() As "_my_charset_big5_bin"
;   my_charset_big5_chinese_ci() As "_my_charset_big5_chinese_ci"
;   my_charset_bin() As "_my_charset_bin"
;   my_charset_cp1250_czech_ci() As "_my_charset_cp1250_czech_ci"
;   my_charset_cp932_bin() As "_my_charset_cp932_bin"
;   my_charset_cp932_japanese_ci() As "_my_charset_cp932_japanese_ci"
;   my_charset_eucjpms_bin() As "_my_charset_eucjpms_bin"
;   my_charset_eucjpms_japanese_ci() As "_my_charset_eucjpms_japanese_ci"
;   my_charset_euckr_bin() As "_my_charset_euckr_bin"
;   my_charset_euckr_korean_ci() As "_my_charset_euckr_korean_ci"
;   my_charset_gb2312_bin() As "_my_charset_gb2312_bin"
;   my_charset_gb2312_chinese_ci() As "_my_charset_gb2312_chinese_ci"
;   my_charset_gbk_bin() As "_my_charset_gbk_bin"
;   my_charset_gbk_chinese_ci() As "_my_charset_gbk_chinese_ci"
;   my_charset_is_8bit_pure_ascii() As "_my_charset_is_8bit_pure_ascii"
;   my_charset_is_ascii_based() As "_my_charset_is_ascii_based"
;   my_charset_latin1() As "_my_charset_latin1"
;   my_charset_latin1_bin() As "_my_charset_latin1_bin"
;   my_charset_latin1_german2_ci() As "_my_charset_latin1_german2_ci"
;   my_charset_latin2_czech_ci() As "_my_charset_latin2_czech_ci"
;   my_charset_same() As "_my_charset_same"
;   my_charset_sjis_bin() As "_my_charset_sjis_bin"
;   my_charset_sjis_japanese_ci() As "_my_charset_sjis_japanese_ci"
;   my_charset_tis620_bin() As "_my_charset_tis620_bin"
;   my_charset_tis620_thai_ci() As "_my_charset_tis620_thai_ci"
;   my_charset_ucs2_bin() As "_my_charset_ucs2_bin"
;   my_charset_ucs2_czech_uca_ci() As "_my_charset_ucs2_czech_uca_ci"
;   my_charset_ucs2_danish_uca_ci() As "_my_charset_ucs2_danish_uca_ci"
;   my_charset_ucs2_esperanto_uca_ci() As "_my_charset_ucs2_esperanto_uca_ci"
;   my_charset_ucs2_estonian_uca_ci() As "_my_charset_ucs2_estonian_uca_ci"
;   my_charset_ucs2_general_ci() As "_my_charset_ucs2_general_ci"
;   my_charset_ucs2_handler() As "_my_charset_ucs2_handler"
;   my_charset_ucs2_hungarian_uca_ci() As "_my_charset_ucs2_hungarian_uca_ci"
;   my_charset_ucs2_icelandic_uca_ci() As "_my_charset_ucs2_icelandic_uca_ci"
;   my_charset_ucs2_latvian_uca_ci() As "_my_charset_ucs2_latvian_uca_ci"
;   my_charset_ucs2_lithuanian_uca_ci() As "_my_charset_ucs2_lithuanian_uca_ci"
;   my_charset_ucs2_persian_uca_ci() As "_my_charset_ucs2_persian_uca_ci"
;   my_charset_ucs2_polish_uca_ci() As "_my_charset_ucs2_polish_uca_ci"
;   my_charset_ucs2_roman_uca_ci() As "_my_charset_ucs2_roman_uca_ci"
;   my_charset_ucs2_romanian_uca_ci() As "_my_charset_ucs2_romanian_uca_ci"
;   my_charset_ucs2_slovak_uca_ci() As "_my_charset_ucs2_slovak_uca_ci"
;   my_charset_ucs2_slovenian_uca_ci() As "_my_charset_ucs2_slovenian_uca_ci"
;   my_charset_ucs2_spanish2_uca_ci() As "_my_charset_ucs2_spanish2_uca_ci"
;   my_charset_ucs2_spanish_uca_ci() As "_my_charset_ucs2_spanish_uca_ci"
;   my_charset_ucs2_swedish_uca_ci() As "_my_charset_ucs2_swedish_uca_ci"
;   my_charset_ucs2_turkish_uca_ci() As "_my_charset_ucs2_turkish_uca_ci"
;   my_charset_ucs2_unicode_ci() As "_my_charset_ucs2_unicode_ci"
;   my_charset_ujis_bin() As "_my_charset_ujis_bin"
;   my_charset_ujis_japanese_ci() As "_my_charset_ujis_japanese_ci"
;   my_charset_utf8_bin() As "_my_charset_utf8_bin"
;   my_charset_utf8_czech_uca_ci() As "_my_charset_utf8_czech_uca_ci"
;   my_charset_utf8_danish_uca_ci() As "_my_charset_utf8_danish_uca_ci"
;   my_charset_utf8_esperanto_uca_ci() As "_my_charset_utf8_esperanto_uca_ci"
;   my_charset_utf8_estonian_uca_ci() As "_my_charset_utf8_estonian_uca_ci"
;   my_charset_utf8_general_ci() As "_my_charset_utf8_general_ci"
;   my_charset_utf8_handler() As "_my_charset_utf8_handler"
;   my_charset_utf8_hungarian_uca_ci() As "_my_charset_utf8_hungarian_uca_ci"
;   my_charset_utf8_icelandic_uca_ci() As "_my_charset_utf8_icelandic_uca_ci"
;   my_charset_utf8_latvian_uca_ci() As "_my_charset_utf8_latvian_uca_ci"
;   my_charset_utf8_lithuanian_uca_ci() As "_my_charset_utf8_lithuanian_uca_ci"
;   my_charset_utf8_persian_uca_ci() As "_my_charset_utf8_persian_uca_ci"
;   my_charset_utf8_polish_uca_ci() As "_my_charset_utf8_polish_uca_ci"
;   my_charset_utf8_roman_uca_ci() As "_my_charset_utf8_roman_uca_ci"
;   my_charset_utf8_romanian_uca_ci() As "_my_charset_utf8_romanian_uca_ci"
;   my_charset_utf8_slovak_uca_ci() As "_my_charset_utf8_slovak_uca_ci"
;   my_charset_utf8_slovenian_uca_ci() As "_my_charset_utf8_slovenian_uca_ci"
;   my_charset_utf8_spanish2_uca_ci() As "_my_charset_utf8_spanish2_uca_ci"
;   my_charset_utf8_spanish_uca_ci() As "_my_charset_utf8_spanish_uca_ci"
;   my_charset_utf8_swedish_uca_ci() As "_my_charset_utf8_swedish_uca_ci"
;   my_charset_utf8_turkish_uca_ci() As "_my_charset_utf8_turkish_uca_ci"
;   my_charset_utf8_unicode_ci() As "_my_charset_utf8_unicode_ci"
;   my_chsize() As "_my_chsize"
;   my_close() As "_my_close"
;   my_collation_8bit_bin_handler() As "_my_collation_8bit_bin_handler"
;   my_collation_8bit_simple_ci_handler() As "_my_collation_8bit_simple_ci_handler"
;   my_collation_any_uca_handler() As "_my_collation_any_uca_handler"
;   my_collation_mb_bin_handler() As "_my_collation_mb_bin_handler"
;   my_collation_ucs2_uca_handler() As "_my_collation_ucs2_uca_handler"
;   my_compress() As "_my_compress"
;   my_compress_alloc() As "_my_compress_alloc"
  my_connect(s.l, *name.sockaddr, namelen.l, timeout.l) As "_my_connect"
;   my_create() As "_my_create"
;   my_create_with_symlink() As "_my_create_with_symlink"
;   my_date_to_str() As "_my_date_to_str"
;   my_datetime_to_str() As "_my_datetime_to_str"
;   my_default_record_cache_size() As "_my_default_record_cache_size"
;   my_defaults_extra_file() As "_my_defaults_extra_file"
;   my_defaults_file() As "_my_defaults_file"
;   my_defaults_group_suffix() As "_my_defaults_group_suffix"
;   my_delete() As "_my_delete"
;   my_delete_with_symlink() As "_my_delete_with_symlink"
;   my_dir() As "_my_dir"
;   my_dirend() As "_my_dirend"
;   my_disable_async_io() As "_my_disable_async_io"
;   my_disable_flush_key_blocks() As "_my_disable_flush_key_blocks"
;   my_disable_locking() As "_my_disable_locking"
;   my_disable_symlinks() As "_my_disable_symlinks"
;   my_dont_interrupt() As "_my_dont_interrupt"
;   my_end() As "_my_end"
;   my_error() As "_my_error"
;   my_error_register() As "_my_error_register"
;   my_error_unregister() As "_my_error_unregister"
;   my_fclose() As "_my_fclose"
;   my_fdopen() As "_my_fdopen"
;   my_file_info() As "_my_file_info"
;   my_file_info_default() As "_my_file_info_default"
;   my_file_limit() As "_my_file_limit"
;   my_file_opened() As "_my_file_opened"
;   my_filename() As "_my_filename"
;   my_fill_8bit() As "_my_fill_8bit"
;   my_fopen() As "_my_fopen"
;   my_fread() As "_my_fread"
;   my_free_open_file_info() As "_my_free_open_file_info"
;   my_fseek() As "_my_fseek"
;   my_fstat() As "_my_fstat"
;   my_ftell() As "_my_ftell"
;   my_fwrite() As "_my_fwrite"
;   my_gethostbyname_r() As "_my_gethostbyname_r"
;   my_gethostbyname_r_free() As "_my_gethostbyname_r_free"
;   my_getopt_error_reporter() As "_my_getopt_error_reporter"
;   my_getopt_print_errors() As "_my_getopt_print_errors"
;   my_getopt_register_get_addr() As "_my_getopt_register_get_addr"
;   my_getwd() As "_my_getwd"
;   my_hash_insert() As "_my_hash_insert"
;   my_hash_reset() As "_my_hash_reset"
;   my_hash_sort_8bit_bin() As "_my_hash_sort_8bit_bin"
;   my_hash_sort_bin() As "_my_hash_sort_bin"
;   my_hash_sort_latin1_de() As "_my_hash_sort_latin1_de"
;   my_hash_sort_simple() As "_my_hash_sort_simple"
;   my_have_got_alarm() As "_my_have_got_alarm"
;   my_inet_ntoa() As "_my_inet_ntoa"
  my_init() As "_my_init"
;   my_init_done() As "_my_init_done"
;   my_init_time() As "_my_init_time"
;   my_instr_mb() As "_my_instr_mb"
;   my_instr_simple() As "_my_instr_simple"
;   my_is_symlink() As "_my_is_symlink"
;   my_l10tostr_ucs2() As "_my_l10tostr_ucs2"
;   my_lengthsp_8bit() As "_my_lengthsp_8bit"
;   my_lengthsp_binary() As "_my_lengthsp_binary"
;   my_like_range_mb() As "_my_like_range_mb"
;   my_like_range_simple() As "_my_like_range_simple"
;   my_like_range_ucs2() As "_my_like_range_ucs2"
;   my_ll10tostr_ucs2() As "_my_ll10tostr_ucs2"
;   my_load_path() As "_my_load_path"
;   my_long10_to_str_8bit() As "_my_long10_to_str_8bit"
;   my_longlong10_to_str_8bit() As "_my_longlong10_to_str_8bit"
;   my_malloc() As "_my_malloc"
;   my_mb_wc_8bit() As "_my_mb_wc_8bit"
;   my_mbcharlen_8bit() As "_my_mbcharlen_8bit"
;   my_memdup() As "_my_memdup"
;   my_message() As "_my_message"
;   my_message_no_curses() As "_my_message_no_curses"
;   my_multi_malloc() As "_my_multi_malloc"
  my_net_init(*net.NET, *vio) As "_my_net_init"
  my_net_local_init(*net.NET) As "_my_net_local_init"
  my_net_read(*net.NET) As "_my_net_read"
  my_net_set_read_timeout(*net.NET, timeout.l) As "_my_net_set_read_timeout"
  my_net_set_write_timeout(*net.NET, timeout.l) As "_my_net_set_write_timeout"
  my_net_write(*net.NET, packet.p-ascii, len.l) As "_my_net_write"
;   my_no_flags_free() As "_my_no_flags_free"
;   my_numcells_8bit() As "_my_numcells_8bit"
;   my_numcells_mb() As "_my_numcells_mb"
;   my_numchars_8bit() As "_my_numchars_8bit"
;   my_numchars_mb() As "_my_numchars_mb"
;   my_once_alloc() As "_my_once_alloc"
;   my_once_extra() As "_my_once_extra"
;   my_once_free() As "_my_once_free"
;   my_once_memdup() As "_my_once_memdup"
;   my_once_root_block() As "_my_once_root_block"
;   my_once_strdup() As "_my_once_strdup"
;   my_open() As "_my_open"
;   my_parameter_handler() As "_my_parameter_handler"
;   my_parse_charset_xml() As "_my_parse_charset_xml"
;   my_path() As "_my_path"
;   my_pipe_sig_handler() As "_my_pipe_sig_handler"
;   my_pread() As "_my_pread"
;   my_print_default_files() As "_my_print_default_files"
;   my_print_help() As "_my_print_help"
;   my_print_variables() As "_my_print_variables"
;   my_printf_error() As "_my_printf_error"
;   my_progname() As "_my_progname"
;   my_propagate_complex() As "_my_propagate_complex"
;   my_propagate_simple() As "_my_propagate_simple"
;   my_pthread_create_detached() As "_my_pthread_create_detached"
;   my_pwrite() As "_my_pwrite"
;   my_qsort() As "_my_qsort"
;   my_read() As "_my_read"
;   my_readlink() As "_my_readlink"
;   my_realloc() As "_my_realloc"
;   my_realpath() As "_my_realpath"
;   my_register_filename() As "_my_register_filename"
;   my_rename() As "_my_rename"
;   my_rename_with_symlink() As "_my_rename_with_symlink"
  my_rnd.d(*rand.rand_struct) As "_my_rnd"
;   my_scan_8bit() As "_my_scan_8bit"
;   my_scan_ucs2() As "_my_scan_ucs2"
;   my_search_option_files() As "_my_search_option_files"
;   my_seek() As "_my_seek"
;   my_set_max_open_files() As "_my_set_max_open_files"
;   my_setwd() As "_my_setwd"
;   my_signals() As "_my_signals"
;   my_sleep() As "_my_sleep"
;   my_snprintf() As "_my_snprintf"
;   my_snprintf_8bit() As "_my_snprintf_8bit"
;   my_sopen() As "_my_sopen"
;   my_stat() As "_my_stat"
;   my_str_free() As "_my_str_free"
;   my_str_malloc() As "_my_str_malloc"
;   my_strcasecmp_8bit() As "_my_strcasecmp_8bit"
;   my_strcasecmp_mb() As "_my_strcasecmp_mb"
;   my_strdup() As "_my_strdup"
;   my_strdup_with_length() As "_my_strdup_with_length"
;   my_stream_opened() As "_my_stream_opened"
;   my_string_repertoire() As "_my_string_repertoire"
;   my_strnncoll_gbk() As "_my_strnncoll_gbk"
;   my_strnncoll_gbk_internal() As "_my_strnncoll_gbk_internal"
;   my_strnncoll_simple() As "_my_strnncoll_simple"
;   my_strnncollsp_simple() As "_my_strnncollsp_simple"
;   my_strntod_8bit() As "_my_strntod_8bit"
;   my_strntod_ucs2() As "_my_strntod_ucs2"
;   my_strntol_8bit() As "_my_strntol_8bit"
;   my_strntol_ucs2() As "_my_strntol_ucs2"
;   my_strntoll_8bit() As "_my_strntoll_8bit"
;   my_strntoll_ucs2() As "_my_strntoll_ucs2"
;   my_strntoul_8bit() As "_my_strntoul_8bit"
;   my_strntoul_ucs2() As "_my_strntoul_ucs2"
;   my_strntoull10rnd_8bit() As "_my_strntoull10rnd_8bit"
;   my_strntoull10rnd_ucs2() As "_my_strntoull10rnd_ucs2"
;   my_strntoull_8bit() As "_my_strntoull_8bit"
;   my_strntoull_ucs2() As "_my_strntoull_ucs2"
;   my_strnxfrm_simple() As "_my_strnxfrm_simple"
;   my_strnxfrmlen_simple() As "_my_strnxfrmlen_simple"
;   my_strtod() As "_my_strtod"
;   my_strtoll10() As "_my_strtoll10"
;   my_strtoll10_8bit() As "_my_strtoll10_8bit"
;   my_strtoll10_ucs2() As "_my_strtoll10_ucs2"
;   my_symlink() As "_my_symlink"
;   my_system_gmt_sec() As "_my_system_gmt_sec"
;   my_tell() As "_my_tell"
  my_thread_end() As "_my_thread_end"
;   my_thread_end_wait_time() As "_my_thread_end_wait_time"
;   my_thread_global_end() As "_my_thread_global_end"
;   my_thread_global_init() As "_my_thread_global_init"
;   my_thread_id() As "_my_thread_id"
  my_thread_init() As "_my_thread_init"
;   my_thread_name() As "_my_thread_name"
;   my_time_to_str() As "_my_time_to_str"
;   my_time_to_wait_for_lock() As "_my_time_to_wait_for_lock"
;   my_tmp_file_created() As "_my_tmp_file_created"
;   my_umask() As "_my_umask"
;   my_umask_dir() As "_my_umask_dir"
;   my_uncompress() As "_my_uncompress"
;   my_unicase_default() As "_my_unicase_default"
;   my_unicase_turkish() As "_my_unicase_turkish"
;   my_use_symdir() As "_my_use_symdir"
;   my_vsnprintf() As "_my_vsnprintf"
;   my_wc_mb_8bit() As "_my_wc_mb_8bit"
;   my_well_formed_len_8bit() As "_my_well_formed_len_8bit"
;   my_well_formed_len_mb() As "_my_well_formed_len_mb"
;   my_wildcmp_8bit() As "_my_wildcmp_8bit"
;   my_wildcmp_bin() As "_my_wildcmp_bin"
;   my_wildcmp_mb() As "_my_wildcmp_mb"
;   my_wildcmp_unicode() As "_my_wildcmp_unicode"
;   my_write() As "_my_write"
;   my_xml_error_lineno() As "_my_xml_error_lineno"
;   my_xml_error_pos() As "_my_xml_error_pos"
;   my_xml_error_string() As "_my_xml_error_string"
;   my_xml_parse() As "_my_xml_parse"
;   my_xml_parser_create() As "_my_xml_parser_create"
;   my_xml_parser_free() As "_my_xml_parser_free"
;   my_xml_set_enter_handler() As "_my_xml_set_enter_handler"
;   my_xml_set_leave_handler() As "_my_xml_set_leave_handler"
;   my_xml_set_user_data() As "_my_xml_set_user_data"
;   my_xml_set_value_handler() As "_my_xml_set_value_handler"
;   myodbc_remove_escape(a.l,b.l) As "_myodbc_remove_escape@8"
  mysql_add_slave(*mysql.MYSQL, host.p-ascii, port.l, user.p-ascii, passwd.p-ascii) As "_mysql_add_slave@20"
;   mysql_affected_rows(a.l) As "_mysql_affected_rows@4"
;   mysql_autocommit(a.l,b.l) As "_mysql_autocommit@8"
;   mysql_change_user(a.l,b.l,c.l,d.l) As "_mysql_change_user@16"
;   mysql_character_set_name(a.l) As "_mysql_character_set_name@4"
;   mysql_close(a.l) As "_mysql_close@4"
;   mysql_commit(a.l) As "_mysql_commit@4"
;   mysql_data_seek(a.l,b.l,c.l) As "_mysql_data_seek@12"
;   mysql_debug(a.l) As "_mysql_debug@4"
;   mysql_detach_stmt_list() As "_mysql_detach_stmt_list"
;   mysql_disable_reads_from_master(a.l) As "_mysql_disable_reads_from_master@4"
;   mysql_disable_rpl_parse(a.l) As "_mysql_disable_rpl_parse@4"
;   mysql_dump_debug_info(a.l) As "_mysql_dump_debug_info@4"
;   mysql_embedded() As "_mysql_embedded@0"
;   mysql_enable_reads_from_master(a.l) As "_mysql_enable_reads_from_master@4"
;   mysql_enable_rpl_parse(a.l) As "_mysql_enable_rpl_parse@4"
;   mysql_eof(a.l) As "_mysql_eof@4"
;   mysql_errno(a.l) As "_mysql_errno@4"
;   mysql_error(a.l) As "_mysql_error@4"
;   mysql_escape_string(a.l,b.l,c.l) As "_mysql_escape_string@12"
;   mysql_fetch_field(a.l) As "_mysql_fetch_field@4"
;   mysql_fetch_field_direct(a.l,b.l) As "_mysql_fetch_field_direct@8"
;   mysql_fetch_fields(a.l) As "_mysql_fetch_fields@4"
;   mysql_fetch_lengths(a.l) As "_mysql_fetch_lengths@4"
;   mysql_fetch_row(a.l) As "_mysql_fetch_row@4"
;   mysql_field_count(a.l) As "_mysql_field_count@4"
;   mysql_field_seek(a.l,b.l) As "_mysql_field_seek@8"
;   mysql_field_tell(a.l) As "_mysql_field_tell@4"
;   mysql_free_result(a.l) As "_mysql_free_result@4"
;   mysql_get_character_set_info(a.l,b.l) As "_mysql_get_character_set_info@8"
;   mysql_get_client_info() As "_mysql_get_client_info@0"
;   mysql_get_client_version() As "_mysql_get_client_version@0"
;   mysql_get_host_info(a.l) As "_mysql_get_host_info@4"
;   mysql_get_parameters() As "_mysql_get_parameters@0"
;   mysql_get_proto_info(a.l) As "_mysql_get_proto_info@4"
;   mysql_get_server_info(a.l) As "_mysql_get_server_info@4"
;   mysql_get_server_version(a.l) As "_mysql_get_server_version@4"
;   mysql_get_ssl_cipher(a.l) As "_mysql_get_ssl_cipher@4"
;   mysql_hex_string(a.l,b.l,c.l) As "_mysql_hex_string@12"
;   mysql_info(a.l) As "_mysql_info@4"
;   mysql_init(a.l) As "_mysql_init@4"
;   mysql_init_character_set() As "_mysql_init_character_set"
;   mysql_insert_id(a.l) As "_mysql_insert_id@4"
;   mysql_kill(a.l,b.l) As "_mysql_kill@8"
;   mysql_list_dbs(a.l,b.l) As "_mysql_list_dbs@8"
;   mysql_list_fields(a.l,b.l,c.l) As "_mysql_list_fields@12"
;   mysql_list_processes(a.l) As "_mysql_list_processes@4"
;   mysql_list_tables(a.l,b.l) As "_mysql_list_tables@8"
  mysql_manager_close(*con.MYSQL_MANAGER) As "_mysql_manager_close@4"
  mysql_manager_command(*con.MYSQL_MANAGER, cmd.p-ascii, cmd_len.l) As "_mysql_manager_command@12"
  mysql_manager_connect(*con.MYSQL_MANAGER, host.p-ascii, user.p-ascii, passwd.p-ascii, port.l) As "_mysql_manager_connect@20"
  mysql_manager_fetch_line(*con.MYSQL_MANAGER, res_buf.p-ascii, res_buf_size.l) As "_mysql_manager_fetch_line@12"
  mysql_manager_init(*con.MYSQL_MANAGER) As "_mysql_manager_init@4"
;   mysql_master_query(a.l,b.l,c.l) As "_mysql_master_query@12"
  mysql_master_send_query(*mysql.MYSQL, q.p-ascii, length.l) As "_mysql_master_send_query@12"
;   mysql_more_results(a.l) As "_mysql_more_results@4"
;   mysql_next_result(a.l) As "_mysql_next_result@4"
;   mysql_num_fields(a.l) As "_mysql_num_fields@4"
;   mysql_num_rows(a.l) As "_mysql_num_rows@4"
;   mysql_options(a.l,b.l,c.l) As "_mysql_options@12"
;   mysql_ping(a.l) As "_mysql_ping@4"
;   mysql_port() As "_mysql_port"
;   mysql_query(a.l,b.l) As "_mysql_query@8"
;   mysql_read_default_options() As "_mysql_read_default_options"
;   mysql_read_query_result(a.l) As "_mysql_read_query_result@4"
  mysql_reads_from_master_enabled(*mysql.MYSQL) As "_mysql_reads_from_master_enabled@4"
;   mysql_real_connect(a.l,b.l,c.l,d.l,e.l,f.l,g.l,h.l) As "_mysql_real_connect@32"
;   mysql_real_escape_string(a.l,b.l,c.l,d.l) As "_mysql_real_escape_string@16"
;   mysql_real_query(a.l,b.l,c.l) As "_mysql_real_query@12"
;   mysql_reconnect() As "_mysql_reconnect"
;   mysql_refresh(a.l,b.l) As "_mysql_refresh@8"
;   mysql_rollback(a.l) As "_mysql_rollback@4"
;   mysql_row_seek(a.l,b.l) As "_mysql_row_seek@8"
;   mysql_row_tell(a.l) As "_mysql_row_tell@4"
;   mysql_rpl_parse_enabled(a.l) As "_mysql_rpl_parse_enabled@4"
;   mysql_rpl_probe(a.l) As "_mysql_rpl_probe@4"
;   mysql_rpl_query_type(a.l,b.l) As "_mysql_rpl_query_type@8"
;   mysql_select_db(a.l,b.l) As "_mysql_select_db@8"
;   mysql_send_query(a.l,b.l,c.l) As "_mysql_send_query@12"
;   mysql_server_end() As "_mysql_server_end@0"
;   mysql_server_init(a.l,b.l,c.l) As "_mysql_server_init@12"
;   mysql_server_last_errno() As "_mysql_server_last_errno"
;   mysql_server_last_error() As "_mysql_server_last_error"
;   mysql_set_character_set(a.l,b.l) As "_mysql_set_character_set@8"
;   mysql_set_local_infile_default() As "_mysql_set_local_infile_default"
;   mysql_set_local_infile_handler() As "_mysql_set_local_infile_handler"
  mysql_set_master(*mysql.MYSQL, host.p-ascii, port.l, user.p-ascii, passwd.p-ascii) As "_mysql_set_master@20"
;   mysql_set_server_option(a.l,b.l) As "_mysql_set_server_option@8"
;   mysql_sha1_input() As "_mysql_sha1_input"
;   mysql_sha1_reset() As "_mysql_sha1_reset"
;   mysql_sha1_result() As "_mysql_sha1_result"
;   mysql_shutdown(a.l,b.l) As "_mysql_shutdown@8"
;   mysql_slave_query(a.l,b.l,c.l) As "_mysql_slave_query@12"
  mysql_slave_send_query(*mysql.MYSQL, q.p-ascii, length.l) As "_mysql_slave_send_query@12"
;   mysql_sqlstate(a.l) As "_mysql_sqlstate@4"
;   mysql_ssl_set(a.l,b.l,c.l,d.l,e.l,f.l) As "_mysql_ssl_set@24"
;   mysql_stat(a.l) As "_mysql_stat@4"
;   mysql_stmt_affected_rows(a.l) As "_mysql_stmt_affected_rows@4"
;   mysql_stmt_attr_get(a.l,b.l,c.l) As "_mysql_stmt_attr_get@12"
;   mysql_stmt_attr_set(a.l,b.l,c.l) As "_mysql_stmt_attr_set@12"
;   mysql_stmt_bind_param(a.l,b.l) As "_mysql_stmt_bind_param@8"
;   mysql_stmt_bind_result(a.l,b.l) As "_mysql_stmt_bind_result@8"
;   mysql_stmt_close(a.l) As "_mysql_stmt_close@4"
;   mysql_stmt_data_seek(a.l,b.l,c.l) As "_mysql_stmt_data_seek@12"
;   mysql_stmt_errno(a.l) As "_mysql_stmt_errno@4"
;   mysql_stmt_error(a.l) As "_mysql_stmt_error@4"
;   mysql_stmt_execute(a.l) As "_mysql_stmt_execute@4"
;   mysql_stmt_fetch(a.l) As "_mysql_stmt_fetch@4"
;   mysql_stmt_fetch_column(a.l,b.l,c.l,d.l) As "_mysql_stmt_fetch_column@16"
;   mysql_stmt_field_count(a.l) As "_mysql_stmt_field_count@4"
;   mysql_stmt_free_result(a.l) As "_mysql_stmt_free_result@4"
;   mysql_stmt_init(a.l) As "_mysql_stmt_init@4"
;   mysql_stmt_insert_id(a.l) As "_mysql_stmt_insert_id@4"
;   mysql_stmt_num_rows(a.l) As "_mysql_stmt_num_rows@4"
;   mysql_stmt_param_count(a.l) As "_mysql_stmt_param_count@4"
;   mysql_stmt_param_metadata(a.l) As "_mysql_stmt_param_metadata@4"
;   mysql_stmt_prepare(a.l,b.l,c.l) As "_mysql_stmt_prepare@12"
;   mysql_stmt_reset(a.l) As "_mysql_stmt_reset@4"
;   mysql_stmt_result_metadata(a.l) As "_mysql_stmt_result_metadata@4"
;   mysql_stmt_row_seek(a.l,b.l) As "_mysql_stmt_row_seek@8"
;   mysql_stmt_row_tell(a.l) As "_mysql_stmt_row_tell@4"
;   mysql_stmt_send_long_data(a.l,b.l,c.l,d.l) As "_mysql_stmt_send_long_data@16"
;   mysql_stmt_sqlstate(a.l) As "_mysql_stmt_sqlstate@4"
;   mysql_stmt_store_result(a.l) As "_mysql_stmt_store_result@4"
;   mysql_store_result(a.l) As "_mysql_store_result@4"
;   mysql_thread_end() As "_mysql_thread_end@0"
;   mysql_thread_id(a.l) As "_mysql_thread_id@4"
;   mysql_thread_init() As "_mysql_thread_init@0"
;   mysql_thread_safe() As "_mysql_thread_safe@0"
;   mysql_unix_port() As "_mysql_unix_port"
;   mysql_use_result(a.l) As "_mysql_use_result@4"
;   mysql_warning_count(a.l) As "_mysql_warning_count@4"
;   mysys_usage_id() As "_mysys_usage_id"
;   mysys_uses_curses() As "_mysys_uses_curses"
;   net_buffer_length() As "_net_buffer_length"
  net_clear(*net.NET) As "_net_clear"
  net_end(*net.NET) As "_net_end"
  net_field_length(*packet) As "_net_field_length@4"
  net_field_length_ll(*packet) As "_net_field_length_ll"
  net_flush(*net.NET) As "_net_flush"
  net_real_write(*net.NET, packet.p-ascii, len.l) As "_net_real_write"
  net_realloc(*net.NET, length.l) As "_net_realloc"
  net_store_length(*pkg, length.l) As "_net_store_length"
  net_write_command(*net.NET, command.p-ascii, header.p-ascii, head_len.l, packet.p-ascii, len.l) As "_net_write_command"
;   new_VioSSLAcceptorFd() As "_new_VioSSLAcceptorFd"
;   new_VioSSLConnectorFd() As "_new_VioSSLConnectorFd"
;   normalize_dirname() As "_normalize_dirname"
;   not_error_sqlstate() As "_not_error_sqlstate"
;   nt_share_delete() As "_nt_share_delete"
;   number_to_datetime() As "_number_to_datetime"
  octet2hex(to_.p-ascii, str.p-ascii, len.l) As "_octet2hex"
;   open_cached_file() As "_open_cached_file"
;   pack_dirname() As "_pack_dirname"
;   page000data() As "_page000data"
;   page001data() As "_page001data"
;   page002data() As "_page002data"
;   page003data() As "_page003data"
;   page004data() As "_page004data"
;   page005data() As "_page005data"
;   page006data() As "_page006data"
;   page007data() As "_page007data"
;   page009data() As "_page009data"
;   page00Adata() As "_page00Adata"
;   page00Bdata() As "_page00Bdata"
;   page00Cdata() As "_page00Cdata"
;   page00Ddata() As "_page00Ddata"
;   page00Edata() As "_page00Edata"
;   page00Fdata() As "_page00Fdata"
;   page010data() As "_page010data"
;   page011data() As "_page011data"
;   page012data() As "_page012data"
;   page013data() As "_page013data"
;   page014data() As "_page014data"
;   page015data() As "_page015data"
;   page016data() As "_page016data"
;   page017data() As "_page017data"
;   page018data() As "_page018data"
;   page019data() As "_page019data"
;   page01Ddata() As "_page01Ddata"
;   page01Edata() As "_page01Edata"
;   page01Fdata() As "_page01Fdata"
;   page020data() As "_page020data"
;   page021data() As "_page021data"
;   page022data() As "_page022data"
;   page023data() As "_page023data"
;   page024data() As "_page024data"
;   page025data() As "_page025data"
;   page026data() As "_page026data"
;   page027data() As "_page027data"
;   page028data() As "_page028data"
;   page029data() As "_page029data"
;   page02Adata() As "_page02Adata"
;   page02Bdata() As "_page02Bdata"
;   page02Edata() As "_page02Edata"
;   page02Fdata() As "_page02Fdata"
;   page030data() As "_page030data"
;   page031data() As "_page031data"
;   page032data() As "_page032data"
;   page033data() As "_page033data"
;   page04Ddata() As "_page04Ddata"
;   page0A0data() As "_page0A0data"
;   page0A1data() As "_page0A1data"
;   page0A2data() As "_page0A2data"
;   page0A3data() As "_page0A3data"
;   page0A4data() As "_page0A4data"
;   page0F9data() As "_page0F9data"
;   page0FAdata() As "_page0FAdata"
;   page0FBdata() As "_page0FBdata"
;   page0FCdata() As "_page0FCdata"
;   page0FDdata() As "_page0FDdata"
;   page0FEdata() As "_page0FEdata"
;   page0FFdata() As "_page0FFdata"
;   pl00() As "_pl00"
;   pl01() As "_pl01"
;   pl02() As "_pl02"
;   pl20() As "_pl20"
;   pl21() As "_pl21"
;   pop_dynamic() As "_pop_dynamic"
;   print_defaults() As "_print_defaults"
;   pthread_attr_destroy() As "_pthread_attr_destroy"
;   pthread_attr_init() As "_pthread_attr_init"
;   pthread_attr_setprio() As "_pthread_attr_setprio"
;   pthread_attr_setstacksize() As "_pthread_attr_setstacksize"
;   pthread_cond_broadcast() As "_pthread_cond_broadcast"
;   pthread_cond_destroy() As "_pthread_cond_destroy"
;   pthread_cond_init() As "_pthread_cond_init"
;   pthread_cond_signal() As "_pthread_cond_signal"
;   pthread_cond_timedwait() As "_pthread_cond_timedwait"
;   pthread_cond_wait() As "_pthread_cond_wait"
;   pthread_create() As "_pthread_create"
;   pthread_dummy() As "_pthread_dummy"
;   pthread_exit() As "_pthread_exit"
;   pthread_no_free() As "_pthread_no_free"
;   pthread_start() As "_pthread_start"
;   raid_type_string() As "_raid_type_string"
  randominit(*rand.rand_struct, seed1.l, seed2.l) As "_randominit"
;   read_user_name() As "_read_user_name"
;   real_open_cached_file() As "_real_open_cached_file"
;   reinit_io_cache() As "_reinit_io_cache"
;   remove_io_thread() As "_remove_io_thread"
;   reset_root_defaults() As "_reset_root_defaults"
  scramble(to_.p-ascii, message.p-ascii, password.p-ascii) As "_scramble"
  scramble_323(to_.p-ascii, message.p-ascii, password.p-ascii) As "_scramble_323"
;   setEnvString() As "_setEnvString"
;   set_dynamic() As "_set_dynamic"
;   set_mysql_error() As "_set_mysql_error"
;   set_prealloc_root() As "_set_prealloc_root"
;   set_stmt_errmsg() As "_set_stmt_errmsg"
;   set_zero_time() As "_set_zero_time"
;   setup_io_cache() As "_setup_io_cache"
;   sf_malloc_count() As "_sf_malloc_count"
;   sf_malloc_cur_memory() As "_sf_malloc_cur_memory"
;   sf_malloc_endhunc() As "_sf_malloc_endhunc"
;   sf_malloc_max_memory() As "_sf_malloc_max_memory"
;   sf_malloc_mem_limit() As "_sf_malloc_mem_limit"
;   sf_malloc_prehunc() As "_sf_malloc_prehunc"
;   sf_malloc_quick() As "_sf_malloc_quick"
;   sf_malloc_root() As "_sf_malloc_root"
;   sf_max_adress() As "_sf_max_adress"
;   sf_min_adress() As "_sf_min_adress"
;   sha_const_key() As "_sha_const_key"
;   shared_memory_base_name() As "_shared_memory_base_name"
;   sort_order_cp1250_croatian_ci() As "_sort_order_cp1250_croatian_ci"
;   sort_order_cp1250_general_ci() As "_sort_order_cp1250_general_ci"
;   sort_order_latin1_danish_ci() As "_sort_order_latin1_danish_ci"
;   sort_order_latin1_general_ci() As "_sort_order_latin1_general_ci"
;   sort_order_latin1_general_cs() As "_sort_order_latin1_general_cs"
;   sort_order_latin1_german1_ci() As "_sort_order_latin1_german1_ci"
;   sort_order_latin1_spanish_ci() As "_sort_order_latin1_spanish_ci"
;   sort_order_latin2_croatian_ci() As "_sort_order_latin2_croatian_ci"
;   sort_order_latin2_general_ci() As "_sort_order_latin2_general_ci"
;   sort_order_latin2_hungarian_ci() As "_sort_order_latin2_hungarian_ci"
;   soundex_map() As "_soundex_map"
;   sql_protocol_names_lib() As "_sql_protocol_names_lib"
;   sql_protocol_typelib() As "_sql_protocol_typelib"
;   sslaccept() As "_sslaccept"
;   sslconnect() As "_sslconnect"
;   str2int() As "_str2int"
;   str_to_datetime() As "_str_to_datetime"
;   str_to_time() As "_str_to_time"
;   strcend() As "_strcend"
;   strcont() As "_strcont"
;   strdup_root() As "_strdup_root"
;   strend() As "_strend"
;   strfill() As "_strfill"
;   strinstr() As "_strinstr"
;   strlength() As "_strlength"
;   strmake() As "_strmake"
;   strmake_root() As "_strmake_root"
;   strmov() As "_strmov"
;   strnmov() As "_strnmov"
;   strtoll() As "_strtoll"
;   strtoull() As "_strtoull"
;   strxmov() As "_strxmov"
;   strxnmov() As "_strxnmov"
;   symdirget() As "_symdirget"
;   system_filename() As "_system_filename"
;   test_if_hard_path() As "_test_if_hard_path"
;   thd_lib_detected() As "_thd_lib_detected"
;   timed_mutexes() As "_timed_mutexes"
;   to_lower_cp1250_bin() As "_to_lower_cp1250_bin"
;   to_lower_cp1250_croatian_ci() As "_to_lower_cp1250_croatian_ci"
;   to_lower_cp1250_general_ci() As "_to_lower_cp1250_general_ci"
;   to_lower_latin1_danish_ci() As "_to_lower_latin1_danish_ci"
;   to_lower_latin1_general_ci() As "_to_lower_latin1_general_ci"
;   to_lower_latin1_general_cs() As "_to_lower_latin1_general_cs"
;   to_lower_latin1_german1_ci() As "_to_lower_latin1_german1_ci"
;   to_lower_latin1_spanish_ci() As "_to_lower_latin1_spanish_ci"
;   to_lower_latin2_bin() As "_to_lower_latin2_bin"
;   to_lower_latin2_croatian_ci() As "_to_lower_latin2_croatian_ci"
;   to_lower_latin2_general_ci() As "_to_lower_latin2_general_ci"
;   to_lower_latin2_hungarian_ci() As "_to_lower_latin2_hungarian_ci"
;   to_uni_cp1250_bin() As "_to_uni_cp1250_bin"
;   to_uni_cp1250_croatian_ci() As "_to_uni_cp1250_croatian_ci"
;   to_uni_cp1250_general_ci() As "_to_uni_cp1250_general_ci"
;   to_uni_latin1_danish_ci() As "_to_uni_latin1_danish_ci"
;   to_uni_latin1_general_ci() As "_to_uni_latin1_general_ci"
;   to_uni_latin1_general_cs() As "_to_uni_latin1_general_cs"
;   to_uni_latin1_german1_ci() As "_to_uni_latin1_german1_ci"
;   to_uni_latin1_spanish_ci() As "_to_uni_latin1_spanish_ci"
;   to_uni_latin2_bin() As "_to_uni_latin2_bin"
;   to_uni_latin2_croatian_ci() As "_to_uni_latin2_croatian_ci"
;   to_uni_latin2_general_ci() As "_to_uni_latin2_general_ci"
;   to_uni_latin2_hungarian_ci() As "_to_uni_latin2_hungarian_ci"
;   to_unix_path() As "_to_unix_path"
;   to_upper_cp1250_bin() As "_to_upper_cp1250_bin"
;   to_upper_cp1250_croatian_ci() As "_to_upper_cp1250_croatian_ci"
;   to_upper_cp1250_general_ci() As "_to_upper_cp1250_general_ci"
;   to_upper_latin1_danish_ci() As "_to_upper_latin1_danish_ci"
;   to_upper_latin1_general_ci() As "_to_upper_latin1_general_ci"
;   to_upper_latin1_general_cs() As "_to_upper_latin1_general_cs"
;   to_upper_latin1_german1_ci() As "_to_upper_latin1_german1_ci"
;   to_upper_latin1_spanish_ci() As "_to_upper_latin1_spanish_ci"
;   to_upper_latin2_bin() As "_to_upper_latin2_bin"
;   to_upper_latin2_croatian_ci() As "_to_upper_latin2_croatian_ci"
;   to_upper_latin2_general_ci() As "_to_upper_latin2_general_ci"
;   to_upper_latin2_hungarian_ci() As "_to_upper_latin2_hungarian_ci"
;   uca_length() As "_uca_length"
;   uca_weight() As "_uca_weight"
;   ullstr() As "_ullstr"
;   ulonglong2double() As "_ulonglong2double"
;   uncompress() As "_uncompress"
;   uni_to_cs() As "_uni_to_cs"
;   unknown_sqlstate() As "_unknown_sqlstate"
;   unpack_dirname() As "_unpack_dirname"
;   unpack_fields() As "_unpack_fields"
;   unpack_filename() As "_unpack_filename"
;   vio_blocking() As "_vio_blocking"
;   vio_close() As "_vio_close"
;   vio_close_pipe() As "_vio_close_pipe"
;   vio_close_shared_memory() As "_vio_close_shared_memory"
;   vio_delete() As "_vio_delete"
;   vio_description() As "_vio_description"
;   vio_end() As "_vio_end"
;   vio_errno() As "_vio_errno"
;   vio_fastsend() As "_vio_fastsend"
;   vio_fd() As "_vio_fd"
;   vio_ignore_timeout() As "_vio_ignore_timeout"
;   vio_in_addr() As "_vio_in_addr"
;   vio_is_blocking() As "_vio_is_blocking"
;   vio_keepalive() As "_vio_keepalive"
;   vio_new() As "_vio_new"
;   vio_new_win32pipe() As "_vio_new_win32pipe"
;   vio_new_win32shared_memory() As "_vio_new_win32shared_memory"
;   vio_peer_addr() As "_vio_peer_addr"
;   vio_poll_read() As "_vio_poll_read"
;   vio_read() As "_vio_read"
;   vio_read_buff() As "_vio_read_buff"
;   vio_read_pipe() As "_vio_read_pipe"
;   vio_read_shared_memory() As "_vio_read_shared_memory"
;   vio_reset() As "_vio_reset"
;   vio_should_retry() As "_vio_should_retry"
;   vio_ssl_blocking() As "_vio_ssl_blocking"
;   vio_ssl_close() As "_vio_ssl_close"
;   vio_ssl_delete() As "_vio_ssl_delete"
;   vio_ssl_read() As "_vio_ssl_read"
;   vio_ssl_write() As "_vio_ssl_write"
;   vio_timeout() As "_vio_timeout"
;   vio_type() As "_vio_type"
;   vio_was_interrupted() As "_vio_was_interrupted"
;   vio_write() As "_vio_write"
;   vio_write_pipe() As "_vio_write_pipe"
;   vio_write_shared_memory() As "_vio_write_shared_memory"
;   wild_compare() As "_wild_compare"
;   wild_many() As "_wild_many"
;   wild_one() As "_wild_one"
;   wild_prefix() As "_wild_prefix"
;   win_pthread_init() As "_win_pthread_init"
;   win_pthread_mutex_trylock() As "_win_pthread_mutex_trylock"
;   win_pthread_setspecific() As "_win_pthread_setspecific"
;   yaASN1_STRING_data() As "_yaASN1_STRING_data"
;   yaASN1_STRING_length() As "_yaASN1_STRING_length"
;   yaASN1_STRING_to_UTF8() As "_yaASN1_STRING_to_UTF8"
;   yaASN1_STRING_type() As "_yaASN1_STRING_type"
;   yaBN_bin2bn() As "_yaBN_bin2bn"
;   yaDES_ecb_encrypt() As "_yaDES_ecb_encrypt"
;   yaDES_ede3_cbc_encrypt() As "_yaDES_ede3_cbc_encrypt"
;   yaDES_set_key() As "_yaDES_set_key"
;   yaDES_set_key_unchecked() As "_yaDES_set_key_unchecked"
;   yaDES_set_odd_parity() As "_yaDES_set_odd_parity"
;   yaDH_free() As "_yaDH_free"
;   yaDH_new() As "_yaDH_new"
;   yaERR_GET_REASON() As "_yaERR_GET_REASON"
;   yaERR_error_string() As "_yaERR_error_string"
;   yaERR_error_string_n() As "_yaERR_error_string_n"
;   yaERR_free_strings() As "_yaERR_free_strings"
;   yaERR_get_error() As "_yaERR_get_error"
;   yaERR_get_error_line_data() As "_yaERR_get_error_line_data"
;   yaERR_peek_error() As "_yaERR_peek_error"
;   yaERR_print_errors_fp() As "_yaERR_print_errors_fp"
;   yaERR_remove_state() As "_yaERR_remove_state"
;   yaEVP_BytesToKey() As "_yaEVP_BytesToKey"
;   yaEVP_PKEY_copy_parameters() As "_yaEVP_PKEY_copy_parameters"
;   yaEVP_PKEY_free() As "_yaEVP_PKEY_free"
;   yaEVP_cleanup() As "_yaEVP_cleanup"
;   yaEVP_des_ede3_cbc() As "_yaEVP_des_ede3_cbc"
;   yaEVP_md5() As "_yaEVP_md5"
;   yaGENERAL_NAMES_free() As "_yaGENERAL_NAMES_free"
;   yaMD4_Final() As "_yaMD4_Final"
;   yaMD4_Init() As "_yaMD4_Init"
;   yaMD4_Update() As "_yaMD4_Update"
;   yaMD5_Final() As "_yaMD5_Final"
;   yaMD5_Init() As "_yaMD5_Init"
;   yaMD5_Update() As "_yaMD5_Update"
;   yaOpenSSL_add_all_algorithms() As "_yaOpenSSL_add_all_algorithms"
;   yaRAND_bytes() As "_yaRAND_bytes"
;   yaRAND_file_name() As "_yaRAND_file_name"
;   yaRAND_load_file() As "_yaRAND_load_file"
;   yaRAND_screen() As "_yaRAND_screen"
;   yaRAND_status() As "_yaRAND_status"
;   yaRAND_write_file() As "_yaRAND_write_file"
;   yaRSA_free() As "_yaRSA_free"
;   yaRSA_generate_key() As "_yaRSA_generate_key"
;   yaSSL_CIPHER_description() As "_yaSSL_CIPHER_description"
;   yaSSL_CTX_check_private_key() As "_yaSSL_CTX_check_private_key"
;   yaSSL_CTX_free() As "_yaSSL_CTX_free"
;   yaSSL_CTX_get_session_cache_mode() As "_yaSSL_CTX_get_session_cache_mode"
;   yaSSL_CTX_get_verify_depth() As "_yaSSL_CTX_get_verify_depth"
;   yaSSL_CTX_get_verify_mode() As "_yaSSL_CTX_get_verify_mode"
;   yaSSL_CTX_load_verify_locations() As "_yaSSL_CTX_load_verify_locations"
;   yaSSL_CTX_new() As "_yaSSL_CTX_new"
;   yaSSL_CTX_sess_accept() As "_yaSSL_CTX_sess_accept"
;   yaSSL_CTX_sess_accept_good() As "_yaSSL_CTX_sess_accept_good"
;   yaSSL_CTX_sess_accept_renegotiate() As "_yaSSL_CTX_sess_accept_renegotiate"
;   yaSSL_CTX_sess_cache_full() As "_yaSSL_CTX_sess_cache_full"
;   yaSSL_CTX_sess_cb_hits() As "_yaSSL_CTX_sess_cb_hits"
;   yaSSL_CTX_sess_connect() As "_yaSSL_CTX_sess_connect"
;   yaSSL_CTX_sess_connect_good() As "_yaSSL_CTX_sess_connect_good"
;   yaSSL_CTX_sess_connect_renegotiate() As "_yaSSL_CTX_sess_connect_renegotiate"
;   yaSSL_CTX_sess_get_cache_size() As "_yaSSL_CTX_sess_get_cache_size"
;   yaSSL_CTX_sess_hits() As "_yaSSL_CTX_sess_hits"
;   yaSSL_CTX_sess_misses() As "_yaSSL_CTX_sess_misses"
;   yaSSL_CTX_sess_number() As "_yaSSL_CTX_sess_number"
;   yaSSL_CTX_sess_set_cache_size() As "_yaSSL_CTX_sess_set_cache_size"
;   yaSSL_CTX_sess_timeouts() As "_yaSSL_CTX_sess_timeouts"
;   yaSSL_CTX_set_cipher_list() As "_yaSSL_CTX_set_cipher_list"
;   yaSSL_CTX_set_default_passwd_cb() As "_yaSSL_CTX_set_default_passwd_cb"
;   yaSSL_CTX_set_default_passwd_cb_userdata() As "_yaSSL_CTX_set_default_passwd_cb_userdata"
;   yaSSL_CTX_set_default_verify_paths() As "_yaSSL_CTX_set_default_verify_paths"
;   yaSSL_CTX_set_info_callback() As "_yaSSL_CTX_set_info_callback"
;   yaSSL_CTX_set_options() As "_yaSSL_CTX_set_options"
;   yaSSL_CTX_set_session_cache_mode() As "_yaSSL_CTX_set_session_cache_mode"
;   yaSSL_CTX_set_session_id_context() As "_yaSSL_CTX_set_session_id_context"
;   yaSSL_CTX_set_timeout() As "_yaSSL_CTX_set_timeout"
;   yaSSL_CTX_set_tmp_dh() As "_yaSSL_CTX_set_tmp_dh"
;   yaSSL_CTX_set_tmp_rsa_callback() As "_yaSSL_CTX_set_tmp_rsa_callback"
;   yaSSL_CTX_set_verify() As "_yaSSL_CTX_set_verify"
;   yaSSL_CTX_use_PrivateKey_file() As "_yaSSL_CTX_use_PrivateKey_file"
;   yaSSL_CTX_use_RSAPrivateKey_file() As "_yaSSL_CTX_use_RSAPrivateKey_file"
;   yaSSL_CTX_use_certificate_chain_file() As "_yaSSL_CTX_use_certificate_chain_file"
;   yaSSL_CTX_use_certificate_file() As "_yaSSL_CTX_use_certificate_file"
;   yaSSL_SESSION_free() As "_yaSSL_SESSION_free"
;   yaSSL_SESSION_set_timeout() As "_yaSSL_SESSION_set_timeout"
;   yaSSL_accept() As "_yaSSL_accept"
;   yaSSL_alert_desc_string_long() As "_yaSSL_alert_desc_string_long"
;   yaSSL_alert_type_string_long() As "_yaSSL_alert_type_string_long"
;   yaSSL_clear() As "_yaSSL_clear"
;   yaSSL_connect() As "_yaSSL_connect"
;   yaSSL_do_handshake() As "_yaSSL_do_handshake"
;   yaSSL_free() As "_yaSSL_free"
;   yaSSL_get1_session() As "_yaSSL_get1_session"
;   yaSSL_get_certificate() As "_yaSSL_get_certificate"
;   yaSSL_get_cipher() As "_yaSSL_get_cipher"
;   yaSSL_get_cipher_list() As "_yaSSL_get_cipher_list"
;   yaSSL_get_cipher_name() As "_yaSSL_get_cipher_name"
;   yaSSL_get_current_cipher() As "_yaSSL_get_current_cipher"
;   yaSSL_get_default_timeout() As "_yaSSL_get_default_timeout"
;   yaSSL_get_error() As "_yaSSL_get_error"
;   yaSSL_get_fd() As "_yaSSL_get_fd"
;   yaSSL_get_peer_certificate() As "_yaSSL_get_peer_certificate"
;   yaSSL_get_privatekey() As "_yaSSL_get_privatekey"
;   yaSSL_get_quiet_shutdown() As "_yaSSL_get_quiet_shutdown"
;   yaSSL_get_session() As "_yaSSL_get_session"
;   yaSSL_get_shared_ciphers() As "_yaSSL_get_shared_ciphers"
;   yaSSL_get_verify_depth() As "_yaSSL_get_verify_depth"
;   yaSSL_get_verify_mode() As "_yaSSL_get_verify_mode"
;   yaSSL_get_verify_result() As "_yaSSL_get_verify_result"
;   yaSSL_get_version() As "_yaSSL_get_version"
;   yaSSL_library_init() As "_yaSSL_library_init"
;   yaSSL_load_error_strings() As "_yaSSL_load_error_strings"
;   yaSSL_new() As "_yaSSL_new"
;   yaSSL_peek() As "_yaSSL_peek"
;   yaSSL_pending() As "_yaSSL_pending"
;   yaSSL_read() As "_yaSSL_read"
;   yaSSL_session_reused() As "_yaSSL_session_reused"
;   yaSSL_set_accept_state() As "_yaSSL_set_accept_state"
;   yaSSL_set_compression() As "_yaSSL_set_compression"
;   yaSSL_set_connect_state() As "_yaSSL_set_connect_state"
;   yaSSL_set_fd() As "_yaSSL_set_fd"
;   yaSSL_set_quiet_shutdown() As "_yaSSL_set_quiet_shutdown"
;   yaSSL_set_rfd() As "_yaSSL_set_rfd"
;   yaSSL_set_session() As "_yaSSL_set_session"
;   yaSSL_set_shutdown() As "_yaSSL_set_shutdown"
;   yaSSL_set_wfd() As "_yaSSL_set_wfd"
;   yaSSL_shutdown() As "_yaSSL_shutdown"
;   yaSSL_state_string_long() As "_yaSSL_state_string_long"
;   yaSSL_want_read() As "_yaSSL_want_read"
;   yaSSL_want_write() As "_yaSSL_want_write"
;   yaSSL_write() As "_yaSSL_write"
;   yaSSLeay_add_ssl_algorithms() As "_yaSSLeay_add_ssl_algorithms"
;   yaSSLeay_version() As "_yaSSLeay_version"
;   yaSSLv23_client_method() As "_yaSSLv23_client_method"
;   yaSSLv23_server_method() As "_yaSSLv23_server_method"
;   yaSSLv2_client_method() As "_yaSSLv2_client_method"
;   yaSSLv3_client_method() As "_yaSSLv3_client_method"
;   yaSSLv3_method() As "_yaSSLv3_method"
;   yaSSLv3_server_method() As "_yaSSLv3_server_method"
;   yaTLSv1_1_client_method() As "_yaTLSv1_1_client_method"
;   yaTLSv1_1_server_method() As "_yaTLSv1_1_server_method"
;   yaTLSv1_client_method() As "_yaTLSv1_client_method"
;   yaTLSv1_server_method() As "_yaTLSv1_server_method"
;   yaX509_LOOKUP_add_dir() As "_yaX509_LOOKUP_add_dir"
;   yaX509_LOOKUP_file() As "_yaX509_LOOKUP_file"
;   yaX509_LOOKUP_hash_dir() As "_yaX509_LOOKUP_hash_dir"
;   yaX509_LOOKUP_load_file() As "_yaX509_LOOKUP_load_file"
;   yaX509_NAME_ENTRY_get_data() As "_yaX509_NAME_ENTRY_get_data"
;   yaX509_NAME_get_entry() As "_yaX509_NAME_get_entry"
;   yaX509_NAME_get_index_by_NID() As "_yaX509_NAME_get_index_by_NID"
;   yaX509_NAME_oneline() As "_yaX509_NAME_oneline"
;   yaX509_STORE_CTX_get_current_cert() As "_yaX509_STORE_CTX_get_current_cert"
;   yaX509_STORE_CTX_get_error() As "_yaX509_STORE_CTX_get_error"
;   yaX509_STORE_CTX_get_error_depth() As "_yaX509_STORE_CTX_get_error_depth"
;   yaX509_STORE_add_lookup() As "_yaX509_STORE_add_lookup"
;   yaX509_STORE_get_by_subject() As "_yaX509_STORE_get_by_subject"
;   yaX509_STORE_new() As "_yaX509_STORE_new"
;   yaX509_free() As "_yaX509_free"
;   yaX509_get_ext_d2i() As "_yaX509_get_ext_d2i"
;   yaX509_get_issuer_name() As "_yaX509_get_issuer_name"
;   yaX509_get_notAfter() As "_yaX509_get_notAfter"
;   yaX509_get_notBefore() As "_yaX509_get_notBefore"
;   yaX509_get_pubkey() As "_yaX509_get_pubkey"
;   yaX509_get_subject_name() As "_yaX509_get_subject_name"
;   yaX509_verify_cert_error_string() As "_yaX509_verify_cert_error_string"
;   yask_GENERAL_NAME_num() As "_yask_GENERAL_NAME_num"
;   yask_GENERAL_NAME_value() As "_yask_GENERAL_NAME_value"
;   yayaSSL_CleanUp() As "_yayaSSL_CleanUp"
;   year_2000_handling() As "_year_2000_handling"
;   zError() As "_zError"
;   z_errmsg() As "_z_errmsg"
;   zcalloc() As "_zcalloc"
;   zcfree() As "_zcfree"
;   zlibCompileFlags() As "_zlibCompileFlags"
;   zlibVersion() As "_zlibVersion"
EndImport

; IDE Options = PureBasic 4.20 (Windows - x86)
; CursorPosition = 541
; FirstLine = 539
; Folding = -
; EnableUnicode