XIncludeFile "RW_SFML_Res.pb"
;{ Audio
  Import "csfml-audio.lib"
    sfListener_GetGlobalVolume.f() As "_sfListener_GetGlobalVolume"
    sfListener_GetPosition(*PosX.f, *PosY.f, *PosZ.f) As "_sfListener_GetPosition"
    sfListener_GetTarget(*TargetX.f, *TargetY.f, *TargetZ.f) As "_sfListener_GetTarget"
    sfListener_SetGlobalVolume(Volume.f) As "_sfListener_SetGlobalVolume"
    sfListener_SetPosition(PosX.f, PosY.f, PosZ.f) As "_sfListener_SetPosition"
    sfListener_SetTarget(TargetX.f, TargetY.f, TargetZ.f) As "_sfListener_SetTarget"
    sfMusic_CreateFromFile(Filename.s) As "_sfMusic_CreateFromFile"
    sfMusic_CreateFromMemory(datamem.l, SizeInBytes.l) As "_sfMusic_CreateFromMemory"
    sfMusic_Destroy(Music.l) As "_sfMusic_Destroy"
    sfMusic_GetAttenuation.f(Music.l) As "_sfMusic_GetAttenuation"
    sfMusic_GetChannelsCount(Music.l) As "_sfMusic_GetChannelsCount"
    sfMusic_GetDuration.f(Music.l) As "_sfMusic_GetDuration"
    sfMusic_GetLoop(Music.l) As "_sfMusic_GetLoop"
    sfMusic_GetMinDistance.f(Music.l) As "_sfMusic_GetMinDistance"
    sfMusic_GetPitch.f(Music.l) As "_sfMusic_GetPitch"
    sfMusic_GetPosition(Music.l, *X.f, *Y.f, *Z.f) As "_sfMusic_GetPosition"
    sfMusic_GetSampleRate(Music.l) As "_sfMusic_GetSampleRate"
    sfMusic_GetStatus(Music.l) As "_sfMusic_GetStatus"
    sfMusic_GetVolume.f(Music.l) As "_sfMusic_GetVolume"
    sfMusic_Pause(Music.l) As "_sfMusic_Pause"
    sfMusic_Play(Music.l) As "_sfMusic_Play"
    sfMusic_SetAttenuation(Music.l, Attenuation.f) As "_sfMusic_SetAttenuation"
    sfMusic_SetLoop(Music.l, Loop.sfBool) As "_sfMusic_SetLoop"
    sfMusic_SetMinDistance(Music.l,MinDistance.f) As "_sfMusic_SetMinDistance"
    sfMusic_SetPitch(Music.l, Pitch.f) As "_sfMusic_SetPitch"
    sfMusic_SetPosition(Music.l, X.f, Y.f, Z.f) As "_sfMusic_SetPosition"
    sfMusic_SetVolume(Music.l, Volume.f) As "_sfMusic_SetVolume"
    sfMusic_Stop(Music.l) As "_sfMusic_Stop"
    sfSoundBufferRecorder_Create() As "_sfSoundBufferRecorder_Create"
    sfSoundBufferRecorder_Destroy(SoundBufferRecorder.l) As "_sfSoundBufferRecorder_Destroy"
    sfSoundBufferRecorder_GetBuffer(SoundBufferRecorder.l) As "_sfSoundBufferRecorder_GetBuffer"
    sfSoundBufferRecorder_GetSampleRate(SoundBufferRecorder.l) As "_sfSoundBufferRecorder_GetSampleRate"
    sfSoundBufferRecorder_Start(SoundBufferRecorder.l, SampleRate.l) As "_sfSoundBufferRecorder_Start"
    sfSoundBufferRecorder_Stop(SoundBufferRecorder.l) As "_sfSoundBufferRecorder_Stop"
    sfSoundBuffer_CreateFromFile(Filename.s) As "_sfSoundBuffer_CreateFromFile"
    sfSoundBuffer_CreateFromMemory(datamem.l, SizeInBytes.l) As "_sfSoundBuffer_CreateFromMemory"
    sfSoundBuffer_CreateFromSamples(*Samples, SamplesCount.l, ChannelsCount.l, SampleRate.l) As "_sfSoundBuffer_CreateFromSamples"
    sfSoundBuffer_Destroy(SoundBuffer.l) As "_sfSoundBuffer_Destroy"
    sfSoundBuffer_GetChannelsCount(SoundBuffer.l) As "_sfSoundBuffer_GetChannelsCount"
    sfSoundBuffer_GetDuration.f(SoundBuffer.l) As "_sfSoundBuffer_GetDuration"
    sfSoundBuffer_GetSampleRate(SoundBuffer.l) As "_sfSoundBuffer_GetSampleRate"
    sfSoundBuffer_GetSamples(SoundBuffer.l) As "_sfSoundBuffer_GetSamples"
    sfSoundBuffer_GetSamplesCount(SoundBuffer.l) As "_sfSoundBuffer_GetSamplesCount"
    sfSoundBuffer_SaveToFile(SoundBuffer.l, Filename.s) As "_sfSoundBuffer_SaveToFile"
    sfSoundRecorder_CanCapture.sfBool() As "_sfSoundRecorder_CanCapture"
    sfSoundRecorder_Create(cb.sfBool, *UserData) As "_sfSoundRecorder_Create"
    sfSoundRecorder_Destroy(SoundRecorder.l) As "_sfSoundRecorder_Destroy"
    sfSoundRecorder_GetSampleRate(SoundRecorder.l) As "_sfSoundRecorder_GetSampleRate"
    sfSoundRecorder_Start(SoundRecorder.l, SampleRate.l) As "_sfSoundRecorder_Start"
    sfSoundRecorder_Stop(SoundRecorder.l) As "_sfSoundRecorder_Stop"
    sfSoundStream_Create(*CB_OnStart_sfSoundStreamStartCallback, *CB_OnGetData_sfSoundStreamGetDataCallback, ChannelsCount.l, SampleRate.l, *UserData) As "_sfSoundStream_Create"
    sfSoundStream_Destroy(SoundStreamStream.l) As "_sfSoundStream_Destroy"
    sfSoundStream_GetAttenuation.f(SoundStream.l) As "_sfSoundStream_GetAttenuation"
    sfSoundStream_GetChannelsCount(SoundStream.l) As "_sfSoundStream_GetChannelsCount"
    sfSoundStream_GetMinDistance.f(SoundStream.l) As "_sfSoundStream_GetMinDistance"
    sfSoundStream_GetPitch.f(SoundStream.l) As "_sfSoundStream_GetPitch"
    sfSoundStream_GetPosition(SoundStream.l, *X.f, *Y.f, *Z.f) As "_sfSoundStream_GetPosition"
    sfSoundStream_GetSampleRate(SoundStream.l) As "_sfSoundStream_GetSampleRate"
    sfSoundStream_GetStatus(SoundStream.l) As "_sfSoundStream_GetStatus"
    sfSoundStream_GetVolume.f(SoundStream.l) As "_sfSoundStream_GetVolume"
    sfSoundStream_Pause(SoundStream.l) As "_sfSoundStream_Pause"
    sfSoundStream_Play(SoundStream.l) As "_sfSoundStream_Play"
    sfSoundStream_SetAttenuation(SoundStream.l, Attenuation.f) As "_sfSoundStream_SetAttenuation"
    sfSoundStream_SetMinDistance(SoundStream.l, MinDistance.f) As "_sfSoundStream_SetMinDistance"
    sfSoundStream_SetPitch(SoundStream.l, Pitch.f) As "_sfSoundStream_SetPitch"
    sfSoundStream_SetPosition(SoundStream.l, X.f, Y.f, Z.f) As "_sfSoundStream_SetPosition"
    sfSoundStream_SetVolume(SoundStream.l, Volume.f) As "_sfSoundStream_SetVolume"
    sfSoundStream_Stop(SoundStream.l) As "_sfSoundStream_Stop"
    sfSound_Create() As "_sfSound_Create"
    sfSound_Destroy(Sound.l) As "_sfSound_Destroy"
    sfSound_GetAttenuation.f(Sound.l) As "_sfSound_GetAttenuation"
    sfSound_GetBuffer(Sound.l) As "_sfSound_GetBuffer"
    sfSound_GetLoop(Sound.l) As "_sfSound_GetLoop"
    sfSound_GetMinDistance.f(Sound.l) As "_sfSound_GetMinDistance"
    sfSound_GetPitch.f(Sound.l) As "_sfSound_GetPitch"
    sfSound_GetPlayingOffset.f(Sound.l) As "_sfSound_GetPlayingOffset"
    sfSound_GetPosition(Sound.l, *X.f, *Y.f, *Z.f) As "_sfSound_GetPosition"
    sfSound_GetStatus(Sound.l) As "_sfSound_GetStatus"
    sfSound_GetVolume.f(Sound.l) As "_sfSound_GetVolume"
    sfSound_Pause(Sound.l) As "_sfSound_Pause"
    sfSound_Play(Sound.l) As "_sfSound_Play"
    sfSound_SetAttenuation(Sound.l, Attenuation.f) As "_sfSound_SetAttenuation"
    sfSound_SetBuffer(Sound.l, Buffer.l) As "_sfSound_SetBuffer"
    sfSound_SetLoop(Sound.l, Loop.sfBool) As "_sfSound_SetLoop"
    sfSound_SetMinDistance(Sound.l, MinDistance.f) As "_sfSound_SetMinDistance"
    sfSound_SetPitch(Sound.l, Pitch.f) As "_sfSound_SetPitch"
    sfSound_SetPosition(Sound.l, X.f, Y.f, Z.f) As "_sfSound_SetPosition"
    sfSound_SetVolume(Sound.l, Volume.f) As "_sfSound_SetVolume"
    sfSound_Stop(Sound.l) As "_sfSound_Stop"
  EndImport
;}
;{ Graphics
  Import "csfml-graphics.lib"
    sfColor_FromRGB(r.c, g.c, b.c) As "_sfColor_FromRGB"
    sfColor_FromRGBA(r.c, g.c, b.c, a.c) As "_sfColor_FromRGBA"
    sfColor_Add(*Color1.sfColor, *Color2.sfColor) As "_sfColor_Add"
    sfColor_Modulate(*Color1.sfColor, *Color2.sfColor) As "_sfColor_Modulate"
    sfImage_Create() As "_sfImage_Create"
    sfImage_CreateFromColor(Width.l, Height.l, *Color.sfColor) As "_sfImage_CreateFromColor"
    sfImage_CreateFromPixels(Width.l, Height.l, *DataMem.c) As "_sfImage_CreateFromPixels"
    sfImage_CreateFromFile(Filename.s) As "_sfImage_CreateFromFile"
    sfImage_CreateFromMemory(*DataMem, SizeInBytes.l) As "_sfImage_CreateFromMemory"
    sfImage_Destroy(Image.l) As "_sfImage_Destroy"
    sfImage_SaveToFile(Image.l, Filename.s) As "_sfImage_SaveToFile"
    sfImage_CreateMaskFromColor(Image.l, *ColorKey.sfColor, Alpha.c) As "_sfImage_CreateMaskFromColor"
    sfImage_Resize(Image.l, Width.l, Height.l, *Color.sfColor) As "_sfImage_Resize"
    sfImage_SetPixel(Image.l, X.l, Y.l, *Color.sfColor) As "_sfImage_SetPixel"
    sfImage_GetPixel(Image.l, X.l, Y.l) As "_sfImage_GetPixel"
    sfImage_GetPixelsPtr(Image.l) As "_sfImage_GetPixelsPtr"
    sfImage_Bind(Image.l) As "_sfImage_Bind"
    sfImage_SetSmooth(Image.l, Smooth.sfBool) As "_sfImage_SetSmooth"
    sfImage_GetWidth(Image.l) As "_sfImage_GetWidth"
    sfImage_GetHeight(Image.l) As "_sfImage_GetHeight"
    sfImage_IsSmooth.sfBool(Image.l) As "_sfImage_IsSmooth"
    sfFloatRect_Offset(*Rect.sfFloatRect, OffsetX.f, OffsetY.f) As "_sfFloatRect_Offset"
    sfFloatRect_Contains(*Rect.sfFloatRect, X.f, Y.f) As "_sfFloatRect_Contains"
    sfFloatRect_Intersects(*Rect1.sfFloatRect, *Rect2.sfFloatRect, *OverlappingRect.sfFloatRect) As "_sfFloatRect_Intersects"
    sfIntRect_Offset(*Rect.sfIntRect, OffsetX.f, OffsetY.f) As "_sfIntRect_Offset"
    sfIntRect_Contains(*Rect.sfIntRect, X.f, Y.f) As "_sfIntRect_Contains"
    sfIntRect_Intersects(*Rect1.sfIntRect, *Rect2.sfIntRect, *OverlappingRect.sfIntRect) As "_sfIntRect_Intersects"
    sfPostFX_CreateFromFile(Filename.s) As "_sfPostFX_CreateFromFile"
    sfPostFX_CreateFromMemory(Effect.s) As "_sfPostFX_CreateFromMemory"
    sfPostFX_Destroy(sfPostFX.l) As "_sfPostFX_Destroy"
    sfPostFX_SetParameter1(sfPostFX.l, Name.s, X.f) As "_sfPostFX_SetParameter1"
    sfPostFX_SetParameter2(sfPostFX.l, Name.s, X.f, Y.f) As "_sfPostFX_SetParameter2"
    sfPostFX_SetParameter3(sfPostFX.l, Name.s, X.f, Y.f, Z.f) As "_sfPostFX_SetParameter3"
    sfPostFX_SetParameter4(sfPostFX.l, Name.s, X.f, Y.f, Z.f, W.f) As "_sfPostFX_SetParameter4"
    sfPostFX_SetTexture(sfPostFX.l, Name.s, Texture.l) As "_sfPostFX_SetTexture"
    sfPostFX_CanUsePostFX.sfBool() As "_sfPostFX_CanUsePostFX"
    sfShape_Create() As "_sfShape_Create"
    sfShape_CreateLine(P1X.f, P1Y.f, P2X.f, P2Y.f, Thickness.f, *Col.sfColor, Outline.f, *OutlineCol.sfColor) As "_sfShape_CreateLine"
    sfShape_CreateRectangle(P1X.f, P1Y.f, P2X.f, P2Y.f, *Col.sfColor, Outline.f, *OutlineCol.sfColor) As "_sfShape_CreateRectangle"
    sfShape_CreateCircle(X.f, Y.f, Radius.f, *Col.sfColor, Outline.f, *OutlineCol.sfColor) As "_sfShape_CreateCircle"
    sfShape_Destroy(Shape.l) As "_sfShape_Destroy"
    sfShape_SetX(Shape.l, X.f) As "_sfShape_SetX"
    sfShape_SetY(Shape.l, Y.f) As "_sfShape_SetY"
    sfShape_SetPosition(Shape.l, X.f, Y.f) As "_sfShape_SetPosition"
    sfShape_SetScaleX(Shape.l, Scale.f) As "_sfShape_SetScaleX"
    sfShape_SetScaleY(Shape.l, Scale.f) As "_sfShape_SetScaleY"
    sfShape_SetScale(Shape.l, ScaleX.f, ScaleY.f) As "_sfShape_SetScale"
    sfShape_SetRotation(Shape.l, Rotation.f) As "_sfShape_SetRotation"
    sfShape_SetCenter(Shape.l, X.f, Y.f) As "_sfShape_SetCenter"
    sfShape_SetColor(Shape.l, *Color.sfColor) As "_sfShape_SetColor"
    sfShape_SetBlendMode(Shape.l, Mode.l) As "_sfShape_SetBlendMode"
    sfShape_GetX.f(Shape.l) As "_sfShape_GetX"
    sfShape_GetY.f(Shape.l) As "_sfShape_GetY"
    sfShape_GetScaleX.f(Shape.l) As "_sfShape_GetScaleX"
    sfShape_GetScaleY.f(Shape.l) As "_sfShape_GetScaleY"
    sfShape_GetRotation.f(Shape.l) As "_sfShape_GetRotation"
    sfShape_GetCenterX.f(Shape.l) As "_sfShape_GetCenterX"
    sfShape_GetCenterY.f(Shape.l) As "_sfShape_GetCenterY"
    sfShape_GetColor(Shape.l) As "_sfShape_GetColor"
    sfShape_GetBlendMode(Shape.l) As "_sfShape_GetBlendMode"
    sfShape_Move(Shape.l, OffsetX.f, OffsetY.f) As "_sfShape_Move"
    sfShape_Scale(Shape.l, FactorX.f, FactorY.f) As "_sfShape_Scale"
    sfShape_Rotate(Shape.l, Angle.f) As "_sfShape_Rotate"
    sfShape_AddPoint(Shape.l, X.f, Y.f, *Col.sfColor, *OutlineCol.sfColor) As "_sfShape_AddPoint"
    sfShape_EnableFill(Shape.l, Enable.sfBool) As "_sfShape_EnableFill"
    sfShape_EnableOutline(Shape.l, Enable.sfBool) As "_sfShape_EnableOutline"
    sfShape_SetOutlineWidth(Shape.l, Width.f) As "_sfShape_SetOutlineWidth"
    sfShape_GetNbPoints(Shape.l) As "_sfShape_GetNbPoints"
    sfShape_GetPoint(Shape.l, Index.l, *X.f, *Y.f) As "_sfShape_GetPoint"
    sfShape_GetOutlineWidth.f(Shape.l) As "_sfShape_GetOutlineWidth"
    sfSprite_Create() As "_sfSprite_Create"
    sfSprite_Destroy(Sprite.l) As "_sfSprite_Destroy"
    sfSprite_SetX(Sprite.l, X.f) As "_sfSprite_SetX"
    sfSprite_SetY(Sprite.l, Y.f) As "_sfSprite_SetY"
    sfSprite_SetPosition(Sprite.l, X.f, Y.f) As "_sfSprite_SetPosition"
    sfSprite_SetScaleX(Sprite.l, Scale.f) As "_sfSprite_SetScaleX"
    sfSprite_SetScaleY(Sprite.l, Scale.f) As "_sfSprite_SetScaleY"
    sfSprite_SetScale(Sprite.l, ScaleX.f, ScaleY.f) As "_sfSprite_SetScale"
    sfSprite_SetRotation(Sprite.l, Rotation.f) As "_sfSprite_SetRotation"
    sfSprite_SetCenter(Sprite.l, X.f, Y.f) As "_sfSprite_SetCenter"
    sfSprite_SetColor(Sprite.l, *Color.sfColor) As "_sfSprite_SetColor"
    sfSprite_SetBlendMode(Sprite.l, Mode.l) As "_sfSprite_SetBlendMode"
    sfSprite_GetX.f(Sprite.l) As "_sfSprite_GetX"
    sfSprite_GetY.f(Sprite.l) As "_sfSprite_GetY"
    sfSprite_GetScaleX.f(Sprite.l) As "_sfSprite_GetScaleX"
    sfSprite_GetScaleY.f(Sprite.l) As "_sfSprite_GetScaleY"
    sfSprite_GetRotation.f(Sprite.l) As "_sfSprite_GetRotation"
    sfSprite_GetCenterX.f(Sprite.l) As "_sfSprite_GetCenterX"
    sfSprite_GetCenterY.f(Sprite.l) As "_sfSprite_GetCenterY"
    sfSprite_GetColor(Sprite.l) As "_sfSprite_GetColor"
    sfSprite_GetBlendMode(Sprite.l) As "_sfSprite_GetBlendMode"
    sfSprite_Move(Sprite.l, OffsetX.f, OffsetY.f) As "_sfSprite_Move"
    sfSprite_Scale(Sprite.l, FactorX.f, FactorY.f) As "_sfSprite_Scale"
    sfSprite_Rotate(Sprite.l, Angle.f) As "_sfSprite_Rotate"
    sfSprite_SetImage(Sprite.l, Image.l) As "_sfSprite_SetImage"
    sfSprite_SetSubRect(Sprite.l, *SubRect.sfIntRect) As "_sfSprite_SetSubRect"
    sfSprite_Resize(Sprite.l, Width.f, Height.f) As "_sfSprite_Resize"
    sfSprite_FlipX(Sprite.l, Flipped.sfBool) As "_sfSprite_FlipX"
    sfSprite_FlipY(Sprite.l, Flipped.sfBool) As "_sfSprite_FlipY"
    sfSprite_GetImage(Sprite.l) As "_sfSprite_GetImage"
    sfSprite_GetSubRect(Sprite.l) As "_sfSprite_GetSubRect"
    sfSprite_GetWidth.f(Sprite.l) As "_sfSprite_GetWidth"
    sfSprite_GetHeight.f(Sprite.l) As "_sfSprite_GetHeight"
    sfSprite_GetPixel(Sprite.l, X.l, Y.l) As "_sfSprite_GetPixel"
    sfFont_Create() As "_sfFont_Create"
    sfFont_CreateFromFile(Filename.s, CharSize.l, Charset.s) As "_sfFont_CreateFromFile"
    sfFont_CreateFromMemory(DataMem.l, SizeInBytes.l, CharSize.l, Charset.s) As "_sfFont_CreateFromMemory"
    sfFont_Destroy(Font.l) As "_sfFont_Destroy"
    sfFont_GetDefaultFont() As "_sfFont_GetDefaultFont"
    sfString_Create() As "_sfString_Create"
    sfString_Destroy(String.l) As "_sfString_Destroy"
    sfString_SetX(String.l, X.f) As "_sfString_SetX"
    sfString_SetY(String.l, Y.f) As "_sfString_SetY"
    sfString_SetPosition(String.l, Left.f, Top.f) As "_sfString_SetPosition"
    sfString_SetScaleX(String.l, Scale.f) As "_sfString_SetScaleX"
    sfString_SetScaleY(String.l, Scale.f) As "_sfString_SetScaleY"
    sfString_SetScale(String.l, ScaleX.f, ScaleY.f) As "_sfString_SetScale"
    sfString_SetRotation(String.l, Rotation.f) As "_sfString_SetRotation"
    sfString_SetCenter(String.l, X.f, Y.f) As "_sfString_SetCenter"
    sfString_SetColor(String.l, *Color.sfColor) As "_sfString_SetColor"
    sfString_SetBlendMode(String.l, Mode.l) As "_sfString_SetBlendMode"
    sfString_GetX.f(String.l) As "_sfString_GetX"
    sfString_GetY.f(String.l) As "_sfString_GetY"
    sfString_GetScaleX.f(String.l) As "_sfString_GetScaleX"
    sfString_GetScaleY.f(String.l) As "_sfString_GetScaleY"
    sfString_GetRotation.f(String.l) As "_sfString_GetRotation"
    sfString_GetCenterX.f(String.l) As "_sfString_GetCenterX"
    sfString_GetCenterY.f(String.l) As "_sfString_GetCenterY"
    sfString_GetColor(String.l) As "_sfString_GetColor"
    sfString_GetBlendMode(String.l) As "_sfString_GetBlendMode"
    sfString_Move(String.l, OffsetX.f, OffsetY.f) As "_sfString_Move"
    sfString_Scale(String.l, FactorX.f, FactorY.f) As "_sfString_Scale"
    sfString_Rotate(String.l, Angle.f) As "_sfString_Rotate"
    sfString_SetText(String.l, Text.s) As "_sfString_SetText"
    sfString_SetUnicodeText(String.l, Text.p-unicode) As "_sfString_SetUnicodeText"
    sfString_SetFont(String.l, Font.l) As "_sfString_SetFont"
    sfString_SetSize(String.l, Size.f) As "_sfString_SetSize"
    sfString_SetStyle(String.l, Style.l) As "_sfString_SetStyle"
    sfString_GetUnicodeText(String.l) As "_sfString_GetUnicodeText"
    sfString_GetText(String.l) As "_sfString_GetText"
    sfString_GetFont(String.l) As "_sfString_GetFont"
    sfString_GetSize.f(String.l) As "_sfString_GetSize"
    sfString_GetStyle(String.l) As "_sfString_GetStyle"
    sfString_GetRect(String.l) As "_sfString_GetRect"
    sfRenderWindow_Create(Mode.l, Title.s, Style.l, *Params.sfWindowSettings) As "_sfRenderWindow_Create"
    sfRenderWindow_CreateFromHandle(Handle.l, *Params.sfWindowSettings) As "_sfRenderWindow_CreateFromHandle"
    sfRenderWindow_Destroy(RenderWindow.l) As "_sfRenderWindow_Destroy"
    sfRenderWindow_Close(RenderWindow.l) As "_sfRenderWindow_Close"
    sfRenderWindow_IsOpened.sfBool(RenderWindow.l) As "_sfRenderWindow_IsOpened"
    sfRenderWindow_GetWidth(RenderWindow.l) As "_sfRenderWindow_GetWidth"
    sfRenderWindow_GetHeight(RenderWindow.l) As "_sfRenderWindow_GetHeight"
    sfRenderWindow_GetSettings(RenderWindow.l) As "_sfRenderWindow_GetSettings"
    sfRenderWindow_GetEvent(RenderWindow.l, *Event.sfEvent) As "_sfRenderWindow_GetEvent"
    sfRenderWindow_UseVerticalSync(RenderWindow.l, Enabled.sfBool) As "_sfRenderWindow_UseVerticalSync"
    sfRenderWindow_ShowMouseCursor(RenderWindow.l, Show.sfBool) As "_sfRenderWindow_ShowMouseCursor"
    sfRenderWindow_SetCursorPosition(RenderWindow.l, Left.l, Top.l) As "_sfRenderWindow_SetCursorPosition"
    sfRenderWindow_SetPosition(RenderWindow.l, Left.l, Top.l) As "_sfRenderWindow_SetPosition"
    sfRenderWindow_Show(RenderWindow.l, State.sfBool) As "_sfRenderWindow_Show"
    sfRenderWindow_EnableKeyRepeat(RenderWindow.l, Enabled.sfBool) As "_sfRenderWindow_EnableKeyRepeat"
    sfRenderWindow_SetActive(RenderWindow.l, Active.sfBool) As "_sfRenderWindow_SetActive"
    sfRenderWindow_Display(RenderWindow.l) As "_sfRenderWindow_Display"
    sfRenderWindow_GetInput(RenderWindow.l) As "_sfRenderWindow_GetInput"
    sfRenderWindow_SetFramerateLimit(RenderWindow.l, Limit.l) As "_sfRenderWindow_SetFramerateLimit"
    sfRenderWindow_GetFrameTime.f(RenderWindow.l) As "_sfRenderWindow_GetFrameTime"
    sfRenderWindow_SetJoystickThreshold(RenderWindow.l, Threshold.f) As "_sfRenderWindow_SetJoystickThreshold"
    sfRenderWindow_DrawPostFX(RenderWindow.l, PostFX.l) As "_sfRenderWindow_DrawPostFX"
    sfRenderWindow_DrawSprite(RenderWindow.l, Sprite.l) As "_sfRenderWindow_DrawSprite"
    sfRenderWindow_DrawString(RenderWindow.l, String.l) As "_sfRenderWindow_DrawString"
    sfRenderWindow_DrawShape(RenderWindow.l, Shape.l) As "_sfRenderWindow_DrawShape"
    sfRenderWindow_Capture(RenderWindow.l) As "_sfRenderWindow_Capture"
    sfRenderWindow_SetBackgroundColor(RenderWindow.l, *Color.sfColor) As "_sfRenderWindow_SetBackgroundColor"
    sfRenderWindow_SetView(RenderWindow.l, View.l) As "_sfRenderWindow_SetView"
    sfRenderWindow_GetView(RenderWindow.l) As "_sfRenderWindow_GetView"
    sfRenderWindow_GetDefaultView(RenderWindow.l) As "_sfRenderWindow_GetDefaultView"
    sfRenderWindow_ConvertCoords(RenderWindow.l, WindowX.l, WindowY.l, *ViewX.f, *ViewY.f, *TargetView.l) As "_sfRenderWindow_ConvertCoords"
    sfRenderWindow_PreserveOpenGLStates(RenderWindow.l, Preserve.sfBool) As "_sfRenderWindow_PreserveOpenGLStates"
    sfView_Create() As "_sfView_Create"
    sfView_CreateFromRect(*Rect.sfFloatRect) As "_sfView_CreateFromRect"
    sfView_Destroy(View.l) As "_sfView_Destroy"
    sfView_SetCenter(View.l, X.f, Y.f) As "_sfView_SetCenter"
    sfView_SetHalfSize(View.l, HalfWidth.f, HalfHeight.f) As "_sfView_SetHalfSize"
    sfView_SetFromRect(View.l, *ViewRect.sfFloatRect) As "_sfView_SetFromRect"
    sfView_GetCenterX.f(View.l) As "_sfView_GetCenterX"
    sfView_GetCenterY.f(View.l) As "_sfView_GetCenterY"
    sfView_GetHalfSizeX.f(View.l) As "_sfView_GetHalfSizeX"
    sfView_GetHalfSizeY.f(View.l) As "_sfView_GetHalfSizeY"
    sfView_GetRect(View.l) As "_sfView_GetRect"
    sfView_Move(View.l, OffsetX.f, OffsetY.f) As "_sfView_Move"
    sfView_Zoom(View.l, Factor.f) As "_sfView_Zoom"
  EndImport
;}
;{ Network
  Import "csfml-network.lib"
    sfIPAddress_FromBytes(Byte0.c, Byte1.c, Byte2.c, Byte3.c) As "_sfIPAddress_FromBytes"
    sfIPAddress_FromString(String.s) As "_sfIPAddress_FromString"
    sfIPAddress_GetLocalAddress() As "_sfIPAddress_GetLocalAddress"
    sfIPAddress_GetPublicAddress() As "_sfIPAddress_GetPublicAddress"
    sfIPAddress_IsValid(*Address.sfIPAddress) As "_sfIPAddress_IsValid"
    sfIPAddress_LocalHost() As "_sfIPAddress_LocalHost"
    sfIPAddress_ToString(*Address.sfIPAddress, String.s) As "_sfIPAddress_ToString"
    sfPacket_Append(Packet.l, *DataMem, SizeInBytes.l) As "_sfPacket_Append"
    sfPacket_CanRead.sfBool(Packet.l) As "_sfPacket_CanRead"
    sfPacket_Clear(Packet.l) As "_sfPacket_Clear"
    sfPacket_Create() As "_sfPacket_Create"
    sfPacket_Destroy(Packet.l) As "_sfPacket_Destroy"
    sfPacket_GetData(Packet.l) As "_sfPacket_GetData"
    sfPacket_GetDataSize(Packet.l) As "_sfPacket_GetDataSize"
    sfPacket_ReadDouble.d(Packet.l) As "_sfPacket_ReadDouble"
    sfPacket_ReadFloat.f(Packet.l) As "_sfPacket_ReadFloat"
    sfPacket_ReadInt16.w(Packet.l) As "_sfPacket_ReadInt16"
    sfPacket_ReadInt32.l(Packet.l) As "_sfPacket_ReadInt32"
    sfPacket_ReadInt8.c(Packet.l) As "_sfPacket_ReadInt8"
    sfPacket_ReadString(Packet.l, *String.s) As "_sfPacket_ReadString"
    sfPacket_ReadUint16.w(Packet.l) As "_sfPacket_ReadUint16"
    sfPacket_ReadUint32.l(Packet.l) As "_sfPacket_ReadUint32"
    sfPacket_ReadUint8.c(Packet.l) As "_sfPacket_ReadUint8"
    sfPacket_ReadWideString(Packet.l, *String.p-unicode) As "_sfPacket_ReadWideString"
    sfPacket_WriteDouble(Packet.l, sfDouble.d) As "_sfPacket_WriteDouble"
    sfPacket_WriteFloat(Packet.l, sfFloat.f) As "_sfPacket_WriteFloat"
    sfPacket_WriteInt16(Packet.l, sfInt16.w) As "_sfPacket_WriteInt16"
    sfPacket_WriteInt32(Packet.l, sfInt32.l) As "_sfPacket_WriteInt32"
    sfPacket_WriteInt8(Packet.l, sfInt8.c) As "_sfPacket_WriteInt8"
    sfPacket_WriteString(Packet.l, sfString.s) As "_sfPacket_WriteString"
    sfPacket_WriteUint16(Packet.l, sfUInt16.w) As "_sfPacket_WriteUint16"
    sfPacket_WriteUint32(Packet.l, sfUInt32.l) As "_sfPacket_WriteUint32"
    sfPacket_WriteUint8(Packet.l, sfUInt8.c) As "_sfPacket_WriteUint8"
    sfPacket_WriteWideString(Packet.l, String.p-unicode) As "_sfPacket_WriteWideString"
    sfSelectorTCP_Add(Selector.l, Socket.l) As "_sfSelectorTCP_Add"
    sfSelectorTCP_Clear(Selector.l) As "_sfSelectorTCP_Clear"
    sfSelectorTCP_Create() As "_sfSelectorTCP_Create"
    sfSelectorTCP_Destroy(Selector.l) As "_sfSelectorTCP_Destroy"
    sfSelectorTCP_GetSocketReady(Selector.l, Index.l) As "_sfSelectorTCP_GetSocketReady"
    sfSelectorTCP_Remove(Selector.l, Socket.l) As "_sfSelectorTCP_Remove"
    sfSelectorTCP_Wait(Selector.l, Timeout.f) As "_sfSelectorTCP_Wait"
    sfSelectorUDP_Add(Selector.l, Socket.l) As "_sfSelectorUDP_Add"
    sfSelectorUDP_Clear(Selector.l) As "_sfSelectorUDP_Clear"
    sfSelectorUDP_Create() As "_sfSelectorUDP_Create"
    sfSelectorUDP_Destroy(Selector.l) As "_sfSelectorUDP_Destroy"
    sfSelectorUDP_GetSocketReady(Selector.l, Index.l) As "_sfSelectorUDP_GetSocketReady"
    sfSelectorUDP_Remove(Selector.l, Socket.l) As "_sfSelectorUDP_Remove"
    sfSelectorUDP_Wait(Selector.l, Timeout.f) As "_sfSelectorUDP_Wait"
    sfSocketTCP_Accept(Socket.l, *Connected, *HostAddress.sfIPAddress) As "_sfSocketTCP_Accept"
    sfSocketTCP_Connect(Socket.l, Port.l, *HostAddress.sfIPAddress) As "_sfSocketTCP_Connect"
    sfSocketTCP_Create() As "_sfSocketTCP_Create"
    sfSocketTCP_Destroy(Socket.l) As "_sfSocketTCP_Destroy"
    sfSocketTCP_IsValid(Socket.l) As "_sfSocketTCP_IsValid"
    sfSocketTCP_Listen(Socket.l, Port.l) As "_sfSocketTCP_Listen"
    sfSocketTCP_Receive(Socket.l, DataMem.s, MaxSize.l, SizeReceived.l) As "_sfSocketTCP_Receive"
    sfSocketTCP_ReceivePacket(Socket.l, Packet.l) As "_sfSocketTCP_ReceivePacket"
    sfSocketTCP_Send(Socket.l, DataMem.s, Size.l) As "_sfSocketTCP_Send"
    sfSocketTCP_SendPacket(Socket.l, Packet.l) As "_sfSocketTCP_SendPacket"
    sfSocketUDP_Bind(Socket.l, Port.l) As "_sfSocketUDP_Bind"
    sfSocketUDP_Create() As "_sfSocketUDP_Create"
    sfSocketUDP_Destroy(Socket.l) As "_sfSocketUDP_Destroy"
    sfSocketUDP_IsValid(Socket.l) As "_sfSocketUDP_IsValid"
    sfSocketUDP_Receive(Socket.l, DataMem.l, MaxSize.l, *Received, *Address.sfIPAddress) As "_sfSocketUDP_Receive"
    sfSocketUDP_ReceivePacket(Socket.l, Packet.l, *Address.sfIPAddress) As "_sfSocketUDP_ReceivePacket"
    sfSocketUDP_Send(Socket.l, DataMem.l, Size.l, *Address.sfIPAddress, Port.l) As "_sfSocketUDP_Send"
    sfSocketUDP_SendPacket(Socket.l, Packet.l, *Address.sfIPAddress, Port.l) As "_sfSocketUDP_SendPacket"
    sfSocketUDP_Unbind(Socket.l) As "_sfSocketUDP_Unbind"
  EndImport
;}
;{ System
  Import "csfml-system.lib"
    sfClock_Create() As "_sfClock_Create"
    sfClock_Destroy(Clock.l) As "_sfClock_Destroy"
    sfClock_GetTime.f(Clock.l) As "_sfClock_GetTime"
    sfClock_Reset(Clock.l) As "_sfClock_Reset"
    sfMutex_Create() As "_sfMutex_Create"
    sfMutex_Destroy(Mutex.l) As "_sfMutex_Destroy"
    sfMutex_Lock(Mutex.l) As "_sfMutex_Lock"
    sfMutex_Unlock(Mutex.l) As "_sfMutex_Unlock"
    sfRandom_SetSeed(Seed.l) As "_sfRandom_SetSeed"
    sfRandom_GetSeed() As "_sfRandom_GetSeed"
    sfRandom_Float.f(Begin.f, End_.f) As "_sfRandom_Float"
    sfRandom_Int(Begin.l, End_.l) As "_sfRandom_Int"
    sfSleep(Duration.f) As "_sfSleep"
    sfThread_Create(*fn, *UserData) As "_sfThread_Create"
    sfThread_Destroy(Thread.l) As "_sfThread_Destroy"
    sfThread_Launch(Thread.l) As "_sfThread_Launch"
    sfThread_Wait(Thread.l) As "_sfThread_Wait"
    sfThread_Terminate(Thread.l) As "_sfThread_Terminate"
  EndImport
;}
;{ Window
  Import "csfml-window.lib"
    sfInput_IsKeyDown(Input.l, KeyCode.l) As "_sfInput_IsKeyDown"
    sfInput_IsMouseButtonDown(Input.l, Button.l) As "_sfInput_IsMouseButtonDown"
    sfInput_IsJoystickButtonDown(Input.l, JoyId.l, Button.l) As "_sfInput_IsJoystickButtonDown"
    sfInput_GetMouseX(Input.l) As "_sfInput_GetMouseX"
    sfInput_GetMouseY(Input.l) As "_sfInput_GetMouseY"
    sfInput_GetJoystickAxis(Input.l, JoyId.l, Axis.l) As "_sfInput_GetJoystickAxis"
    sfVideoMode_GetDesktopMode() As "_sfVideoMode_GetDesktopMode"
    sfVideoMode_GetMode(Index.l) As "_sfVideoMode_GetMode"
    sfVideoMode_GetModesCount() As "_sfVideoMode_GetModesCount"
    sfVideoMode_IsValid.sfBool(Mode.l) As "_sfVideoMode_IsValid"
    sfWindow_Create(Mode.l, Title.s, Style.l, *Params.sfWindowSettings) As "_sfWindow_Create"
    sfWindow_CreateFromHandle(Handle.l, *Params.sfWindowSettings) As "_sfWindow_CreateFromHandle"
    sfWindow_Close(Window.l) As "_sfWindow_Close"
    sfWindow_IsOpened(Window.l) As "_sfWindow_IsOpened"
    sfWindow_Destroy(Window.l) As "_sfWindow_Destroy"
    sfWindow_GetWidth(Window.l) As "_sfWindow_GetWidth"
    sfWindow_GetHeight(Window.l) As "_sfWindow_GetHeight"
    sfWindow_GetSettings(Window.l) As "_sfWindow_GetSettings"
    sfWindow_GetEvent.sfBool(Window.l, *Event.sfEvent) As "_sfWindow_GetEvent"
    sfWindow_UseVerticalSync(Window.l, Enabled.sfBool) As "_sfWindow_UseVerticalSync"
    sfWindow_ShowMouseCursor(Window.l, Show.sfBool) As "_sfWindow_ShowMouseCursor"
    sfWindow_SetCursorPosition(Window.l, Left.l, Top.l) As "_sfWindow_SetCursorPosition"
    sfWindow_SetPosition(Window.l, Left.l, Top.l) As "_sfWindow_SetPosition"
    sfWindow_Show(Window.l, State.sfBool) As "_sfWindow_Show"
    sfWindow_EnableKeyRepeat(Window.l, Enabled.sfBool) As "_sfWindow_EnableKeyRepeat"
    sfWindow_SetActive(Window.l, Active.sfBool) As "_sfWindow_SetActive"
    sfWindow_Display(Window.l) As "_sfWindow_Display"
    sfWindow_GetInput(Window.l) As "_sfWindow_GetInput"
    sfWindow_SetFramerateLimit(Window.l, Limit.l) As "_sfWindow_SetFramerateLimit"
    sfWindow_GetFrameTime.f(Window.l) As "_sfWindow_GetFrameTime"
    sfWindow_SetJoystickThreshold(Window.l, Threshold.f) As "_sfWindow_SetJoystickThreshold"
  EndImport
;}

; IDE Options = PureBasic 4.20 (Windows - x86)
; CursorPosition = 270
; FirstLine = 177
; Folding = d0
; EnableUnicode