XIncludeFile "RW_LibPNG_Res.pb"
CompilerSelect #PB_Compiler_OS
  CompilerCase #PB_OS_Windows 
  ;{
    #gLibPNG_Filename = "libpng.lib"
    #gLibPNG_SymbolSys = "_"
  ;}
  CompilerCase #PB_OS_Linux
  ;{
    #gLibPNG_Filename = "/usr/lib/libpng12.so"
    #gLibPNG_SymbolSys = ""
  ;}
CompilerEndSelect


ImportC #gLibPNG_Filename
  DllGetVersion() As #gLibPNG_SymbolSys + "DllGetVersion"
  png_access_version_number() As #gLibPNG_SymbolSys + "png_access_version_number"
  png_build_grayscale_palette(bit_depth.l, palette.l) As #gLibPNG_SymbolSys + "png_build_grayscale_palette"
  png_check_sig(sig.l, num.l) As #gLibPNG_SymbolSys + "png_check_sig"
  png_chunk_error(png_ptr.l, error.l) As #gLibPNG_SymbolSys + "png_chunk_error"
  png_chunk_warning(png_ptr.l, message.l) As #gLibPNG_SymbolSys + "png_chunk_warning"
  png_convert_from_struct_tm(ptime.l, ttime.l) As #gLibPNG_SymbolSys + "png_convert_from_struct_tm"
  png_convert_from_time_t(ptime.l, ttime.l) As #gLibPNG_SymbolSys + "png_convert_from_time_t"
  png_convert_to_rfc1123(png_ptr.l, ptime.l) As #gLibPNG_SymbolSys + "png_convert_to_rfc1123"
  png_create_info_struct(png_ptr.l) As #gLibPNG_SymbolSys + "png_create_info_struct"
  png_create_read_struct(user_png_ver.l, error_ptr.l, error_fn.l, warn_f.l) As #gLibPNG_SymbolSys + "png_create_read_struct"
  png_create_read_struct_2(user_png_ver.l, error_ptr.l, error_fn.l, warn_f.l, mem_ptr.l, malloc_fn.l, free_fn.l) As #gLibPNG_SymbolSys + "png_create_read_struct_2"
  png_create_write_struct(user_png_ver.l, error_ptr.l, error_fn.l, warn_f.l) As #gLibPNG_SymbolSys + "png_create_write_struct"
  png_create_write_struct_2(user_png_ver.l, error_ptr.l, error_fn.l, warn_f.l, mem_ptr.l, malloc_fn.l, free_fn.l) As #gLibPNG_SymbolSys + "png_create_write_struct_2"
  png_data_freer(png_ptr.l, info_ptr.l, freer.l, mask.l) As #gLibPNG_SymbolSys + "png_data_freer"
  png_destroy_info_struct(png_ptr.l, info_ptr_ptr.l) As #gLibPNG_SymbolSys + "png_destroy_info_struct"
  png_destroy_read_struct(png_ptr_ptr.l, info_ptr_ptr.l, end_info_ptr_ptr.l) As #gLibPNG_SymbolSys + "png_destroy_read_struct"
  png_destroy_write_struct(png_ptr_ptr.l, info_ptr_ptr.l) As #gLibPNG_SymbolSys + "png_destroy_write_struct"
  png_error(png_ptr.l, error.l) As #gLibPNG_SymbolSys + "png_error"
  png_free(png_ptr.l, ptr.l) As #gLibPNG_SymbolSys + "png_free"
  png_free_data(png_ptr.l, info_ptr.l, num.l) As #gLibPNG_SymbolSys + "png_free_data"
  png_free_default(png_ptr.l, ptr.l) As #gLibPNG_SymbolSys + "png_free_default"
  png_get_IHDR(png_ptr.l, info_ptr.l, width.l, height.l, bit_depth.l, color_type.l, interlace_type.l, compression_type.l, filter_type.l) As #gLibPNG_SymbolSys + "png_get_IHDR"
  png_get_PLTE(png_ptr.l, info_ptr.l, palette.l, num_palette.l) As #gLibPNG_SymbolSys + "png_get_PLTE"
  png_get_asm_flagmask(mask.l) As #gLibPNG_SymbolSys + "png_get_asm_flagmask"
  png_get_asm_flags(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_asm_flags"
  png_get_bKGD(png_ptr.l, info_ptr.l, background.l) As #gLibPNG_SymbolSys + "png_get_bKGD"
  png_get_bit_depth(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_bit_depth"
  png_get_cHRM(png_ptr.l, info_ptr.l, white_x.d, white_y.d, red_x.d, red_y.d, green_x.d, green_y.d, blue_x.d, blue_y.d) As #gLibPNG_SymbolSys + "png_get_cHRM"
  png_get_cHRM_fixed(png_ptr.l, info_ptr.l, white_x.l, white_y.l, red_x.l, red_y.l, green_x.l, green_y.l, blue_x.l, blue_y.l) As #gLibPNG_SymbolSys + "png_get_cHRM_fixed"
  png_get_channels(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_channels"
  png_get_color_type(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_color_type"
  png_get_compression_buffer_size(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_compression_buffer_size"
  png_get_compression_type(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_compression_type"
  png_get_copyright(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_copyright"
  png_get_error_ptr(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_error_ptr"
  png_get_filter_type(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_filter_type"
  png_get_gAMA(png_ptr.l, info_ptr.l, file_gamma.d) As #gLibPNG_SymbolSys + "png_get_gAMA"
  png_get_gAMA_fixed(png_ptr.l, info_ptr.l, int_file_gamma.l) As #gLibPNG_SymbolSys + "png_get_gAMA_fixed"
  png_get_hIST(png_ptr.l, info_ptr.l, hist.l) As #gLibPNG_SymbolSys + "png_get_hIST"
  png_get_header_ver(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_header_ver"
  png_get_header_version(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_header_version"
  png_get_iCCP(png_ptr.l, info_ptr.l, name.l, compression_type.l, profile.l, proflen.l) As #gLibPNG_SymbolSys + "png_get_iCCP"
  png_get_image_height(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_image_height"
  png_get_image_width(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_image_width"
  png_get_int_32(buf.l) As #gLibPNG_SymbolSys + "png_get_int_32"
  png_get_interlace_type(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_interlace_type"
  png_get_io_ptr(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_io_ptr"
  png_get_libpng_ver(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_libpng_ver"
  png_get_mem_ptr(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_mem_ptr"
  png_get_mmx_bitdepth_threshold(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_mmx_bitdepth_threshold"
  png_get_mmx_flagmask(flag_select.l, compilerID.l) As #gLibPNG_SymbolSys + "png_get_mmx_flagmask"
  png_get_mmx_rowbytes_threshold(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_mmx_rowbytes_threshold"
  png_get_oFFs(png_ptr.l, info_ptr.l, offset_x.l, offset_y.l, unit_type.l) As #gLibPNG_SymbolSys + "png_get_oFFs"
  png_get_pCAL(png_ptr.l, info_ptr.l, purpose.l, X0.l, X1.l, type.l, nparams.l, units.l, params.l) As #gLibPNG_SymbolSys + "png_get_pCAL"
  png_get_pHYs(png_ptr.l, info_ptr.l, res_x.l, res_y.l, unit_type.l) As #gLibPNG_SymbolSys + "png_get_pHYs"
  png_get_pixel_aspect_ratio(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_pixel_aspect_ratio"
  png_get_pixels_per_meter(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_pixels_per_meter"
  png_get_progressive_ptr(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_progressive_ptr"
  png_get_rgb_to_gray_status(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_rgb_to_gray_status"
  png_get_rowbytes(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_rowbytes"
  png_get_rows(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_rows"
  png_get_sBIT(png_ptr.l, info_ptr.l, sig_bit.l) As #gLibPNG_SymbolSys + "png_get_sBIT"
  png_get_sCAL(png_ptr.l, info_ptr.l, unit.l, width.l, height.l) As #gLibPNG_SymbolSys + "png_get_sCAL"
  png_get_sPLT(png_ptr.l, info_ptr.l, splt_ptr.l) As #gLibPNG_SymbolSys + "png_get_sPLT"
  png_get_sRGB(png_ptr.l, info_ptr.l, intent.l) As #gLibPNG_SymbolSys + "png_get_sRGB"
  png_get_signature(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_signature"
  png_get_tIME(png_ptr.l, info_ptr.l, mod_time.l) As #gLibPNG_SymbolSys + "png_get_tIME"
  png_get_tRNS(png_ptr.l, info_ptr.l, trans.l, num_trans.l, trans_values.l) As #gLibPNG_SymbolSys + "png_get_tRNS"
  png_get_text(png_ptr.l, info_ptr.l, text_ptr.l, num_text.l) As #gLibPNG_SymbolSys + "png_get_text"
  png_get_uint_16(buf.l) As #gLibPNG_SymbolSys + "png_get_uint_16"
  png_get_uint_31(buf.l) As #gLibPNG_SymbolSys + "png_get_uint_31"
  png_get_uint_32(buf.l) As #gLibPNG_SymbolSys + "png_get_uint_32"
  png_get_unknown_chunks(png_ptr.l, info_ptr.l, unknows.l) As #gLibPNG_SymbolSys + "png_get_unknown_chunks"
  png_get_user_chunk_ptr(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_user_chunk_ptr"
  png_get_user_height_max(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_user_height_max"
  png_get_user_transform_ptr(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_user_transform_ptr"
  png_get_user_width_max(png_ptr.l) As #gLibPNG_SymbolSys + "png_get_user_width_max"
  png_get_valid(png_ptr.l, info_ptr.l, flag.l) As #gLibPNG_SymbolSys + "png_get_valid"
  png_get_x_offset_microns(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_x_offset_microns"
  png_get_x_offset_pixels(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_x_offset_pixels"
  png_get_x_pixels_per_meter(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_x_pixels_per_meter"
  png_get_y_offset_microns(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_y_offset_microns"
  png_get_y_offset_pixels(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_y_offset_pixels"
  png_get_y_pixels_per_meter(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_get_y_pixels_per_meter"
  png_handle_as_unknown(png_ptr.l, chunk_name.l) As #gLibPNG_SymbolSys + "png_handle_as_unknown"
  png_info_init(info_ptr.l) As #gLibPNG_SymbolSys + "png_info_init"
  png_info_init_3(ptr_ptr.l, png_info_struct_size.l) As #gLibPNG_SymbolSys + "png_info_init_3"
  png_init_io(png_ptr.l, fp.l) As #gLibPNG_SymbolSys + "png_init_io"
  png_malloc(png_ptr.l, size.l) As #gLibPNG_SymbolSys + "png_malloc"
  png_malloc_default(png_ptr.l, size.l) As #gLibPNG_SymbolSys + "png_malloc_default"
  png_malloc_warn(png_ptr.l, length.l) As #gLibPNG_SymbolSys + "png_malloc_warn"
  png_memcpy_check(s1.l, s2.l, size.l) As #gLibPNG_SymbolSys + "png_memcpy_check"
  png_memset_check(png_ptr.l, s1.l, value.l, size.l) As #gLibPNG_SymbolSys + "png_memset_check"
  png_mmx_support() As #gLibPNG_SymbolSys + "png_mmx_support"
  png_permit_empty_plte(png_ptr.l, empty_plte_permitted.l) As #gLibPNG_SymbolSys + "png_permit_empty_plte"
  png_permit_mng_features(png_ptr.l, mask.l) As #gLibPNG_SymbolSys + "png_permit_mng_features"
  png_process_data(png_ptr.l, info_ptr.l, buffer.l, t_buffer_size.l) As #gLibPNG_SymbolSys + "png_process_data"
  png_progressive_combine_row(png_ptr.l, old_row.l, new_row.l) As #gLibPNG_SymbolSys + "png_progressive_combine_row"
  png_read_destroy(png_ptr.l, info_ptr.l, end_info_ptr.l) As #gLibPNG_SymbolSys + "png_read_destroy"
  png_read_end(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_read_end"
  png_read_image(png_ptr.l, image.l) As #gLibPNG_SymbolSys + "png_read_image"
  png_read_info(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_read_info"
  png_read_init(png_ptr.l) As #gLibPNG_SymbolSys + "png_read_init"
  png_read_init_2(png_ptr.l, user_png_ver.l, png_struct_size.l, png_info_size.l) As #gLibPNG_SymbolSys + "png_read_init_2"
  png_read_init_3(ptr_ptr.l, user_png_ver.l, png_struct_size.l) As #gLibPNG_SymbolSys + "png_read_init_3"
  png_read_png(png_ptr.l, info_ptr.l, transforms.l, params.l) As #gLibPNG_SymbolSys + "png_read_png"
  png_read_row(png_ptr.l, row.l, display_row.l) As #gLibPNG_SymbolSys + "png_read_row"
  png_read_rows(png_ptr.l, row.l, display_row.l, num_rows.l) As #gLibPNG_SymbolSys + "png_read_rows"
  png_read_update_info(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_read_update_info"
  png_reset_zstream(png_ptr.l) As #gLibPNG_SymbolSys + "png_reset_zstream"
  png_save_int_32(buf.l, i.l) As #gLibPNG_SymbolSys + "png_save_int_32"
  png_save_uint_16(buf.l, i.l) As #gLibPNG_SymbolSys + "png_save_uint_16"
  png_save_uint_32(buf.l, i.l) As #gLibPNG_SymbolSys + "png_save_uint_32"
  png_set_IHDR(png_ptr.l, info_ptr.l, width.l, height.l, bit_depth.l, color_type.l, interlace_type.l, compression_type.l, filter_type.l) As #gLibPNG_SymbolSys + "png_set_IHDR"
  png_set_PLTE(png_ptr.l, info_ptr.l, palette.l, num_palette.l) As #gLibPNG_SymbolSys + "png_set_PLTE"
  png_set_add_alpha(png_ptr.l, filler.l, flags.l) As #gLibPNG_SymbolSys + "png_set_add_alpha"
  png_set_asm_flags(png_ptr.l, asm_flags.l) As #gLibPNG_SymbolSys + "png_set_asm_flags"
  png_set_bKGD(png_ptr.l, info_ptr.l, background.l) As #gLibPNG_SymbolSys + "png_set_bKGD"
  png_set_background(png_ptr.l, background_color.l, background_gamma_code.l, need_expand.l, background_gamma.d) As #gLibPNG_SymbolSys + "png_set_background"
  png_set_bgr(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_bgr"
  png_set_cHRM(png_ptr.l, info_ptr.l, white_x.d, white_y.d, red_x.d, red_y.d, green_x.d, green_y.d, blue_x.d, blue_y.d) As #gLibPNG_SymbolSys + "png_set_cHRM"
  png_set_cHRM_fixed(png_ptr.l, info_ptr.l, white_x.l, white_y.l, red_x.l, red_y.l, green_x.l, green_y.l, blue_x.l, blue_y.l) As #gLibPNG_SymbolSys + "png_set_cHRM_fixed"
  png_set_compression_buffer_size(png_ptr.l, size.l) As #gLibPNG_SymbolSys + "png_set_compression_buffer_size"
  png_set_compression_level(png_ptr.l, level.l) As #gLibPNG_SymbolSys + "png_set_compression_level"
  png_set_compression_mem_level(png_ptr.l, mem_level.l) As #gLibPNG_SymbolSys + "png_set_compression_mem_level"
  png_set_compression_method(png_ptr.l, method.l) As #gLibPNG_SymbolSys + "png_set_compression_method"
  png_set_compression_strategy(png_ptr.l, strategy.l) As #gLibPNG_SymbolSys + "png_set_compression_strategy"
  png_set_compression_window_bits(png_ptr.l, window_bits.l) As #gLibPNG_SymbolSys + "png_set_compression_window_bits"
  png_set_crc_action(png_ptr.l, crit_action.l, ancil_action.l) As #gLibPNG_SymbolSys + "png_set_crc_action"
  png_set_dither(png_ptr.l, palette.l, num_palette.l, maximum_colors.l, histogram.l, full_dither.l) As #gLibPNG_SymbolSys + "png_set_dither"
  png_set_error_fn(png_ptr.l, error_ptr.l, error_fn.l, warning_fn.l) As #gLibPNG_SymbolSys + "png_set_error_fn"
  png_set_expand(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_expand"
  png_set_expand_gray_1_2_4_to_8(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_expand_gray_1_2_4_to_8"
  png_set_filler(png_ptr.l, filler.l, flags.l) As #gLibPNG_SymbolSys + "png_set_filler"
  png_set_filter(png_ptr.l, method.l, filters.l) As #gLibPNG_SymbolSys + "png_set_filter"
  png_set_filter_heuristics(png_ptr.l, heuristic_method.l, num_weights.l, flter_weights.l, filter_costs.l) As #gLibPNG_SymbolSys + "png_set_filter_heuristics"
  png_set_flush(png_ptr.l, nrows.l) As #gLibPNG_SymbolSys + "png_set_flush"
  png_set_gAMA(png_ptr.l, info_ptr.l, file_gamma.d) As #gLibPNG_SymbolSys + "png_set_gAMA"
  png_set_gAMA_fixed(png_ptr.l, info_ptr.l, file_gamma.l) As #gLibPNG_SymbolSys + "png_set_gAMA_fixed"
  png_set_gamma(png_ptr.l, screen_gamma.d, default_file_gamma.d) As #gLibPNG_SymbolSys + "png_set_gamma"
  png_set_gray_1_2_4_to_8(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_gray_1_2_4_to_8"
  png_set_gray_to_rgb(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_gray_to_rgb"
  png_set_hIST(png_ptr.l, info_ptr.l, hist.l) As #gLibPNG_SymbolSys + "png_set_hIST"
  png_set_iCCP(png_ptr.l, info_ptr.l, name.l, compression_type.l, profile.l, proflen.l) As #gLibPNG_SymbolSys + "png_set_iCCP"
  png_set_interlace_handling(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_interlace_handling"
  png_set_invalid(png_ptr.l, info_ptr.l, mask.l) As #gLibPNG_SymbolSys + "png_set_invalid"
  png_set_invert_alpha(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_invert_alpha"
  png_set_invert_mono(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_invert_mono"
  png_set_keep_unknown_chunks(png_ptr.l, keep.l, chunk_list.l, num_chunks.l) As #gLibPNG_SymbolSys + "png_set_keep_unknown_chunks"
  png_set_mem_fn(png_ptr.l, mem_ptr.l, malloc_fn.l, free_fn.l) As #gLibPNG_SymbolSys + "png_set_mem_fn"
  png_set_mmx_thresholds(png_ptr.l, mmx_bitdepth_threshold.l, mmx_rowbytes_threshold.l) As #gLibPNG_SymbolSys + "png_set_mmx_thresholds"
  png_set_oFFs(png_ptr.l, info_ptr.l, offset_x.l, offset_y.l, unit_type.l) As #gLibPNG_SymbolSys + "png_set_oFFs"
  png_set_pCAL(png_ptr.l, info_ptr.l, purpose.l, X0.l, X1.l, type.l, nparams.l, units.l, params.l) As #gLibPNG_SymbolSys + "png_set_pCAL"
  png_set_pHYs(png_ptr.l, info_ptr.l, res_x.l, res_y.l, unit_type.l) As #gLibPNG_SymbolSys + "png_set_pHYs"
  png_set_packing(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_packing"
  png_set_packswap(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_packswap"
  png_set_palette_to_rgb(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_palette_to_rgb"
  png_set_progressive_read_fn(png_ptr.l, progressive_ptr.l, info_fn.l, row_fn.l, end_fn.l) As #gLibPNG_SymbolSys + "png_set_progressive_read_fn"
  png_set_read_fn(png_ptr.l, io_ptr.l, read_data_fn.l) As #gLibPNG_SymbolSys + "png_set_read_fn"
  png_set_read_status_fn(png_ptr.l, read_row_fn.l) As #gLibPNG_SymbolSys + "png_set_read_status_fn"
  png_set_read_user_chunk_fn(png_ptr.l, user_chunk_ptr.l, read_user_chunk_fn.l) As #gLibPNG_SymbolSys + "png_set_read_user_chunk_fn"
  png_set_read_user_transform_fn(png_ptr.l, read_user_transform_fn.l) As #gLibPNG_SymbolSys + "png_set_read_user_transform_fn"
  png_set_rgb_to_gray(png_ptr.l, error_action.l, red.d, green.d) As #gLibPNG_SymbolSys + "png_set_rgb_to_gray"
  png_set_rgb_to_gray_fixed(png_ptr.l, error_action.l, red.l, green.l) As #gLibPNG_SymbolSys + "png_set_rgb_to_gray_fixed"
  png_set_rows(png_ptr.l, info_ptr.l, row_pointers.l) As #gLibPNG_SymbolSys + "png_set_rows"
  png_set_sBIT(png_ptr.l, info_ptr.l, sig_bit.l) As #gLibPNG_SymbolSys + "png_set_sBIT"
  png_set_sCAL(png_ptr.l, info_ptr.l, unit.l, width.d, height.d) As #gLibPNG_SymbolSys + "png_set_sCAL"
  png_set_sPLT(png_ptr.l, info_ptr.l, splt_ptr.l, num_palettes.l) As #gLibPNG_SymbolSys + "png_set_sPLT"
  png_set_sRGB(png_ptr.l, info_ptr.l, intent.l) As #gLibPNG_SymbolSys + "png_set_sRGB"
  png_set_sRGB_gAMA_and_cHRM(png_ptr.l, info_ptr.l, intent.l) As #gLibPNG_SymbolSys + "png_set_sRGB_gAMA_and_cHRM"
  png_set_shift(png_ptr.l, true_bits.l) As #gLibPNG_SymbolSys + "png_set_shift"
  png_set_sig_bytes(png_ptr.l, number.l) As #gLibPNG_SymbolSys + "png_set_sig_bytes"
  png_set_strip_16(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_strip_16"
  png_set_strip_alpha(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_strip_alpha"
  png_set_strip_error_numbers(png_ptr.l, strip_mode.l) As #gLibPNG_SymbolSys + "png_set_strip_error_numbers"
  png_set_swap(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_swap"
  png_set_swap_alpha(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_swap_alpha"
  png_set_tIME(png_ptr.l, info_ptr.l, mod_time.l) As #gLibPNG_SymbolSys + "png_set_tIME"
  png_set_tRNS(png_ptr.l, info_ptr.l, trans.l, num_trans.l, trans_values.l) As #gLibPNG_SymbolSys + "png_set_tRNS"
  png_set_tRNS_to_alpha(png_ptr.l) As #gLibPNG_SymbolSys + "png_set_tRNS_to_alpha"
  png_set_text(png_ptr.l, info_ptr.l, text_ptr.l, num_text.l) As #gLibPNG_SymbolSys + "png_set_text"
  png_set_unknown_chunk_location(png_ptr.l, info_ptr.l, unknows.l, nums.l, location.l) As #gLibPNG_SymbolSys + "png_set_unknown_chunk_location"
  png_set_unknown_chunks(png_ptr.l, info_ptr.l, chunk.l, location.l) As #gLibPNG_SymbolSys + "png_set_unknown_chunks"
  png_set_user_limits(png_ptr.l, user_width_max.l, user_height_max.l) As #gLibPNG_SymbolSys + "png_set_user_limits"
  png_set_user_transform_info(png_ptr.l, user_transform_ptr.l, user_transform_depth.l, user_transform_channels.l) As #gLibPNG_SymbolSys + "png_set_user_transform_info"
  png_set_write_fn(png_ptr.l, io_ptr.l, write_data_fn.l, output_flash_fn.l) As #gLibPNG_SymbolSys + "png_set_write_fn"
  png_set_write_status_fn(png_ptr.l, write_row_fn.l) As #gLibPNG_SymbolSys + "png_set_write_status_fn"
  png_set_write_user_transform_fn(png_ptr.l, write_user_transform_fn.l) As #gLibPNG_SymbolSys + "png_set_write_user_transform_fn"
  png_sig_cmp(sig.l, start.l, num_to_check) As #gLibPNG_SymbolSys + "png_sig_cmp"
  png_start_read_image(png_ptr.l) As #gLibPNG_SymbolSys + "png_start_read_image"
  png_warning(png_ptr.l, message.l) As #gLibPNG_SymbolSys + "png_warning"
  png_write_chunk(png_ptr.l, chunk_name.l, data_.l, length.l) As #gLibPNG_SymbolSys + "png_write_chunk"
  png_write_chunk_data(png_ptr.l, data_.l, length.l) As #gLibPNG_SymbolSys + "png_write_chunk_data"
  png_write_chunk_end(png_ptr.l) As #gLibPNG_SymbolSys + "png_write_chunk_end"
  png_write_chunk_start(png_ptr.l, chunk_name.l, length.l) As #gLibPNG_SymbolSys + "png_write_chunk_start"
  png_write_destroy(png_ptr.l) As #gLibPNG_SymbolSys + "png_write_destroy"
  png_write_end(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_write_end"
  png_write_flush(png_ptr.l) As #gLibPNG_SymbolSys + "png_write_flush"
  png_write_image(png_ptr.l, image.l) As #gLibPNG_SymbolSys + "png_write_image"
  png_write_info(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_write_info"
  png_write_info_before_PLTE(png_ptr.l, info_ptr.l) As #gLibPNG_SymbolSys + "png_write_info_before_PLTE"
  png_write_init(png_ptr.l) As #gLibPNG_SymbolSys + "png_write_init"
  png_write_init_2(ptr_ptr.l, user_png_ver.l, png_struct_size.l, png_info_size.l) As #gLibPNG_SymbolSys + "png_write_init_2"
  png_write_init_3(ptr_ptr.l, user_png_ver.l, png_struct_size.l) As #gLibPNG_SymbolSys + "png_write_init_3"
  png_write_png(png_ptr.l, info_ptr.l, transforms.l, params.l) As #gLibPNG_SymbolSys + "png_write_png"
  png_write_row(png_ptr.l, row.l) As #gLibPNG_SymbolSys + "png_write_row"
  png_write_rows(png_ptr.l, row.l, num_rows.l) As #gLibPNG_SymbolSys + "png_write_rows"
EndImport

Debug png_access_version_number()