XIncludeFile "RW_FMod_Res.pb"
ImportC "fmodex_vc.lib"
  ;-FMOD global system functions (optional).
  FMOD_Memory_Initialize(*poolmem, poollen.l, *useralloc, *userrealloc, *userfree) As "_FMOD_Memory_Initialize@20"
  FMOD_Memory_GetStats(*currentalloced.l, *maxalloced.l) As "_FMOD_Memory_GetStats@8"
  FMOD_Debug_SetLevel(level.FMOD_DEBUGLEVEL) As "_FMOD_Debug_SetLevel@4"
  FMOD_Debug_GetLevel(*level.FMOD_DEBUGLEVEL) As "_FMOD_Debug_GetLevel@4"
  FMOD_File_SetDiskBusy(busy.l) As "_FMOD_File_SetDiskBusy@4"
  FMOD_File_GetDiskBusy(*busy.l) As "_FMOD_File_GetDiskBusy@4"
  ;-FMOD System factory functions.  Use this to create an FMOD System Instance.  below you will see FMOD_System_Init/Close to get started.
  FMOD_System_Create(*system) As "_FMOD_System_Create@4"
  FMOD_System_Release(system.l) As "_FMOD_System_Release@4"
  ;------>'System' API
  ;-Pre-init functions.
  FMOD_System_SetOutput(system.l, output.l) As "_FMOD_System_SetOutput@8"
  FMOD_System_GetOutput(system.l, *output.l) As "_FMOD_System_GetOutput@8"
  FMOD_System_GetNumDrivers(system.l, *numdrivers.l) As "_FMOD_System_GetNumDrivers@8"
  FMOD_System_GetDriverInfo(system.l, id.l, *name.s, *namelen.l, *guid.FMOD_GUID) As "_FMOD_System_GetDriverInfo@20"
  FMOD_System_GetDriverCaps(system.l, id.l, *caps.FMOD_CAPS, *minfrequency.l, *maxfrequency.l, *controlpanelspeakermode.l) As "_FMOD_System_GetDriverCaps@24"
  FMOD_System_SetDriver(system.l, driver.l) As "_FMOD_System_SetDriver@8"
  FMOD_System_GetDriver(system.l, *driver.l) As "_FMOD_System_GetDriver@8"
  FMOD_System_SetHardwareChannels(system.l, min2d.l, max2d.l, min3d.l, max3d.l) As "_FMOD_System_SetHardwareChannels@20"
  FMOD_System_SetSoftwareChannels(system.l, numsoftwarechannels.l) As "_FMOD_System_SetSoftwareChannels@8"
  FMOD_System_GetSoftwareChannels(system.l, *numsoftwarechannels.l) As "_FMOD_System_GetSoftwareChannels@8"
  FMOD_System_SetSoftwareFormat(system.l, samplerate.l, format.FMOD_SOUND_FORMAT, numoutputchannels.l, maxinputchannels.l, resamplemethod.l) As "_FMOD_System_SetSoftwareFormat@24"
  FMOD_System_GetSoftwareFormat(system.l, *samplerate.l, *format.FMOD_SOUND_FORMAT, *numoutputchannels.l, *maxinputchannels.l, *resamplemethod.l, *bits.l) As "_FMOD_System_GetSoftwareFormat@28"
  FMOD_System_SetDSPBufferSize(system.l, bufferlength.l, numbuffers.l) As "_FMOD_System_SetDSPBufferSize@12"
  FMOD_System_GetDSPBufferSize(system.l, *bufferlength.l, *numbuffers.l) As "_FMOD_System_GetDSPBufferSize@12"
  FMOD_System_SetFileSystem(system.l, *useropen, *userclose, *userread, *userseek, blockalign.l) As "_FMOD_System_SetFileSystem@24"
  FMOD_System_AttachFileSystem(system.l, *useropen, *userclose, *userread, *userseek) As "_FMOD_System_AttachFileSystem@20"
  FMOD_System_SetAdvancedSettings(system.l, *settings.FMOD_ADVANCEDSETTINGS) As "_FMOD_System_SetAdvancedSettings@8"
  FMOD_System_GetAdvancedSettings(system.l, *settings.FMOD_ADVANCEDSETTINGS) As "_FMOD_System_GetAdvancedSettings@8"
  FMOD_System_SetSpeakerMode(system.l, speakermode.l) As "_FMOD_System_SetSpeakerMode@8"
  FMOD_System_GetSpeakerMode(system.l, *speakermode.l) As "_FMOD_System_GetSpeakerMode@8"
  FMOD_System_SetCallback(system.l, *callback) As "_FMOD_System_SetCallback@8"
  ;-Plug-in support
  FMOD_System_SetPluginPath(system.l, path.p-ascii) As "_FMOD_System_SetPluginPath@8"
  FMOD_System_LoadPlugin(system.l, filename.p-ascii, *plugintype.FMOD_PLUGINTYPE, *index.l) As "_FMOD_System_LoadPlugin@16"
  FMOD_System_GetNumPlugins(system.l, plugintype.FMOD_PLUGINTYPE, *numplugins.l) As "_FMOD_System_GetNumPlugins@12"
  FMOD_System_GetPluginInfo(system.l, plugintype.FMOD_PLUGINTYPE, index.l, name.p-ascii, namelen.l, *version.l) As "_FMOD_System_GetPluginInfo@24"
  FMOD_System_UnloadPlugin(system.l, plugintype.FMOD_PLUGINTYPE, index.l) As "_FMOD_System_UnloadPlugin@12"
  FMOD_System_SetOutputByPlugin(system.l, index.l) As "_FMOD_System_SetOutputByPlugin@8"
  FMOD_System_GetOutputByPlugin(system.l, *index.l) As "_FMOD_System_GetOutputByPlugin@8"
  FMOD_System_CreateCodec(system.l, *description.FMOD_CODEC_DESCRIPTION) As "_FMOD_System_CreateCodec@8"
  ;-Init/Close
  FMOD_System_Init(system.l, maxchannels.l, flags.FMOD_INITFLAGS, *extradriverdata) As "_FMOD_System_Init@16"
  FMOD_System_Close(system.l) As "_FMOD_System_Close@4"
  ;-General post-init system functions
  FMOD_System_Update(system.l) As "_FMOD_System_Update@4"
  FMOD_System_Set3DSettings(system.l, dopplerscale.f, distancefactor.f, rolloffscale.f) As "_FMOD_System_Set3DSettings@16"
  FMOD_System_Get3DSettings(system.l, *dopplerscale.f, *distancefactor.f, *rolloffscale.f) As "_FMOD_System_Get3DSettings@16"
  FMOD_System_Set3DNumListeners(system.l, numlisteners.l) As "_FMOD_System_Set3DNumListeners@8"
  FMOD_System_Get3DNumListeners(system.l, *numlisteners.l) As "_FMOD_System_Get3DNumListeners@8"
  FMOD_System_Set3DListenerAttributes(system.l, listener.l, *pos.FMOD_VECTOR, *vel.FMOD_VECTOR, *forward.FMOD_VECTOR, *up.FMOD_VECTOR) As "_FMOD_System_Set3DListenerAttributes@24"
  FMOD_System_Get3DListenerAttributes(system.l, listener.l, *pos.FMOD_VECTOR, *vel.FMOD_VECTOR, *forward.FMOD_VECTOR, *up.FMOD_VECTOR) As "_FMOD_System_Get3DListenerAttributes@24"
  FMOD_System_Set3DRolloffCallback(system.l, *callback) As "_FMOD_System_Set3DRolloffCallback@8"
  FMOD_System_Set3DSpeakerPosition(system.l, speaker.FMOD_SPEAKER, x.f, y.f, active.FMOD_BOOL) As "_FMOD_System_Set3DSpeakerPosition@20"
  FMOD_System_Get3DSpeakerPosition(system.l, speaker.FMOD_SPEAKER, *x.f, *y.f, *active.FMOD_BOOL) As "_FMOD_System_Get3DSpeakerPosition@20"
  FMOD_System_SetStreamBufferSize(system.l, filebuffersize.l, filebuffersizetype.FMOD_TIMEUNIT) As "_FMOD_System_SetStreamBufferSize@12"
  FMOD_System_GetStreamBufferSize(system.l, *filebuffersize.l, *filebuffersizetype.FMOD_TIMEUNIT) As "_FMOD_System_GetStreamBufferSize@12"
  ;-System information functions.
  FMOD_System_GetVersion(system.l, *version.l) As "_FMOD_System_GetVersion@8"
  FMOD_System_GetOutputHandle(system.l, *handle) As "_FMOD_System_GetOutputHandle@8"
  FMOD_System_GetChannelsPlaying(system.l, *channels.l) As "_FMOD_System_GetChannelsPlaying@8"
  FMOD_System_GetHardwareChannels(system.l, *num2d.l, *num3d.l, *total.l) As "_FMOD_System_GetHardwareChannels@16"
  FMOD_System_GetCPUUsage(system.l, *dsp.f, *stream.f, *update.f, *total.f) As "_FMOD_System_GetCPUUsage@20"
  FMOD_System_GetSoundRAM(system.l, *currentalloced.l, *maxalloced.l, *total.l) As "_FMOD_System_GetSoundRAM@16"
  FMOD_System_GetNumCDROMDrives(system.l, *numdrives.l) As "_FMOD_System_GetNumCDROMDrives@8"
  FMOD_System_GetCDROMDriveName(system.l, drive.l, *drivename.s, drivenamelen.l, *scsiname.s, scsinamelen.l, *devicename.s, devicenamelen.l) As "_FMOD_System_GetCDROMDriveName@32"
  FMOD_System_GetSpectrum(system.l, *spectrumarray.f, numvalues.l, channeloffset.l, windowtype.FMOD_DSP_FFT_WINDOW) As "_FMOD_System_GetSpectrum@20"
  FMOD_System_GetWaveData(system.l, *wavearray.f, numvalues.l, channeloffset.l) As "_FMOD_System_GetWaveData@16"
  ;-Sound/DSP/Channel/FX creation and retrieval.
  FMOD_System_CreateSound(system.l, name_or_data.p-ascii, mode.FMOD_MODE, *exinfo.FMOD_CREATESOUNDEXINFO, *sound.FMOD_SOUND) As "_FMOD_System_CreateSound@20"
  FMOD_System_CreateStream(system.l, name_or_data.p-ascii, mode.FMOD_MODE, *exinfo.FMOD_CREATESOUNDEXINFO, *sound.FMOD_SOUND) As "_FMOD_System_CreateStream@20"
  FMOD_System_CreateDSP(system.l, *description.FMOD_DSP_DESCRIPTION, *dsp.FMOD_DSP) As "_FMOD_System_CreateDSP@12"
  FMOD_System_CreateDSPByType(system.l, type.FMOD_DSP_TYPE, *dsp.FMOD_DSP) As "_FMOD_System_CreateDSPByType@12"
  FMOD_System_CreateDSPByIndex(system.l, index.l, *dsp.FMOD_DSP) As "_FMOD_System_CreateDSPByIndex@12"
  FMOD_System_CreateChannelGroup(system.l, name.p-ascii, *channelgroup.FMOD_CHANNELGROUP) As "_FMOD_System_CreateChannelGroup@12"
  FMOD_System_CreateSoundGroup(system.l, name.p-ascii, *soundgroup.FMOD_SOUNDGROUP) As "_FMOD_System_CreateSoundGroup@12"
  FMOD_System_CreateReverb(system.l, *reverb.FMOD_REVERB) As "_FMOD_System_CreateReverb@8"
  FMOD_System_PlaySound(system.l, channelid.FMOD_CHANNELINDEX, *sound.FMOD_SOUND, paused.FMOD_BOOL, *channel.FMOD_CHANNEL) As "_FMOD_System_PlaySound@20"
  FMOD_System_PlayDSP(system.l, channelid.FMOD_CHANNELINDEX, *dsp.FMOD_DSP, paused.FMOD_BOOL, *channel.FMOD_CHANNEL) As "_FMOD_System_PlayDSP@20"
  FMOD_System_GetChannel(system.l, channelid.l, *channel.FMOD_CHANNEL) As "_FMOD_System_GetChannel@12"
  FMOD_System_GetMasterChannelGroup(system.l, *channelgroup.FMOD_CHANNELGROUP) As "_FMOD_System_GetMasterChannelGroup@8"
  FMOD_System_GetMasterSoundGroup(system.l, *soundgroup.FMOD_SOUNDGROUP) As "_FMOD_System_GetMasterSoundGroup@8"
  ;-Reverb API   
  FMOD_System_SetReverbProperties(system.l, *prop.FMOD_REVERB_PROPERTIES) As "_FMOD_System_SetReverbProperties@8"
  FMOD_System_GetReverbProperties(system.l, *prop.FMOD_REVERB_PROPERTIES) As "_FMOD_System_GetReverbProperties@8"
  FMOD_System_SetReverbAmbientProperties(system.l, *prop.FMOD_REVERB_PROPERTIES) As "_FMOD_System_SetReverbAmbientProperties@8"
  FMOD_System_GetReverbAmbientProperties(system.l, *prop.FMOD_REVERB_PROPERTIES) As "_FMOD_System_GetReverbAmbientProperties@8"
  ;-System level DSP access.
  FMOD_System_GetDSPHead(system.l, *dsp.FMOD_DSP) As "_FMOD_System_GetDSPHead@8"
  FMOD_System_AddDSP(system.l, *dsp.FMOD_DSP) As "_FMOD_System_AddDSP@8"
  FMOD_System_LockDSP(system.l) As "_FMOD_System_LockDSP@4"
  FMOD_System_UnlockDSP(system.l) As "_FMOD_System_UnlockDSP@4"
  FMOD_System_GetDSPClock(system.l, *hi, *lo) As "_FMOD_System_GetDSPClock@12"
  ;-Recording API.
  FMOD_System_SetRecordDriver(system.l, driver.l) As "_FMOD_System_SetRecordDriver@8"
  FMOD_System_GetRecordDriver(system.l, *driver.l) As "_FMOD_System_GetRecordDriver@8"
  FMOD_System_GetRecordNumDrivers(system.l, *numdrivers.l) As "_FMOD_System_GetRecordNumDrivers@8"
  FMOD_System_GetRecordDriverInfo(system.l, id.l, *name.s, namelen.l, *guid.FMOD_GUID) As "_FMOD_System_GetRecordDriverInfo@20"
  FMOD_System_GetRecordDriverCaps(system.l, id.l, *caps.FMOD_CAPS, *minfrequency.l, *maxfrequency.l) As "_FMOD_System_GetRecordDriverCaps@20"
  FMOD_System_GetRecordPosition(system.l, *position.l) As "_FMOD_System_GetRecordPosition@8"
  FMOD_System_RecordStart(system.l, *sound.FMOD_SOUND, loop.FMOD_BOOL) As "_FMOD_System_RecordStart@12"
  FMOD_System_RecordStop(system.l) As "_FMOD_System_RecordStop@4"
  FMOD_System_IsRecording(system.l, *recording.FMOD_BOOL) As "_FMOD_System_IsRecording@8"
  ;-Geometry API
  FMOD_System_CreateGeometry(system.l, maxpolygons.l, maxvertices.l, *geometry.FMOD_GEOMETRY) As "_FMOD_System_CreateGeometry@16"
  FMOD_System_SetGeometrySettings(system.l, maxworldsize.f) As "_FMOD_System_SetGeometrySettings@8"
  FMOD_System_GetGeometrySettings(system.l, *maxworldsize.f) As "_FMOD_System_GetGeometrySettings@8"
  FMOD_System_LoadGeometry(system.l, *data_, datasize.l, *geometry.FMOD_GEOMETRY) As "_FMOD_System_LoadGeometry@16"
  ;-Network functions
  FMOD_System_SetNetworkProxy(system.l, proxy.p-ascii) As "_FMOD_System_SetNetworkProxy@8"
  FMOD_System_GetNetworkProxy(system.l, *proxy.s, proxylen.l) As "_FMOD_System_GetNetworkProxy@12"
  FMOD_System_SetNetworkTimeout(system.l, timeout.l) As "_FMOD_System_SetNetworkTimeout@8"
  FMOD_System_GetNetworkTimeout(system.l, *timeout.l) As "_FMOD_System_GetNetworkTimeout@8"
  ;-Userdata set/get
  FMOD_System_SetUserData(system.l, *userdata) As "_FMOD_System_SetUserData@8"
  FMOD_System_GetUserData(system.l, *userdata) As "_FMOD_System_GetUserData@8"
  ;------>'Sound' API
  FMOD_Sound_Release(sound.l) As "_FMOD_Sound_Release@4"
  FMOD_Sound_GetSystemObject(sound.l, *system.FMOD_SYSTEM) As "_FMOD_Sound_GetSystemObject@8"
  ;-Standard sound manipulation functions
  FMOD_Sound_Lock(sound.l, offset.l, length.l, *ptr1, *ptr2, *len1.l, *len2.l) As "_FMOD_Sound_Lock@28"
  FMOD_Sound_Unlock(sound.l, *ptr1, *ptr2, len1.l, len2.l) As "_FMOD_Sound_Unlock@20"
  FMOD_Sound_SetDefaults(sound.l, frequency.f, volume.f, pan.f, priority.l) As "_FMOD_Sound_SetDefaults@20"
  FMOD_Sound_GetDefaults(sound.l, *frequency.f, *volume.f, *pan.f, *priority.l) As "_FMOD_Sound_GetDefaults@20"
  FMOD_Sound_SetVariations(sound.l, frequencyvar.f, volumevar.f, panvar.f) As "_FMOD_Sound_SetVariations@16"
  FMOD_Sound_GetVariations(sound.l, *frequencyvar.f, *volumevar.f, *panvar.f) As "_FMOD_Sound_GetVariations@16"
  FMOD_Sound_Set3DMinMaxDistance(sound.l, min.f, max.f) As "_FMOD_Sound_Set3DMinMaxDistance@12"
  FMOD_Sound_Get3DMinMaxDistance(sound.l, *min.f, *max.f) As "_FMOD_Sound_Get3DMinMaxDistance@12"
  FMOD_Sound_Set3DConeSettings(sound.l, insideconeangle.f, outsideconeangle.f, outsidevolume.f) As "_FMOD_Sound_Set3DConeSettings@16"
  FMOD_Sound_Get3DConeSettings(sound.l, *insideconeangle.f, *outsideconeangle.f, *outsidevolume.f) As "_FMOD_Sound_Get3DConeSettings@16"
  FMOD_Sound_Set3DCustomRolloff(sound.l, *points.FMOD_VECTOR, numpoints.l) As "_FMOD_Sound_Set3DCustomRolloff@12"
  FMOD_Sound_Get3DCustomRolloff(sound.l, *points.FMOD_VECTOR, *numpoints.l) As "_FMOD_Sound_Get3DCustomRolloff@12"
  FMOD_Sound_SetSubSound(sound.l, index.l, *subsound.FMOD_SOUND) As "_FMOD_Sound_SetSubSound@12"
  FMOD_Sound_GetSubSound(sound.l, index.l, *subsound.FMOD_SOUND) As "_FMOD_Sound_GetSubSound@12"
  FMOD_Sound_SetSubSoundSentence(sound.l, *subsoundlist.l, numsubsounds.l) As "_FMOD_Sound_SetSubSoundSentence@12"
  FMOD_Sound_GetName(sound.l, name.p-ascii, namelen.l) As "_FMOD_Sound_GetName@12"
  FMOD_Sound_GetLength(sound.l, *length.l, lengthtype.FMOD_TIMEUNIT) As "_FMOD_Sound_GetLength@12"
  FMOD_Sound_GetFormat(sound.l, *type.FMOD_SOUND_TYPE, *format.FMOD_SOUND_FORMAT, *channels.l, *bits.l) As "_FMOD_Sound_GetFormat@20"
  FMOD_Sound_GetNumSubSounds(sound.l, *numsubsounds.l) As "_FMOD_Sound_GetNumSubSounds@8"
  FMOD_Sound_GetNumTags(sound.l, *numtags.l, *numtagsupdated.l) As "_FMOD_Sound_GetNumTags@12"
  FMOD_Sound_GetTag(sound.l, *name.s, index.l, *tag.FMOD_TAG) As "_FMOD_Sound_GetTag@16"
  FMOD_Sound_GetOpenState(sound.l, *openstate.FMOD_OPENSTATE, *percentbuffered.l, *starving.FMOD_BOOL) As "_FMOD_Sound_GetOpenState@16"
  FMOD_Sound_ReadData(sound.l, *buffer, lenbytes.l, *read_.l) As "_FMOD_Sound_ReadData@16"
  FMOD_Sound_SeekData(sound.l, pcm.l) As "_FMOD_Sound_SeekData@8"
  FMOD_Sound_SetSoundGroup(sound.l, *soundgroup.FMOD_SOUNDGROUP) As "_FMOD_Sound_SetSoundGroup@8"
  FMOD_Sound_GetSoundGroup(sound.l, *soundgroup.FMOD_SOUNDGROUP) As "_FMOD_Sound_GetSoundGroup@8"
  ;-Synchronization point API.  These points can come from markers embedded in wav files, and can also generate channel callbacks.
  FMOD_Sound_GetNumSyncPoints(sound.l, *numsyncpoints.l) As "_FMOD_Sound_GetNumSyncPoints@8"
  FMOD_Sound_GetSyncPoint(sound.l, index.l, *point.FMOD_SYNCPOINT) As "_FMOD_Sound_GetSyncPoint@12"
  FMOD_Sound_GetSyncPointInfo(sound.l, *point.FMOD_SYNCPOINT, *name.s, namelen.l, *offset.l, offsettype.FMOD_TIMEUNIT) As "_FMOD_Sound_GetSyncPointInfo@24"
  FMOD_Sound_AddSyncPoint(sound.l, offset.l, offsettype.FMOD_TIMEUNIT, *name.s, *point.FMOD_SYNCPOINT) As "_FMOD_Sound_AddSyncPoint@20"
  FMOD_Sound_DeleteSyncPoint(sound.l, *point.FMOD_SYNCPOINT) As "_FMOD_Sound_DeleteSyncPoint@8"
  ;-Functions also in Channel class but here they are the 'default' to save having to change it in Channel all the time.
  FMOD_Sound_SetMode(sound.l, mode.FMOD_MODE) As "_FMOD_Sound_SetMode@8"
  FMOD_Sound_GetMode(sound.l, *mode.FMOD_MODE) As "_FMOD_Sound_GetMode@8"
  FMOD_Sound_SetLoopCount(sound.l, loopcount.l) As "_FMOD_Sound_SetLoopCount@8"
  FMOD_Sound_GetLoopCount(sound.l, *loopcount.l) As "_FMOD_Sound_GetLoopCount@8"
  FMOD_Sound_SetLoopPoints(sound.l, loopstart.l, loopstarttype.FMOD_TIMEUNIT, loopend.l, loopendtype.FMOD_TIMEUNIT) As "_FMOD_Sound_SetLoopPoints@20"
  FMOD_Sound_GetLoopPoints(sound.l, *loopstart.l, loopstarttype.FMOD_TIMEUNIT, *loopend.l, loopendtype.FMOD_TIMEUNIT) As "_FMOD_Sound_GetLoopPoints@20"
  ;-For MOD/S3M/XM/IT/MID sequenced formats only.
  FMOD_Sound_GetMusicNumChannels     (sound.l, *numchannels) As "_FMOD_Sound_GetMusicNumChannels@8"
  FMOD_Sound_SetMusicChannelVolume   (sound.l, channel.l, volume.f) As "_FMOD_Sound_SetMusicChannelVolume@12"
  FMOD_Sound_GetMusicChannelVolume   (sound.l, channel.l, *volume.f) As "_FMOD_Sound_GetMusicChannelVolume@12"
  ;-Userdata set/get.
  FMOD_Sound_SetUserData(sound.l, *userdata) As "_FMOD_Sound_SetUserData@8"
  FMOD_Sound_GetUserData(sound.l, *userdata) As "_FMOD_Sound_GetUserData@8"
  ;------>'Channel' API
  FMOD_Channel_GetSystemObject(channel.l, *system.FMOD_SYSTEM) As "_FMOD_Channel_GetSystemObject@8"
  FMOD_Channel_Stop(channel.l) As "_FMOD_Channel_Stop@4"
  FMOD_Channel_SetPaused(channel.l, paused.FMOD_BOOL) As "_FMOD_Channel_SetPaused@8"
  FMOD_Channel_GetPaused(channel.l, *paused.FMOD_BOOL) As "_FMOD_Channel_GetPaused@8"
  FMOD_Channel_SetVolume(channel.l, volume.f) As "_FMOD_Channel_SetVolume@8"
  FMOD_Channel_GetVolume(channel.l, *volume.f) As "_FMOD_Channel_GetVolume@8"
  FMOD_Channel_SetFrequency(channel.l, frequency.f) As "_FMOD_Channel_SetFrequency@8"
  FMOD_Channel_GetFrequency(channel.l, *frequency.f) As "_FMOD_Channel_GetFrequency@8"
  FMOD_Channel_SetPan(channel.l, pan.f) As "_FMOD_Channel_SetPan@8"
  FMOD_Channel_GetPan(channel.l, *pan.f) As "_FMOD_Channel_GetPan@8"
  FMOD_Channel_SetDelay(channel.l, startdelay.l, enddelay.l) As "_FMOD_Channel_SetDelay@12"
  FMOD_Channel_GetDelay(channel.l, *startdelay.l, *enddelay.l) As "_FMOD_Channel_GetDelay@12"
  FMOD_Channel_SetSpeakerMix(channel.l, frontleft.f, frontright.f, center.f, lfe.f, backleft.f, backright.f, sideleft.f, sideright.f) As "_FMOD_Channel_SetSpeakerMix@36"
  FMOD_Channel_GetSpeakerMix(channel.l, *frontleft.f, *frontright.f, *center.f, *lfe.f, *backleft.f, *backright.f, *sideleft.f, *sideright.f) As "_FMOD_Channel_GetSpeakerMix@36"
  FMOD_Channel_SetSpeakerLevels(channel.l, speaker.FMOD_SPEAKER, *levels.f, numlevels.l) As "_FMOD_Channel_SetSpeakerLevels@16"
  FMOD_Channel_GetSpeakerLevels(channel.l, speaker.FMOD_SPEAKER, *levels.f, numlevels.l) As "_FMOD_Channel_GetSpeakerLevels@16"
  FMOD_Channel_SetInputChannelMix(channel.l, *levels.f, numlevels.l) As "_FMOD_Channel_SetInputChannelMix@12"
  FMOD_Channel_GetInputChannelMix(channel.l, *levels.f, numlevels.l) As "_FMOD_Channel_GetInputChannelMix@12"
  FMOD_Channel_SetMute(channel.l, mute.FMOD_BOOL) As "_FMOD_Channel_SetMute@8"
  FMOD_Channel_GetMute(channel.l, *mute.FMOD_BOOL) As "_FMOD_Channel_GetMute@8"
  FMOD_Channel_SetPriority(channel.l, priority.l) As "_FMOD_Channel_SetPriority@8"
  FMOD_Channel_GetPriority(channel.l, *priority.l) As "_FMOD_Channel_GetPriority@8"
  FMOD_Channel_SetPosition(channel.l, position.l, postype.FMOD_TIMEUNIT) As "_FMOD_Channel_SetPosition@12"
  FMOD_Channel_GetPosition(channel.l, *position.l, postype.FMOD_TIMEUNIT) As "_FMOD_Channel_GetPosition@12"
  FMOD_Channel_SetReverbProperties(channel.l, *prop.FMOD_REVERB_CHANNELPROPERTIES) As "_FMOD_Channel_SetReverbProperties@8"
  FMOD_Channel_GetReverbProperties(channel.l, *prop.FMOD_REVERB_CHANNELPROPERTIES) As "_FMOD_Channel_GetReverbProperties@8"
  FMOD_Channel_SetChannelGroup(channel.l, *channelgroup.FMOD_CHANNELGROUP) As "_FMOD_Channel_SetChannelGroup@8"
  FMOD_Channel_GetChannelGroup(channel.l, *channelgroup.FMOD_CHANNELGROUP) As "_FMOD_Channel_GetChannelGroup@8"
  FMOD_Channel_SetCallback(channel.l, type.l, *callback, command.l) As "_FMOD_Channel_SetCallback@16"
  ;-3D functionality
  FMOD_Channel_Set3DAttributes(channel.l, *pos.FMOD_VECTOR,  *vel.FMOD_VECTOR) As "_FMOD_Channel_Set3DAttributes@12"
  FMOD_Channel_Get3DAttributes(channel.l, *pos.FMOD_VECTOR,  *vel.FMOD_VECTOR) As "_FMOD_Channel_Get3DAttributes@12"
  FMOD_Channel_Set3DMinMaxDistance(channel.l, mindistance.f, maxdistance.f) As "_FMOD_Channel_Set3DMinMaxDistance@12"
  FMOD_Channel_Get3DMinMaxDistance(channel.l, *mindistance.f, *maxdistance.f) As "_FMOD_Channel_Get3DMinMaxDistance@12"
  FMOD_Channel_Set3DConeSettings(channel.l, insideconeangle.f, outsideconeangle.f, outsidevolume.f) As "_FMOD_Channel_Set3DConeSettings@16"
  FMOD_Channel_Get3DConeSettings(channel.l, *insideconeangle.f, *outsideconeangle.f, *outsidevolume.f) As "_FMOD_Channel_Get3DConeSettings@16"
  FMOD_Channel_Set3DConeOrientation(channel.l, *orientation.FMOD_VECTOR) As "_FMOD_Channel_Set3DConeOrientation@8"
  FMOD_Channel_Get3DConeOrientation(channel.l, *orientation.FMOD_VECTOR) As "_FMOD_Channel_Get3DConeOrientation@8"
  FMOD_Channel_Set3DCustomRolloff(channel.l, *points.FMOD_VECTOR, numpoints.l) As "_FMOD_Channel_Set3DCustomRolloff@12"
  FMOD_Channel_Get3DCustomRolloff(channel.l, *points.FMOD_VECTOR, *numpoints.l) As "_FMOD_Channel_Get3DCustomRolloff@12"
  FMOD_Channel_Set3DOcclusion(channel.l, directocclusion.f, reverbocclusion.f) As "_FMOD_Channel_Set3DOcclusion@12"
  FMOD_Channel_Get3DOcclusion(channel.l, *directocclusion.f, *reverbocclusion.f) As "_FMOD_Channel_Get3DOcclusion@12"
  FMOD_Channel_Set3DSpread(channel.l, angle.f) As "_FMOD_Channel_Set3DSpread@8"
  FMOD_Channel_Get3DSpread(channel.l, *angle.f) As "_FMOD_Channel_Get3DSpread@8"
  FMOD_Channel_Set3DPanLevel(channel.l, level.f) As "_FMOD_Channel_Set3DPanLevel@8"
  FMOD_Channel_Get3DPanLevel(channel.l, *level.f) As "_FMOD_Channel_Get3DPanLevel@8"
  FMOD_Channel_Set3DDopplerLevel(channel.l, level.f) As "_FMOD_Channel_Set3DDopplerLevel@8"
  FMOD_Channel_Get3DDopplerLevel(channel.l, *level.f) As "_FMOD_Channel_Get3DDopplerLevel@8"
  ;-DSP functionality only for channels playing sounds created with FMOD_SOFTWARE
  FMOD_Channel_GetDSPHead(channel.l, *dsp.FMOD_DSP) As "_FMOD_Channel_GetDSPHead@8"
  FMOD_Channel_AddDSP(channel.l, *dsp.FMOD_DSP) As "_FMOD_Channel_AddDSP@8"
  ;- Information only functions
  FMOD_Channel_IsPlaying(channel.l, *isplaying.FMOD_BOOL) As "_FMOD_Channel_IsPlaying@8"
  FMOD_Channel_IsVirtual(channel.l, *isvirtual.FMOD_BOOL) As "_FMOD_Channel_IsVirtual@8"
  FMOD_Channel_GetAudibility(channel.l, *audibility.f) As "_FMOD_Channel_GetAudibility@8"
  FMOD_Channel_GetCurrentSound(channel.l, *sound.FMOD_SOUND) As "_FMOD_Channel_GetCurrentSound@8"
  FMOD_Channel_GetSpectrum(channel.l, *spectrumarray.f, numvalues.l, channeloffset.l, windowtype.FMOD_DSP_FFT_WINDOW) As "_FMOD_Channel_GetSpectrum@20"
  FMOD_Channel_GetWaveData(channel.l, *wavearray.f, numvalues.l, channeloffset.l) As "_FMOD_Channel_GetWaveData@16"
  FMOD_Channel_GetIndex(channel.l, *index.l) As "_FMOD_Channel_GetIndex@8"
  ;-Functions also found in Sound class but here they can be set per channel
  FMOD_Channel_SetMode(channel.l, mode.FMOD_MODE) As "_FMOD_Channel_SetMode@8"
  FMOD_Channel_GetMode(channel.l, *mode.FMOD_MODE) As "_FMOD_Channel_GetMode@8"
  FMOD_Channel_SetLoopCount(channel.l, loopcount.l) As "_FMOD_Channel_SetLoopCount@8"
  FMOD_Channel_GetLoopCount(channel.l, *loopcount.l) As "_FMOD_Channel_GetLoopCount@8"
  FMOD_Channel_SetLoopPoints(channel.l, loopstart.l, loopstarttype.FMOD_TIMEUNIT, loopend.l, loopendtype.FMOD_TIMEUNIT) As "_FMOD_Channel_SetLoopPoints@20"
  FMOD_Channel_GetLoopPoints(channel.l, *loopstart.l, loopstarttype.FMOD_TIMEUNIT, *loopend.l, loopendtype.FMOD_TIMEUNIT) As "_FMOD_Channel_GetLoopPoints@20"
  ;-Userdata set/get
  FMOD_Channel_SetUserData(channel.l, *userdata) As "_FMOD_Channel_SetUserData@8"
  FMOD_Channel_GetUserData(channel.l, *userdata) As "_FMOD_Channel_GetUserData@8"
  ;------>'ChannelGroup' API
  FMOD_ChannelGroup_Release(channelgroup.l) As "_FMOD_ChannelGroup_Release@4"
  FMOD_ChannelGroup_GetSystemObject(channelgroup.l, *system.FMOD_SYSTEM) As "_FMOD_ChannelGroup_GetSystemObject@8"
  ;-Channelgroup scale values.  (changes attributes relative to the channels, doesn't overwrite them)
  FMOD_ChannelGroup_SetVolume(channelgroup.l, volume.f) As "_FMOD_ChannelGroup_SetVolume@8"
  FMOD_ChannelGroup_GetVolume(channelgroup.l, *volume.f) As "_FMOD_ChannelGroup_GetVolume@8"
  FMOD_ChannelGroup_SetPitch(channelgroup.l, pitch.f) As "_FMOD_ChannelGroup_SetPitch@8"
  FMOD_ChannelGroup_GetPitch(channelgroup.l, *pitch.f) As "_FMOD_ChannelGroup_GetPitch@8"
  FMOD_ChannelGroup_Set3DOcclusion(channelgroup.l, directocclusion.f, reverbocclusion.f) As "_FMOD_ChannelGroup_Set3DOcclusion@12"
  FMOD_ChannelGroup_Get3DOcclusion(channelgroup.l, *directocclusion.f, *reverbocclusion.f) As "_FMOD_ChannelGroup_Get3DOcclusion@12"
  FMOD_ChannelGroup_SetPaused(channelgroup.l, paused.FMOD_BOOL) As "_FMOD_ChannelGroup_SetPaused@8"
  FMOD_ChannelGroup_GetPaused(channelgroup.l, *paused.FMOD_BOOL) As "_FMOD_ChannelGroup_GetPaused@8"
  FMOD_ChannelGroup_SetMute(channelgroup.l, mute.FMOD_BOOL) As "_FMOD_ChannelGroup_SetMute@8"
  FMOD_ChannelGroup_GetMute(channelgroup.l, *mute.FMOD_BOOL) As "_FMOD_ChannelGroup_GetMute@8"
  ;-Channelgroup override values.  (recursively overwrites whatever settings the channels had)
  FMOD_ChannelGroup_Stop(channelgroup.l) As "_FMOD_ChannelGroup_Stop@4"
  FMOD_ChannelGroup_OverrideVolume(channelgroup.l, volume.f) As "_FMOD_ChannelGroup_OverrideVolume@8"
  FMOD_ChannelGroup_OverrideFrequency(channelgroup.l, frequency.f) As "_FMOD_ChannelGroup_OverrideFrequency@8"
  FMOD_ChannelGroup_OverridePan(channelgroup.l, pan.f) As "_FMOD_ChannelGroup_OverridePan@8"
  FMOD_ChannelGroup_OverrideReverbProperties(channelgroup.l, *prop.FMOD_REVERB_CHANNELPROPERTIES) As "_FMOD_ChannelGroup_OverrideReverbProperties@8"
  FMOD_ChannelGroup_Override3DAttributes(channelgroup.l, *pos.FMOD_VECTOR, *vel.FMOD_VECTOR) As "_FMOD_ChannelGroup_Override3DAttributes@12"
  FMOD_ChannelGroup_OverrideSpeakerMix(channelgroup.l, frontleft.f,  frontright.f,  center.f,  lfe.f,  backleft.f,  backright.f,  sideleft.f,  sideright.f) As "_FMOD_ChannelGroup_OverrideSpeakerMix@36"
  ;-Nested channel groups
  FMOD_ChannelGroup_AddGroup(channelgroup.l, *group.FMOD_CHANNELGROUP) As "_FMOD_ChannelGroup_AddGroup@8"
  FMOD_ChannelGroup_GetNumGroups(channelgroup.l, *numgroups.l) As "_FMOD_ChannelGroup_GetNumGroups@8"
  FMOD_ChannelGroup_GetGroup(channelgroup.l, index.l, *group.FMOD_CHANNELGROUP) As "_FMOD_ChannelGroup_GetGroup@12"
  FMOD_ChannelGroup_GetParentGroup(channelgroup.l, *group.FMOD_CHANNELGROUP) As "_FMOD_ChannelGroup_GetParentGroup@8"
  ;-DSP functionality only for channel groups playing sounds created with FMOD_SOFTWARE
  FMOD_ChannelGroup_GetDSPHead(channelgroup.l, *dsp.FMOD_DSP) As "_FMOD_ChannelGroup_GetDSPHead@8"
  FMOD_ChannelGroup_AddDSP(channelgroup.l, *dsp.FMOD_DSP) As "_FMOD_ChannelGroup_AddDSP@8"
  ;-Information only functions
  FMOD_ChannelGroup_GetName(channelgroup.l, *name.s, namelen.l) As "_FMOD_ChannelGroup_GetName@12"
  FMOD_ChannelGroup_GetNumChannels(channelgroup.l, *numchannels.l) As "_FMOD_ChannelGroup_GetNumChannels@8"
  FMOD_ChannelGroup_GetChannel(channelgroup.l, index.l, *channel.FMOD_CHANNEL) As "_FMOD_ChannelGroup_GetChannel@12"
  FMOD_ChannelGroup_GetSpectrum(channelgroup.l, *spectrumarray.f, numvalues.l, channeloffset.l, windowtype.FMOD_DSP_FFT_WINDOW) As "_FMOD_ChannelGroup_GetSpectrum@20"
  FMOD_ChannelGroup_GetWaveData(channelgroup.l, *wavearray.f, numvalues.l, channeloffset.l) As "_FMOD_ChannelGroup_GetWaveData@16"
  ;-Userdata set/get.
  FMOD_ChannelGroup_SetUserData(channelgroup.l, *userdata) As "_FMOD_ChannelGroup_SetUserData@8"
  FMOD_ChannelGroup_GetUserData(channelgroup.l, *userdata) As "_FMOD_ChannelGroup_GetUserData@8"
  ;------>'SoundGroup' API
  FMOD_SoundGroup_Release(soundgroup.l) As "_FMOD_SoundGroup_Release@4"
  FMOD_SoundGroup_GetSystemObject(soundgroup.l, *system.FMOD_SYSTEM) As "_FMOD_SoundGroup_GetSystemObject@8"
  ;-SoundGroup control functions.
  FMOD_SoundGroup_SetMaxAudible(soundgroup.l, maxaudible.l) As "_FMOD_SoundGroup_SetMaxAudible@8"
  FMOD_SoundGroup_GetMaxAudible(soundgroup.l, *maxaudible.l) As "_FMOD_SoundGroup_GetMaxAudible@8"
  FMOD_SoundGroup_SetMaxAudibleBehavior(soundgroup.l, behavior.FMOD_SOUNDGROUP_BEHAVIOR) As "_FMOD_SoundGroup_SetMaxAudibleBehavior@8"
  FMOD_SoundGroup_GetMaxAudibleBehavior(soundgroup.l, *behavior.FMOD_SOUNDGROUP_BEHAVIOR) As "_FMOD_SoundGroup_GetMaxAudibleBehavior@8"
  FMOD_SoundGroup_SetMuteFadeSpeed(soundgroup.l, speed.f) As "_FMOD_SoundGroup_SetMuteFadeSpeed@8"
  FMOD_SoundGroup_GetMuteFadeSpeed(soundgroup.l, *speed.f) As "_FMOD_SoundGroup_GetMuteFadeSpeed@8"
  FMOD_SoundGroup_SetVolume(soundgroup.l, volume.f) As "_FMOD_SoundGroup_SetVolume@8"
  FMOD_SoundGroup_GetVolume(soundgroup.l, *volume.f) As "_FMOD_SoundGroup_GetVolume@8"
  FMOD_SoundGroup_Stop(soundgroup.l) As "_FMOD_SoundGroup_Stop@4"
  ;-Information only functions.
  FMOD_SoundGroup_GetName(soundgroup.l, *name.s, namelen.l) As "_FMOD_SoundGroup_GetName@12"
  FMOD_SoundGroup_GetNumSounds(soundgroup.l, *numsounds.l) As "_FMOD_SoundGroup_GetNumSounds@8"
  FMOD_SoundGroup_GetSound(soundgroup.l, index.l, *sound.FMOD_SOUND) As "_FMOD_SoundGroup_GetSound@12"
  FMOD_SoundGroup_GetNumPlaying(soundgroup.l, *numplaying.l) As "_FMOD_SoundGroup_GetNumPlaying@8"
  ;-Userdata set/get.
  FMOD_SoundGroup_SetUserData(soundgroup.l, *userdata) As "_FMOD_SoundGroup_SetUserData@8"
  FMOD_SoundGroup_GetUserData(soundgroup.l, *userdata) As "_FMOD_SoundGroup_GetUserData@8"
  ;------>'DSP' API
  FMOD_DSP_Release(dsp.l) As "_FMOD_DSP_Release@4"
  FMOD_DSP_GetSystemObject(dsp.l, *system.FMOD_SYSTEM) As "_FMOD_DSP_GetSystemObject@8"
  ;-Connection / disconnection / input and output enumeration
  FMOD_DSP_AddInput(dsp.l, *target.FMOD_DSP) As "_FMOD_DSP_AddInput@8"
  FMOD_DSP_DisconnectFrom(dsp.l, *target.FMOD_DSP) As "_FMOD_DSP_DisconnectFrom@8"
  FMOD_DSP_DisconnectAll(dsp.l, inputs.FMOD_BOOL, outputs.FMOD_BOOL) As "_FMOD_DSP_DisconnectAll@12"
  FMOD_DSP_Remove(dsp.l) As "_FMOD_DSP_Remove@4"
  FMOD_DSP_GetNumInputs(dsp.l, *numinputs.l) As "_FMOD_DSP_GetNumInputs@8"
  FMOD_DSP_GetNumOutputs(dsp.l, *numoutputs.l) As "_FMOD_DSP_GetNumOutputs@8"
  FMOD_DSP_GetInput(dsp.l, index.l, *input.FMOD_DSP) As "_FMOD_DSP_GetInput@12"
  FMOD_DSP_GetOutput(dsp.l, index.l, *output.FMOD_DSP) As "_FMOD_DSP_GetOutput@12"
  FMOD_DSP_SetInputMix(dsp.l, index.l, volume.f) As "_FMOD_DSP_SetInputMix@12"
  FMOD_DSP_GetInputMix(dsp.l, index.l, *volume.f) As "_FMOD_DSP_GetInputMix@12"
  FMOD_DSP_SetInputLevels(dsp.l, index.l, speaker.FMOD_SPEAKER, *levels.f, numlevels.l) As "_FMOD_DSP_SetInputLevels@20"
  FMOD_DSP_GetInputLevels(dsp.l, index.l, speaker.FMOD_SPEAKER, *levels.f, numlevels.l) As "_FMOD_DSP_GetInputLevels@20"
  FMOD_DSP_SetOutputMix(dsp.l, index.l, volume.f) As "_FMOD_DSP_SetOutputMix@12"
  FMOD_DSP_GetOutputMix(dsp.l, index.l, *volume.f) As "_FMOD_DSP_GetOutputMix@12"
  FMOD_DSP_SetOutputLevels(dsp.l, index.l, speaker.FMOD_SPEAKER, *levels.f, numlevels.l) As "_FMOD_DSP_SetOutputLevels@20"
  FMOD_DSP_GetOutputLevels(dsp.l, index.l, speaker.FMOD_SPEAKER, *levels.f, numlevels.l) As "_FMOD_DSP_GetOutputLevels@20"
  ;-DSP unit control
  FMOD_DSP_SetActive(dsp.l, active.FMOD_BOOL) As "_FMOD_DSP_SetActive@8"
  FMOD_DSP_GetActive(dsp.l, *active.FMOD_BOOL) As "_FMOD_DSP_GetActive@8"
  FMOD_DSP_SetBypass(dsp.l, bypass.FMOD_BOOL) As "_FMOD_DSP_SetBypass@8"
  FMOD_DSP_GetBypass(dsp.l, *bypass.FMOD_BOOL) As "_FMOD_DSP_GetBypass@8"
  FMOD_DSP_SetSpeakerActive(dsp.l, speaker.FMOD_SPEAKER, active.FMOD_BOOL) As "_FMOD_DSP_SetSpeakerActive@12"
  FMOD_DSP_GetSpeakerActive(dsp.l, speaker.FMOD_SPEAKER, *active.FMOD_BOOL) As "_FMOD_DSP_GetSpeakerActive@12"
  FMOD_DSP_Reset(dsp.l) As "_FMOD_DSP_Reset@4"
  ;-DSP parameter control
  FMOD_DSP_SetParameter(dsp.l, index.l, value.f) As "_FMOD_DSP_SetParameter@12"
  FMOD_DSP_GetParameter(dsp.l, index.l, *value.f, *valuestr.s, valuestrlen.l) As "_FMOD_DSP_GetParameter@20"
  FMOD_DSP_GetNumParameters(dsp.l, *numparams.l) As "_FMOD_DSP_GetNumParameters@8"
  FMOD_DSP_GetParameterInfo(dsp.l, index.l, *name.s, *label.s, *description.s, descriptionlen.l, *min.f, *max.f) As "_FMOD_DSP_GetParameterInfo@32"
  FMOD_DSP_ShowConfigDialog(dsp.l, *hwnd, show.FMOD_BOOL) As "_FMOD_DSP_ShowConfigDialog@12"
  ;-DSP attributes
  FMOD_DSP_GetInfo(dsp.l, *name.s, *version.l, *channels.l, *configwidth.l, *configheight.l) As "_FMOD_DSP_GetInfo@24"
  FMOD_DSP_GetType(dsp.l, *type.FMOD_DSP_TYPE) As "_FMOD_DSP_GetType@8"
  FMOD_DSP_SetDefaults(dsp.l, frequency.f, volume.f, pan.f, priority.f) As "_FMOD_DSP_SetDefaults@20"
  FMOD_DSP_GetDefaults(dsp.l, *frequency.f, *volume.f, *pan.f, *priority.f) As "_FMOD_DSP_GetDefaults@20"
  ;-Userdata set/get
  FMOD_DSP_SetUserData(dsp.l, *userdata) As "_FMOD_DSP_SetUserData@8"
  FMOD_DSP_GetUserData(dsp.l, *userdata) As "_FMOD_DSP_GetUserData@8"
  ;------>'Geometry' API
  FMOD_Geometry_Release(geometry.l) As "_FMOD_Geometry_Release@4"
  ;-Polygon manipulation
  FMOD_Geometry_AddPolygon(geometry.l, directocclusion.f, reverbocclusion.f, doublesided.FMOD_BOOL, numvertices.l, *vertices.FMOD_VECTOR, *polygonindex.l) As "_FMOD_Geometry_AddPolygon@28"
  FMOD_Geometry_GetNumPolygons(geometry.l, *numpolygons.l) As "_FMOD_Geometry_GetNumPolygons@8"
  FMOD_Geometry_GetMaxPolygons(geometry.l, *maxpolygons.l, *maxvertices.l) As "_FMOD_Geometry_GetMaxPolygons@12"
  FMOD_Geometry_GetPolygonNumVertices(geometry.l, index.l, *numvertices.l) As "_FMOD_Geometry_GetPolygonNumVertices@12"
  FMOD_Geometry_SetPolygonVertex(geometry.l, index.l, vertexindex.l, *vertex.FMOD_VECTOR) As "_FMOD_Geometry_SetPolygonVertex@16"
  FMOD_Geometry_GetPolygonVertex(geometry.l, index.l, vertexindex.l, *vertex.FMOD_VECTOR) As "_FMOD_Geometry_GetPolygonVertex@16"
  FMOD_Geometry_SetPolygonAttributes(geometry.l, index.l, directocclusion.f, reverbocclusion.f, doublesided.FMOD_BOOL) As "_FMOD_Geometry_SetPolygonAttributes@20"
  FMOD_Geometry_GetPolygonAttributes(geometry.l, index.l, *directocclusion.f, *reverbocclusion.f, *doublesided.FMOD_BOOL) As "_FMOD_Geometry_GetPolygonAttributes@20"
  ;-Object manipulation.
  FMOD_Geometry_SetActive(geometry.l, active.FMOD_BOOL) As "_FMOD_Geometry_SetActive@8"
  FMOD_Geometry_GetActive(geometry.l, *active.FMOD_BOOL) As "_FMOD_Geometry_GetActive@8"
  FMOD_Geometry_SetRotation(geometry.l, *forward.FMOD_VECTOR, *up.FMOD_VECTOR) As "_FMOD_Geometry_SetRotation@12"
  FMOD_Geometry_GetRotation(geometry.l, *forward.FMOD_VECTOR, *up.FMOD_VECTOR) As "_FMOD_Geometry_GetRotation@12"
  FMOD_Geometry_SetPosition(geometry.l, *position.FMOD_VECTOR) As "_FMOD_Geometry_SetPosition@8"
  FMOD_Geometry_GetPosition(geometry.l, *position.FMOD_VECTOR) As "_FMOD_Geometry_GetPosition@8"
  FMOD_Geometry_SetScale(geometry.l, *scale.FMOD_VECTOR) As "_FMOD_Geometry_SetScale@8"
  FMOD_Geometry_GetScale(geometry.l, *scale.FMOD_VECTOR) As "_FMOD_Geometry_GetScale@8"
  FMOD_Geometry_Save(geometry.l, *data_, *datasize.l) As "_FMOD_Geometry_Save@12"
  ;-Userdata set/get.
  FMOD_Geometry_SetUserData(geometry.l, *userdata) As "_FMOD_Geometry_SetUserData@8"
  FMOD_Geometry_GetUserData(geometry.l, *userdata) As "_FMOD_Geometry_GetUserData@8"
  ;------>'Reverb' API
  FMOD_Reverb_Release(reverb.l) As "_FMOD_Reverb_Release@4"
  ;-Reverb manipulation
  FMOD_Reverb_Set3DAttributes(reverb.l, *position.FMOD_VECTOR, mindistance.f, maxdistance.f) As "_FMOD_Reverb_Set3DAttributes@16"
  FMOD_Reverb_Get3DAttributes(reverb.l, *position.FMOD_VECTOR, *mindistance.f, *maxdistance.f) As "_FMOD_Reverb_Get3DAttributes@16"
  FMOD_Reverb_SetProperties(reverb.l, *properties.FMOD_REVERB_PROPERTIES) As "_FMOD_Reverb_SetProperties@8"
  FMOD_Reverb_GetProperties(reverb.l, *properties.FMOD_REVERB_PROPERTIES) As "_FMOD_Reverb_GetProperties@8"
  FMOD_Reverb_SetActive(reverb.l, *active.FMOD_BOOL) As "_FMOD_Reverb_SetActive@8"
  FMOD_Reverb_GetActive(reverb.l, *active.FMOD_BOOL) As "_FMOD_Reverb_GetActive@8"
  ;-Userdata set/get.
  FMOD_Reverb_SetUserData(reverb.l, *userdata) As "_FMOD_Reverb_SetUserData@8"
  FMOD_Reverb_GetUserData(reverb.l, *userdata) As "_FMOD_Reverb_GetUserData@8"
  ;------>'Debug'API
  FMOD_Debug_SetMode(*mode.FMOD_BOOL) As "_FMOD_Debug_SetMode@4"
  FMOD_Debug_GetMode(*mode.FMOD_BOOL) As "_FMOD_Debug_GetMode@4"
EndImport

; IDE Options = PureBasic 4.20 (Windows - x86)
; CursorPosition = 381
; Folding = +